import type { CopyTemplateValue } from '@zoltar/ui-core-shared/copy/types.js'

export const bidAmountEth = 'Bid Amount (ETH)'
export const scrollableAuctionBidHistory = 'Scrollable auction bid history'
export const scrollableMyBids = 'Scrollable wallet bid history'
export const selectedChildPoolRepReadinessLoading = 'Checking whether pool-held REP is already ready for the selected child universe.'
export const clearingPrice = 'Clearing Price'
export const closed = 'Closed'
export const entryDepthLead = 'Entry depth: '
export const escalationDepositDetailsUnavailable = 'Escalation deposit details are unavailable for this pool right now.'
export const ethRaisedPerCap = 'ETH Raised / Cap'
export const forkDepositSettlementAvailabilityDetail = 'Winning fork-carried escalation deposits can be settled after this child pool finalizes.'
export const escalationAuctionHaircutDetail =
	'A repair auction can sell from both pool-held REP available to the repair auction and paused dispute-staked REP. Purchased REP is floor-allocated to the game; claims already present share that game-specific retention ratio. This prioritizes restoring settlement collateral that backs open interest over preserving escalation rewards, and the game resumes from reduced effective balances with a fresh response period.'
export const initiallyDepositedLead = 'Initially deposited: '
export const loadedDepthEth = 'Visible Depth (ETH)'
export const loadingCurrentChainTime = 'Loading current chain time.'
export const migrateVaultTitle = 'Migrate Vault'
export const migratingVault = 'Migrating vault…'
export const migrationTimingIsUnavailable = 'Migration timing is unavailable.'
export const poolMigrationCapacityEmpty = 'No REP backing or capacity ownership remains to migrate for the connected wallet.'
export const notStarted = 'Not started'
export const walletUnresolvedDepositsEmpty = 'No unresolved parent escalation deposits remain for the connected wallet.'
export const open = 'Open'
export const priceEthPerRep = 'Price (ETH / REP)'
export const repPurchasedAttoRep = 'REP Purchased'
export const startingTruthAuction = 'Starting truth auction…'
export const startTruthAuction = 'Start truth auction'
export const startTruthAuctionTitle = 'Start Truth Auction'
export const submitBid = 'Submit bid'
export const submitBidTitle = 'Submit Bid'
export const unresolvedDepositDetailsUnavailable = 'Unresolved escalation deposit details are unavailable for this pool right now.'
export const worthNowLead = 'Worth now: '
export const formatCheckingPoolRepMigratedToChildUniverse = (outcomeLabel: CopyTemplateValue) => `Checking whether pool-held REP has already been migrated for the ${outcomeLabel} child universe.`
export const formatEthPerRepValue = (price: CopyTemplateValue) => `${price}\u00a0ETH / REP`
export const attoEthRaised = 'ETH Raised'
export const attoRepSold = 'REP Sold'
export const minBid = 'Min Bid'
export const winningThreshold = 'Winning Threshold'
export const zeroEth = '0\u00a0ETH'
export const truthAuctionVisibleDepthChart = 'Truth auction visible depth chart'
export const formatSelectPriceValueEthRepFromDepthChart = (price: CopyTemplateValue) => `Select price ${price}\u00a0ETH / REP from depth chart`
export const formatImportedForkDepositPageSummary = (startIndex: CopyTemplateValue, endIndex: CopyTemplateValue, totalCount: CopyTemplateValue, paginationSummary: CopyTemplateValue) => `Showing parent deposits ${startIndex}-${endIndex} of ${totalCount}. ${paginationSummary}`
export const formatDepositSelectionRequired = (outcomeLabel: CopyTemplateValue) => `Select at least one ${outcomeLabel} fork-carried deposit to settle.`
export const importedFromParentUniverse = 'Imported from parent universe'
export const parentDepositNumber = 'Parent deposit #'
export const worthNowPendingFinalSettlement = 'Worth now: Pending final settlement'
export const importedEntryDepthLead = 'Imported entry depth: '
export const nextParentDeposits = 'Next parent deposits'
export const previousParentDeposits = 'Previous parent deposits'
export const settleForkCarriedEscalationDeposits = 'Settle Fork-Carried Escalation Deposits'
export const importedDepositSettlementDetail = 'Imported from the parent universe. After finalization, only winning positions can be settled; inherited losers require no transaction.'
export const leading = 'Leading'
export const totalDisputeStakedRep = 'Total dispute-staked REP'
export const yourDisputeStakedRep = 'Your dispute-staked REP'
export const formatMissingOutcomePoolDetail = (outcomeLabel: CopyTemplateValue) => `Security Pool for ${outcomeLabel} universe does not exist.`
export const forkUnavailablePlaceholder = '-'
export const migration = 'Migration'
export const forkReadiness = 'Fork Readiness'
export const notChosen = 'Not chosen'
export const systemIsForking = 'System is forking'
export const ethRep = 'ETH / REP'
export const refundSettlementDetail = 'Refund-only settlement returns locked ETH.'
export const formatFinalizedRefundOnlySettlementNotice = (capacityOwnershipLabel: CopyTemplateValue) => `Finalized refund-only settlement uses the child-pool settlement path to unlock ETH, and it does not assign REP backing units or ${capacityOwnershipLabel}.`
export const formatWinningClaimCapacityOwnershipHeadline = (capacityOwnershipLabel: CopyTemplateValue) => `Winning claims add REP backing units and ${capacityOwnershipLabel}.`
export const formatWinningClaimSettlementNotice = (capacityOwnershipLabel: CopyTemplateValue) =>
	`Claiming a winning bid adds REP backing units and a pro-rata share of the ${capacityOwnershipLabel} to the bidder vault. That capacity ownership is the remaining capacity ownership being assigned during settlement. Refund-only bids just return locked ETH.`
export const formatMixedSettlementPreviewDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Winning rows receive estimated REP backing units plus estimated ${capacityOwnershipLabel}, while refund rows return locked ETH.`
export const formatWinningSettlementPreviewDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Winning rows receive estimated REP backing units plus estimated ${capacityOwnershipLabel}.`
export const formatRefundSettlementPreviewDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Refund-only settlement returns locked ETH and does not assign ${capacityOwnershipLabel}.`
export const truthAuctionRefundEstimateDetail = 'Estimated ETH refunded includes fully losing bids and any unfilled remainder on partially cleared winning bids.'
export const underfundedWinningClaimUnavailable = 'Claim preview is unavailable for underfunded winning bids because the required per-tick ETH denominator is not exposed in current UI data.'
export const settlementRoundingNotice = 'These are pre-transaction estimates. Final on-chain settlement can differ slightly because claim math is rounded on-chain.'
export const selectedBidSettlementPreview = 'Selected-bid settlement preview.'
export const selectedBids = 'Selected Bids'
export const selectedWinningBids = 'Selected Winning Bids'
export const selectedRefundRows = 'Selected Refund Rows'
export const estimatedVaultRepBackingAttoRep = 'Estimated REP backing'
export const formatEstimatedValue = (label: CopyTemplateValue) => `Estimated ${label}`
export const estimatedRefundedAttoEth = 'Estimated ETH Refunded'
export const ownEscalationFork = 'Own escalation fork'
export const parentZoltarFork = 'Parent universe fork'
export const childSecurityPools = 'Child Security Pools'
export const pendingOutcome = 'Pending outcome'
export const openSecurityPool = 'Open security pool'
export const truthAuctionMigrationPendingDetail = 'Migration is still active. Truth auction can start once migration ends.'
export const parentMigrationExpiredDetail = 'Migration window has closed for this parent pool.'
export const truthAuctionNoCollateralDetail = 'No parent settlement collateral remains to auction, so this step immediately bypasses bidding and finalizes the child pool.'
export const truthAuctionNoRepDetail = 'No REP was present at fork, so no truth auction is needed for this child universe.'
export const childUniverseFullyMigratedDetail = 'This child universe already has all REP migrated from the parent pool, so no truth auction is needed.'
export const loadingTruthAuction = 'Loading truth auction…'
export const truthAuctionNotStartedReason = 'Truth auction has not started.'
export const truthAuctionFinalizedReason = 'Truth auction is already finalized.'
export const auctionEndTimeUnavailable = 'Truth auction end time is unavailable.'
export const auctionOngoingReason = 'Truth auction is still ongoing.'
export const inactive = 'Inactive'
export const clearing = 'Clearing'
export const shortfall = 'Shortfall'
export const unfilled = 'Unfilled'
export const notStartedBadgeLabel = 'Not Started'
export const childPool = 'Child pool'
export const parentBalancesWalletRequired = 'Connect wallet to inspect your parent-pool balances.'
export const parentVaultBalancesUnavailableDetail = 'Parent-pool vault balances are unavailable for the connected wallet. You can still use the migration actions below if this wallet has parent-pool state to move.'
export const migratedBalancesForThisOutcome = 'Migrated balances for this outcome:'
export const selectedOutcomeRepCollateral = 'Selected Outcome REP backing'
export const selectedOutcomeCapacityOwnershipAttoRep = 'Selected Outcome Capacity ownership'
export const walletDisputeStakedRepEmpty = 'No parent dispute-staked REP remains available for a direct branch claim by the connected wallet.'
export const startingTruncated = 'Starting…'
export const formatStartsInValue = (duration: CopyTemplateValue) => `Starts in ${duration}`
export const pendingConfirmation = 'Pending confirmation'
export const settleSelectedBids = 'Settle selected bids'
export const formatWinningBidBatchSettlementDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Select winning bids and settle them together. Winning claims add REP backing units plus ${capacityOwnershipLabel}.`
export const formatFinalizedRefundBatchSettlementDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Select finalized refund rows and settle them together. These rows return locked ETH without adding ${capacityOwnershipLabel}.`
export const formatRefundableBidBatchSettlementDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Select refundable bids and settle them together. Refund-only settlement returns locked ETH without adding ${capacityOwnershipLabel}.`
export const formatMixedBidBatchSettlementDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Select winning and refundable bids and settle them together. Winning selections add REP backing units plus ${capacityOwnershipLabel}, while refundable selections return locked ETH.`
export const submittingSettlementTransactionTruncated = 'Submitting settlement transaction…'
export const forkActionWalletRequired = 'Connect a wallet before using fork and auction actions.'
export const auctionEndedStatus = 'Truth auction has ended.'
export const formatFinalizedSettlementDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Bidding is closed and finalized settlement paths are now in effect. Winning claims receive REP backing units plus ${capacityOwnershipLabel}, while losing bids are refunded.`
export const truthAuctionFinalizationRequiredDetail = 'Bidding is closed. Finalize the truth auction to settle against the final clearing result.'
export const endedAtLead = 'Ended at: '
export const finalizeTruthAuction = 'Finalize truth auction'
export const finalizingTruthAuctionTruncated = 'Finalizing truth auction…'
export const formatTruthAuctionStartDelay = (duration: CopyTemplateValue) => `Truth auction can be started in ${duration} once migration ends.`
export const eligibleDepositsLoading = 'Loading eligible escalation deposits.'
export const useUnresolvedMigrationReason = 'Use the optional unresolved parent escalation-deposit accounting cleanup for this pool.'
export const unresolvedMigrationExpiredReason = 'The optional unresolved parent escalation-deposit accounting cleanup window has closed.'
export const formatNoClaimableParentEscalationDeposits = (outcomeLabel: CopyTemplateValue) => `No ${outcomeLabel} parent escalation deposits are currently available for a direct claim by this wallet.`
export const parentEscalationClaimSelectionRequired = 'Select at least one deposit to claim.'
export const unresolvedMigrationUnavailableReason = 'Optional unresolved parent escalation-deposit accounting cleanup is unavailable for this pool.'
export const unresolvedDepositsLoading = 'Loading unresolved escalation deposits.'
export const formatPoolRepAlreadyMigrated = (outcomeLabel: CopyTemplateValue) => `Pool-held REP has already been migrated to the ${outcomeLabel} universe.`
export const formatPoolMigrationRequiredForVault = (outcomeLabel: CopyTemplateValue) => `Migrate pool to the ${outcomeLabel} universe before moving vault balances.`
export const vaultMigrationCompleteReason = 'Vault migration is already complete for this wallet.'
export const combinedUnresolvedMigrationDetail = 'Optionally clear unresolved parent escalation-deposit accounting while migrating remaining REP backing units and capacity ownership.'
export const selectedLadderPriceLead = 'Selected ladder price: '
export const bidPriceEthRep = 'Bid Price (ETH / REP)'
export const submittingBidTruncated = 'Submitting bid…'
export const truthAuctionAddress = 'Truth Auction Address'
export const started = 'Started'
export const minBidSizeAttoEth = 'Min Bid Size'
export const maxAttoRepBeingSold = 'Max REP Being Sold'
export const settlementAvailable = 'Settlement Available'
export const migrationStatus = 'Migration Status'
export const repAtFork = 'REP At Fork'
export const migratedAttoRep = 'Migrated REP'
export const settlementCollateral = 'Settlement collateral'
export const migrationStarted = 'Migration Started'
export const migrationEnds = 'Migration Ends'
export const forkType = 'Fork Type'
export const advancedDiagnostics = 'Advanced Diagnostics'
export const totalPoolHeldRepAtForkAttoRep = 'Pool-held REP at fork'
export const escalationChildRepPerSelectedOutcomeAttoRep = 'Dispute-staked REP per selected outcome'
export const escrowSourceRepAtForkAttoRep = 'Dispute-staked REP source at fork'
export const formatSettleSelectedValueForkCarriedDeposits = (outcomeLabel: CopyTemplateValue) => `Settle selected ${outcomeLabel} fork-carried deposits`
export const settlingForkCarriedDepositsTruncated = 'Settling fork-carried deposits…'
export const forkLifecycleStages = 'Fork lifecycle stages'
export const viewing = 'Viewing'
export const triggeredAt = 'Triggered At'
export const forkNotTriggered = 'Fork Not Triggered'
export const yourMigrationBalances = 'Your Migration Balances'
export const parentWalletBalancesDescription = 'Wallet-level balances in the parent pool that may still need migration.'
export const clearUnresolvedParentEscalationDepositAccounting = 'Optional: Clear Unresolved Parent Escalation-Deposit Accounting'
export const unresolvedMigrationExpiredDetail = 'The optional unresolved parent escalation-deposit accounting cleanup window has closed. Child backing and winning-proof eligibility are unchanged.'
export const unresolvedEscalationMigrationWithVaultDetail =
	'First transfers this wallet’s REP backing units and capacity ownership to the selected child, checkpoints but retains claimable fees in the parent vault, and separately routes proportional pool-level settlement collateral. It then clears the three parent outcome totals in constant-size work. This is not required to fund dispute-staked REP backing or claim a winning carried proof; inherited losers require no claim transaction.'
export const walletUnresolvedDepositsLoading = 'Loading unresolved parent escalation-deposit accounting for the connected wallet…'
export const capturedEntitlementDetail = 'Unresolved parent escalation-deposit accounting was already cleared. Child proof eligibility is unchanged.'
export const formatEntitlementAlreadyMaterialized = (outcomeLabel: CopyTemplateValue) => `This wallet’s optional unresolved parent escalation-deposit accounting cleanup is already recorded for the ${outcomeLabel} child universe.`
export const formatNoUnresolvedDeposits = (outcomeLabel: string) => `No ${outcomeLabel} unresolved deposits remain for this wallet.`
export const formatMigrateUnresolvedEscalationToValue = (outcomeLabel: CopyTemplateValue) => `Clear unresolved parent escalation-deposit accounting for ${outcomeLabel}`
export const migratingUnresolvedEscalationTruncated = 'Clearing unresolved parent escalation-deposit accounting…'
export const claimResolvedParentEscalationDeposits = 'Optional: Claim Parent Escalation Deposits'
export const resolvedParentDepositClaimDetail = 'This fast path pays selected winning parent deposits directly in child REP and marks their carried proofs spent. Unclaimed winners can instead settle from aggregate child backing with a proof.'
export const parentEscalationClaimEmptyDisputeStakedRepDetail = 'No parent dispute-staked REP is currently visible for a direct claim by the connected wallet.'
export const walletEscalationDepositsLoading = 'Loading escalation deposits for the selected wallet…'
export const chooseParentDepositsToClaim = 'Choose deposits to claim'
export const worthNowPendingClaimFinalization = 'Worth now: Pending direct claim'
export const formatClaimSelectedValueParentDeposits = (outcomeLabel: CopyTemplateValue) => `Claim selected ${outcomeLabel} deposits`
export const claimingParentEscalationDepositsTruncated = 'Claiming parent escalation deposits…'
export const migratePoolToUniverse = 'Migrate Pool To Universe'
export const poolRepMigrationDetail = 'This moves pool-held REP attributed to the selected outcome into the child universe. It affects the outcome pool, not just your vault.'
export const poolRepAlreadyMigratedDetail = 'Pool-held REP has already been migrated to the selected child universe.'
export const poolRepStagedForVaultMigrationDetail = 'Pool-held REP for this outcome is already staged and will sweep into the child universe during vault migration.'
export const formatMigratePoolToValueUniverse = (outcomeLabel: CopyTemplateValue) => `Migrate pool to ${outcomeLabel} universe`
export const migratingPoolToUniverseTruncated = 'Migrating pool to universe…'
export const vaultMigrationDetail = 'This moves all remaining pool-held vault REP backing migration power and capacity ownership from your parent vault into the selected child pool. Escalation claims have zero parent-OI migration power and follow their separate claim path.'
export const formatMigrateVaultToValue = (outcomeLabel: CopyTemplateValue) => `Migrate vault to ${outcomeLabel}`
export const alreadyMigratedStatus = 'Already migrated'
export const truthAuctionStatus = 'Truth Auction Status'
export const formatStartTruthAuctionDetail = (capacityOwnershipLabel: CopyTemplateValue) => `Start the ETH-for-REP truth auction only after migration closes. Winning bids later claim REP backing units plus ${capacityOwnershipLabel}, while losing bids are refunded during settlement.`
export const bypassTruthAuction = 'Bypass truth auction'
export const bypassingAuctionTruncated = 'Bypassing auction…'
export const settlementStatus = 'Settlement Status'
export const forkWorkflowDescription = 'Select a pool to inspect fork progress, migration, and the truth auction.'
export const forkTruthAuction = 'Fork & Truth Auction'
export const formatMissingChildUniverseDetail = (outcomeLabel: CopyTemplateValue) => `Child universe not created for the ${outcomeLabel} outcome.`
export const bidder = 'Bidder'
export const currentBids = 'Current Bids'
export const loadedLevels = 'Visible Levels'
export const loadedBids = 'Visible Bids'
export const coverage = 'Coverage'
export const formatLoadedBidCoverageSummary = (loadedBidCount: CopyTemplateValue, visibleBidCount: CopyTemplateValue) => `Showing ${loadedBidCount} of ${visibleBidCount} bids across visible levels`
export const loadingAuctionBids = 'Loading auction bids…'
export const retryAuctionBids = 'Retry'
export const retryCurrentBids = 'Retry current bids'
export const retryMyBids = 'Retry my bids'
export const retryingAuctionBids = 'Retrying auction bids…'
export const retryAuctionDetails = 'Retry'
export const retryingAuctionDetails = 'Retrying auction details…'
export const retryForkWorkflow = 'Retry fork workflow'
export const retryChildUniverse = 'Retry child universe'
export const formatLoadingOutcomePoolDetail = (outcomeLabel: CopyTemplateValue) => `Loading the ${outcomeLabel} child pool…`
export const retryPoolRepReadiness = 'Retry pool-held REP readiness'
export const retryReporting = 'Retry reporting'
export const loadingReportingDetails = 'Loading reporting details…'
export const auctionPriceLevelsEmpty = 'No active prices are currently visible for this auction.'
export const loadedPriceBidsEmpty = 'No bids are currently indexed for the visible prices.'
export const auctionBidHistory = 'Auction bid history'
export const loadMoreTruthAuctionBids = 'Show more truth auction bids'
export const myBids = 'My Bids'
export const walletBidsConnectionRequired = 'Connect a wallet to inspect your submitted truth auction bids.'
export const loadingYourBids = 'Loading your bids…'
export const walletBidsEmpty = 'No bids from this wallet are indexed for the current auction.'
export const loadMoreOfMyBids = 'Show more of my bids'
export const formatEscalationDepositPageSummary = (startIndex: CopyTemplateValue, endIndex: CopyTemplateValue, totalCount: CopyTemplateValue, paginationSummary: CopyTemplateValue) => `Showing deposits ${startIndex}-${endIndex} of ${totalCount}. ${paginationSummary}`
export const depositNumber = 'Deposit #'
export const nextDeposits = 'Next deposits'
export const previousDeposits = 'Previous deposits'
export const currentFormPrice = 'Current form price'
export const currentSize = 'Current size'
export const clearingLevel = 'Clearing level'
export const loadedDepth = 'Visible depth'
export const loadMorePriceLevels = 'Show more price levels'
export const loadingOrderBook = 'Loading order book…'
export const loadingPriceLevels = 'Loading price levels…'
export const marketDepth = 'Market Depth'
export const potentialRepIfFilled = 'Potential REP If Fully Filled'
export const enteredBidPrice = 'Entered Bid Price'
export const submittedTickPrice = 'Submitted Tick Price'
export const bidEscrowRisk = 'Bid ETH remains locked until settlement; losing and unfilled amounts require a later refund settlement.'
export const bidFillRisk = 'The clearing result can change before the auction ends, so estimated REP is not guaranteed.'
export const winningBidCapacityOwnershipRisk = 'Winning settlement can also assign a pro-rata share of the pool capacity ownership.'
export const visibleAuctionLevelsEmpty = 'No active levels are visible.'
export const auctionLiveLevelsEmpty = 'No live price levels are currently active for this auction.'
export const priceLadder = 'Price Ladder'
export const priceLevel = 'Price level'
export const formatSubmissionsLabel = (count: string) => `${count} submissions`
export const visibleDepth = 'Visible Depth'
