export const deploying = 'Deploying…'
export const deploymentReadyStatus = 'Can deploy now.'
export const deploymentRunningStatus = 'Deployment in progress.'
export const waiting = 'Waiting'
export const formatPrerequisiteDetail = (prerequisiteLabel: string) => `Requires ${prerequisiteLabel}.`
export const allDeployed = 'All deployed'
export const contractsDeployed = 'Contracts deployed'
export const deployNextContract = 'Deploy next contract'
export const allContracts = 'All contracts'
export { deploymentDescription as deploymentOverviewDetail } from '@zoltar/ui-core-shared/copy/app.js'
export const loadingDeploymentStatus = 'Loading deployment status…'
export const deploymentStatusUnavailableReason = 'Deployment status is unavailable.'
export const nextDeployable = 'Next deployable'
export const alreadyDeployedReason = 'Already deployed.'
export const otherDeploymentRunningReason = 'Another deployment is already in progress.'
export const allContractsDeployedReason = 'All contracts are already deployed.'
export const deploymentFailed = 'Deployment failed'
export const deploymentBlocked = 'Deployment blocked'
export const formatDeployPrerequisiteFirstError = (prerequisiteLabel: string) => `Deploy ${prerequisiteLabel} first.`
export const deploymentVerificationFailedError = 'Deployment verification failed: no contract code was found at the expected address. Check the selected network and retry.'
export const formatDeploymentUnverifiableError = (contractLabel: string) => `${contractLabel} cannot be verified on this network, so it cannot be deployed from this app.`
