export const deploying = 'Deploying…'
export const deploymentReadyStatus = 'Can deploy now.'
export const deploymentRunningStatus = 'Deployment in progress.'
export const waiting = 'Waiting'
export const formatPrerequisiteDetail = (prerequisiteLabel: string) => `Requires ${prerequisiteLabel}`
export const allDeployed = 'All deployed'
export const contractsDeployed = 'Contracts deployed'
export const deployNextMissing = 'Deploy next missing'
export const browseQuestions = 'Browse questions'
export const allContracts = 'All contracts'
export { deploymentDescription as deploymentOverviewDetail } from '@zoltar/ui-core-shared/copy/app.js'
export const deterministicContractDeployment = 'Deterministic contract deployment'
export const loadingDeploymentStatus = 'Loading deployment status…'
export const deploymentStatusUnavailableReason = 'Deployment status is unavailable.'
export const nextDeployable = 'Next deployable'
