export const loadingOutcomes = 'Loading outcomes…'
export const openOutcomeArrowTail = ' →'
export const outcomesUnavailable = 'Unable to load child outcomes.'
export const selectScalarOutcome = 'Select outcome'
export const loadingChild = 'Loading child universe…'
export const invalidScalarTick = 'Enter an exact tick within the question’s range.'
