export const loadingOutcomes = 'Loading outcomes…'
export const openOutcomeArrowTail = ' →'
export const outcomesUnavailable = 'Unable to load child outcomes.'
export const scalarValue = 'Find outcome by value'
export const findOutcome = 'Find outcome'
export const invalidScalarValue = 'Enter an exact outcome value within the question’s range.'
