import type { CopyTemplateValue } from '@zoltar/ui-core-shared/copy/types.js'

export const applicationTitle = 'Zoltar'
export const forkZoltar = 'Fork Universe'
export const migrateRep = 'Migrate REP'
export const alreadyForkedReason = 'This universe has already forked.'
export const forkQuestionRequiredReason = 'Select a valid fork question to continue.'
export const forkQuestionIdInvalid = 'Enter a valid hexadecimal question ID.'
export const forkQuestionTimeLoadingReason = 'Loading current chain time before checking whether the selected question has ended.'
export const formatForkQuestionActiveReason = (endTime: CopyTemplateValue, relativeEndTime: CopyTemplateValue) => `The selected question must end before the universe can fork. It ends ${endTime} (${relativeEndTime}).`
export const forkEconomicsUnavailableReason = 'Fork burn and migration-credit terms are unavailable.'
export const forkRepInsufficientReason = 'Insufficient REP to meet the fork threshold.'
export const forkRepApprovalRequiredReason = 'Approve enough REP to continue.'
export const forkingActionLabel = 'forking the universe'
export const forkRepApprovalPending = 'Approving REP threshold…'
export const forkQuestionId = 'Fork Question ID'
export const forkSubmissionPending = 'Forking universe…'
export const outcomeUniversesEmpty = 'No outcome universes available.'
export const permanentRepBurn = 'Permanent REP Burn'

export const universeDetails = 'Universe details'
export const repSupply = 'REP supply'

export const migrationIntro = 'Migrating burns REP in this universe and gives you the same amount of REP in each outcome universe you choose. It cannot be undone.'
export const migrationProgress = 'Migration steps'
export const migrationStepChooseOutcomes = 'Choose outcomes'
export const migrationStepAmount = 'Amount'
export const migrationStepApprove = 'Approve'
export const migrationStepReview = 'Review'
export const migrationStepDone = 'Done'
export const migrationStepNotNeeded = 'Not needed'
export const migrationStepReady = 'Ready'
export const migrationStepToDo = 'To do'
export const migrationStepLoading = 'Loading'
export const migrationStepBlocked = 'Blocked'
export const migrationBack = 'Back'
export const migrationContinue = 'Continue'

export const chooseOutcomesDetail = 'Pick every outcome universe that should receive your REP. Universes that do not exist yet are created when you migrate.'
export const outcomeUniverseStatus = 'Universe'
export const outcomeUniverseCreated = 'Created'
export const outcomeUniverseNotCreated = 'Not created yet'
export const outcomeHeldRep = 'You hold'
export const outcomeAlreadyMigrated = 'Already migrated'
export const formatOpenOutcomeUniverse = (outcome: CopyTemplateValue) => `Open ${outcome} universe`
export const outcomeSelectionRequired = 'Select at least one outcome.'

export const migrationAmountLabel = 'Amount to migrate'
export const formatUseAllRep = (amount: CopyTemplateValue) => `Use all ${amount}\u00a0REP`
export const migrationAmountInvalid = 'Enter a valid REP amount.'
export const formatMigrationAmountExceeded = (maxAmount: CopyTemplateValue) => `You can migrate at most ${maxAmount}\u00a0REP to these outcomes.`
export const migrationFromBalance = 'From your migration balance'
export const migrationFromWallet = 'Burned from your wallet'
export const migrationEachOutcomeReceives = 'Each outcome universe receives'
export const migrationBalanceExplainer = 'Your migration balance is REP you already burned here. Each outcome universe can receive up to that amount without using more wallet REP.'
export const outcomeBalancesLoading = 'Loading migration balances…'
export const migrationBalancesReadFailed = 'Could not read migration balances. Retry to continue.'

export const migrationApprovalNotNeededChildRep = 'Outcome-universe REP is burned directly, so no approval is needed.'
export const migrationApprovalNotNeededNoWalletRep = 'Your migration balance covers this amount, so no wallet REP needs approval.'
export const migrationApprovalNeedsAmount = 'Enter an amount first.'
export const migrationApprovalLoading = 'Loading your REP approval…'
export const formatMigrationApprovalRequired = (amount: CopyTemplateValue) => `Approve ${amount}\u00a0REP to continue.`
export const migrationApprovalActionLabel = 'migrating REP'

export const formatMigrationSummary = (amount: CopyTemplateValue, outcomes: CopyTemplateValue) => `Migrate ${amount}\u00a0REP to: ${outcomes}`
export const migrationIrreversible = 'Burned REP cannot be returned to this universe.'
export const migrationMintsPerOutcome = 'Every selected outcome universe mints the full amount to your wallet.'
export const migrateRepAction = 'Migrate REP'
export const migratingRepPending = 'Migrating REP…'
export const migrationCompleteTitle = 'All your REP here is migrated'
export const migrationCompleteDetail = 'Every outcome universe has received your full migration balance.'
export const outcomeRepInWallet = 'Outcome-universe REP in your wallet'
export const formatUnnamedOutcome = (position: CopyTemplateValue) => `Outcome ${position}`
export const migrationStepCurrent = 'Current'
export const migrationForkRequired = 'This universe must fork before REP can be migrated.'
export const walletRep = 'Wallet REP'
export const migrationBalance = 'Migration balance'
