import type { CopyTemplateValue } from '@zoltar/ui-core-shared/copy/types.js'

export const applicationTitle = 'Zoltar'
export const forkZoltar = 'Fork Universe'
export const migrateRep = 'Migrate REP'
export const splitRep = 'Split REP'
export const migrationAmountAlreadySplitDetail = 'This amount is already fully split across the selected universes.'
export const alreadyForkedReason = 'This universe has already forked.'
export const formatAddMigrationRepDetail = (attoRepAmount: CopyTemplateValue) => `Splitting will automatically prepare ${attoRepAmount}\u00a0REP from your wallet.`
export const forkQuestionRequiredReason = 'Select an ended question to continue.'
export const forkQuestionIdInvalid = 'Enter a valid hexadecimal question ID.'
export const forkQuestionTimeLoadingReason = 'Loading current chain time before checking whether the selected question has ended.'
export const formatForkQuestionActiveReason = (endTime: CopyTemplateValue, relativeEndTime: CopyTemplateValue) => `The selected question must end before the universe can fork. It ends ${endTime} (${relativeEndTime}).`
export const forkEconomicsUnavailableReason = 'Fork burn and migration-credit terms are unavailable.'
export const forkingActionLabel = 'forking the universe'
export const forkRepApprovalPending = 'Approving REP threshold…'
export const forkQuestionId = 'Question ID'
export const forkQuestionLoadingReason = 'Loading the selected question…'
export const forkQuestionEndedReason = 'Question has ended.'
export const forkRepBalanceLoadingReason = 'Loading your REP balance…'
export const formatForkRepShortfall = (balance: CopyTemplateValue, threshold: CopyTemplateValue, shortfall: CopyTemplateValue, tokenSymbol: CopyTemplateValue) => `You have ${balance}\u00a0${tokenSymbol}; ${threshold}\u00a0${tokenSymbol} needed (${shortfall}\u00a0short).`
export const formatForkRepSufficient = (balance: CopyTemplateValue, threshold: CopyTemplateValue, tokenSymbol: CopyTemplateValue) => `You have ${balance}\u00a0${tokenSymbol}; ${threshold}\u00a0${tokenSymbol} needed.`
export const forkStepWaitingReason = 'Checked once your wallet and the universe are ready.'
export const forkApprovalNotRequired = 'Child-universe REP needs no approval.'
export const forkApprovalLoadingReason = 'Loading REP approval…'
export const formatForkApprovalRequired = (approved: CopyTemplateValue, threshold: CopyTemplateValue, tokenSymbol: CopyTemplateValue) => `Approve ${threshold}\u00a0${tokenSymbol} (${approved}\u00a0approved).`
export const formatForkApprovalSufficient = (threshold: CopyTemplateValue, tokenSymbol: CopyTemplateValue) => `${threshold}\u00a0${tokenSymbol} approved.`
export const forkReviewReady = 'Forking takes the full threshold from your wallet. The permanent burn below cannot be undone.'
export const forkReviewWaiting = 'Complete the steps above to fork.'
export const forkStepQuestion = 'Choose an ended question'
export const forkStepRep = 'Hold enough REP'
export const forkStepApproval = 'Approve REP'
export const forkStepReview = 'Review and fork'
export const forkStepDone = 'Done'
export const forkStepBlocked = 'Blocked'
export const forkStepPending = 'To do'
export const forkStepReady = 'Ready'
export const forkChecklistLabel = 'Fork checklist'
export const searchEndedQuestions = 'Search ended questions'
export const forkQuestionSearchPlaceholder = 'Search by title'
export const forkQuestionsLoading = 'Loading questions…'
export const forkEligibleQuestionsEmpty = 'No ended questions yet'
export const forkEligibleQuestionsEmptyDetail = 'A question can fork the universe once its end time passes.'
export const forkEligibleQuestionsNoMatches = 'No ended questions match this search.'
export const formatForkEligibleQuestionsTruncated = (shown: CopyTemplateValue, total: CopyTemplateValue) => `Showing ${shown} of ${total}. Refine the search to find others.`
export const formatEndedAt = (relativeEndTime: CopyTemplateValue) => `Ended ${relativeEndTime}`
export const enterQuestionId = 'Enter question ID'
export const changeQuestion = 'Change question'
export const forkSubmissionPending = 'Forking universe…'
export const addAnotherUniverse = 'Add another universe'
export const openUniverse = 'Open universe'
export const outcomeUniversesEmpty = 'No outcome universes available.'
export const walletBalanceLabel = 'Your balance:'
export const migratedBalanceLabel = 'Already migrated:'
export const migrationBalanceReadyDetail = 'This split uses your prepared REP.'
export const formatMigrationRepShortfall = (repShortfallAttoRep: CopyTemplateValue) => `Need ${repShortfallAttoRep}\u00a0more\u00a0REP in this universe to prepare the selected amount.`
export const migrationApprovalPendingDetail = 'Approve the wallet REP needed for this split.'
export const outcomeSelectionRequired = 'Select at least one outcome universe.'
export const outcomeBalancesLoading = 'Loading outcome universe balances…'
export const formatMigrationBalanceExceeded = (availableRep: CopyTemplateValue, migrationBalance: CopyTemplateValue, walletBalance: CopyTemplateValue) => `You only have ${availableRep}\u00a0REP available for migration in this universe (${migrationBalance} unused prepared REP and ${walletBalance}\u00a0wallet\u00a0REP).`
export const migrationRepBalance = 'Migration REP Balance'
export const migrationAmount = 'Migration Amount'
export const preparingCurrentAmountLabel = 'splitting the current amount'
export const splittingRepPending = 'Splitting REP…'
export const walletRepBalance = 'Wallet REP Balance'
export const walletRepTokens = 'Wallet REP Tokens'
export const selectedDestinations = 'Selected Destinations'
export const childUniverseRepReceived = 'Child-Universe REP Received'
export const permanentRepBurn = 'Permanent REP Burn'

export const migrationAvailableRep = 'Available to migrate'
export const migrationMaxIncludesPrepared = 'Max includes wallet REP and unused prepared REP for the selected destinations.'

export const migrationForkRequired = 'This universe must fork before REP can be split.'
export const walletRepUsed = 'Wallet REP Used'
export const migrationBalancesReadFailed = 'Could not read migration balances. Retry to continue.'

export const balanceDetails = 'Balance details'
export const chooseDestinations = 'Choose destinations'
export const reviewMigration = 'Review migration'

export const universeDetails = 'Universe details'
export const repSupply = 'REP supply'
