name: zoltar-statoblast

services:
  statoblast:
    build:
      context: ../..
      dockerfile: ui/Dockerfile
      target: local-runtime-statoblast
    image: zoltar-statoblast
    ports:
      - 127.0.0.1:8011:8011
    environment:
      UI_APP: statoblast

networks:
  default:
    name: zoltar
    external: true
