// Generated by scripts/generate-executor-abi.mts. Do not edit.
export const openOracleArbitrageExecutorAbi = [
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'account',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'reportId',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'bool',
				name: 'boughtToken2',
				type: 'bool',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'hedgeAmountToken2',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'hedgeAmountWethAttoEth',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'contribution1',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'contribution2',
				type: 'uint256',
			},
		],
		name: 'HedgeAndDisputeExecuted',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'account',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'reportId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'token1',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount1',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'token2',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount2',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'settlerRewardAttoEth',
				type: 'uint256',
			},
		],
		name: 'LifecycleExecuted',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'account',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'reportId',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'token',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount',
				type: 'uint256',
			},
		],
		name: 'ReplacementCreditWithdrawn',
		type: 'event',
	},
	{
		inputs: [
			{
				internalType: 'uint256',
				name: 'parentBlockNumber',
				type: 'uint256',
			},
			{
				internalType: 'bytes32',
				name: 'expectedParentBlockHash',
				type: 'bytes32',
			},
		],
		name: 'assertParentBlock',
		outputs: [],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{
						internalType: 'uint128',
						name: 'currentAmount1',
						type: 'uint128',
					},
					{
						internalType: 'uint128',
						name: 'currentAmount2',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'currentReporter',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'reportTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'address',
						name: 'token1',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'lastReportOppoTime',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTime',
						type: 'uint48',
					},
					{
						internalType: 'uint128',
						name: 'escalationHalt',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'protocolFeeRecipient',
						type: 'address',
					},
					{
						internalType: 'uint96',
						name: 'settlerRewardAttoEth',
						type: 'uint96',
					},
					{
						internalType: 'address',
						name: 'token2',
						type: 'address',
					},
					{
						internalType: 'uint24',
						name: 'numReports',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'disputeDelay',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'feePercentage',
						type: 'uint24',
					},
					{
						internalType: 'uint16',
						name: 'multiplier',
						type: 'uint16',
					},
					{
						internalType: 'address',
						name: 'callbackContract',
						type: 'address',
					},
					{
						internalType: 'uint32',
						name: 'callbackGasLimit',
						type: 'uint32',
					},
					{
						internalType: 'uint24',
						name: 'protocolFee',
						type: 'uint24',
					},
					{
						internalType: 'uint8',
						name: 'flags',
						type: 'uint8',
					},
				],
				internalType: 'struct IOpenOracleDispute.OracleGame',
				name: 'game',
				type: 'tuple',
			},
			{
				internalType: 'uint128',
				name: 'newAmount1',
				type: 'uint128',
			},
			{
				internalType: 'uint128',
				name: 'newAmount2',
				type: 'uint128',
			},
		],
		name: 'contributions',
		outputs: [
			{
				internalType: 'uint256',
				name: 'contribution1',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'contribution2',
				type: 'uint256',
			},
		],
		stateMutability: 'pure',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: 'openOracle',
				type: 'address',
			},
			{
				internalType: 'uint128',
				name: 'newAmount1',
				type: 'uint128',
			},
			{
				internalType: 'uint128',
				name: 'newAmount2',
				type: 'uint128',
			},
			{
				components: [
					{
						internalType: 'uint128',
						name: 'currentAmount1',
						type: 'uint128',
					},
					{
						internalType: 'uint128',
						name: 'currentAmount2',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'currentReporter',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'reportTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'address',
						name: 'token1',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'lastReportOppoTime',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTime',
						type: 'uint48',
					},
					{
						internalType: 'uint128',
						name: 'escalationHalt',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'protocolFeeRecipient',
						type: 'address',
					},
					{
						internalType: 'uint96',
						name: 'settlerRewardAttoEth',
						type: 'uint96',
					},
					{
						internalType: 'address',
						name: 'token2',
						type: 'address',
					},
					{
						internalType: 'uint24',
						name: 'numReports',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'disputeDelay',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'feePercentage',
						type: 'uint24',
					},
					{
						internalType: 'uint16',
						name: 'multiplier',
						type: 'uint16',
					},
					{
						internalType: 'address',
						name: 'callbackContract',
						type: 'address',
					},
					{
						internalType: 'uint32',
						name: 'callbackGasLimit',
						type: 'uint32',
					},
					{
						internalType: 'uint24',
						name: 'protocolFee',
						type: 'uint24',
					},
					{
						internalType: 'uint8',
						name: 'flags',
						type: 'uint8',
					},
				],
				internalType: 'struct IOpenOracleDispute.OracleGame',
				name: 'game',
				type: 'tuple',
			},
			{
				components: [
					{
						internalType: 'uint256',
						name: 'reportId',
						type: 'uint256',
					},
					{
						internalType: 'address',
						name: 'creator',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'blockTimestamp',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockNumber',
						type: 'uint256',
					},
				],
				internalType: 'struct IOpenOracleDispute.PreimageHelper',
				name: 'helper',
				type: 'tuple',
			},
			{
				components: [
					{
						internalType: 'uint256',
						name: 'blockNumber',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockNumberBound',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockTimestamp',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockTimestampBound',
						type: 'uint256',
					},
				],
				internalType: 'struct IOpenOracleDispute.TimingBoundaries',
				name: 'timing',
				type: 'tuple',
			},
		],
		name: 'dispute',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{
						internalType: 'address',
						name: 'openOracle',
						type: 'address',
					},
					{
						internalType: 'address',
						name: 'router',
						type: 'address',
					},
					{
						internalType: 'uint8',
						name: 'venue',
						type: 'uint8',
					},
					{
						internalType: 'uint24',
						name: 'poolFee',
						type: 'uint24',
					},
					{
						internalType: 'uint128',
						name: 'newAmount1',
						type: 'uint128',
					},
					{
						internalType: 'uint128',
						name: 'newAmount2',
						type: 'uint128',
					},
					{
						internalType: 'uint256',
						name: 'hedgeWethLimitAttoEth',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'swapDeadline',
						type: 'uint256',
					},
					{
						internalType: 'bytes32',
						name: 'expectedParentBlockHash',
						type: 'bytes32',
					},
				],
				internalType: 'struct OpenOracleArbitrageExecutor.HedgeRequest',
				name: 'request',
				type: 'tuple',
			},
			{
				components: [
					{
						internalType: 'uint128',
						name: 'currentAmount1',
						type: 'uint128',
					},
					{
						internalType: 'uint128',
						name: 'currentAmount2',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'currentReporter',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'reportTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'address',
						name: 'token1',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'lastReportOppoTime',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTime',
						type: 'uint48',
					},
					{
						internalType: 'uint128',
						name: 'escalationHalt',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'protocolFeeRecipient',
						type: 'address',
					},
					{
						internalType: 'uint96',
						name: 'settlerRewardAttoEth',
						type: 'uint96',
					},
					{
						internalType: 'address',
						name: 'token2',
						type: 'address',
					},
					{
						internalType: 'uint24',
						name: 'numReports',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'disputeDelay',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'feePercentage',
						type: 'uint24',
					},
					{
						internalType: 'uint16',
						name: 'multiplier',
						type: 'uint16',
					},
					{
						internalType: 'address',
						name: 'callbackContract',
						type: 'address',
					},
					{
						internalType: 'uint32',
						name: 'callbackGasLimit',
						type: 'uint32',
					},
					{
						internalType: 'uint24',
						name: 'protocolFee',
						type: 'uint24',
					},
					{
						internalType: 'uint8',
						name: 'flags',
						type: 'uint8',
					},
				],
				internalType: 'struct IOpenOracleDispute.OracleGame',
				name: 'game',
				type: 'tuple',
			},
			{
				components: [
					{
						internalType: 'uint256',
						name: 'reportId',
						type: 'uint256',
					},
					{
						internalType: 'address',
						name: 'creator',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'blockTimestamp',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockNumber',
						type: 'uint256',
					},
				],
				internalType: 'struct IOpenOracleDispute.PreimageHelper',
				name: 'helper',
				type: 'tuple',
			},
			{
				components: [
					{
						internalType: 'uint256',
						name: 'blockNumber',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockNumberBound',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockTimestamp',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockTimestampBound',
						type: 'uint256',
					},
				],
				internalType: 'struct IOpenOracleDispute.TimingBoundaries',
				name: 'timing',
				type: 'tuple',
			},
		],
		name: 'hedgeAndDispute',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{
						internalType: 'address',
						name: 'openOracle',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'parentBlockNumber',
						type: 'uint256',
					},
					{
						internalType: 'bytes32',
						name: 'expectedParentBlockHash',
						type: 'bytes32',
					},
					{
						internalType: 'uint128',
						name: 'amount1',
						type: 'uint128',
					},
					{
						internalType: 'uint128',
						name: 'amount2',
						type: 'uint128',
					},
				],
				internalType: 'struct OpenOracleArbitrageExecutor.LifecycleRequest',
				name: 'request',
				type: 'tuple',
			},
			{
				components: [
					{
						internalType: 'uint128',
						name: 'currentAmount1',
						type: 'uint128',
					},
					{
						internalType: 'uint128',
						name: 'currentAmount2',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'currentReporter',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'reportTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTimestamp',
						type: 'uint48',
					},
					{
						internalType: 'address',
						name: 'token1',
						type: 'address',
					},
					{
						internalType: 'uint48',
						name: 'lastReportOppoTime',
						type: 'uint48',
					},
					{
						internalType: 'uint48',
						name: 'settlementTime',
						type: 'uint48',
					},
					{
						internalType: 'uint128',
						name: 'escalationHalt',
						type: 'uint128',
					},
					{
						internalType: 'address',
						name: 'protocolFeeRecipient',
						type: 'address',
					},
					{
						internalType: 'uint96',
						name: 'settlerRewardAttoEth',
						type: 'uint96',
					},
					{
						internalType: 'address',
						name: 'token2',
						type: 'address',
					},
					{
						internalType: 'uint24',
						name: 'numReports',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'disputeDelay',
						type: 'uint24',
					},
					{
						internalType: 'uint24',
						name: 'feePercentage',
						type: 'uint24',
					},
					{
						internalType: 'uint16',
						name: 'multiplier',
						type: 'uint16',
					},
					{
						internalType: 'address',
						name: 'callbackContract',
						type: 'address',
					},
					{
						internalType: 'uint32',
						name: 'callbackGasLimit',
						type: 'uint32',
					},
					{
						internalType: 'uint24',
						name: 'protocolFee',
						type: 'uint24',
					},
					{
						internalType: 'uint8',
						name: 'flags',
						type: 'uint8',
					},
				],
				internalType: 'struct IOpenOracleDispute.OracleGame',
				name: 'game',
				type: 'tuple',
			},
			{
				components: [
					{
						internalType: 'uint256',
						name: 'reportId',
						type: 'uint256',
					},
					{
						internalType: 'address',
						name: 'creator',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'blockTimestamp',
						type: 'uint256',
					},
					{
						internalType: 'uint256',
						name: 'blockNumber',
						type: 'uint256',
					},
				],
				internalType: 'struct IOpenOracleDispute.PreimageHelper',
				name: 'helper',
				type: 'tuple',
			},
		],
		name: 'settleAndWithdraw',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'bytes',
				name: 'data',
				type: 'bytes',
			},
		],
		name: 'unlockCallback',
		outputs: [
			{
				internalType: 'bytes',
				name: 'result',
				type: 'bytes',
			},
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{
						internalType: 'address',
						name: 'openOracle',
						type: 'address',
					},
					{
						internalType: 'address',
						name: 'token',
						type: 'address',
					},
					{
						internalType: 'uint256',
						name: 'parentBlockNumber',
						type: 'uint256',
					},
					{
						internalType: 'bytes32',
						name: 'expectedParentBlockHash',
						type: 'bytes32',
					},
					{
						internalType: 'uint256',
						name: 'amount',
						type: 'uint256',
					},
				],
				internalType: 'struct OpenOracleArbitrageExecutor.ReplacementWithdrawalRequest',
				name: 'request',
				type: 'tuple',
			},
			{
				internalType: 'uint256',
				name: 'reportId',
				type: 'uint256',
			},
		],
		name: 'withdrawReplacementCredit',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		stateMutability: 'payable',
		type: 'receive',
	},
] as const
