import { promises as fs } from 'node:fs'
import path from 'node:path'
import solc from 'solc'

const projectRoot = path.resolve(import.meta.dir, '../..')
const repositoryRoot = path.resolve(projectRoot, '..')
const contractRoot = path.join(projectRoot, 'contracts')
const importPattern = /import\s+(?:[^'\"]+\s+from\s+)?['\"]([^'\"]+)['\"];?/g

async function solidityFiles(directory: string): Promise<string[]> {
	const entries = await fs.readdir(directory, { withFileTypes: true })
	const nested = await Promise.all(
		entries.map(entry => {
			const location = path.join(directory, entry.name)
			return entry.isDirectory() ? solidityFiles(location) : Promise.resolve(entry.name.endsWith('.sol') ? [location] : [])
		}),
	)
	return nested.flat()
}

async function collectSource(file: string, sources: Map<string, { content: string }>, sourceNameOverride?: string) {
	const sourceName = sourceNameOverride ?? path.relative(repositoryRoot, file).replaceAll('\\', '/')
	if (sources.has(sourceName)) return
	const rawContent = await fs.readFile(file, 'utf8')
	const content = rawContent.replace('pragma solidity 0.8.28;', 'pragma solidity 0.8.35;')
	sources.set(sourceName, { content })
	for (const match of content.matchAll(importPattern)) {
		const importName = match[1]
		if (importName === undefined) throw new Error(`Malformed import in ${sourceName}`)
		if (importName.startsWith('@openzeppelin/contracts/')) {
			const vendorRelative = importName.slice('@openzeppelin/contracts/'.length)
			const vendorFile = path.join(repositoryRoot, 'solidity/contracts/peripherals/openOracle/openzeppelin/contracts', vendorRelative)
			await collectSource(vendorFile, sources, importName)
			continue
		}
		if (!importName.startsWith('.')) throw new Error(`Unsupported package import ${importName} in ${sourceName}`)
		const importedSourceName = path.posix.normalize(path.posix.join(path.posix.dirname(sourceName), importName))
		await collectSource(path.resolve(path.dirname(file), importName), sources, importedSourceName)
	}
}

type TradingContracts = typeof import('../artifacts/contractArtifact.ts').tradingContracts

export async function compileTradingContracts({ writeArtifacts = true }: { writeArtifacts?: boolean } = {}): Promise<TradingContracts> {
	const sources = new Map<string, { content: string }>()
	for (const file of await solidityFiles(contractRoot)) await collectSource(file, sources)

	const input = {
		language: 'Solidity',
		sources: Object.fromEntries(sources),
		settings: {
			viaIR: true,
			evmVersion: 'osaka',
			optimizer: { enabled: true, runs: 1_000 },
			metadata: { appendCBOR: false, bytecodeHash: 'none' },
			outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object', 'storageLayout'] } },
		},
	}

	const output = JSON.parse(solc.compile(JSON.stringify(input))) as {
		errors?: { severity: string; formattedMessage: string }[]
		contracts?: Record<string, Record<string, unknown>>
	}
	const diagnostics = output.errors ?? []
	for (const diagnostic of diagnostics.filter(item => item.severity !== 'error')) console.warn(diagnostic.formattedMessage)
	const errors = diagnostics.filter(item => item.severity === 'error')
	if (errors.length > 0) throw new Error(errors.map(error => error.formattedMessage).join('\n'))
	if (output.contracts === undefined) throw new Error('Compiler returned no contracts')

	const contracts = Object.fromEntries(Object.entries(output.contracts).filter(([source]) => source.startsWith('trading/contracts/'))) as TradingContracts
	if (writeArtifacts) {
		const artifactsDirectory = path.join(projectRoot, 'artifacts')
		const typedArtifactDirectory = path.join(projectRoot, 'ts/artifacts')
		const uiArtifactDirectory = path.join(projectRoot, 'ui/ts/generated')
		await Promise.all([fs.mkdir(artifactsDirectory, { recursive: true }), fs.mkdir(typedArtifactDirectory, { recursive: true }), fs.mkdir(uiArtifactDirectory, { recursive: true })])
		const artifactJson = `${JSON.stringify({ compiler: solc.version(), settings: input.settings, contracts }, undefined, 2)}\n`
		const typedArtifact = `// Generated by trading/ts/compiler/compile.mts. Do not edit.\nexport const tradingContracts = ${JSON.stringify(contracts)} as const\n`
		await Promise.all([fs.writeFile(path.join(artifactsDirectory, 'Contracts.json'), artifactJson), fs.writeFile(path.join(typedArtifactDirectory, 'contractArtifact.ts'), typedArtifact), fs.writeFile(path.join(uiArtifactDirectory, 'contractArtifact.ts'), typedArtifact)])
		console.log(`Compiled ${Object.keys(contracts).length} trading Solidity source files with ${solc.version()}`)
	}
	return contracts
}

const invokedPath = process.argv[1]
if (invokedPath !== undefined && path.resolve(invokedPath) === import.meta.path) await compileTradingContracts()
