import { operatorSnapshot, type OperatorSnapshot, type OperatorState } from '#state/operator-state'
import type { PositionRecord } from '#state/position-store'
import { emptySettlementSnapshot } from '#state/settlement-store'
import { address, checkedAt, executor, hash, now, openOracle, pool, rep, repNo, repYes, sampledAt, transactionHash, wallet } from './fixture-constants.mts'

const history = [
	{
		actualGasCostEth: '0.0011',
		blockNumber: '23841995',
		direction: 'sell-rep' as const,
		estimatedNetProfitWeth: '0.0184',
		estimatedProfitBeforeGasEth: '0.0202',
		executedAt: sampledAt(74),
		pool,
		poolFee: 3_000,
		reportId: '814',
		requiredToken: '42',
		requiredWeth: '0.164',
		token: rep,
		tokenSymbol: 'REPv2',
		trackedNetProfitEth: '0.0179',
		transactionHash: transactionHash('fixture-814'),
	},
	{
		actualGasCostEth: '0.0013',
		blockNumber: '23842041',
		direction: 'buy-rep' as const,
		estimatedNetProfitWeth: '0.0121',
		estimatedProfitBeforeGasEth: '0.0140',
		executedAt: sampledAt(51),
		pool,
		poolFee: 500,
		reportId: '815',
		requiredToken: '31',
		requiredWeth: '0.128',
		token: repYes,
		tokenSymbol: 'REPv2_YES',
		trackedNetProfitEth: '0.0114',
		transactionHash: transactionHash('fixture-815'),
	},
	{
		actualGasCostEth: '0.0010',
		blockNumber: '23842088',
		direction: 'sell-rep' as const,
		estimatedNetProfitWeth: '0.0158',
		estimatedProfitBeforeGasEth: '0.0174',
		executedAt: sampledAt(28),
		pool,
		poolFee: 3_000,
		reportId: '816',
		requiredToken: '38',
		requiredWeth: '0.151',
		token: repNo,
		tokenSymbol: 'REPv2_NO',
		trackedNetProfitEth: '0.0151',
		transactionHash: transactionHash('fixture-816'),
	},
]

const tokenMarkets = [
	{
		address: rep,
		balance: '184.25',
		decimals: 18,
		name: 'Reputation',
		pools: [
			{ address: address(0x3101), fee: 3_000, liquidity: '168234922505184', priceWeth: '0.00418', url: 'https://etherscan.io/address/0x0000000000000000000000000000000000003101', venue: 'Uniswap V3' },
			{ address: address(0x3102), fee: 3_000, liquidity: '8240 REPv2 / 34.18 WETH', priceWeth: '0.004147', url: 'https://etherscan.io/address/0x0000000000000000000000000000000000003102', venue: 'Uniswap V2' },
		],
		symbol: 'REPv2',
	},
	{
		address: repYes,
		balance: '71',
		decimals: 18,
		name: 'Reputation YES',
		pools: [{ address: address(0x3201), fee: 10_000, liquidity: '28100821380564', priceWeth: '0.00372', url: 'https://etherscan.io/address/0x0000000000000000000000000000000000003201', venue: 'Uniswap V3' }],
		symbol: 'REPv2_YES',
	},
	{
		address: repNo,
		balance: '55',
		decimals: 18,
		name: 'Reputation NO',
		pools: [],
		symbol: 'REPv2_NO',
	},
]

const priceHistory = tokenMarkets.flatMap(token =>
	token.pools.flatMap(poolSnapshot =>
		poolSnapshot.priceWeth === undefined
			? []
			: [35, 28, 21, 14, 7, 0].map((minutesAgo, index) => ({
					blockNumber: (23_842_080 + index * 12).toString(),
					pool: poolSnapshot.address,
					priceWeth: (Number(poolSnapshot.priceWeth) * (0.985 + index * 0.006)).toFixed(7),
					sampledAt: sampledAt(minutesAgo),
					symbol: token.symbol,
					token: token.address,
					venue: `${poolSnapshot.venue} ${(poolSnapshot.fee / 10_000).toString()}%`,
				})),
	),
)

const openPosition = {
	account: wallet,
	actualEntryGasCostEth: '0.0034',
	capitalAtRiskWeth: '0.151',
	closedAt: undefined,
	direction: 'sell-rep',
	entryTransactionHash: hash,
	entryTransactionHashes: [hash],
	gasExpenditures: [{ costEth: '0.0034', minedAt: sampledAt(1), transactionHash: hash }],
	historyOutbox: undefined,
	hedgeAmountToken: '38',
	hedgeWeth: '0.1692',
	hedgedProfitBeforeGasEth: '0.0182',
	lifecycleGasCostEth: '0',
	lifecycleReceiptRecovered: false,
	lifecycleTargetBlockNumber: undefined,
	lifecycleTokenDecimals: undefined,
	lifecycleTransactionHashes: [],
	lifecycleUpdatedAt: undefined,
	lifecycleWalletTokenBefore: undefined,
	lifecycleWalletWethBefore: undefined,
	lockedToken: '38',
	lockedWeth: '0.151',
	manualReconciliation: undefined,
	openedAt: sampledAt(1),
	realizedNetProfitEth: undefined,
	reportId: '816',
	status: 'open',
	token: repNo,
	tokenSymbol: 'REPv2_NO',
	withdrawnToken: '0',
	withdrawnWeth: '0',
} satisfies PositionRecord

const closedPositionHash = transactionHash('closed-open-oracle-documentation-fixture')
const closedPosition = {
	account: wallet,
	actualEntryGasCostEth: '0.0011',
	capitalAtRiskWeth: '0.164',
	closedAt: sampledAt(60),
	direction: 'sell-rep',
	entryTransactionHash: closedPositionHash,
	entryTransactionHashes: [closedPositionHash],
	gasExpenditures: [
		{ costEth: '0.0011', minedAt: sampledAt(74), transactionHash: closedPositionHash },
		{ costEth: '0.0008', minedAt: sampledAt(60), transactionHash: transactionHash('closed-lifecycle-documentation-fixture') },
	],
	historyOutbox: undefined,
	hedgeAmountToken: '42',
	hedgeWeth: '0.1955',
	hedgedProfitBeforeGasEth: '0.0315',
	lifecycleGasCostEth: '0.0008',
	lifecycleReceiptRecovered: true,
	lifecycleSettlerRewardEth: '0.002',
	lifecycleTargetBlockNumber: undefined,
	lifecycleTokenDecimals: undefined,
	lifecycleTransactionHashes: [],
	lifecycleUpdatedAt: sampledAt(60),
	lifecycleWalletTokenBefore: undefined,
	lifecycleWalletWethBefore: undefined,
	lockedToken: '42',
	lockedWeth: '0.164',
	manualReconciliation: undefined,
	openedAt: sampledAt(74),
	realizedNetProfitEth: '0.0316',
	reportId: '814',
	status: 'closed',
	token: rep,
	tokenSymbol: 'REPv2',
	withdrawnToken: '42',
	withdrawnWeth: '0.164',
} satisfies PositionRecord

const positions = [openPosition, closedPosition]
const positionDerivedSnapshot = operatorSnapshot(
	{
		activeReportCount: 0,
		balances: undefined,
		blockNumber: '23842152',
		blockTimestamp: Math.floor((now - 4_000) / 1_000).toString(),
		centralizedMarket: {
			assetId: rep,
			askDepthAttoEth: 63n * 10n ** 17n,
			bidDepthAttoEth: 71n * 10n ** 17n,
			chainId: 1,
			maximumPriceRepPerEth: 1042n * 10n ** 16n,
			minimumPriceRepPerEth: 1031n * 10n ** 16n,
			observations: [
				{ assetId: rep, askDepthAttoEth: 34n * 10n ** 17n, bestAskQuote: '9.72', bestBidQuote: '9.68', bidDepthAttoEth: 38n * 10n ** 17n, chainId: 1, ethTickerTimestamp: now, exchangeId: 'kraken', observedAt: now, orderBookTimestamp: now, priceRepPerEth: 1031n * 10n ** 16n, repMarket: 'REP/USD', usesEthTicker: true },
				{
					assetId: rep,
					askDepthAttoEth: 29n * 10n ** 17n,
					bestAskQuote: '0.097',
					bestBidQuote: '0.096',
					bidDepthAttoEth: 33n * 10n ** 17n,
					chainId: 1,
					ethTickerTimestamp: undefined,
					exchangeId: 'coinbase',
					observedAt: now,
					orderBookTimestamp: now,
					priceRepPerEth: 1042n * 10n ** 16n,
					repMarket: 'REP/ETH',
					usesEthTicker: false,
				},
			],
			priceRepPerEth: 10365n * 10n ** 15n,
			reasons: [],
			reliable: true,
		},
		marketConsensus: {
			assetId: rep,
			cex: {
				askDepthAttoEth: 63n * 10n ** 17n,
				bidDepthAttoEth: 71n * 10n ** 17n,
				kind: 'cex',
				maximumPriceRepPerEth: 1042n * 10n ** 16n,
				minimumPriceRepPerEth: 1031n * 10n ** 16n,
				observations: [
					{ assetId: rep, askDepthAttoEth: 34n * 10n ** 17n, bidDepthAttoEth: 38n * 10n ** 17n, chainId: 1, kind: 'cex', observationId: 'kraken:1', observedAt: now, priceRepPerEth: 1031n * 10n ** 16n, sourceId: 'kraken' },
					{ assetId: rep, askDepthAttoEth: 29n * 10n ** 17n, bidDepthAttoEth: 33n * 10n ** 17n, chainId: 1, kind: 'cex', observationId: 'coinbase:1', observedAt: now, priceRepPerEth: 1042n * 10n ** 16n, sourceId: 'coinbase' },
				],
				priceRepPerEth: 10365n * 10n ** 15n,
				reasons: [],
				reliable: true,
			},
			chainId: 1,
			dex: {
				askDepthAttoEth: 48n * 10n ** 17n,
				bidDepthAttoEth: 52n * 10n ** 17n,
				kind: 'dex',
				maximumPriceRepPerEth: 1041n * 10n ** 16n,
				minimumPriceRepPerEth: 1037n * 10n ** 16n,
				observations: [
					{ assetId: rep, askDepthAttoEth: 24n * 10n ** 17n, bidDepthAttoEth: 26n * 10n ** 17n, chainId: 1, kind: 'dex', observationId: 'uniswap-v2:1', observedAt: now, priceRepPerEth: 1037n * 10n ** 16n, sourceId: 'uniswap-v2' },
					{ assetId: rep, askDepthAttoEth: 24n * 10n ** 17n, bidDepthAttoEth: 26n * 10n ** 17n, chainId: 1, kind: 'dex', observationId: 'uniswap-v3:1', observedAt: now, priceRepPerEth: 1041n * 10n ** 16n, sourceId: 'uniswap-v3' },
				],
				priceRepPerEth: 1039n * 10n ** 16n,
				reasons: [],
				reliable: true,
			},
			priceRepPerEth: 103775n * 10n ** 14n,
			reasons: [],
			reliable: true,
			sourceCount: 4,
		},
		endpointChecks: [],
		executionHistory: [],
		gameCapital: { eth: '0', totalEthWeth: '0', weth: '0' },
		lastError: undefined,
		lastPollAt: undefined,
		operationLog: [],
		opportunities: [],
		paused: false,
		positions,
		priceHistory: [],
		reportPaths: [],
		status: 'running',
		tokenAddresses: [],
		tokenMarkets: [],
		settlements: emptySettlementSnapshot(),
		transactionActivity: [],
	} satisfies OperatorState,
	{ maxSpotTwapTicks: 120n, minimumProfitBps: 100n, minimumProfitAttoWeth: 10n ** 16n, minimumRemainingBlocks: 3n, minimumRemainingSeconds: 36n, pollMilliseconds: 12_000, twapSeconds: 1_800 },
	{ minimumBundleRelaySuccesses: 1, mode: 'private', relayUrls: ['https://relay.flashbots.net/'] },
	{ publicRpcUrls: ['https://rpc.example/'], readRpcUrl: 'https://read.example/' },
	{ execute: true, executor, expectedChainId: 1, explorerUrl: 'https://etherscan.io', network: 'mainnet', openOracle, queuedSigner: undefined, savedWallet: wallet, wallet },
	{ lifecycleGasReserveAttoWeth: 10n ** 16n, maxConcurrentPositions: 2, maxDailyGasSpendAttoWeth: 5n * 10n ** 16n, maxPositionNotionalAttoWeth: 5n * 10n ** 18n, maxTotalLockedAttoWeth: 10n * 10n ** 18n },
)

/** The healthy mainnet operator snapshot every capture starts from; `fixture-state.mts` derives each scenario from it. */
export const snapshot = {
	activeReportCount: 3,
	balances: { availableEth: '1.842', availableRep: '184.25', availableWeth: '2.375', repValueWeth: '0.770165', totalValueWeth: '4.987165' },
	blockNumber: '23842152',
	blockTimestamp: Math.floor((now - 4_000) / 1_000).toString(),
	centralizedMarket: positionDerivedSnapshot.centralizedMarket,
	marketConsensus: positionDerivedSnapshot.marketConsensus,
	connectivity: { publicRpcUrls: ['https://rpc.example/'], readRpcUrl: 'https://read.example/' },
	deployment: positionDerivedSnapshot.deployment,
	endpointChecks: [
		{ chainId: 1, checkedAt, error: undefined, kind: 'read-rpc' as const, status: 'healthy' as const, target: 'https://read.example' },
		{ chainId: 1, checkedAt, error: undefined, kind: 'public-rpc' as const, status: 'healthy' as const, target: 'https://rpc.example' },
		{ chainId: 1, checkedAt, error: undefined, kind: 'private-relay' as const, status: 'healthy' as const, target: 'https://relay.flashbots.net' },
	],
	rpcEndpointHealth: [
		{ consecutiveFailures: 0, error: undefined, lastFailureAt: undefined, lastSuccessAt: sampledAt(0), latencyMilliseconds: 76, nextRetryAt: undefined, status: 'healthy', target: 'https://rpc.example' },
		{ consecutiveFailures: 1, error: 'HTTP 503 while calling eth_blockNumber', lastFailureAt: sampledAt(0), lastSuccessAt: undefined, latencyMilliseconds: 112, nextRetryAt: sampledAt(60), status: 'degraded', target: 'https://quorum.example' },
	],
	execute: true,
	executionHistory: history,
	executionHistoryRecordCount: history.length,
	executor,
	expectedChainId: 1,
	explorerUrl: 'https://etherscan.io',
	gameCapital: { eth: '0.06', totalEthWeth: '1.284', weth: '1.224' },
	lastError: undefined,
	lastPollAt: sampledAt(0),
	mode: 'execute' as const,
	network: 'mainnet' as const,
	networkConfigured: true,
	openOracle,
	operationLog: [
		{ category: 'decision' as const, details: 'net 0.0158 ETH · 992 bps', level: 'info' as const, message: 'Selected profitable sell-REP dispute', reason: 'quote, TWAP, inventory, and risk checks passed', reportId: '816', timestamp: sampledAt(1) },
		{ category: 'transaction' as const, details: 'https://relay.flashbots.net', level: 'info' as const, message: 'Atomic entry accepted', reason: 'target block 23842153', reportId: '816', timestamp: sampledAt(1) },
		{ category: 'configuration' as const, details: '3 supported REP-family tokens', level: 'info' as const, message: 'Token catalog synchronized', reason: undefined, reportId: undefined, timestamp: sampledAt(2) },
	],
	opportunities: [
		{
			centralizedPriceDeviationBps: '86',
			decision: 'selected' as const,
			direction: 'sell-rep' as const,
			estimatedNetProfitEth: '0.0158',
			estimatedNetProfitWeth: '0.0158',
			executablePriceRepPerEth: '10.284',
			hasRequiredInventory: true,
			pool,
			poolFee: 3_000,
			reportId: '816',
			requiredToken: '38',
			requiredWeth: '0.151',
			timeRemaining: '27',
			token: repNo,
			tokenSymbol: 'REPv2_NO',
			venue: 'uniswap-v4' as const,
			windowUnit: 'blocks' as const,
		},
		{
			centralizedPriceDeviationBps: undefined,
			decision: 'unprofitable' as const,
			direction: 'buy-rep' as const,
			estimatedNetProfitEth: '-0.0012',
			estimatedNetProfitWeth: '-0.0012',
			executablePriceRepPerEth: '9.845',
			hasRequiredInventory: true,
			pool: address(0x3201),
			poolFee: 10_000,
			reportId: '817',
			requiredToken: '24',
			requiredWeth: '0.098',
			timeRemaining: '42',
			token: repYes,
			tokenSymbol: 'REPv2_YES',
			venue: 'uniswap-v3' as const,
			windowUnit: 'blocks' as const,
		},
	],
	paused: false,
	operatorCapable: true,
	positionRecordCount: positionDerivedSnapshot.positionRecordCount,
	positions: positionDerivedSnapshot.positions,
	priceHistory,
	queuedSettings: [],
	queuedSigner: undefined,
	reportPaths: [
		{
			reportId: '816',
			settled: false,
			steps: [
				{ amount1: '38', amount2: '0.151', blockNumber: '23842088', event: 'submitted' as const, reporter: address(0xb0b), transactionHash: transactionHash('submitted-816') },
				{ amount1: '40', amount2: '0.159', blockNumber: '23842112', event: 'disputed' as const, reporter: wallet, transactionHash: hash },
			],
		},
	],
	risk: positionDerivedSnapshot.risk,
	savedWallet: wallet,
	settlements: positionDerivedSnapshot.settlements,
	settings: { maxSpotTwapTicks: '120', minimumProfitBps: '100', minimumProfitWeth: '0.01', minimumRemainingBlocks: '3', minimumRemainingSeconds: '36', pollMilliseconds: 12_000, twapSeconds: 1_800 },
	status: 'running' as const,
	submission: { minimumBundleRelaySuccesses: 1, mode: 'private' as const, relayUrls: ['https://relay.flashbots.net/'] },
	tokenAddresses: [rep, repYes, repNo],
	tokenMarkets,
	totalActualGasCostEth: '0.0034',
	totalEstimatedNetProfitEth: '0.0463',
	totalEstimatedNetProfitWeth: '0.0463',
	totalHedgedProfitBeforeGasEth: positionDerivedSnapshot.totalHedgedProfitBeforeGasEth,
	totalOpenHedgedNetProfitEth: positionDerivedSnapshot.totalOpenHedgedNetProfitEth,
	totalRealizedNetProfitEth: positionDerivedSnapshot.totalRealizedNetProfitEth,
	totalRevenueBeforeGasEth: '0.0516',
	totalTrackedNetProfitEth: '0.0444',
	transactionActivity: [
		{
			acceptedTargets: ['https://relay.flashbots.net'],
			actualGasCostEth: undefined,
			estimatedNetProfitEth: '0.0158',
			failedTargets: [],
			hash,
			kind: 'dispute' as const,
			mode: 'private' as const,
			originalHash: hash,
			reportId: '816',
			status: 'pending' as const,
			submittedAt: sampledAt(1),
			token: repNo,
			tokenSymbol: 'REPv2_NO',
			trackedNetProfitEth: undefined,
			updatedAt: sampledAt(1),
		},
	],
	updatedAt: sampledAt(0),
	wallet,
} satisfies OperatorSnapshot

if (
	snapshot.positionRecordCount !== positions.length ||
	snapshot.risk.usage.openPositions !== 1 ||
	snapshot.risk.usage.lockedWeth !== openPosition.capitalAtRiskWeth ||
	snapshot.totalOpenHedgedNetProfitEth !== '0.0148' ||
	snapshot.totalRealizedNetProfitEth !== closedPosition.realizedNetProfitEth ||
	snapshot.totalTrackedNetProfitEth !== '0.0444'
) {
	throw new Error('OpenOracle documentation fixture position, risk, and profit totals are inconsistent')
}
