export type ContractAtlasBehavioralReference = {
	members: string[]
	relation: 'calls' | 'tests' | 'uses'
	source: string
	target: string
}

export function contractAtlasBehavioralRelationIsCovered(behavioralRelation: ContractAtlasBehavioralReference['relation'], atlasRelation: string): boolean {
	return behavioralRelation === 'calls' ? atlasRelation === 'calls' || atlasRelation === 'assets' : behavioralRelation === atlasRelation
}

const contractAtlasBehavioralReferenceRows: readonly (readonly [source: string, target: string, relation: ContractAtlasBehavioralReference['relation'], ...members: string[]])[] = [
	['openoracle-core', 'openoracle-ierc20', 'calls', 'transfer'],
	['openoracle-safe-erc20', 'openoracle-ierc1363', 'calls', 'approveAndCall', 'transferAndCall', 'transferFromAndCall'],
	['openoracle-safe-erc20', 'openoracle-ierc20', 'calls', 'allowance', 'approve', 'transfer', 'transferFrom'],
	['statoblast-auction-settlement-base', 'statoblast-security-pool-interface', 'calls', 'addFeeEligibleSecurityBondAllowance', 'configureVault', 'poolOwnershipDenominator', 'securityVaults', 'updateVaultFees'],
	['statoblast-escalation-carry', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-escalation-carry', 'statoblast-forker-interface', 'calls', 'getDirectlyClaimedEscalationPrincipal'],
	['statoblast-escalation-carry', 'statoblast-merkle-mountain-range', 'uses', 'hashLeaf', 'hashParent'],
	['statoblast-escalation-carry', 'zoltar-constants', 'uses', 'MINIMUM_FORK_BURN_DIVISOR'],
	['statoblast-escalation-deposit-delegate', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-escalation-escrow', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-escalation-game', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-escalation-game', 'statoblast-escalation-proof-verifier', 'calls', 'computeLnRatioScaled'],
	['statoblast-escalation-game-factory', 'statoblast-escalation-game', 'calls', 'start', 'startFromFork'],
	['statoblast-escalation-game-forker', 'statoblast-security-pool-interface', 'calls', 'configureVault', 'escalationGame', 'securityVaults', 'systemState'],
	['statoblast-escalation-game-forker', 'statoblast-security-pool-utils', 'uses', 'MIGRATION_TIME'],
	['statoblast-escalation-proof-verifier', 'statoblast-binary-outcomes', 'uses', 'Invalid', 'No', 'None', 'Yes'],
	['statoblast-escalation-settlement', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-escalation-state', 'statoblast-security-pool-interface', 'calls', 'securityPoolForker'],
	['statoblast-escalation-state', 'zoltar-safe-erc20-ops', 'uses', 'safeTransfer', 'using for IERC20'],
	['statoblast-forker-base', 'statoblast-escalation-game', 'calls', 'forkCarrySnapshotInitialized'],
	['statoblast-forker-base', 'statoblast-security-pool-factory-interface', 'calls', 'getSecurityPoolOriginId'],
	['statoblast-forker-base', 'statoblast-security-pool-interface', 'calls', 'awaitingForkContinuation', 'escalationGame', 'initializeForkCarrySnapshotWithResolutionBalances', 'poolOwnershipDenominator', 'repToken', 'resumeForkedEscalationGame', 'securityPoolFactory', 'setAwaitingForkContinuation', 'systemState'],
	['statoblast-forker-base', 'statoblast-security-pool-utils', 'uses', 'PRICE_PRECISION'],
	['statoblast-migration-proxy', 'zoltar-safe-erc20-ops', 'uses', 'safeApprove', 'safeTransfer', 'using for IERC20'],
	[
		'statoblast-pool-forker',
		'statoblast-security-pool-interface',
		'calls',
		'activateForkMode',
		'completeSetCollateralAmount',
		'escalationGame',
		'initializeForkedEscalationGame',
		'parent',
		'poolOwnershipDenominator',
		'questionId',
		'repToken',
		'setOwnershipDenominator',
		'setSystemState',
		'setTotalShares',
		'shareToken',
		'shareTokenSupply',
		'systemState',
		'universeId',
		'updateCollateralAmount',
		'updateRetentionRate',
	],
	['statoblast-pool-forker', 'zoltar-safe-erc20-ops', 'uses', 'safeTransfer', 'using for IERC20'],
	[
		'statoblast-price-coordinator',
		'statoblast-security-pool-interface',
		'calls',
		'completeSetCollateralAmount',
		'getTotalRepBalance',
		'isEscalationResolved',
		'performLiquidation',
		'performSetSecurityBondsAllowance',
		'performWithdrawRep',
		'poolOwnershipDenominator',
		'poolOwnershipToRep',
		'repToPoolOwnership',
		'securityVaults',
		'statoblastSecurityMultiplierBps',
	],
	['statoblast-price-coordinator', 'statoblast-stored-open-oracle-game', 'calls', 'storedGame'],
	['statoblast-security-pool', 'statoblast-forker-interface', 'calls', 'getQuestionOutcome'],
	['statoblast-security-pool', 'statoblast-security-pool-factory-interface', 'calls', 'getSecurityPoolHasInheritedForkOutcome'],
	['statoblast-security-pool', 'statoblast-security-pool-interface', 'calls', 'priceOracleManagerAndOperatorQueuer', 'universeId'],
	['statoblast-security-pool', 'statoblast-share-token-interface', 'calls', 'authorize', 'burnCompleteSets', 'burnTokenIdAndGetRemainingSupply', 'getTokenId', 'mintCompleteSets'],
	['statoblast-security-pool', 'zoltar-safe-erc20-ops', 'uses', 'safeApprove', 'safeTransfer', 'safeTransferFrom', 'using for IERC20'],
	['statoblast-security-pool-deployer', 'statoblast-security-pool-worker', 'calls', 'deploy'],
	['statoblast-security-pool-factory', 'statoblast-security-pool-interface', 'calls', 'priceOracleManagerAndOperatorQueuer', 'setStartingParams', 'shareToken', 'universeId'],
	['statoblast-security-pool-factory', 'statoblast-security-pool-utils', 'uses', 'BPS_DENOMINATOR', 'calculateRetentionRate'],
	['statoblast-security-pool-factory', 'statoblast-share-token-interface', 'calls', 'authorize'],
	['statoblast-share-token', 'statoblast-erc1155', 'calls', '_internalBatchTransferFrom', '_internalTransferFrom'],
	['statoblast-share-token', 'statoblast-forker-interface', 'calls', 'createChildUniverse', 'initiateSecurityPoolFork'],
	['statoblast-share-token', 'zoltar-constants', 'uses', 'NUM_OUTCOMES'],
	['statoblast-vault-migration-base', 'openoracle-math', 'uses', 'ceilDiv'],
	[
		'statoblast-vault-migration-base',
		'statoblast-security-pool-interface',
		'calls',
		'authorizeChildPool',
		'completeSetCollateralAmount',
		'configureVault',
		'escalationGame',
		'feeIndex',
		'parent',
		'poolOwnershipDenominator',
		'questionId',
		'repToken',
		'securityPoolFactory',
		'securityPoolForker',
		'securityVaults',
		'setAwaitingForkContinuation',
		'setOwnershipDenominator',
		'shareToken',
		'statoblastSecurityMultiplierBps',
		'systemState',
		'totalSecurityBondAllowance',
		'transferEth',
		'truthAuction',
		'universeId',
		'updateCollateralAmount',
		'updateVaultFees',
	],
	['statoblast-vault-migration-base', 'statoblast-security-pool-utils', 'uses', 'MIGRATION_TIME', 'PRICE_PRECISION', 'calculateRetentionRate'],
	['statoblast-vault-migration-delegate', 'statoblast-child-game-initializer', 'calls', 'initializeChildForkedEscalationGameIfNeeded'],
	['statoblast-vault-migration-delegate', 'statoblast-security-pool-interface', 'calls', 'parent', 'setPoolFinancials', 'setSystemState', 'totalSecurityBondAllowance'],
	['statoblast-vault-migration-delegate', 'statoblast-security-pool-utils', 'uses', 'MIGRATION_TIME'],
	['test-complete-set-reentrant-receiver', 'statoblast-security-pool-interface', 'tests', 'createCompleteSet'],
	['test-coverage-helpers-harness', 'statoblast-merkle-mountain-range', 'uses', 'bagPeaks', 'hashLeaf', 'hashParent'],
	['test-coverage-helpers-harness', 'statoblast-escalation-proof-verifier', 'tests', 'bagCarryPeaks', 'computeEmptyNullifierRoot', 'computeMerkleMountainRangeRootFromProof', 'computeNullifierRoot', 'getCurrentCarryPeakForLeaf'],
	['test-coverage-helpers-harness', 'statoblast-token-id', 'uses', 'getTokenId', 'getTokenIds', 'unpackTokenId'],
	['test-coverage-helpers-harness', 'zoltar-safe-erc20-ops', 'uses', 'safeApprove', 'safeTransfer', 'safeTransferFrom', 'using for IERC20'],
	['test-coverage-helpers-harness', 'zoltar-scalar-outcomes', 'uses', 'absoluteInt256', 'addInt256Uint256', 'getScalarOutcomeName', 'intToDecimalString', 'mulDiv', 'uintToString', 'zeroPadLeft'],
	['test-escalation-factory-coverage-pool', 'statoblast-binary-outcomes', 'uses', 'None'],
	['test-escalation-forker-harness', 'statoblast-escalation-game', 'tests', 'exportForkedEscrowByOutcomeWithoutTransfer', 'exportVaultUnresolvedTotalsWithoutTransfer', 'recordForkedEscrowForOutcome'],
	[
		'test-escalation-proof-pool',
		'statoblast-escalation-game',
		'tests',
		'claimDepositForWinning',
		'drainAllRep',
		'exportForkedEscrowByOutcome',
		'exportForkedEscrowByOutcomeWithoutTransfer',
		'exportUnresolvedDeposit',
		'exportVaultUnresolvedTotals',
		'getFinalQuestionResolution',
		'initializeForkCarrySnapshotWithResolutionBalances',
		'previewDepositOnOutcome',
		'recordDepositFromSecurityPool',
		'recordForkedEscrowForOutcome',
		'sweepResidualRepToSecurityPool',
		'withdrawDeposit',
	],
	['test-escalation-proof-pool', 'zoltar-core', 'tests', 'burnRep', 'getRepToken'],
	['test-escalation-proof-pool', 'zoltar-reputation-token', 'tests', 'approve', 'transferFrom'],
	['test-forker-escrow-game', 'statoblast-binary-outcomes', 'uses', 'None'],
	['test-forker-escrow-game', 'zoltar-reputation-token', 'tests', 'balanceOf', 'transfer'],
	['test-forker-escrow-parent', 'test-forker-escrow-game', 'tests', 'drainToForker'],
	['test-forker-escrow-parent', 'zoltar-reputation-token', 'tests', 'balanceOf', 'transfer'],
	['test-forker-malicious-emitter', 'statoblast-security-pool-interface', 'tests', 'completeSetCollateralAmount', 'transferEth'],
	['test-incompatible-proof-verifier', 'statoblast-merkle-mountain-range', 'uses', 'hashParent'],
	['test-openoracle-rejecting-receiver', 'test-openoracle-adversarial-target', 'tests', 'getETHProtocolFees'],
	['test-safe-erc20-ops-harness', 'zoltar-safe-erc20-ops', 'uses', 'safeApprove', 'safeTransfer', 'safeTransferFrom', 'using for IERC20'],
	['test-share-token-authorization-pool', 'statoblast-share-token-interface', 'tests', 'authorize'],
	['test-truth-auction-alias-parent', 'zoltar-reputation-token', 'tests', 'balanceOf', 'transfer'],
	['zoltar-core', 'zoltar-reputation-token', 'calls', 'burn', 'getTotalTheoreticalSupply', 'mint', 'setMaxTheoreticalSupply'],
	['zoltar-safe-erc20-ops', 'zoltar-ierc20', 'calls', 'approve', 'transfer', 'transferFrom'],

	// Candidates whose pair and relation are already covered by a manually evidenced edge.
	['openoracle-core', 'openoracle-safe-erc20', 'uses', 'safeTransfer', 'safeTransferFrom', 'using for IERC20'],
	['openoracle-core', 'openoracle-signature-transfer', 'calls', 'permitWitnessTransferFrom'],
	['openoracle-math', 'openoracle-panic', 'uses', 'DIVISION_BY_ZERO', 'UNDER_OVERFLOW', 'panic'],
	['openoracle-math', 'openoracle-safe-cast', 'uses', 'toUint'],
	['statoblast-erc1155', 'statoblast-ierc1155-receiver', 'calls', 'onERC1155BatchReceived', 'onERC1155Received'],
	['statoblast-escalation-calculations', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-escalation-deposit-delegate', 'statoblast-escalation-deposit-context', 'calls', 'getQuestionResolution', 'hasReachedNonDecision'],
	['statoblast-escalation-deposit-delegate', 'statoblast-merkle-mountain-range', 'uses', 'hashLeaf', 'hashParent'],
	['statoblast-escalation-game-factory', 'statoblast-forker-interface', 'calls', 'getOwnForkRepBuckets', 'isEscalationWinnerHaircutPaidByFork'],
	['statoblast-escalation-game-factory', 'statoblast-security-pool-interface', 'calls', 'parent', 'repToken', 'securityPoolForker'],
	['statoblast-escalation-game-forker', 'statoblast-child-game-initializer', 'calls', 'initializeChildForkedEscalationGameIfNeeded'],
	['statoblast-escalation-game-forker', 'statoblast-escalation-game', 'calls', 'canTriggerOwnFork', 'claimDepositForWinningWithoutTransfer', 'exportForkedEscrowByOutcome', 'exportForkedEscrowByOutcomeWithoutTransfer', 'exportVaultUnresolvedTotalsWithoutTransfer', 'recordForkedEscrowForOutcome'],
	['statoblast-escalation-proof-verifier', 'statoblast-merkle-mountain-range', 'uses', 'bagPeaks', 'hashParent'],
	['statoblast-escalation-settlement', 'statoblast-forker-interface', 'calls', 'getQuestionOutcome', 'isEscalationDepositClaimedDirectly'],
	['statoblast-escalation-state', 'statoblast-escalation-proof-verifier', 'calls', 'computeEmptyNullifierRoot'],
	['statoblast-migration-proxy', 'zoltar-core', 'calls', 'addRepToMigrationBalance', 'forkUniverse', 'splitMigrationRep'],
	['statoblast-pool-forker', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-pool-forker', 'statoblast-escalation-game', 'calls', 'canTriggerOwnFork', 'getEscalationGameEndDate', 'getFinalQuestionResolution', 'getForkCarryRoots', 'getForkCarrySnapshot', 'getOutcomeBalances', 'getQuestionResolution'],
	['statoblast-pool-forker', 'statoblast-migration-proxy', 'calls', 'forkUniverse', 'lockRep'],
	['statoblast-pool-forker', 'statoblast-security-pool-utils', 'uses', 'AUCTION_TIME', 'MAX_AUCTION_VAULT_HAIRCUT_DIVISOR', 'MIGRATION_TIME', 'PRICE_PRECISION'],
	['statoblast-pool-forker', 'statoblast-truth-auction', 'calls', 'finalize', 'refundLosingBidsFor', 'startAuction', 'withdrawBids'],
	['statoblast-pool-forker', 'zoltar-core', 'calls', 'forkQuestionMatches', 'getForkThreshold', 'getForkTime', 'getMigrationRepBalance'],
	['statoblast-pool-forker', 'zoltar-reputation-token', 'calls', 'balanceOf'],
	['statoblast-price-coordinator', 'openoracle-core', 'calls', 'report', 'withdrawTo'],
	['statoblast-price-coordinator', 'openoracle-math', 'uses', 'Ceil', 'ceilDiv', 'mulDiv'],
	['statoblast-price-coordinator', 'statoblast-iweth9', 'calls', 'approve', 'transferFrom'],
	['statoblast-price-coordinator', 'statoblast-security-pool-utils', 'uses', 'BPS_DENOMINATOR', 'MIN_REP_DEPOSIT'],
	['statoblast-price-coordinator', 'zoltar-reputation-token', 'calls', 'approve', 'transferFrom'],
	['statoblast-security-pool', 'statoblast-binary-outcomes', 'uses', 'None'],
	['statoblast-security-pool', 'statoblast-deployment-worker-config', 'calls', 'eventEmitter', 'factory'],
	['statoblast-security-pool', 'statoblast-escalation-game', 'calls', 'getEscalationGameEndDate', 'hasReachedNonDecision', 'initializeForkCarrySnapshotWithResolutionBalances', 'previewDepositOnOutcome', 'recordDepositFromSecurityPool', 'resumeFromFork', 'withdrawDeposit'],
	['statoblast-security-pool', 'statoblast-escalation-game-factory', 'calls', 'deployEscalationGame', 'deployEscalationGameFromFork'],
	['statoblast-security-pool', 'statoblast-price-coordinator', 'calls', 'isPriceValid', 'setRepEthPrice'],
	['statoblast-security-pool', 'statoblast-security-pool-utils', 'uses', 'BPS_DENOMINATOR', 'MIN_REP_DEPOSIT', 'MIN_SECURITY_BOND_DEBT', 'PRICE_PRECISION', 'calculateFeeAccrual', 'calculateLiquidationTransfer', 'calculateRetentionRate', 'calculateVaultFee'],
	['statoblast-security-pool', 'zoltar-core', 'calls', 'burnRep', 'forkQuestionMatches', 'getForkTime', 'getNonDecisionThreshold', 'getRepToken'],
	['statoblast-security-pool', 'zoltar-question-data', 'calls', 'getQuestionEndDate'],
	['statoblast-security-pool', 'zoltar-reputation-token', 'calls', 'balanceOf'],
	['statoblast-security-pool-factory', 'statoblast-auction-factory', 'calls', 'deployUniformPriceDualCapBatchAuction'],
	['statoblast-security-pool-factory', 'statoblast-price-coordinator', 'calls', 'setSecurityPool'],
	['statoblast-security-pool-factory', 'statoblast-price-coordinator-factory', 'calls', 'deployPriceOracleManagerAndOperatorQueuer'],
	['statoblast-security-pool-factory', 'statoblast-security-pool-deployer', 'calls', 'deploy'],
	['statoblast-security-pool-factory', 'statoblast-share-token-factory', 'calls', 'deployShareToken'],
	['statoblast-security-pool-factory', 'zoltar-core', 'calls', 'forkQuestionMatches', 'getForkTime', 'getNonDecisionThreshold', 'getRepToken'],
	['statoblast-security-pool-factory', 'zoltar-question-data', 'calls', 'getOutcomeLabels'],
	['statoblast-share-token', 'statoblast-binary-outcomes', 'uses', 'Invalid', 'No', 'Yes'],
	['statoblast-share-token', 'statoblast-security-pool-interface', 'calls', 'parent', 'securityPoolForker', 'shareToken', 'systemState', 'universeId'],
	['statoblast-share-token', 'statoblast-token-id', 'uses', 'getTokenId', 'getTokenIds', 'unpackTokenId'],
	['statoblast-share-token', 'zoltar-core', 'calls', 'getForkTime'],
	['statoblast-truth-auction', 'openoracle-math', 'uses', 'Ceil', 'mulDiv'],
	['statoblast-vault-migration-base', 'statoblast-migration-proxy', 'calls', 'splitToChild', 'sweepChildRep'],
	['test-escalation-factory-coverage-pool', 'statoblast-escalation-game-factory', 'tests', 'deployEscalationGame', 'deployEscalationGameFromFork'],
	['zoltar-core', 'zoltar-constants', 'uses', 'BURN_ADDRESS', 'GENESIS_REPUTATION_TOKEN', 'MINIMUM_FORK_BURN_DIVISOR'],
	['zoltar-core', 'zoltar-question-data', 'calls', 'getQuestionEndDate', 'isMalformedAnswerOption'],
	['zoltar-core', 'zoltar-safe-erc20-ops', 'uses', 'safeTransfer', 'safeTransferFrom', 'using for IERC20'],
	['zoltar-question-data', 'zoltar-scalar-outcomes', 'uses', 'getScalarOutcomeName'],
]

export const contractAtlasBehavioralReferences: ContractAtlasBehavioralReference[] = contractAtlasBehavioralReferenceRows.map(([source, target, relation, ...members]) => ({
	members,
	relation,
	source,
	target,
}))
