export type ContractAtlasSourceReference = {
	source: string
	symbols: string[]
	target: string
}

export const contractAtlasSourceOwnerOverrides: Readonly<Record<string, string>> = {
	'solidity/contracts/peripherals/OpenOraclePriceCoordinator.sol': 'statoblast-price-coordinator',
	'solidity/contracts/peripherals/interfaces/ISecurityPool.sol': 'statoblast-security-pool-interface',
}

const contractAtlasSourceReferenceRows: readonly (readonly [source: string, target: string, ...symbols: string[]])[] = [
	['openoracle-core', 'openoracle-errors', 'Errors'],
	['openoracle-core', 'openoracle-ierc20', 'IERC20'],
	['openoracle-core', 'openoracle-safe-erc20', 'SafeERC20'],
	['openoracle-core', 'openoracle-signature-transfer', 'ISignatureTransfer'],
	['openoracle-ierc1363', 'openoracle-ierc165', 'IERC165'],
	['openoracle-ierc1363', 'openoracle-ierc20', 'IERC20'],
	['openoracle-math', 'openoracle-panic', 'Panic'],
	['openoracle-math', 'openoracle-safe-cast', 'SafeCast'],
	['openoracle-safe-erc20', 'openoracle-ierc1363', 'IERC1363'],
	['openoracle-safe-erc20', 'openoracle-ierc20', 'IERC20'],
	['statoblast-auction-factory', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['statoblast-auction-interface', 'statoblast-auction-events', 'IUniformPriceDualCapBatchAuctionEvents'],
	['statoblast-child-game-initializer', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-child-game-initializer', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-deployment-worker-config', 'statoblast-event-emitter', 'SecurityPoolEventEmitter'],
	['statoblast-deployment-worker-config', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['statoblast-erc1155', 'statoblast-ierc1155', 'IERC1155'],
	['statoblast-erc1155', 'statoblast-ierc1155-receiver', 'IERC1155Receiver'],
	['statoblast-escalation-calculations', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-calculations', 'statoblast-escalation-state', 'EscalationGameState'],
	['statoblast-escalation-calculations', 'statoblast-escalation-types', 'ESCALATION_TIME_LENGTH', 'NonDecisionState'],
	['statoblast-escalation-carry', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-carry', 'statoblast-escalation-calculations', 'EscalationGameCalculations'],
	['statoblast-escalation-carry', 'statoblast-escalation-events', 'CarryConsumptionReason'],
	['statoblast-escalation-carry', 'statoblast-escalation-types', 'CarriedDepositProof', 'CarryLeafView', 'Deposit', 'MERKLE_MOUNTAIN_RANGE_MAX_PEAKS', 'NULLIFIER_DEPTH', 'Node', 'NonDecisionState', 'OutcomeState', 'OutcomeStateView'],
	['statoblast-escalation-carry', 'statoblast-forker-interface', 'ISecurityPoolForker'],
	['statoblast-escalation-carry', 'statoblast-merkle-mountain-range', 'MerkleMountainRange'],
	['statoblast-escalation-carry', 'zoltar-constants', 'Constants'],
	['statoblast-escalation-deposit-context', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-deposit-delegate', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-deposit-delegate', 'statoblast-escalation-deposit-context', 'IEscalationGameDepositContext'],
	['statoblast-escalation-deposit-delegate', 'statoblast-escalation-events', 'IEscalationGameEvents'],
	['statoblast-escalation-deposit-delegate', 'statoblast-escalation-storage', 'EscalationGameStorage'],
	['statoblast-escalation-deposit-delegate', 'statoblast-escalation-types', 'Deposit', 'MERKLE_MOUNTAIN_RANGE_MAX_PEAKS', 'Node', 'NonDecisionState', 'OutcomeState'],
	['statoblast-escalation-deposit-delegate', 'statoblast-merkle-mountain-range', 'MerkleMountainRange'],
	['statoblast-escalation-escrow', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-escrow', 'statoblast-escalation-carry', 'EscalationGameCarry'],
	['statoblast-escalation-escrow', 'statoblast-escalation-types', 'ForkedEscrowState', 'OutcomeState'],
	['statoblast-escalation-events', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-game', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-game', 'statoblast-escalation-deposit-delegate', 'EscalationGameDepositDelegate'],
	['statoblast-escalation-game', 'statoblast-escalation-proof-verifier', 'EscalationGameProofVerifier'],
	['statoblast-escalation-game', 'statoblast-escalation-settlement', 'EscalationGameSettlement'],
	['statoblast-escalation-game', 'statoblast-escalation-state', 'EscalationGameState'],
	['statoblast-escalation-game', 'statoblast-escalation-types', 'ESCALATION_TIME_LENGTH', 'NonDecisionState'],
	['statoblast-escalation-game', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-escalation-game', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-escalation-game-factory', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-game-factory', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-escalation-game-factory', 'statoblast-escalation-proof-verifier', 'EscalationGameProofVerifier'],
	['statoblast-escalation-game-factory', 'statoblast-forker-interface', 'ISecurityPoolForker'],
	['statoblast-escalation-game-factory', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-escalation-game-forker', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-game-forker', 'statoblast-child-game-initializer', 'ISecurityPoolForkerChildEscalationGameInitializer'],
	['statoblast-escalation-game-forker', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-escalation-game-forker', 'statoblast-forker-base', 'SecurityPoolForkerBase'],
	['statoblast-escalation-game-forker', 'statoblast-forker-types', 'EscalationMigrationEntitlement', 'SecurityPoolForkerForkData'],
	['statoblast-escalation-game-forker', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['statoblast-escalation-game-forker', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-escalation-game-forker', 'statoblast-vault-migration-base', 'SecurityPoolForkerVaultMigrationBase'],
	['statoblast-escalation-game-forker', 'zoltar-core', 'Zoltar'],
	['statoblast-escalation-proof-verifier', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-proof-verifier', 'statoblast-escalation-types', 'EXCESS_REWARD_WINDOW_DIVISOR', 'LN2_SCALED', 'MAX_ATANH_ITERATIONS', 'MAX_EXP_ITERATIONS', 'MERKLE_MOUNTAIN_RANGE_MAX_PEAKS', 'NULLIFIER_DEPTH', 'SCALE'],
	['statoblast-escalation-proof-verifier', 'statoblast-merkle-mountain-range', 'MerkleMountainRange'],
	['statoblast-escalation-settlement', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-settlement', 'statoblast-escalation-escrow', 'EscalationGameEscrow'],
	['statoblast-escalation-settlement', 'statoblast-escalation-events', 'CarryConsumptionReason'],
	['statoblast-escalation-settlement', 'statoblast-escalation-types', 'CarriedDepositProof', 'Deposit', 'NonDecisionState'],
	['statoblast-escalation-settlement', 'statoblast-forker-interface', 'ISecurityPoolForker'],
	['statoblast-escalation-state', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-state', 'statoblast-escalation-events', 'IEscalationGameEvents'],
	['statoblast-escalation-state', 'statoblast-escalation-proof-verifier', 'EscalationGameProofVerifier'],
	['statoblast-escalation-state', 'statoblast-escalation-storage', 'EscalationGameStorage'],
	['statoblast-escalation-state', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-escalation-state', 'zoltar-ierc20', 'IERC20'],
	['statoblast-escalation-state', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-escalation-state', 'zoltar-safe-erc20-ops', 'SafeERC20Ops'],
	['statoblast-escalation-storage', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-escalation-storage', 'statoblast-escalation-types', 'ForkedEscrowState', 'Node', 'NonDecisionState', 'OutcomeState'],
	['statoblast-escalation-types', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-event-emitter', 'statoblast-forker-events', 'ISecurityPoolForkerEvents'],
	['statoblast-event-emitter', 'statoblast-forker-storage', 'SecurityPoolForkerStorage'],
	['statoblast-event-emitter', 'statoblast-forker-types', 'SecurityPoolForkerForkData'],
	['statoblast-event-emitter', 'statoblast-security-pool-interface', 'AccountingReason', 'ISecurityPool', 'PoolAccountingSnapshot'],
	['statoblast-forker-base', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-forker-base', 'statoblast-forker-events', 'ISecurityPoolForkerEvents'],
	['statoblast-forker-base', 'statoblast-forker-storage', 'SecurityPoolForkerStorage'],
	['statoblast-forker-base', 'statoblast-forker-types', 'EscalationForkSnapshot', 'SecurityPoolForkerForkData'],
	['statoblast-forker-base', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['statoblast-forker-base', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['statoblast-forker-base', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-forker-base', 'zoltar-core', 'Zoltar'],
	['statoblast-forker-events', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-forker-interface', 'statoblast-auction-interface', 'IUniformPriceDualCapBatchAuction'],
	['statoblast-forker-interface', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-forker-interface', 'statoblast-forker-events', 'ISecurityPoolForkerEvents'],
	['statoblast-forker-interface', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-forker-storage', 'statoblast-forker-types', 'EscalationForkSnapshot', 'EscalationMigrationEntitlement', 'OwnForkChildRepAllocation', 'SecurityPoolForkerForkData'],
	['statoblast-forker-storage', 'statoblast-migration-proxy', 'SecurityPoolMigrationProxy'],
	['statoblast-forker-storage', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-forker-types', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['statoblast-ierc1155', 'statoblast-ierc165', 'IERC165'],
	['statoblast-ierc1155-receiver', 'statoblast-ierc165', 'IERC165'],
	['statoblast-merkle-mountain-range', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-migration-proxy', 'zoltar-core', 'Zoltar'],
	['statoblast-migration-proxy', 'zoltar-ierc20', 'IERC20'],
	['statoblast-migration-proxy', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-migration-proxy', 'zoltar-safe-erc20-ops', 'SafeERC20Ops'],
	['statoblast-pool-forker', 'statoblast-auction-interface', 'IUniformPriceDualCapBatchAuction'],
	['statoblast-pool-forker', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-pool-forker', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-pool-forker', 'statoblast-escalation-game-forker', 'EscalationGameForker'],
	['statoblast-pool-forker', 'statoblast-escalation-types', 'ESCALATION_TIME_LENGTH'],
	['statoblast-pool-forker', 'statoblast-event-emitter', 'SecurityPoolEventEmitter'],
	['statoblast-pool-forker', 'statoblast-forker-base', 'SecurityPoolForkerBase'],
	['statoblast-pool-forker', 'statoblast-forker-types', 'EscalationForkSnapshot', 'EscalationMigrationEntitlement', 'SecurityPoolForkerForkData'],
	['statoblast-pool-forker', 'statoblast-migration-proxy', 'SecurityPoolMigrationProxy'],
	['statoblast-pool-forker', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['statoblast-pool-forker', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-pool-forker', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['statoblast-pool-forker', 'statoblast-vault-migration-delegate', 'SecurityPoolForkerVaultMigrationDelegate'],
	['statoblast-pool-forker', 'zoltar-core', 'Zoltar'],
	['statoblast-pool-forker', 'zoltar-ierc20', 'IERC20'],
	['statoblast-pool-forker', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-pool-forker', 'zoltar-safe-erc20-ops', 'SafeERC20Ops'],
	['statoblast-price-coordinator', 'openoracle-core', 'OpenOracle'],
	['statoblast-price-coordinator', 'openoracle-math', 'Math'],
	['statoblast-price-coordinator', 'statoblast-iweth9', 'IWeth9'],
	['statoblast-price-coordinator', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-price-coordinator', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-price-coordinator', 'statoblast-stored-open-oracle-game', 'IStoredOpenOracleGame'],
	['statoblast-price-coordinator', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-price-coordinator-factory', 'openoracle-core', 'OpenOracle'],
	['statoblast-price-coordinator-factory', 'statoblast-iweth9', 'IWeth9'],
	['statoblast-price-coordinator-factory', 'statoblast-price-coordinator', 'OpenOraclePriceCoordinator'],
	['statoblast-price-coordinator-factory', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-security-pool', 'openoracle-core', 'OpenOracle'],
	['statoblast-security-pool', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-security-pool', 'statoblast-deployment-worker-config', 'ISecurityPoolDeploymentWorkerConfiguration'],
	['statoblast-security-pool', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-security-pool', 'statoblast-escalation-game-factory', 'EscalationGameFactory'],
	['statoblast-security-pool', 'statoblast-escalation-types', 'CarriedDepositProof'],
	['statoblast-security-pool', 'statoblast-event-emitter', 'SecurityPoolEventEmitter'],
	['statoblast-security-pool', 'statoblast-forker-interface', 'ISecurityPoolForker'],
	['statoblast-security-pool', 'statoblast-price-coordinator', 'OpenOraclePriceCoordinator'],
	['statoblast-security-pool', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['statoblast-security-pool', 'statoblast-security-pool-interface', 'AccountingReason', 'ISecurityPool', 'PoolAccountingSnapshot', 'QuestionOutcome', 'SecurityVault', 'SystemState'],
	['statoblast-security-pool', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-security-pool', 'statoblast-share-token-interface', 'IShareToken'],
	['statoblast-security-pool', 'zoltar-core', 'Zoltar'],
	['statoblast-security-pool', 'zoltar-ierc20', 'IERC20'],
	['statoblast-security-pool', 'zoltar-question-data', 'ZoltarQuestionData'],
	['statoblast-security-pool', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-security-pool', 'zoltar-safe-erc20-ops', 'SafeERC20Ops'],
	['statoblast-security-pool-deployer', 'openoracle-core', 'OpenOracle'],
	['statoblast-security-pool-deployer', 'statoblast-escalation-game-factory', 'EscalationGameFactory'],
	['statoblast-security-pool-deployer', 'statoblast-event-emitter', 'SecurityPoolEventEmitter'],
	['statoblast-security-pool-deployer', 'statoblast-price-coordinator', 'OpenOraclePriceCoordinator'],
	['statoblast-security-pool-deployer', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['statoblast-security-pool-deployer', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-security-pool-deployer', 'statoblast-security-pool-worker', 'SecurityPoolDeploymentWorker'],
	['statoblast-security-pool-deployer', 'statoblast-share-token-interface', 'IShareToken'],
	['statoblast-security-pool-deployer', 'zoltar-core', 'Zoltar'],
	['statoblast-security-pool-deployer', 'zoltar-question-data', 'ZoltarQuestionData'],
	['statoblast-security-pool-factory', 'openoracle-core', 'OpenOracle'],
	['statoblast-security-pool-factory', 'statoblast-auction-factory', 'UniformPriceDualCapBatchAuctionFactory'],
	['statoblast-security-pool-factory', 'statoblast-escalation-game-factory', 'EscalationGameFactory'],
	['statoblast-security-pool-factory', 'statoblast-forker-interface', 'ISecurityPoolForker'],
	['statoblast-security-pool-factory', 'statoblast-price-coordinator', 'OpenOraclePriceCoordinator'],
	['statoblast-security-pool-factory', 'statoblast-price-coordinator-factory', 'PriceOracleManagerAndOperatorQueuerFactory'],
	['statoblast-security-pool-factory', 'statoblast-security-pool-deployer', 'SecurityPoolDeployer'],
	['statoblast-security-pool-factory', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['statoblast-security-pool-factory', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-security-pool-factory', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-security-pool-factory', 'statoblast-share-token-factory', 'ShareTokenFactory'],
	['statoblast-security-pool-factory', 'statoblast-share-token-interface', 'IShareToken'],
	['statoblast-security-pool-factory', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['statoblast-security-pool-factory', 'zoltar-core', 'Zoltar'],
	['statoblast-security-pool-factory', 'zoltar-question-data', 'ZoltarQuestionData'],
	['statoblast-security-pool-factory', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-security-pool-factory-interface', 'statoblast-price-coordinator', 'OpenOraclePriceCoordinator'],
	['statoblast-security-pool-factory-interface', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-security-pool-factory-interface', 'statoblast-share-token-interface', 'IShareToken'],
	['statoblast-security-pool-factory-interface', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['statoblast-security-pool-interface', 'openoracle-core', 'OpenOracle'],
	['statoblast-security-pool-interface', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-security-pool-interface', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-security-pool-interface', 'statoblast-escalation-types', 'CarriedDepositProof'],
	['statoblast-security-pool-interface', 'statoblast-price-coordinator', 'OpenOraclePriceCoordinator'],
	['statoblast-security-pool-interface', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['statoblast-security-pool-interface', 'statoblast-share-token-interface', 'IShareToken'],
	['statoblast-security-pool-interface', 'zoltar-core', 'Zoltar'],
	['statoblast-security-pool-interface', 'zoltar-question-data', 'ZoltarQuestionData'],
	['statoblast-security-pool-interface', 'zoltar-reputation-token', 'ReputationToken'],
	['statoblast-security-pool-worker', 'openoracle-core', 'OpenOracle'],
	['statoblast-security-pool-worker', 'statoblast-escalation-game-factory', 'EscalationGameFactory'],
	['statoblast-security-pool-worker', 'statoblast-event-emitter', 'SecurityPoolEventEmitter'],
	['statoblast-security-pool-worker', 'statoblast-price-coordinator', 'OpenOraclePriceCoordinator'],
	['statoblast-security-pool-worker', 'statoblast-security-pool', 'SecurityPool'],
	['statoblast-security-pool-worker', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['statoblast-security-pool-worker', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-security-pool-worker', 'statoblast-share-token-interface', 'IShareToken'],
	['statoblast-security-pool-worker', 'zoltar-core', 'Zoltar'],
	['statoblast-security-pool-worker', 'zoltar-question-data', 'ZoltarQuestionData'],
	['statoblast-share-token', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-share-token', 'statoblast-erc1155', 'ERC1155'],
	['statoblast-share-token', 'statoblast-forker-interface', 'ISecurityPoolForker'],
	['statoblast-share-token', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['statoblast-share-token', 'statoblast-share-token-interface', 'IShareToken'],
	['statoblast-share-token', 'statoblast-token-id', 'TokenId'],
	['statoblast-share-token', 'zoltar-constants', 'Constants'],
	['statoblast-share-token', 'zoltar-core', 'Zoltar'],
	['statoblast-share-token-factory', 'statoblast-share-token', 'ShareToken'],
	['statoblast-share-token-factory', 'zoltar-core', 'Zoltar'],
	['statoblast-share-token-interface', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-share-token-interface', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['statoblast-token-id', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-truth-auction', 'openoracle-math', 'Math'],
	['statoblast-truth-auction', 'statoblast-auction-events', 'IUniformPriceDualCapBatchAuctionEvents'],
	['statoblast-truth-auction', 'statoblast-auction-interface', 'IUniformPriceDualCapBatchAuction'],
	['statoblast-vault-migration-base', 'openoracle-math', 'Math'],
	['statoblast-vault-migration-base', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['statoblast-vault-migration-base', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-vault-migration-base', 'statoblast-forker-base', 'SecurityPoolForkerBase'],
	['statoblast-vault-migration-base', 'statoblast-forker-types', 'OwnForkChildRepAllocation', 'SecurityPoolForkerForkData'],
	['statoblast-vault-migration-base', 'statoblast-migration-proxy', 'SecurityPoolMigrationProxy'],
	['statoblast-vault-migration-base', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['statoblast-vault-migration-base', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-vault-migration-base', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['statoblast-vault-migration-delegate', 'statoblast-child-game-initializer', 'ISecurityPoolForkerChildEscalationGameInitializer'],
	['statoblast-vault-migration-delegate', 'statoblast-escalation-game', 'EscalationGame'],
	['statoblast-vault-migration-delegate', 'statoblast-forker-base', 'SecurityPoolForkerBase'],
	['statoblast-vault-migration-delegate', 'statoblast-forker-types', 'SecurityPoolForkerForkData'],
	['statoblast-vault-migration-delegate', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['statoblast-vault-migration-delegate', 'statoblast-security-pool-utils', 'SecurityPoolUtils'],
	['statoblast-vault-migration-delegate', 'statoblast-vault-migration-base', 'SecurityPoolForkerVaultMigrationBase'],
	['statoblast-vault-migration-delegate', 'zoltar-core', 'Zoltar'],
	['test-complete-set-reentrant-receiver', 'statoblast-ierc1155-receiver', 'IERC1155Receiver'],
	['test-complete-set-reentrant-receiver', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-constructor-failure-zoltar', 'zoltar-reputation-token', 'ReputationToken'],
	['test-coverage-helpers-harness', 'infra-deployment-status-oracle', 'DeploymentStatusOracle'],
	['test-coverage-helpers-harness', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['test-coverage-helpers-harness', 'statoblast-escalation-proof-verifier', 'EscalationGameProofVerifier'],
	['test-coverage-helpers-harness', 'statoblast-escalation-types', 'MERKLE_MOUNTAIN_RANGE_MAX_PEAKS'],
	['test-coverage-helpers-harness', 'statoblast-merkle-mountain-range', 'MerkleMountainRange'],
	['test-coverage-helpers-harness', 'statoblast-token-id', 'TokenId'],
	['test-coverage-helpers-harness', 'zoltar-ierc20', 'IERC20'],
	['test-coverage-helpers-harness', 'zoltar-safe-erc20-ops', 'SafeERC20Ops'],
	['test-coverage-helpers-harness', 'zoltar-scalar-outcomes', 'ScalarOutcomes'],
	['test-erc1155-coverage-harness', 'statoblast-erc1155', 'ERC1155'],
	['test-erc1155-receiver-mock', 'statoblast-ierc1155-receiver', 'IERC1155Receiver'],
	['test-escalation-factory-coverage-pool', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['test-escalation-factory-coverage-pool', 'statoblast-escalation-game', 'EscalationGame'],
	['test-escalation-factory-coverage-pool', 'statoblast-escalation-game-factory', 'EscalationGameFactory'],
	['test-escalation-factory-coverage-pool', 'zoltar-reputation-token', 'ReputationToken'],
	['test-escalation-forker-harness', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['test-escalation-forker-harness', 'statoblast-escalation-game', 'EscalationGame'],
	['test-escalation-proof-pool', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['test-escalation-proof-pool', 'statoblast-escalation-game', 'EscalationGame'],
	['test-escalation-proof-pool', 'statoblast-escalation-types', 'CarriedDepositProof'],
	['test-escalation-proof-pool', 'zoltar-core', 'Zoltar'],
	['test-escalation-proof-pool', 'zoltar-reputation-token', 'ReputationToken'],
	['test-false-returning-erc20', 'zoltar-ierc20', 'IERC20'],
	['test-fork-boundary-pool', 'zoltar-core', 'Zoltar'],
	['test-fork-threshold-harness', 'statoblast-escalation-calculations', 'EscalationGameCalculations'],
	['test-fork-threshold-harness', 'statoblast-escalation-proof-verifier', 'EscalationGameProofVerifier'],
	['test-fork-threshold-harness', 'statoblast-escalation-state', 'EscalationGameState'],
	['test-fork-threshold-harness', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-fork-threshold-harness', 'zoltar-reputation-token', 'ReputationToken'],
	['test-forker-alternating-game', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-forker-attack-factory', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-forker-attack-factory', 'statoblast-share-token-interface', 'IShareToken'],
	['test-forker-attack-factory', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['test-forker-attack-parent', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['test-forker-attack-parent', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['test-forker-attack-parent', 'statoblast-share-token-interface', 'IShareToken'],
	['test-forker-auction-settlement', 'statoblast-forker-types', 'SecurityPoolForkerForkData'],
	['test-forker-auction-settlement', 'statoblast-pool-forker', 'SecurityPoolForker'],
	['test-forker-auction-settlement', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-forker-auction-settlement', 'zoltar-core', 'Zoltar'],
	['test-forker-child-validation-harness', 'statoblast-forker-base', 'SecurityPoolForkerBase'],
	['test-forker-child-validation-harness', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-forker-child-validation-harness', 'zoltar-core', 'Zoltar'],
	['test-forker-escrow-child', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['test-forker-escrow-child', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['test-forker-escrow-child', 'zoltar-reputation-token', 'ReputationToken'],
	['test-forker-escrow-factory', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-forker-escrow-factory', 'statoblast-share-token-interface', 'IShareToken'],
	['test-forker-escrow-factory', 'statoblast-truth-auction', 'UniformPriceDualCapBatchAuction'],
	['test-forker-escrow-game', 'statoblast-binary-outcomes', 'BinaryOutcomes'],
	['test-forker-escrow-game', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-forker-escrow-game', 'zoltar-reputation-token', 'ReputationToken'],
	['test-forker-escrow-parent', 'statoblast-security-pool-factory-interface', 'ISecurityPoolFactory'],
	['test-forker-escrow-parent', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['test-forker-escrow-parent', 'statoblast-share-token-interface', 'IShareToken'],
	['test-forker-escrow-parent', 'test-forker-escrow-game', 'SecurityPoolForkerEscrowAttackGameMock'],
	['test-forker-escrow-parent', 'zoltar-reputation-token', 'ReputationToken'],
	['test-forker-fake-pool', 'statoblast-security-pool-interface', 'SystemState'],
	['test-forker-fake-pool', 'zoltar-reputation-token', 'ReputationToken'],
	['test-forker-malicious-emitter', 'statoblast-security-pool-interface', 'ISecurityPool'],
	['test-incompatible-proof-verifier', 'statoblast-escalation-types', 'NULLIFIER_DEPTH'],
	['test-incompatible-proof-verifier', 'statoblast-merkle-mountain-range', 'MerkleMountainRange'],
	['test-openoracle-rejecting-receiver', 'statoblast-ierc1155-receiver', 'IERC1155Receiver'],
	['test-openoracle-rejecting-receiver', 'test-openoracle-adversarial-target', 'IOpenOracleAdversarialTarget'],
	['test-openoracle-token', 'zoltar-ierc20', 'IERC20'],
	['test-safe-erc20-ops-harness', 'zoltar-ierc20', 'IERC20'],
	['test-safe-erc20-ops-harness', 'zoltar-safe-erc20-ops', 'SafeERC20Ops'],
	['test-share-token-authorization-pool', 'statoblast-security-pool-interface', 'ISecurityPool', 'SystemState'],
	['test-share-token-authorization-pool', 'statoblast-share-token-interface', 'IShareToken'],
	['zoltar-core', 'zoltar-constants', 'Constants'],
	['zoltar-core', 'zoltar-ierc20', 'IERC20'],
	['zoltar-core', 'zoltar-question-data', 'ZoltarQuestionData'],
	['zoltar-core', 'zoltar-reputation-token', 'ReputationToken'],
	['zoltar-core', 'zoltar-safe-erc20-ops', 'SafeERC20Ops'],
	['zoltar-erc20', 'zoltar-context', 'Context'],
	['zoltar-erc20', 'zoltar-ierc20', 'IERC20'],
	['zoltar-erc20', 'zoltar-ierc20-metadata', 'IERC20Metadata'],
	['zoltar-ierc20-metadata', 'zoltar-ierc20', 'IERC20'],
	['zoltar-question-data', 'zoltar-scalar-outcomes', 'ScalarOutcomes'],
	['zoltar-reputation-token', 'zoltar-erc20', 'ERC20'],
	['zoltar-safe-erc20-ops', 'zoltar-ierc20', 'IERC20'],
]

export const contractAtlasSourceReferences: ContractAtlasSourceReference[] = contractAtlasSourceReferenceRows.map(([source, target, ...symbols]) => ({ source, symbols, target }))
