import type { UiScreenshotCrop, UiScreenshotSpec, UiScreenshotStep } from '../ui-screenshot-specs.mts'

const openFirstMarket: readonly UiScreenshotStep[] = [{ click: 'Will this resolve?' }, { waitForText: 'Question end' }]
const initializeAtSeventyPercent: readonly UiScreenshotStep[] = [{ click: 'Create market' }, { waitForText: 'Conditional YES price' }, { fill: 'ETH amount', value: '0.01' }, { fill: 'Conditional YES price', value: '70' }, { waitForText: 'You receive ≈' }, { waitForEnabled: 'Initialize pool' }]
const travelOneYear: readonly UiScreenshotStep[] = [{ click: 'Show details' }, { click: 'QA controls, prices, and time travel' }, { click: '+1 year' }, { waitForEnabled: '+1 year' }, { click: 'Hide details' }]
// The trade panel scrolls inside the viewport, so panel shots use a taller window.
const tradePanel: UiScreenshotCrop = { selector: '.market-ticket__panel' }
const tallViewport = { width: 1440, height: 1600 }
// Page shots crop to one card or panel in a narrow window so the image stays legible when scaled to a phone-width column.
const pageViewport = { width: 800, height: 900 }

export const TRADING_SCREENSHOTS: readonly UiScreenshotSpec[] = [
	{
		id: 'markets',
		app: 'trading',
		scenario: 'trading-funded',
		steps: [{ waitForText: 'Conditional odds' }, { waitForNoText: 'Discovering…' }],
		expectText: ['Markets', 'Conditional odds', 'TRADING OPEN'],
		viewport: pageViewport,
		crop: { selector: '.entity-card', containing: 'Conditional odds' },
		usedBy: ['tutorials/trading-first-trade.html'],
	},
	{
		id: 'buy-ticket',
		app: 'trading',
		scenario: 'trading-funded',
		steps: [...openFirstMarket, { fill: 'You pay', value: '0.001' }, { waitForEnabled: 'Buy YES' }],
		expectText: ['Trade', 'Buy', 'Sell', 'You pay', 'You receive ≈', 'Minimum received', 'INVALID insurance', 'Buy YES'],
		viewport: tallViewport,
		crop: tradePanel,
		usedBy: ['tutorials/trading-first-trade.html'],
	},
	{
		id: 'sell-ticket',
		app: 'trading',
		scenario: 'trading-funded',
		steps: [...openFirstMarket, { click: 'Sell' }, { waitForText: 'Shares to sell' }, { fill: 'Shares to sell', value: '0.001' }, { waitForEnabled: 'Sell YES' }],
		expectText: ['Shares to sell', 'Max', 'INVALID used', 'Minimum received', 'Sell YES'],
		viewport: tallViewport,
		crop: tradePanel,
		usedBy: ['tutorials/trading-first-trade.html', 'how-to/trading-exit-a-position.html'],
	},
	{
		id: 'trade-settings',
		app: 'trading',
		scenario: 'trading-funded',
		steps: [{ click: 'Settings' }, { waitForText: 'Trade settings' }],
		expectText: ['Trade settings', 'Slippage tolerance', 'Transaction valid for'],
		crop: { selector: '[role=dialog]', containing: 'Trade settings', padding: 0 },
		usedBy: ['tutorials/trading-first-trade.html'],
	},
	{
		id: 'portfolio',
		app: 'trading',
		scenario: 'deployed',
		route: '#/create-market',
		steps: [...initializeAtSeventyPercent, { click: 'Initialize pool' }, { waitForText: 'TRADING OPEN' }, { click: 'Portfolio' }, { waitForText: 'LP' }],
		expectText: ['Portfolio', 'INVALID', 'LP'],
		viewport: pageViewport,
		crop: { selector: '.portfolio-positions' },
		usedBy: ['tutorials/trading-first-market.html'],
	},
	{
		id: 'create-market',
		app: 'trading',
		scenario: 'deployed',
		route: '#/create-market',
		steps: [{ waitForText: 'Will this resolve?' }],
		expectText: ['Create new market', 'Security pools', 'Create market', 'Details'],
		viewport: pageViewport,
		crop: { selector: '.entity-card', containing: 'Create market' },
		usedBy: ['tutorials/trading-first-market.html'],
	},
	{
		id: 'security-pool-details',
		app: 'trading',
		scenario: 'deployed',
		route: '#/create-market',
		steps: [{ click: 'Details' }, { waitForText: 'Minting capacity' }],
		expectText: ['Pool facts', 'System state', 'Minting capacity', 'Deploy trading pool'],
		viewport: pageViewport,
		crop: { selector: '.section-block', containing: 'Pool facts', padding: 6 },
		usedBy: ['tutorials/trading-first-market.html'],
	},
	{
		id: 'initialize-pool',
		app: 'trading',
		scenario: 'deployed',
		route: '#/create-market',
		steps: initializeAtSeventyPercent,
		expectText: ['PAIR NOT CREATED', 'Initialize', 'ETH amount', 'Conditional YES price', 'You provide', 'You receive ≈', 'Initialize pool'],
		viewport: pageViewport,
		crop: { selector: '.section-block', containing: 'Conditional YES price' },
		usedBy: ['tutorials/trading-first-market.html'],
	},
	{
		id: 'remove-liquidity',
		app: 'trading',
		scenario: 'trading-funded',
		steps: [...openFirstMarket, { click: 'Liquidity' }, { click: 'Remove' }, { waitForText: 'LP tokens' }, { fill: 'LP tokens', value: '0.001' }, { waitForEnabled: 'Remove liquidity' }],
		expectText: ['Remove', 'LP tokens', 'You receive ≈', 'Remove liquidity'],
		viewport: tallViewport,
		crop: tradePanel,
		usedBy: ['how-to/trading-remove-liquidity.html'],
	},
	{
		id: 'settlement',
		app: 'trading',
		scenario: 'trading-funded',
		steps: [...travelOneYear, ...openFirstMarket, { waitForText: 'Complete-set value to redeem' }, { fill: 'Complete-set value to redeem', value: '0.001' }, { waitForEnabled: 'Redeem complete sets' }],
		expectText: ['Settlement', 'Complete set', 'Fork migration', 'Complete-set value to redeem', 'Redeem complete sets'],
		viewport: tallViewport,
		crop: tradePanel,
		usedBy: ['how-to/trading-handle-resolution.html'],
	},
	{
		id: 'deploy-contracts',
		app: 'trading',
		scenario: 'baseline',
		route: '#/deploy',
		expectText: ['Trading contracts', 'Deployment progress', 'SECURITY POOL FACTORY IS NOT DEPLOYED', 'Deploy Trading factory'],
		viewport: pageViewport,
		crop: { selector: '.section-block', containing: 'Trading contracts', padding: 6 },
		usedBy: ['how-to/trading-deploy-contracts.html'],
	},
]
