import type { CopyTemplateValue } from '@zoltar/ui-core-shared/copy/types.js'
import * as commonCopy from '@zoltar/ui-core-shared/copy/common.js'
export {
	initiallyDepositedLead,
	worthNowLead,
} from './reportingEscalation.js'

export const bidAmountEth = 'Bid amount (ETH)'
export const bidAmount = 'Bid amount'
export const scrollableAuctionBidHistory = 'Scrollable auction bid history'
export const scrollableMyBids = 'Scrollable wallet bid history'
export const selectedChildPoolRepReadinessLoading = 'Checking whether pool-held REP is already ready for the selected child universe.'
export const clearingPrice = 'Clearing price'
export const closed = 'Closed'
export const entryDepthLead = 'Entry depth: '
export const escalationDepositDetailsUnavailable = 'Escalation deposit details are unavailable for this pool right now.'
export const ethRaisedPerCap = 'ETH raised / cap'
export const cumulativeBidsEth = 'Cumulative bids (ETH)'
export const loadingCurrentChainTime = 'Loading current chain time.'
export const migrateVaultTitle = 'Migrate vault'
export const migratingVault = 'Migrating vault…'
export const migrationTimingIsUnavailable = 'Migration timing is unavailable.'
export const poolMigrationCapacityEmpty = 'No REP backing or underwriting commitments remain to migrate for the connected wallet.'
export const notStarted = 'Not started'
export const walletUnresolvedDepositsEmpty = 'No unresolved parent escalation deposits remain for the connected wallet.'
export const open = 'Open'
export const priceEthPerRep = 'Price (ETH per REP)'
export const depthChartPriceAxis = 'Price (ETH per REP), highest to lowest'
export const repPurchasedAttoRep = 'REP purchased'
export const startingTruthAuction = 'Starting truth auction…'
export const startTruthAuction = 'Start truth auction'
export const startTruthAuctionTitle = 'Start truth auction'
export const submitBid = 'Submit bid'
export const submitBidTitle = 'Submit bid'
export const unresolvedDepositDetailsUnavailable = 'Unresolved escalation deposit details are unavailable for this pool right now.'
export const formatCheckingPoolRepMigratedToChildUniverse = (outcomeLabel: CopyTemplateValue) => `Checking whether pool-held REP has already been migrated for the ${outcomeLabel} child universe.`
export const formatEthPerRepValue = (price: CopyTemplateValue) => `${price}\u00a0ETH per REP`
export const attoEthRaised = 'ETH raised'
export const attoRepSold = 'REP sold'
export const minBid = 'Min bid'
export const winningThreshold = 'Winning threshold'
export const reservePrice = 'Reserve price'
export const zeroEth = '0\u00a0ETH'
export const truthAuctionVisibleDepthChart = 'Truth auction visible depth chart'
export const formatSelectPriceValueEthRepFromDepthChart = (price: CopyTemplateValue) => `Select price ${price}\u00a0ETH per REP from depth chart`
export const formatMissingOutcomePoolDetail = (outcomeLabel: CopyTemplateValue) => `Security pool for ${outcomeLabel} universe does not exist.`
export const migration = 'Migration'
export const forkReadiness = 'Fork readiness'
export const notChosen = 'Not chosen'
export const systemIsForking = 'System is forking'
export const ethRep = 'ETH per REP'
export const pendingRefund = 'Pending refund'
export const refundWithdrawal = 'Refund withdrawal'
export const withdrawRefund = 'Withdraw refund'
export const withdrawingRefundTruncated = 'Withdrawing refund…'
export const loadingPendingRefund = 'Loading pending refund…'
export const pendingRefundUnavailable = 'Failed to load the pending refund balance.'
export const retryPendingRefund = 'Retry pending refund'
export const noPendingRefund = 'No credited refund is available to withdraw.'
export const settleRefundableBidsFirst = 'Settle your refundable bids above first. Their ETH then appears here to withdraw.'
export const mixedSettlementPreviewDetail = 'Winning bids add REP backing units to your vault, with a matching share of the auctioned underwriting commitments. Refundable bids credit their ETH for withdrawal.'
export const winningSettlementPreviewDetail = 'Winning bids add REP backing units to your vault, with a matching share of the auctioned underwriting commitments.'
export const refundSettlementPreviewDetail = 'Refundable bids credit their ETH for withdrawal. They add no REP backing units or underwriting commitments.'
export const truthAuctionRefundEstimateDetail = 'Estimated ETH refunded includes fully losing bids and any unfilled remainder on partially cleared winning bids.'
export const underfundedWinningClaimUnavailable = 'Claim preview is unavailable for underfunded winning bids because the required per-tick ETH denominator is not exposed in current UI data.'
export const settlementRoundingNotice = 'These are pre-transaction estimates. Final on-chain settlement can differ slightly because claim math is rounded on-chain.'
export const selectedBidSettlementPreview = 'Settlement preview.'
export const selectedBids = 'Selected bids'
export const selectedWinningBids = 'Selected winning bids'
export const selectedRefundRows = 'Selected refundable bids'
export const estimatedVaultRepBackingAttoRep = 'Estimated REP backing'
export const estimatedUnderwritingCommitments = 'Estimated underwriting commitments'
export const estimatedRefundedAttoEth = 'Estimated ETH refunded'
export const ownEscalationFork = 'Own escalation fork'
export const parentZoltarFork = 'Parent universe fork'
export const childSecurityPools = 'Child security pools'
export const pendingOutcome = 'Pending outcome'
export const openSecurityPool = 'Open security pool'
export const truthAuctionMigrationPendingDetail = 'Migration is still active. Truth auction can start once migration ends.'
export const migrationWindowEndsTooSoon = 'Migration window ends too soon to submit.'
export const parentMigrationExpiredDetail = 'Migration window has closed for this parent pool.'
export const truthAuctionNoCollateralDetail = 'No parent settlement collateral remains to auction, so this step immediately bypasses bidding and finalizes the child pool.'
export const truthAuctionNoRepDetail = 'No REP was present at fork, so no truth auction is needed for this child universe.'
export const childUniverseFullyMigratedDetail = 'This child universe already has all REP migrated from the parent pool, so no truth auction is needed.'
export const loadingTruthAuction = 'Loading truth auction…'
export const truthAuctionNotStartedReason = 'Truth auction has not started.'
export const truthAuctionFinalizedReason = 'Truth auction is already finalized.'
export const auctionEndTimeUnavailable = 'Truth auction end time is unavailable.'
export const auctionOngoingReason = 'Truth auction is still ongoing.'
export const inactive = 'Inactive'
export const clearing = 'Target reached'
export const shortfall = 'Shortfall'
export const unfilled = 'Unfilled'
export const notStartedBadgeLabel = 'Not started'
export const childPool = 'Child pool'
export const parentBalancesWalletRequired = 'Connect wallet to inspect your parent-pool balances.'
export const parentVaultBalancesUnavailableDetail = 'Parent-pool vault balances are unavailable for the connected wallet. You can still use the migration actions below if this wallet has parent-pool state to move.'
export const migratedBalancesForThisOutcome = 'Migrated balances for this outcome:'
export const selectedOutcomeRepCollateral = 'Selected outcome REP backing'
export const selectedOutcomeUnderwritingLimitAttoEth = 'Selected outcome underwriting commitments'
export const walletDisputeStakedRepEmpty = 'No parent dispute-staked REP remains available for a direct branch claim by the connected wallet.'
export const startingTruncated = 'Starting…'
export const formatStartsInValue = (duration: CopyTemplateValue) => `Starts in ${duration}`
export const pendingConfirmation = 'Pending confirmation'
export const settleSelectedBids = 'Settle selected bids'
export const winningBidBatchSettlementDetail = 'Select your winning bids to claim them. Each claim adds REP backing units to your vault in this pool, with a matching share of the auctioned underwriting commitments.'
export const refundableBidBatchSettlementDetail = 'Select your refundable bids to get their ETH back.'
export const mixedBidBatchSettlementDetail = 'Select bids to settle. Winning bids add REP backing units to your vault, with a matching share of the auctioned underwriting commitments. Refundable bids return their ETH.'
export const submittingSettlementTransactionTruncated = 'Submitting settlement transaction…'
export const forkActionWalletRequired = commonCopy.formatConnectWalletBefore('using fork and auction actions')
export const auctionEndedStatus = 'Truth auction has ended.'
export const auctionEndsTooSoonToBid = 'Truth auction ends too soon to submit a bid.'
export const finalizedSettlementDetail = 'The result is final.'
export const openSettlement = 'Open settlement'
export const truthAuctionFinalizationRequiredDetail = 'Finalize it to lock in the clearing price. Bids can be settled afterwards.'
export const finalizeTruthAuctionReviewDescription = 'Locks in the final clearing price. Afterwards, winning bids can claim REP backing units and losing bids can be refunded in Settlement.'
export const finalizeTruthAuction = 'Finalize truth auction'
export const finalizingTruthAuctionTruncated = 'Finalizing truth auction…'
export const formatTruthAuctionStartDelay = (duration: CopyTemplateValue) => `Truth auction can be started in ${duration} once migration ends.`
export const eligibleDepositsLoading = 'Loading eligible escalation deposits.'
export const useUnresolvedMigrationReason = 'Use the optional unresolved parent escalation-deposit accounting cleanup for this pool.'
export const unresolvedMigrationExpiredReason = 'The optional unresolved parent escalation-deposit accounting cleanup window has closed.'
export const formatNoClaimableParentEscalationDeposits = (outcomeLabel: CopyTemplateValue) => `No ${outcomeLabel} parent escalation deposits are currently available for a direct claim by this wallet.`
export const parentEscalationClaimSelectionRequired = 'Select at least one deposit to claim.'
export const unresolvedMigrationUnavailableReason = 'Optional unresolved parent escalation-deposit accounting cleanup is unavailable for this pool.'
export const unresolvedDepositsLoading = 'Loading unresolved escalation deposits.'
export const formatPoolRepAlreadyMigrated = (outcomeLabel: CopyTemplateValue) => `Pool-held REP has already been migrated to the ${outcomeLabel} universe.`
export const formatPoolMigrationRequiredForVault = (outcomeLabel: CopyTemplateValue) => `Migrate pool to the ${outcomeLabel} universe before moving vault balances.`
export const vaultMigrationCompleteReason = 'Vault migration is already complete for this wallet.'
export const combinedUnresolvedMigrationDetail = 'Optionally clear unresolved parent escalation-deposit accounting while migrating remaining REP backing units and underwriting commitments.'
export const bidPrice = 'Bid price'
export const bidPriceUnit = 'ETH per REP'
export const submittingBidTruncated = 'Submitting bid…'
export const truthAuctionAddress = 'Truth auction address'
export const started = 'Started'
export const ended = 'Ended'
export const minBidSizeAttoEth = 'Min bid size'
export const maxAttoRepBeingSold = 'Max REP being sold'
export const settlementAvailable = 'Settlement available'
export const migrationStatus = 'Migration status'
export const repAtFork = 'REP at fork'
export const migratedAttoRep = 'Migrated REP'
export const settlementCollateral = 'Settlement collateral'
export const migrationStarted = 'Migration started'
export const migrationEnds = 'Migration ends'
export const forkType = 'Fork type'
export const advancedDiagnostics = 'Advanced diagnostics'
export const totalPoolHeldRepAtForkAttoRep = 'Pool-held REP at fork'
export const escalationChildRepPerSelectedOutcomeAttoRep = 'Dispute-staked REP per selected outcome'
export const escrowSourceRepAtForkAttoRep = 'Dispute-staked REP source at fork'
export const formatSettleSelectedValueForkCarriedDeposits = (outcomeLabel: CopyTemplateValue) => `Settle selected ${outcomeLabel} fork-carried deposits`
export const settlingForkCarriedDepositsTruncated = 'Settling fork-carried deposits…'
export const forkLifecycleStages = 'Fork lifecycle stages'
export const viewing = 'Viewing'
export const triggeredAt = 'Triggered at'
export const forkNotTriggered = 'Fork not triggered'
export const yourMigrationBalances = 'Your migration balances'
export const parentWalletBalancesDescription = 'Wallet-level balances in the parent pool that may still need migration.'
export const clearUnresolvedParentEscalationDepositAccounting = 'Optional: Clear unresolved parent escalation-deposit accounting'
export const unresolvedMigrationExpiredDetail = 'The optional unresolved parent escalation-deposit accounting cleanup window has closed. Child backing and winning-proof eligibility are unchanged.'
export const unresolvedEscalationMigrationWithVaultDetail =
	'First transfers this wallet’s REP backing units and underwriting commitments to the selected child, checkpoints but retains claimable fees in the parent vault, and separately routes proportional pool-level settlement collateral. It then clears the three parent outcome totals in constant-size work. This is not required to fund dispute-staked REP backing or claim a winning carried proof; inherited losers require no claim transaction.'
export const walletUnresolvedDepositsLoading = 'Loading unresolved parent escalation-deposit accounting for the connected wallet…'
export const capturedEntitlementDetail = 'Unresolved parent escalation-deposit accounting was already cleared. Child proof eligibility is unchanged.'
export const formatEntitlementAlreadyMaterialized = (outcomeLabel: CopyTemplateValue) => `This wallet’s optional unresolved parent escalation-deposit accounting cleanup is already recorded for the ${outcomeLabel} child universe.`
export const formatNoUnresolvedDeposits = (outcomeLabel: string) => `No ${outcomeLabel} unresolved deposits remain for this wallet.`
export const formatMigrateUnresolvedEscalationToValue = (outcomeLabel: CopyTemplateValue) => `Clear unresolved parent escalation-deposit accounting for ${outcomeLabel}`
export const migratingUnresolvedEscalationTruncated = 'Clearing unresolved parent escalation-deposit accounting…'
export const claimResolvedParentEscalationDeposits = 'Optional: Claim parent escalation deposits'
export const resolvedParentDepositClaimDetail = 'This fast path pays selected winning parent deposits directly in child REP and marks their carried proofs spent. Unclaimed winners can instead settle from aggregate child backing with a proof.'
export const parentEscalationClaimEmptyDisputeStakedRepDetail = 'No parent dispute-staked REP is currently visible for a direct claim by the connected wallet.'
export const walletEscalationDepositsLoading = 'Loading escalation deposits for the selected wallet…'
export const chooseParentDepositsToClaim = 'Choose deposits to claim'
export const worthNowPendingClaimFinalization = 'Worth now: Pending direct claim'
export const formatClaimSelectedValueParentDeposits = (outcomeLabel: CopyTemplateValue) => `Claim selected ${outcomeLabel} deposits`
export const claimingParentEscalationDepositsTruncated = 'Claiming parent escalation deposits…'
export const migratePoolToUniverse = 'Migrate pool to universe'
export const poolRepMigrationDetail = 'This moves pool-held REP attributed to the selected outcome into the child universe. It affects the outcome pool, not just your vault.'
export const poolRepAlreadyMigratedDetail = 'Pool-held REP has already been migrated to the selected child universe.'
export const poolRepStagedForVaultMigrationDetail = 'Pool-held REP for this outcome is already staged and will sweep into the child universe during vault migration.'
export const formatMigratePoolToValueUniverse = (outcomeLabel: CopyTemplateValue) => `Migrate pool to ${outcomeLabel} universe`
export const migratingPoolToUniverseTruncated = 'Migrating pool to universe…'
export const vaultMigrationDetail = 'This moves all remaining pool-held vault REP backing migration power and underwriting commitments from your parent vault into the selected child pool. Escalation claims have zero parent-OI migration power and follow their separate claim path.'
export const formatMigrateVaultToValue = (outcomeLabel: CopyTemplateValue) => `Migrate vault to ${outcomeLabel}`
export const alreadyMigratedStatus = 'Already migrated'
export const truthAuctionStatus = 'Truth auction status'
export const startTruthAuctionDetail = 'Start the ETH-for-REP truth auction once migration closes. Winning bids later claim REP backing units and a share of the auctioned underwriting commitments; losing bids are credited for withdrawal during settlement.'
export const bypassTruthAuction = 'Bypass truth auction'
export const bypassingAuctionTruncated = 'Bypassing auction…'
export const settlementStatus = 'Settlement status'
export const forkWorkflowDescription = 'Select a pool to inspect fork progress, migration, and the truth auction.'
export const forkTruthAuction = 'Fork & truth auction'
export const formatMissingChildUniverseDetail = (outcomeLabel: CopyTemplateValue) => `Child universe not created for the ${outcomeLabel} outcome.`
export const bidder = 'Bidder'
export const currentBids = 'Current bids'
export const formatShownBidCount = (shownBidCount: CopyTemplateValue, totalBidCount: CopyTemplateValue) => `Showing ${shownBidCount} of ${totalBidCount} bids at the loaded prices`
export const loadingAuctionBids = 'Loading auction bids…'
export const retryAuctionBids = 'Retry'
export const retryCurrentBids = 'Retry current bids'
export const retryMyBids = 'Retry my bids'
export const retryingAuctionBids = 'Retrying auction bids…'
export const retryAuctionDetails = 'Retry'
export const retryingAuctionDetails = 'Retrying auction details…'
export const retryForkWorkflow = 'Retry fork workflow'
export const retryChildUniverse = 'Retry child universe'
export const formatLoadingOutcomePoolDetail = (outcomeLabel: CopyTemplateValue) => `Loading the ${outcomeLabel} child pool…`
export const retryPoolRepReadiness = 'Retry pool-held REP readiness'
export const retryReporting = 'Retry reporting'
export const loadingReportingDetails = 'Loading reporting details…'
export const auctionPriceLevelsEmpty = 'No active prices are currently visible for this auction.'
export const loadedPriceBidsEmpty = 'No bids are currently indexed for the visible prices.'
export const auctionBidHistory = 'Auction bid history'
export const loadMoreTruthAuctionBids = 'Show more truth auction bids'
export const myBids = 'My bids'
export const walletBidsConnectionRequired = 'Connect a wallet to inspect your submitted truth auction bids.'
export const loadingYourBids = 'Loading your bids…'
export const walletBidsEmpty = 'No bids from this wallet are indexed for the current auction.'
export const loadMoreOfMyBids = 'Show more of my bids'
export const currentFormPrice = 'Your bid price'
export const currentSize = 'At this price'
export const loadedDepth = 'At or above'
export const loadMorePriceLevels = 'Show more price levels'
export const loadingOrderBook = 'Loading order book…'
export const loadingPriceLevels = 'Loading price levels…'
export const marketDepth = 'Market depth'
export const visibleAuctionLevelsEmpty = 'No active levels are visible.'
export const auctionLiveLevelsEmpty = 'No live price levels are currently active for this auction.'
export const priceLadder = 'Price ladder'
export const priceLadderHint = 'Select a price to use it as your bid price.'
export const formatSubmissionsLabel = (count: string) => `${count} submissions`
export const visibleDepth = 'Bids at or above each price'

export const auctionDetails = 'Auction details'

export const notYetCleared = 'Not yet cleared'
export const estimatedResult = 'Estimated result'
export const ethRefundSuffix = 'ETH refund'
export const selectAllBids = 'Select all'
export const clearBidSelection = 'Clear selection'
export const currentClearingPriceLead = 'Current clearing price: '
export const formatUseMinimumWinningPrice = (price: CopyTemplateValue) => `Use lowest winning price (${price}\u00a0ETH per REP)`
export const formatRepPerEthValue = (price: CopyTemplateValue) => `(≈\u00a0${price}\u00a0REP per ETH)`
export const formatBidBelowClearingWarning = (price: CopyTemplateValue) => `This price is below the current clearing price, so the bid would lose and only be refunded. Bid above ${price}\u00a0ETH per REP to win.`
export const bidAtClearingWarning = 'This price equals the clearing price. Earlier bids at this price fill first, so this bid may fill only partly or not at all. Bid higher to win in full.'
export const truthAuctionOpenProgressDetail = 'The ETH target has not been reached, so there is no clearing price yet. Once it is reached, a single clearing price decides which bids win.'
export const truthAuctionClearingProgressDetail = 'Higher bids now raise the clearing price, so less REP is sold.'
