export const poolDetails = 'Pool details'
export const changePool = 'Change pool'
export const openPool = 'Open pool'
export const backToPools = 'Browse pools'
export const moreTools = 'More tools'
export const moreActions = 'More actions'
export const capacityLabel = 'Open interest / estimated capacity'
export const capacityUnavailable = 'A current price is needed to estimate capacity.'
export const oracleUnavailable = 'Oracle price needs attention. Price-dependent actions may be unavailable.'
export const reviewOracle = 'Review oracle'
export const pendingReport = 'An oracle report is pending.'
export const viewReport = 'View report'
export const forkAvailable = 'This pool has a fork workflow to review.'
export const reviewFork = 'Review fork & migration'
export const stagedOperations = (count: bigint) => `${count.toString()} staged ${count === 1n ? 'operation' : 'operations'}`
export const reviewOperations = 'Review operations'
export const ends = 'Ends'
export const ended = 'Ended'
export const vaults = (count: bigint) => `${count.toString()} ${count === 1n ? 'vault' : 'vaults'}`
export const myVault = 'My vault'
export const vaultDetails = 'Vault details'
export const inspectVault = 'Look up a vault'
export const backingDetails = 'Backing details'
export const healthUnknown = 'Health unavailable'
export const poolPriceUnavailable = 'Oracle price unavailable'
export const poolPriceExpired = 'Oracle price expired'
export const openVault = 'Open vault'
