export const poolDetails = 'Pool details'
export const moreTools = 'More tools'
export const moreActions = 'More actions'
export const capacityLabel = 'Open interest / estimated capacity'
export const capacityUnavailable = 'Capacity needs a current price.'
export const viewReport = 'View report'
export const forkAvailable = 'Fork & migration available.'
export const reviewFork = 'Review fork & migration'
export const stagedOperationCount = (count: bigint) => `${count.toString()} staged ${count === 1n ? 'operation' : 'operations'}`
export const reviewOperations = 'Review operations'
export const vaults = (count: bigint) => `${count.toString()} ${count === 1n ? 'vault' : 'vaults'}`
export const myVault = 'My vault'
export const vaultDetails = 'Vault details'
export const byAddress = 'By address'
export const backingDetails = 'Backing details'
export const healthUnknown = 'Health unavailable'
export const poolPriceUnavailable = 'Oracle price unavailable'
export const poolPriceExpired = 'Oracle price expired'
export const openVault = 'Open vault'

export const allVaults = 'All vaults'
