import type { CopyTemplateValue } from '@zoltar/ui-core-shared/copy/types.js'

export const createPoolDescriptionLead = 'Set up a '
export const createPoolDescriptionTail = ' for one question. Vaults secure it with REP; traders mint its shares with ETH.'
export const createQuestionForPoolDetail = undefined
export const createQuestionForPoolTitle = 'Create a pool question'
export const questionSourceLegend = 'How do you want to choose the pool question?'
export const useQuestionId = 'Use a question ID'
export const createNewQuestion = 'Create a new question'
export const questionCreatedPoolPending = 'Question created. The security pool transaction is next.'
export const retryPoolCreation = 'Retry pool creation'
export const createQuestionAndPool = 'Create question and pool'
export const checkingQuestionExists = 'Checking whether this question exists…'
export const questionAlreadyExists = 'This question already exists.'
export const questionAlreadyHasPool = 'A pool already exists for this question and configuration.'
export const openExistingPool = 'Open existing pool →'
export const useExistingQuestion = 'Use existing question'
export const questionExistenceUnavailable = 'Could not check whether this question exists. Try again after the connection recovers.'
export const creatingQuestionAndPool = 'Creating question and pool…'
export const poolCreationInProgress = 'Security pool creation is already in progress.'
export const createQuestionAndPoolReviewTitle = 'Create question and security pool'
export const createPoolReviewTitle = 'Create security pool'
export const universesDescriptionLead = 'Security pools grouped by '
export const universesDescriptionTail = '. A fork creates child universes, each with its own REP and pools.'
export const createPoolFromQuestion = 'Create pool from question'
export const formatCreatePoolFromQuestionLabel = (questionTitle: string, questionId: string) => `Create pool from question: ${questionTitle} (${questionId})`
export const badDebt = 'Bad debt'
export const formatDepositRepToVault = (tokenSymbol: CopyTemplateValue) => `Deposit ${tokenSymbol}`
export const formatDepositingRep = (tokenSymbol: CopyTemplateValue) => `Depositing ${tokenSymbol}…`
export const depositRepToVaultDescription = 'Increase the vault’s collateral.'
export const loadingVault = 'Loading vault details…'
export const openPool = 'Open pool'
export const formatOpenPoolLabel = (questionTitle: string, securityPoolAddress: string) => `Open pool: ${questionTitle} (${securityPoolAddress})`
export const priceValidUntil = 'Price valid until'
export const refreshing = 'Refreshing…'
export const reviewLiquidation = 'Liquidate vault'
export const selectedVaultOwner = 'Vault owner address'
export const missingVaultDetail = 'This vault does not exist.'
export const missingVaultRepBalanceReason = 'No REP is available in the active universe. Obtain or migrate REP into this universe before creating a vault.'
export const withdrawRep = 'Withdraw REP'
export const formatWithdrawRep = (tokenSymbol: CopyTemplateValue) => `Withdraw ${tokenSymbol}`
export const claimFees = 'Claim fees'
export const claimFeesTitle = 'Claim fees'
export const claimFeesDescription = 'Paid to the vault owner.'
export const escalationWithdrawalRequiredDetail = 'Withdraw escalation deposits before redeeming REP.'
export const openInterestFeeYear = 'Open interest fee / year'
export const totalPoolHeldAttoRep = 'Pool-held REP'
export const vaultCount = 'Known vaults'
export const loadingSecurityPools = 'Loading security pools…'
export const retryLoadingPools = 'Retry'
export const searchPools = 'Search or paste a pool address'
export const sortPools = 'Sort'
export const remainingCapacity = 'Remaining capacity'
export const noFavoritePools = 'No favorite pools yet'
export const noFavoritePoolsDetail = 'Open a pool by address to save it here.'
export const openPoolAtAddress = 'Open pool at this address'
export const formatOtherUniversePoolsHidden = (count: CopyTemplateValue) => `${count} saved in other universes.`
export const formatPoolUpdated = (relativeTime: CopyTemplateValue) => `Updated ${relativeTime}`
export const formatCapacityUsed = (percent: CopyTemplateValue) => `${percent}% used`
export const capacityRemaining = 'remaining'
export const poolSearchPlaceholder = 'Address, question ID, or text'
export const systemState = 'System state'
export const allStates = 'All states'
export const ended = 'Ended'
export const questionEnded = 'Question ended'
export const questionEnds = 'Question ends'
export const poolForked = 'Pool forked'
export const forkMigration = 'Fork migration'
export const poolCountSingular = 'pool'
export const poolCountPlural = 'pools'
export const poolSummarySingularVerb = 'matches'
export const poolSummaryPluralVerb = 'match'
export const formatPoolPageSummary = (matchingPoolCount: CopyTemplateValue, loadedPoolCount: CopyTemplateValue, poolLabel: CopyTemplateValue, matchVerb: CopyTemplateValue) => `${matchingPoolCount} of ${loadedPoolCount} ${poolLabel} ${matchVerb}.`
export const poolFiltersEmpty = 'No pools match the current search and filter settings.'
export const managerAddress = 'Manager address'
export const formatVaultDirectorySummary = (loadedVaultCount: CopyTemplateValue, totalVaultCount: CopyTemplateValue) => `Showing ${loadedVaultCount} current positions from ${totalVaultCount} known vaults, newest-registered first.`
export const vaultRegistryScanCapped = 'Registry scan limit reached. Some current positions may not be shown.'
export const vaultRegistryScanEmpty = 'No current positions found within the scan limit.'
export const formatNoCurrentVaultPositions = (knownVaultCount: bigint) => `No current positions among ${knownVaultCount.toString()} known ${knownVaultCount === 1n ? 'vault' : 'vaults'}.`
export const poolVaultsEmpty = 'No known vaults in this pool.'
export const autoExecPending = 'Auto-exec pending'
export const executeStagedOperation = 'Execute staged operation'
export const executingStagedOperationLabel = 'Executing staged operation…'
export const operationalForkReadOnlyDetail = 'This pool is currently operational, so fork and truth auction actions are read only.'
export const initiator = 'Initiator'
export const loadingStagedOperations = 'Loading staged operations…'
export const retryStagedOperations = 'Retry staged operations'
export const manualExecution = 'Manual execution'
export const stagedOperationsEmpty = 'No staged operations are currently queued for this pool.'
export const noneQueued = 'None queued'
export const liquidation = 'Liquidation'
export const formatPendingReportLabel = (reportId: string) => `Report #${reportId}`
export const poolNotFound = 'Pool not found'
export const refreshOracle = 'Refresh oracle'
export const refreshPool = 'Refresh pool'
export const refreshStagedOperations = 'Refresh staged operations'
export const refreshingOperations = 'Refreshing operations…'
export const refreshingPool = 'Refreshing pool…'
export const requestCost = 'Base request cost'
export const requestNewPrice = 'Request new price'
export const requestNewPriceTitle = 'Request new price'
export const requestingNewPrice = 'Requesting new price…'
export const confirmPriceRequest = 'Request new price'
export const loadOracleBeforePriceReview = 'Loading price oracle details…'
export const liquidationWorkflowDescription = 'Transfer commitments and REP backing from an unhealthy vault.'
export const selectedPool = 'Selected pool'
export const selectedPoolVaultViews = 'Selected pool vault views'
export const selectedPoolViews = 'Selected pool views'
export const selectedPoolUnavailableDetail = 'This pool does not exist.'
export const securityPoolAddressNotFoundDetail = 'This security pool address was not found.'
export const poolNotFoundDetail = 'Pool not found.'
export const noPoolSelectedBadgeLabel = 'No pool selected'
export const noPoolSelectedDetail = 'No pool selected.'
export const noPoolSelectedHint = 'Enter a pool address above or browse pools.'
export const poolPriceOracle = 'Price oracle'
export const parentPool = 'Parent pool'
export const pendingRequest = 'Pending request'
export const selectVault = 'Select vault'
export const formatShowingActiveStagedOperationsLabel = (loadedCount: string, activeCount: string) => `Showing ${loadedCount} of ${activeCount} active staged operations, newest first.`
export const stagedOperationId = 'Staged operation ID'
export const zeroPlaceholder = '0'
export const stagedOperations = 'Staged operations'
export const universeMismatch = 'Universe mismatch'
export const formatBrowsePoolUniverseMismatch = (poolUniverse: string) => `This pool belongs to ${poolUniverse}`
export const poolUniverseLead = 'This pool belongs to'
export const activeUniverseSeparator = 'but the app is currently set to'
export const missingPoolDetail = 'Pool actions are locked until the app uses the same universe.'
export const switchToPoolUniverse = 'Switch to pool universe'
export const returnToCurrentUniverse = 'Return to current universe'
export const refreshVaultActionsDetail = 'Refresh the vault to use these actions.'
export const retryVaultActionsDetail = 'Retry loading the vault to use these actions.'
export const invalidVaultAddressHint = 'Try another vault owner address.'
export const forkAlreadyTriggeredSettlementReason = 'The universe fork has already been triggered for this pool. Continue in Fork & migration.'
export const poolForkMigrationStatus = 'This pool has already entered Fork & migration.'
export const forkTriggerUnavailableReason = 'Triggering a universe fork is not available in the current pool state.'
export const reportingLockedDuringMigrationReason = 'This pool is in fork migration. Reporting actions unlock once the pool becomes operational.'
export const parentForkMigrationRedirectDetail = 'This parent pool is forked. Continue in Fork & migration for migration and settlement.'
export const reportingLockedDuringAuctionReason = 'This pool is in truth auction. Reporting actions unlock once the pool becomes operational.'
export const reportingStartDetail = 'Reporting opens after the question end time.'
export const reportingOraclePriceExpiredReason = "The pool's oracle price expired. Request a new price in Price Oracle, then retry."
export const reportingOraclePriceRequiredReason = 'The pool needs an oracle price before reporting. Request one in Price oracle.'
export const operationId = 'Operation ID'
export const createAnotherPool = 'Create another pool'
export const creatingPool = 'Creating pool…'
export const questionIdFallbackHint = 'Enter an exact binary Yes / No Zoltar question ID.'
export const poolCreationLocked = 'Pool creation locked'
export const poolCreated = 'Pool created'
export const poolCreationAfterForkReason = 'Security pools cannot be created after this universe has forked.'
export const checkingDuplicate = 'Checking duplicate…'
export const duplicatePoolDetail = 'Change the priority fee or security multiplier to create a different origin pool.'
export const initialOpenInterestFeeYear = 'Starting open interest fee / year'
export const ineligibleQuestionDetail = 'Security pools can only be created for exact binary Yes / No questions. Enter an eligible question to proceed.'
export const loadingQuestion = 'Loading question…'
export const poolAddressLabel = 'Pool address'
export const poolAlreadyExists = 'Pool already exists'
export const statoblastSecurityMultiplierBpsHelpText = 'Up to four decimal places; higher values require more REP.'
export const initialReportPriorityFeeHelpText = 'Fixed gas-price premium added to Open Oracle report security.'
export const initialReportPriorityFeeUnit = 'nanoETH per gas'
// A word rather than a lone ×, which reads as a clear-field button at the end of the input.
export const securityMultiplierInputUnit = 'times'
export const stagedOperationFailedDetail = 'The staged operation did not execute.'
export const claimableFees = 'Claimable fees'
export const claimingFees = 'Claiming fees…'
export const missingVaultDepositDetail = 'This vault does not exist. Deposit REP to create it.'
export const repBackingLabel = 'REP backing'
export const formatInsufficientRepBalanceDetail = (amount: string) => `Insufficient REP balance. Deposit amount exceeds your wallet balance by ${amount}\u00a0REP.`
export const connectWalletBeforeClaimingFees = 'Connect a wallet before claiming fees.'
export const connectWalletBeforeDepositingRep = 'Connect a wallet before depositing REP.'
export const connectWalletBeforeRedeemingRep = 'Connect a wallet before redeeming REP.'
export const connectWalletBeforeWithdrawingRep = 'Connect a wallet before withdrawing REP.'
export const selectOwnVaultToClaimFees = 'Select your own vault to claim fees.'
export const selectOwnVaultToDepositRep = 'Select your own vault to deposit REP.'
export const selectOwnVaultToRedeemRep = 'Select your own vault to redeem REP.'
export const selectOwnVaultToWithdrawRep = 'Select your own vault to withdraw REP.'
export const selfServiceExecutionTimeoutHelpText = 'Whole minutes; expires after oracle settlement.'
export const formatManualExecutionTimeoutResolvedDetail = (duration: string) => `If queued, this operation expires ${duration} after the oracle settlement window completes.`
export const owned = 'Owned'
export const readOnlyBadgeLabel = 'Read only'
export const refreshingWithdrawalStatusDetail = 'Refreshing the oracle manager to determine whether the withdrawal was queued or executed immediately.'
export const refreshingWithdrawalState = 'Refreshing withdrawal state'
export const repAvailableToQueue = 'REP available to queue'
export const actionRejectedDetail = 'The security pool rejected the action.'
export const repWithdrawalExecuted = 'REP withdrawal executed'
export const repWithdrawalFailed = 'REP withdrawal failed'
export const immediateWithdrawalRejectedDetail = 'The oracle manager attempted the withdrawal immediately, but the security pool rejected it.'
export const repWithdrawalQueued = 'REP withdrawal queued'
export const repWithdrawalSubmitted = 'REP withdrawal submitted'
export const formatRedeemRepFromVault = (tokenSymbol: CopyTemplateValue) => `Redeem ${tokenSymbol}`
export const redeemingRep = 'Redeeming REP…'
export const redeemableAttoRep = 'Redeemable REP'
export const repRedemptionDescription = 'Recover remaining REP after escalation deposits settle.'
export const repWithdrawAmount = 'REP withdraw amount'
export const repWithdrawal = 'REP withdrawal'
export const repWithdrawalDescription = 'Executes immediately with a valid oracle price; otherwise queued.'
export const selectedVaultDetailsUnavailable = 'Selected vault details are unavailable.'
export const associatedRepPerCapacity = 'Associated backing ratio'
export const poolHeldRepPerCapacity = 'Pool-held REP per committed ETH'
export const vaultHealthHealthy = 'Healthy'
export const vaultHealthNearMinimum = 'Near minimum'
export const vaultHealthUnderwater = 'Underwater'
export const requestedLiquidationDebt = 'Commitment to transfer'
export const securityVault = 'Security vault'
export const immediateWithdrawalSuccessDetail = 'A valid oracle price was already available, so the withdrawal executed immediately and no staged operation was created.'
export const vault = 'Vault'
export const noClaimableFeesReason = 'No fees are available to claim.'
export const vaultActions = 'Vault actions'
export const vaultActionsEndedDetail = 'REP deposits are unavailable because this pool has ended. Available redemption and fee actions remain below.'
export const vaultActionsForkMigrationDetail = 'REP-backing deposits and REP withdrawals are unavailable while this pool is in fork migration. Continue in Fork & migration. Fee claiming remains available only when this vault has accrued fees.'
export const vaultActionsTruthAuctionDetail = 'REP-backing deposits and REP withdrawals are unavailable while this pool is in a truth auction. Continue in Fork & migration. Fee claiming remains available only when this vault has accrued fees.'
export const vaultDepositAdmissionClosedDetail = 'New vault REP backing is unavailable after this question ends. Fork-continuation child pools remain fundable.'
export const vaultLookup = 'Vault lookup'
export const vaultMissing = 'Vault missing'
export const vaultSummary = 'Vault summary'
export const withdrawableAttoRep = 'Withdrawable REP'
export const withdrawingRep = 'Withdrawing REP…'

export const setVaultUnderwritingLimit = 'Set commitment limit'
export const adjustingVaultBackingFactor = 'Setting commitment limit'
export const minimumBackingRatio = 'Minimum backing ratio'
export const vaultBackingFactor = 'Commitment limit (ETH)'
export const vaultBackingFactorHelp = 'A standing ETH limit authorizes proportional coverage up to this amount. Depositing REP does not change it.'
export const queueTargetChangeFundingAction = 'queue this target change'
export const setVaultUnderwritingLimitDescription = 'Set your standing ETH underwriting limit.'
export const currentCapacity = 'Current commitment'
export const resultingCapacity = 'Resulting commitment'
export const initialReportPriorityFee = 'Initial report priority fee'
export const commitmentLimit = 'Commitment limit'

export const backingRatioChangeQueued = 'Commitment limit change queued'
export const backingRatioChangeExecuted = 'Commitment limit changed'
export const backingRatioChangeFailed = 'Commitment limit change failed'
export const backingRatioChangeSubmitted = 'Commitment limit change submitted'
export const refreshingBackingRatioStatus = 'Refreshing commitment status'
export const refreshingBackingRatioStatusDetail = 'Checking the target change result.'
export const backingRatioChangeSuccessDetail = 'The standing ETH commitment has been updated. REP deposits leave this limit unchanged.'
export const queuedVaultAutomaticExecution = 'Executes automatically when the oracle report settles.'

export const exposureSupported = 'Commitment limit'

export const queuedVaultOperationExpired = 'Queued operation expired'
export const queuedVaultOperationExpiredDetail = 'The execution window ended before this operation completed.'
export const queuedVaultOperationSuperseded = 'Target change replaced'
export const queuedVaultOperationSupersededDetail = 'A newer target change replaced this request.'

export const queuedVaultOperationManualRefreshDetail = 'If this operation is still pending, execute it manually after a valid oracle price is available.'
export const queuedVaultOperationAutomaticRefreshDetail = 'This request was submitted for automatic execution. Check its current status in staged operations.'

export const operationDetails = 'Operation details'
export const selectOperation = 'Select operation'
export const openOperationById = 'Open operation by ID'

export function universePoolCount(count: bigint) {
	return `${count} ${count === 1n ? 'pool' : 'pools'}`
}
export function universeVaultCount(count: bigint) {
	return `${count} known ${count === 1n ? 'vault' : 'vaults'}`
}

export const manualRepPerEth = 'Open Oracle REP per ETH starting price'
export const manualInitialPriceError = 'Enter a positive REP per ETH price with up to 18 decimal places.'

export const currentProportionalObligation = 'Current proportional obligation'

export const oracleOperationExecutesImmediately = 'Executes immediately with the current oracle price.'
export const oracleOperationQueuesForSettlement = 'Queues for execution after oracle settlement.'
export const oracleOperationMayNeedManualExecution = 'Queues; manual execution may be needed after oracle settlement.'
export const oracleOperationExecutionLoading = 'Checking whether this operation will execute immediately or queue.'

export const liquidationWalletRequiredReason = 'Connect a wallet to liquidate a vault.'
export const liquidationUnavailableReason = 'Liquidation is unavailable in this pool state.'
export const liquidationOwnVaultReason = 'Choose another vault to liquidate.'
export const withdrawalUnavailableReason = 'REP withdrawal is unavailable in this pool state.'
export const noWithdrawableRepReason = 'No REP is available to withdraw.'

export const maximumHealthyCommitment = 'Maximum before liquidation'
export const commitmentUnchanged = 'Enter a commitment limit different from the current one.'
export const commitmentPriceUnavailable = 'The selected UI price is unavailable. A liquidation-safe maximum cannot be estimated.'
export const commitmentRiskWarning = 'This limit would make your vault liquidatable at the selected UI price. The execution price may differ.'
export const commitmentRiskAcknowledgement = 'I understand that my vault could be liquidated immediately.'
export const commitmentRiskRequired = 'Confirm the immediate liquidation risk to continue.'
export const commitmentDirectExitDetail = 'The question has resolved, so this change goes straight to the pool without an oracle price. Commitments can only be lowered now; set 0 ETH to unlock REP redemption.'
export const commitmentIncreaseAfterResolutionError = 'Commitments can only be lowered after the question resolves.'
export const formatWithdrawEntireVaultNotice = (minimum: CopyTemplateValue) => `This leaves less than the ${minimum} vault minimum, so the whole vault is withdrawn instead.`
export const customApprovalAmountDisclosure = 'Advanced: custom approval amount'

export const questionEndedReason = 'This question has already ended.'

export const commitmentNeedsOracleReport = 'A new Open Oracle report is needed to change the commitment limit. Set its starting price and fund the report when submitting the change.'
export const openPriceOracle = 'Open price oracle'

export const oracleOperationPriceExpiresTooSoon = 'The oracle price expires too soon. Retry after it expires and review report funding.'
export const oracleOperationFundingChanged = 'Oracle funding requirements changed. Review funding again before sending.'
export const oracleOperationTimingUnavailable = 'Checking oracle price validity.'
