import { applicationMimeTypeExtensions } from './devServerApplicationMimeTypes.mts'

// Space-separated file extensions that the development server serves with each non-application MIME type.
const mediaMimeTypeExtensions: Readonly<Record<string, string>> = {
	'audio/adpcm': 'adp',
	'audio/basic': 'au snd',
	'audio/midi': 'mid midi kar rmi',
	'audio/mp4': 'm4a mp4a',
	'audio/mpeg': 'mpga mp2 mp2a mp3 m2a m3a',
	'audio/ogg': 'oga ogg spx opus',
	'audio/s3m': 's3m',
	'audio/silk': 'sil',
	'audio/vnd.dece.audio': 'uva uvva',
	'audio/vnd.digital-winds': 'eol',
	'audio/vnd.dra': 'dra',
	'audio/vnd.dts': 'dts',
	'audio/vnd.dts.hd': 'dtshd',
	'audio/vnd.lucent.voice': 'lvp',
	'audio/vnd.ms-playready.media.pya': 'pya',
	'audio/vnd.nuera.ecelp4800': 'ecelp4800',
	'audio/vnd.nuera.ecelp7470': 'ecelp7470',
	'audio/vnd.nuera.ecelp9600': 'ecelp9600',
	'audio/vnd.rip': 'rip',
	'audio/webm': 'weba',
	'audio/x-aac': 'aac',
	'audio/x-aiff': 'aif aiff aifc',
	'audio/x-caf': 'caf',
	'audio/x-flac': 'flac',
	'audio/x-matroska': 'mka',
	'audio/x-mpegurl': 'm3u',
	'audio/x-ms-wax': 'wax',
	'audio/x-ms-wma': 'wma',
	'audio/x-pn-realaudio': 'ram ra',
	'audio/x-pn-realaudio-plugin': 'rmp',
	'audio/x-wav': 'wav',
	'audio/xm': 'xm',
	'chemical/x-cdx': 'cdx',
	'chemical/x-cif': 'cif',
	'chemical/x-cmdf': 'cmdf',
	'chemical/x-cml': 'cml',
	'chemical/x-csml': 'csml',
	'chemical/x-xyz': 'xyz',
	'font/collection': 'ttc',
	'font/otf': 'otf',
	'font/ttf': 'ttf',
	'font/woff': 'woff',
	'font/woff2': 'woff2',
	'image/avif': 'avif',
	'image/bmp': 'bmp',
	'image/cgm': 'cgm',
	'image/g3fax': 'g3',
	'image/gif': 'gif',
	'image/ief': 'ief',
	'image/jpeg': 'jpeg jpg jpe',
	'image/jxl': 'jxl',
	'image/ktx': 'ktx',
	'image/png': 'png',
	'image/prs.btif': 'btif',
	'image/sgi': 'sgi',
	'image/svg+xml': 'svg svgz',
	'image/tiff': 'tiff tif',
	'image/vnd.adobe.photoshop': 'psd',
	'image/vnd.dece.graphic': 'uvi uvvi uvg uvvg',
	'image/vnd.djvu': 'djvu djv',
	'image/vnd.dwg': 'dwg',
	'image/vnd.dxf': 'dxf',
	'image/vnd.fastbidsheet': 'fbs',
	'image/vnd.fpx': 'fpx',
	'image/vnd.fst': 'fst',
	'image/vnd.fujixerox.edmics-mmr': 'mmr',
	'image/vnd.fujixerox.edmics-rlc': 'rlc',
	'image/vnd.ms-modi': 'mdi',
	'image/vnd.ms-photo': 'wdp',
	'image/vnd.net-fpx': 'npx',
	'image/vnd.wap.wbmp': 'wbmp',
	'image/vnd.xiff': 'xif',
	'image/webp': 'webp',
	'image/x-3ds': '3ds',
	'image/x-cmu-raster': 'ras',
	'image/x-cmx': 'cmx',
	'image/x-freehand': 'fh fhc fh4 fh5 fh7',
	'image/x-icon': 'ico',
	'image/x-mrsid-image': 'sid',
	'image/x-pcx': 'pcx',
	'image/x-pict': 'pic pct',
	'image/x-portable-anymap': 'pnm',
	'image/x-portable-bitmap': 'pbm',
	'image/x-portable-graymap': 'pgm',
	'image/x-portable-pixmap': 'ppm',
	'image/x-rgb': 'rgb',
	'image/x-tga': 'tga',
	'image/x-xbitmap': 'xbm',
	'image/x-xpixmap': 'xpm',
	'image/x-xwindowdump': 'xwd',
	'message/rfc822': 'eml mime',
	'model/iges': 'igs iges',
	'model/mesh': 'msh mesh silo',
	'model/vnd.collada+xml': 'dae',
	'model/vnd.dwf': 'dwf',
	'model/vnd.gdl': 'gdl',
	'model/vnd.gtw': 'gtw',
	'model/vnd.vtu': 'vtu',
	'model/vrml': 'wrl vrml',
	'model/x3d+binary': 'x3db x3dbz',
	'model/x3d+vrml': 'x3dv x3dvz',
	'model/x3d+xml': 'x3d x3dz',
	'text/cache-manifest': 'appcache',
	'text/calendar': 'ics ifb',
	'text/css': 'css',
	'text/csv': 'csv',
	'text/html': 'html htm',
	'text/javascript': 'js mjs',
	'text/n3': 'n3',
	'text/plain': 'txt text conf def list log in',
	'text/prs.lines.tag': 'dsc',
	'text/richtext': 'rtx',
	'text/sgml': 'sgml sgm',
	'text/tab-separated-values': 'tsv',
	'text/troff': 't tr roff man me ms',
	'text/turtle': 'ttl',
	'text/uri-list': 'uri uris urls',
	'text/vcard': 'vcard',
	'text/vnd.curl': 'curl',
	'text/vnd.curl.dcurl': 'dcurl',
	'text/vnd.curl.mcurl': 'mcurl',
	'text/vnd.curl.scurl': 'scurl',
	'text/vnd.dvb.subtitle': 'sub',
	'text/vnd.fly': 'fly',
	'text/vnd.fmi.flexstor': 'flx',
	'text/vnd.graphviz': 'gv',
	'text/vnd.in3d.3dml': '3dml',
	'text/vnd.in3d.spot': 'spot',
	'text/vnd.sun.j2me.app-descriptor': 'jad',
	'text/vnd.wap.wml': 'wml',
	'text/vnd.wap.wmlscript': 'wmls',
	'text/x-asm': 's asm',
	'text/x-c': 'c cc cxx cpp h hh dic',
	'text/x-fortran': 'f for f77 f90',
	'text/x-java-source': 'java',
	'text/x-nfo': 'nfo',
	'text/x-opml': 'opml',
	'text/x-pascal': 'p pas',
	'text/x-setext': 'etx',
	'text/x-sfv': 'sfv',
	'text/x-uuencode': 'uu',
	'text/x-vcalendar': 'vcs',
	'text/x-vcard': 'vcf',
	'video/3gpp': '3gp',
	'video/3gpp2': '3g2',
	'video/h261': 'h261',
	'video/h263': 'h263',
	'video/h264': 'h264',
	'video/jpeg': 'jpgv',
	'video/jpm': 'jpm jpgm',
	'video/mj2': 'mj2 mjp2',
	'video/mp2t': 'ts m2t m2ts mts',
	'video/mp4': 'mp4 mp4v mpg4',
	'video/mpeg': 'mpeg mpg mpe m1v m2v',
	'video/ogg': 'ogv',
	'video/quicktime': 'qt mov',
	'video/vnd.dece.hd': 'uvh uvvh',
	'video/vnd.dece.mobile': 'uvm uvvm',
	'video/vnd.dece.pd': 'uvp uvvp',
	'video/vnd.dece.sd': 'uvs uvvs',
	'video/vnd.dece.video': 'uvv uvvv',
	'video/vnd.dvb.file': 'dvb',
	'video/vnd.fvt': 'fvt',
	'video/vnd.mpegurl': 'mxu m4u',
	'video/vnd.ms-playready.media.pyv': 'pyv',
	'video/vnd.uvvu.mp4': 'uvu uvvu',
	'video/vnd.vivo': 'viv',
	'video/webm': 'webm',
	'video/x-f4v': 'f4v',
	'video/x-fli': 'fli',
	'video/x-flv': 'flv',
	'video/x-m4v': 'm4v',
	'video/x-matroska': 'mkv mk3d mks',
	'video/x-mng': 'mng',
	'video/x-ms-asf': 'asf asx',
	'video/x-ms-vob': 'vob',
	'video/x-ms-wm': 'wm',
	'video/x-ms-wmv': 'wmv',
	'video/x-ms-wmx': 'wmx',
	'video/x-ms-wvx': 'wvx',
	'video/x-msvideo': 'avi',
	'video/x-sgi-movie': 'movie',
	'video/x-smv': 'smv',
	'x-conference/x-cooltalk': 'ice',
}

const buildExtensionMimeTypes = (...mimeTypeTables: ReadonlyArray<Readonly<Record<string, string>>>): ReadonlyMap<string, string> => {
	const mimeTypesByExtension = new Map<string, string>()
	for (const mimeTypeTable of mimeTypeTables) {
		for (const [mimeType, extensions] of Object.entries(mimeTypeTable)) {
			for (const extension of extensions.split(' ')) {
				const existingMimeType = mimeTypesByExtension.get(extension)
				if (existingMimeType !== undefined) throw new Error(`File extension ${extension} maps to both ${existingMimeType} and ${mimeType}`)
				mimeTypesByExtension.set(extension, mimeType)
			}
		}
	}
	return mimeTypesByExtension
}

const extensionMimeTypes = buildExtensionMimeTypes(applicationMimeTypeExtensions, mediaMimeTypeExtensions)

// Responses for unknown extensions carry no Content-Type header.
export const getDevServerMimeType = (filePath: string): string | undefined => {
	const extension = filePath.split('.').pop()
	return extension === undefined ? 'text/plain' : extensionMimeTypes.get(extension)
}
