export const sharedBrowserArtifactRelativePaths = [
	'shared/js/serialization/bigInt.js',
	'shared/js/constants.js',
	'shared/js/deployment/deploymentAddresses.js',
	'shared/js/oracle/escalationMath.js',
	'shared/js/evm/ethereum.js',
	'shared/js/statoblast/liquidation.js',
	'shared/js/evm/logScan.js',
	'shared/js/oracle/openOracle.js',
	'shared/js/oracle/oracleInitialReport.js',
	'shared/js/deployment/protocolConfig.js',
	'shared/js/statoblast/scalarOutcome.js',
	'shared/js/deployment/sepoliaRepAllocations.js',
	'shared/js/serialization/sortStringArrayByKeccak.js',
	'shared/js/statoblast/truthAuctionTickMath.js',
	'shared/js/trading/math.js',
	'shared/js/trading/positions.js',
	'shared/js/trading/transactions.js',
] as const
