export const appDocumentTitleSuffix = 'Zoltar + Augur Placeholder'
export const connecting = 'Connecting…'
export const changeWallet = 'Change Wallet'
export const disconnectWallet = 'Disconnect'
export const accountMenu = 'Account Menu'
export const currentNetwork = 'Current Network'
export const copyAddress = 'Copy Address'
export const addressCopied = 'Address Copied'
export const switchToEthereumMainnet = 'Switch to Ethereum Mainnet'
export const ethereumMainnet = 'Ethereum Mainnet'
export const managingWallet = 'Updating wallet…'
export const formatWalletNetwork = (chainId: string | undefined) => {
	if (chainId === undefined) return 'Unknown network'
	if (chainId === '0xaa36a7') return 'Sepolia (11155111)'
	return `Chain ${chainId}`
}
export const oracleReports = 'Oracle Reports'
export const questionsAndMarkets = 'Questions & Markets'
export const refreshRepPrices = 'Refresh REP prices'
export const repPerEthCompact = 'REP/ETH'
export const skipToMainContent = 'Skip to main content'
export const createOracleReport = 'Create Oracle Report'
export const deployContracts = 'Deploy Contracts'
export const manageSecurityPool = 'Manage Security Pool'
export const oracleReportDetails = 'Oracle Report Details'
export const pageNotFoundTitle = 'Page Not Found'
export const browse = 'Browse'
export const createReport = 'Create Report'
export const oracleReportViews = 'Oracle report views'
export const browsePools = 'Browse Pools'
export const securityPoolsViews = 'Security Pools views'
export const marketViews = 'Market views'
export const usdc = 'USDC'
export const activeReadRpc = 'Active read RPC'
export const configuredFallbackReadRpc = 'Configured fallback read RPC'
export const defaultSource = 'default'
export const environment = 'environment'
export const explicitOverride = 'explicit override'
export const deploymentIncompleteReason = 'Required application contracts are not deployed.'
export const globalRuntime = 'global runtime'
export const readRpcOverrideIgnored = 'Read RPC override ignored'
export const localStorage = 'local storage'
export const pageUrl = 'page URL'
export const formatReadRpcOverrideIgnoredDetail = (sourceLabel: string, url: string, reason: string, configuredRpcLabel: string, activeRpcUrl: string) => `Ignored ${sourceLabel} RPC override (${url}): ${reason} ${configuredRpcLabel} is ${activeRpcUrl}.`
export const formatReadRpcOverrideFromUrlDetail = (configuredRpcLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from the page URL: ${rpcUrl}. Verify this endpoint before relying on displayed onchain state.`
export const formatReadRpcOverrideActiveDetail = (configuredRpcLabel: string, sourceLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from ${sourceLabel}: ${rpcUrl}. Verify this endpoint before relying on displayed onchain state.`
export const readWriteNetworkMismatchDetail = 'Displayed onchain state may not match the network this interface writes to.'
export const readRpcMismatch = 'Read RPC mismatch'
export const readRpcOverrideActive = 'Read RPC override active'
export const setupIncomplete = 'Setup incomplete'
export const simulationBootstrapFailed = 'Simulation bootstrap failed'
export const staleReadBackendDetail = 'Displayed onchain state may be behind the latest chain state. Refresh or switch RPC before acting on balances, settlement, or liquidation.'
export const hasForkedOn = 'has forked on'
export const universeForked = 'Universe forked'
export const urlProvidedReadRpc = 'URL-provided read RPC'
export const address = 'Address'
export const augurPlaceholderTitle = 'Augur Placeholder'
export const connected = 'Connected'
export const notConnected = 'Not connected'
export const operations = 'Operations'
export const parentUniverse = 'Parent Universe'
export const readOnly = 'Read-only'
export const repUsdc = 'REP/USDC'
export const refreshingRepPrices = 'Refreshing REP prices…'
export const simulation = 'Simulation'
export const simulationNetworkDisclaimer = 'Simulation mode uses browser-local contract state. Transactions do not affect a public network.'
export const universeForkedDetail = 'This universe has forked.'
export const zoltarForkedOn = 'Zoltar forked on'
export const wrongNetworkBadgeLabel = 'Wrong Network'
export const showEnvironmentDetails = 'Show environment details'
export const hideEnvironmentDetails = 'Hide environment details'
export const applicationSections = 'Application sections'
export const deploymentRequiredDetail = 'Deploy the application contracts before using this section.'
export const currentApplicationSection = 'Current application section'
export const protocolGuide = 'Protocol Guide'
export const protocolGuideHref = 'https://augurproject.github.io/zoltar/docs/start-here.html'
