import type { CopyTemplateValue } from './types.js'

export const active = 'Active'
export const amount = 'Amount'
export const approvingRep = 'Approving REP…'
export const cancel = 'Cancel'
export const walletConnectionRequired = 'Connect wallet to continue.'
export const copied = 'Copied'
export const createQuestion = 'Create Question'
export const createSecurityPool = 'Create Security Pool'
export const deployed = 'Deployed'
export const ends = 'Ends'
export const positiveAmountRequired = 'Enter an amount greater than zero.'
export const error = 'Error'
export const escrowedRep = 'Escrowed REP'
export const eth = 'ETH'
export const failed = 'Failed'
export const forked = 'Forked'
export const forkThreshold = 'Fork Threshold'
export const forkTime = 'Fork Time'
export const forkTriggered = 'Fork Triggered'
export const hexValuePlaceholder = '0x...'
export const invalid = 'Invalid'
export const liquidationExecuted = 'Liquidation Executed'
export const liquidationFailed = 'Liquidation Failed'
export const liquidationSubmitted = 'Liquidation Submitted'
export const loading = 'Loading'
export const loadingWithEllipsis = 'Loading…'
export const loadingUniverseDetails = 'Loading universe details.'
export const managePool = 'Manage Pool'
export const max = 'Max'
export const multiplier = 'Multiplier'
export const no = 'No'
export const noMatches = 'No matches'
export const notFound = 'Not found'
export const opening = 'Opening…'
export const openOraclePrice = 'Open Oracle Price'
export const operational = 'Operational'
export const outcome = 'Outcome'
export const outcomeIndex = 'Outcome Index'
export const pending = 'Pending'
export const percent = '%'
export const question = 'Question'
export const questionId = 'Question ID'
export const rep = 'REP'
export const required = 'required'
export const repCollateral = 'REP Collateral'
export const repPerEth = 'REP / ETH'
export const reputationToken = 'Reputation Token'
export const securityBondAllowance = 'Security Bond Allowance'
export const securityMultiplier = 'Security Multiplier'
export const securityPoolAddress = 'Security Pool Address'
export const securityPools = 'Security Pools'
export const selected = 'Selected'
export const settled = 'Settled'
export const settlement = 'Settlement'
export const stagedOperation = 'Staged Operation'
export const starts = 'Starts'
export const status = 'Status'
export const technicalDetails = 'Technical details'
export const targetVault = 'Target Vault'
export const truthAuction = 'Truth Auction'
export const unavailable = 'Unavailable'
export const universe = 'Universe'
export const weth = 'WETH'
export const yes = 'Yes'
export const zeroDecimalPlaceholder = '0.0'
export const connectWallet = 'Connect wallet'
export const createPool = 'Create Pool'
export const close = 'Close'
export const manualExecutionTimeout = 'Manual Execution Timeout'
export const deploy = 'Deploy'
export const goToGenesisUniverse = 'Go to Genesis universe'
export const zoltar = 'Zoltar'
export const none = 'None'
export const refresh = 'Refresh'
export const refreshingWithoutEllipsis = 'Refreshing'
export const reportDetails = 'Report Details'
export const returnToBrowse = 'Return to Browse'
export const viewInStagedOperations = 'View In Staged Operations'
export const executed = 'Executed'
export const stagedOperationRetryDetail = 'Submit a new staged operation if you want to try again.'
export const transactionStateUnavailableDetail = 'The transaction succeeded, but the latest manager state is not available.'
export const manualQueuedOperationDetail = 'The settlement auto-execute list is full. Execute this staged operation manually with its ID after a valid oracle price is available.'
export const formatLabelValue = (label: CopyTemplateValue, value: CopyTemplateValue) => `${label}: ${value}`
export const formatPairSlash = (leftValue: CopyTemplateValue, rightValue: CopyTemplateValue) => `${leftValue} / ${rightValue}`
export const dismissErrorActionLabel = 'Dismiss error'
export const dropdownOptions = 'Dropdown options'
export const unknown = 'Unknown'
export const availableNow = 'Available now'
export const blocked = 'Blocked'
export const formatCopyAddressValue = (address: CopyTemplateValue) => `Copy address ${address}`
export const formatCopyIdentifierValue = (identifier: CopyTemplateValue) => `Copy identifier ${identifier}`
export const metricUnavailablePlaceholder = '—'
export const loadMore = 'Load More'
export const nextPage = 'Next Page'
export const previousPage = 'Previous Page'
export const formatDecimalNumberRequiredError = (fieldLabel: CopyTemplateValue) => `${fieldLabel} must be a decimal number.`
export const approvalAmountInvalidError = 'Approval amount must be a decimal number.'
export const approvalAmount = 'Approval amount'
export const formatApproveValue = (tokenLabel: CopyTemplateValue) => `Approve ${tokenLabel}`
export const approvalSatisfied = 'Approval Satisfied'
export const formatApproveMaxValue = (tokenLabel: CopyTemplateValue) => `Approve Max ${tokenLabel}`
export const formatApproveTokenAmount = (amountLabel: CopyTemplateValue, tokenSymbol: CopyTemplateValue) => `Approve ${amountLabel} ${tokenSymbol}`
export const formatRequiredValue = (amount: CopyTemplateValue) => `Required ${amount}`
export const formatApprovedValue = (amount: CopyTemplateValue) => `Approved ${amount}`
export const formatValueApprovalAmount = (tokenLabel: CopyTemplateValue) => `${tokenLabel} Approval Amount`
export const leaveBlankForRequiredTotal = 'Leave blank for required total'
export const emptyStateDetail = 'Nothing to show.'
export const unlimitedApproval = 'Unlimited approval'
export const minutes = 'minutes'
export const noneSelected = 'None selected'
export const exists = 'Exists'
export const notDeployed = 'Not deployed'
export const working = 'Working…'
export const formatSelectedTickLabel = (selectedTick: string, totalTicks: string) => `${selectedTick} / ${totalTicks}`
export const mainnetRequiredReason = 'Switch to Ethereum mainnet.'
