export const deploying = 'Deploying…'
export const deploymentReadyStatus = 'Can deploy now.'
export const deploymentRunningStatus = 'Deployment in progress.'
export const notDeployedBadgeLabel = 'Not Deployed'
export const waiting = 'Waiting'
export const formatWaitingForPrerequisiteDetail = (prerequisiteLabel: string) => `Waiting for ${prerequisiteLabel}.`
export const allDeployed = 'All deployed'
export const formatCompletedSectionTitle = (sectionTitle: string) => `${sectionTitle} (Completed)`
export const contractsDeployed = 'Contracts deployed'
export const deployNextMissing = 'Deploy Next Missing'
export const deploymentGroups = 'Deployment Groups'
export const deploymentRunningStatusLabel = 'Deployment In Progress'
export const deploymentOverviewDetail = 'Deploy and verify the shared deterministic contracts that back the application.'
export const deterministicContractDeployment = 'Deterministic contract deployment'
export const loadingDeploymentStatus = 'Loading deployment status…'
export const nextDeployable = 'Next deployable'
