import * as commonCopy from './common.js'
import type { CopyTemplateValue } from './types.js'

export const disputeReport = 'Dispute Report'
export const settleReport = 'Settle Report'
export const disputeAndSwap = 'Dispute & Swap'
export const disputeDelay = 'Dispute Delay'
export const escalationHalt = 'Escalation Halt'
export const feePercentage = 'Fee Percentage'
export const price = 'Price'
export const protocolFee = 'Protocol Fee'
export const reportId = 'Report ID'
export const settlementTime = 'Settlement Time'
export const settlerReward = 'Settler Reward'
export const tokenPair = 'Token Pair'
export const standaloneOracleDescription = 'Create and fund a standalone Open Oracle report atomically, then review its dispute and settlement state.'
export const openOracleGame = 'Open Oracle Game'
export const formatApprovingTokenPendingLabel = (tokenSymbol: string) => `Approving ${tokenSymbol}…`
export const browseReports = 'Browse Reports'
export const formatBrowseReportsDescription = (pageSize: string) => `Browse every Open Oracle game and open a selected report view. Page size is fixed at ${pageSize} reports.`
export const formatBrowseShownCountSummary = (shownCount: string, pageCount: string) => `${shownCount} of ${pageCount} reports shown on this page.`
export const callbackContract = 'Callback Contract'
export const callbackExtra = 'Callback / Extra'
export const callbackGasLimit = 'Callback Gas Limit'
export const formatCurrentAmount1Label = (tokenSymbol: string) => `Current Amount 1 (${tokenSymbol})`
export const formatCurrentAmount2Label = (tokenSymbol: string) => `Current Amount 2 (${tokenSymbol})`
export const formatTokenPairSuffix = (token1Symbol: string, token2Symbol: string) => commonCopy.formatPairSlash(token1Symbol, token2Symbol)
export const formatReportBrowseTitle = (token1Symbol: string, token2Symbol: string, reportId: string) => `${formatTokenPairSuffix(token1Symbol, token2Symbol)} · ${formatReportNumberTitle(reportId)}`
export const createAnother = 'Create Another'
export const createStandaloneOracleGame = 'Create Standalone Oracle Game'
export const creating = 'Creating…'
export const reportCreatedDetail = 'The funded report was created successfully.'
export const createSuccess = 'Create Success'
export const currentPrice = 'Current Price'
export const currentReportState = 'Current Report State'
export const currentReporter = 'Current Reporter'
export const replacementSwapAmountsHint = 'Provide the replacement swap amounts for the selected report.'
export const submittingDispute = 'Submitting dispute…'
export const disputingTheReport = 'disputing the report'
export const disputeDelayHelpText = 'Delay in seconds after the initial report before disputes can begin.'
export const disputeOccurred = 'Dispute Occurred'
export const formatDisconnectedWalletApprovalReason = (tokenSymbol: string) => `Connect a wallet before approving ${tokenSymbol}.`
export const disputeWalletRequiredReason = 'Connect a wallet before disputing the report.'
export const settlementWalletRequiredReason = 'Connect a wallet before settling the report.'
export const economics = 'Economics'
export const formatDisputeAmountsInvalidReason = (tokenSymbol: string) => `Enter valid dispute amounts before approving ${tokenSymbol}.`
export const disputeEscalationStopAmountHelpText = 'Token1 amount where dispute escalation stops, entered as a decimal value for the token1 address.'
export const creationFundingRequirementHelpText = 'For ERC-20 pairs, this must exactly equal the settler reward.'
export const ethValueToSend = 'ETH Value To Send'
export const formatExactTokenRequiredLabel = (tokenSymbol: string) => `Exact ${tokenSymbol} Required`
export const initialToken1AmountHelpText = 'Token1 amount to report, entered as a decimal value for the token1 address.'
export const exactToken1Report = 'Exact Token1 Report'
export const initialToken2Amount = 'Initial Token2 Amount'
export const initialToken2AmountHelpText = 'Token2 amount in the initial price report, entered as a decimal value for the token2 address.'
export const disputeFeeHelpText = 'Fee charged during dispute economics, entered as a percentage.'
export const fee = 'Fee'
export const identity = 'Identity'
export const initialEconomics = 'Initial Economics'
export const initialReporter = 'Initial Reporter'
export const lastReportOpportunity = 'Last Report Opportunity'
export const reportLoadError = 'Failed to load Open Oracle reports.'
export const reportLoadRequired = 'Load a report first.'
export const escalationMultiplierHelpText = 'Escalation multiplier for dispute economics.'
export const formatNewAmountMustBeExactDetail = (tokenSymbol: string, amount: string) => `New ${tokenSymbol} amount must be exactly ${amount} for this dispute.`
export const settledReportReadOnlyDetail = 'This report lifecycle is settled. Connected accounts can still withdraw credited Oracle balances.'
export const oracleBalances = 'Your Oracle Balances'
export const oracleBalancesDetail = 'Settlement rewards, returned report liquidity, and dispute proceeds stay in the Oracle until the credited account withdraws them.'
export const noOracleBalances = 'No withdrawable Oracle balances are available for this token pair.'
export const loadingOracleBalances = 'Loading Oracle balances…'
export const withdrawBalance = (tokenSymbol: string) => `Withdraw ${tokenSymbol}`
export const withdrawingBalance = (tokenSymbol: string) => `Withdrawing ${tokenSymbol}…`
export const numberOfReports = 'Number of Reports'
export const openReport = 'Open report'
export const oracleAddress = 'Oracle Address'
export const protocolFeeHelpText = 'Protocol fee charged during disputes, entered as a percentage.'
export const protocolFeeRecipient = 'Protocol Fee Recipient'
export const report = 'Report'
export const formatReportNumberTitle = (reportId: string) => commonCopy.formatReportNumberLabel(reportId)
export const reportTimestamp = 'Report Timestamp'
export const reportActions = 'Report Actions'
export const reportActionFlowHint = 'Open a focused action flow for the selected report when it is available.'
export const searchReports = 'Search Reports'
export const settlementConfirmationHelpText = 'Settlement is confirmation-first. Review the current report state and confirm only when the dispute window is closed.'
export const settlementConfirmationHint = 'Confirm settlement once the selected report is ready.'
export const settlingReport = 'Settling report…'
export const settledReport = 'Settled Report'
export const settlerRewardHelpText = 'ETH paid to the account that settles the report.'
export const settlementSummary = 'Settlement Summary'
export const settlementDelayHelpText = 'Delay in seconds after the initial report before settlement can begin.'
export const settlementTimestamp = 'Settlement Timestamp'
export const notSettled = 'Not settled'
export const stateHash = 'State Hash'
export const allStatuses = 'All statuses'
export const disputed = 'Disputed'
export const oracleGamesEmpty = 'No Open Oracle games found.'
export const reportFiltersEmpty = 'No reports match the current search and status filters.'
export const reportSummariesRefreshingDetail = 'Refreshing report summaries.'
export const refreshReport = 'Refresh report'
export const reportAmounts = 'Report Amounts'
export const openOracleReportDetails = 'Open Oracle Report Details'
export const searchByReportIdTokenSymbolOrTokenAddress = 'Search by report ID, token symbol, or token address'
export const standaloneOracleWarningDetail = 'Use this only when you intend to create a standalone oracle game directly from the connected wallet. Pool-managed oracle requests should be started from a selected security pool.'
export const standaloneOperatorWorkflow = 'Standalone operator workflow'
export const standaloneOperatorWorkflowDetail = 'Creation approves both ERC-20 amounts and submits the funded initial report in one oracle call.'
export const verifyTokenPairStep = '1. Verify token pair'
export const setEconomicsStep = '2. Set economics'
export const setDisputeTimingStep = '3. Set dispute timing'
export const formatTimingValue = (timingAmount: CopyTemplateValue, usesSeconds: boolean) => `${timingAmount} ${usesSeconds ? 's' : 'blocks'}`
export const timing = 'Timing'
export const baseTokenHelpText = 'Base token for the reported pair.'
export const token1Address = 'Token1 Address'
export const formatTokenApprovalTitle = (tokenSymbol: string) => `${tokenSymbol} Approval`
export const quoteTokenHelpText = 'Quote token for the reported pair.'
export const token2Address = 'Token2 Address'
export const tokenToSwapOut = 'Token to Swap Out'
export const trackDisputes = 'Track Disputes'
export const formatNewTokenAmountFieldLabel = (tokenSymbol: string) => `New ${tokenSymbol} Amount`
export const reporter = 'Reporter'
export const stage = 'Stage'
