import type { CopyTemplateValue } from './types.js'

export const settleReport = 'Settle Report'
export const disputeAndSwap = 'Dispute & Swap'
export const disputeDelay = 'Dispute Delay'
export const disputeDelaySeconds = 'Dispute Delay (seconds)'
export const escalationHalt = 'Escalation Halt'
export const feePercentage = 'Fee Percentage'
export const disputeFeePercentage = 'Dispute Fee (%)'
export const price = 'Price'
export const protocolFee = 'Protocol Fee'
export const protocolFeePercentage = 'Protocol Fee (%)'
export const reportId = 'Report ID'
export const settlementTime = 'Settlement Time'
export const settlementDelaySeconds = 'Settlement Delay (seconds)'
export const settlerReward = 'Settler Reward'
export const tokenPair = 'Token Pair'
export const baseToken = 'Base Token'
export const quoteToken = 'Quote Token'
export const oracleBalance = 'Oracle Balance'
export const openOracleGame = 'Standalone Oracle Report'
export const formatApprovingTokenPendingLabel = (tokenSymbol: string) => `Approving ${tokenSymbol}…`
export const formatApproveToken = (tokenSymbol: CopyTemplateValue) => `Approve ${tokenSymbol}`
export const formatTokenApproved = (tokenSymbol: CopyTemplateValue) => `${tokenSymbol} Approved`
export const formatTokenWithdrawn = (tokenSymbol: CopyTemplateValue) => `${tokenSymbol} Withdrawn`
export const browseReports = 'Browse Reports'
export const formatBrowseShownCountSummary = (shownCount: string, pageCount: string) => `${shownCount} of ${pageCount} reports shown on this page.`
export const callbackContract = 'Callback Contract'
export const callbackExtra = 'Callback / Extra'
export const callbackGasLimit = 'Callback Gas Limit'
export const formatCurrentAmount1Label = (tokenSymbol: string) => `Current Amount 1 (${tokenSymbol})`
export const formatCurrentAmount2Label = (tokenSymbol: string) => `Current Amount 2 (${tokenSymbol})`
export const formatTokenPairSuffix = (token1Symbol: string, token2Symbol: string) => `${token1Symbol} / ${token2Symbol}`
export const formatReportBrowseTitle = (token1Symbol: string, token2Symbol: string, reportId: string) => `${token1Symbol} / ${token2Symbol} · Report #${reportId}`
export const createAnother = 'Create Another'
export const createStandaloneOracleGame = 'Create Standalone Oracle Report'
export const creating = 'Creating…'
export const createSuccess = 'Report created'
export const currentPrice = 'Current Price'
export const currentReportState = 'Current Report State'
export const currentReporter = 'Current Reporter'
export const submittingDispute = 'Submitting dispute…'
export const disputingTheReport = 'disputing the report'
export const disputeOccurred = 'Dispute Occurred'
export const formatDisconnectedWalletApprovalReason = (tokenSymbol: string) => `Connect a wallet before approving ${tokenSymbol}.`
export const disputeWalletRequiredReason = 'Connect a wallet before disputing the report.'
export const settlementWalletRequiredReason = 'Connect a wallet before settling the report.'
export const economics = 'Economics'
export const formatDisputeAmountsInvalidReason = (tokenSymbol: string) => `Enter valid dispute amounts before approving ${tokenSymbol}.`
export const disputeEscalationStopAmountHelpText = 'Base-token amount that ends escalation.'
export const creationFundingRequirementHelpText = 'ETH funding, including the settler reward.'
export const ethValueToSend = 'ETH Value To Send'
export const formatExactTokenRequiredLabel = (tokenSymbol: string) => `Exact ${tokenSymbol} Required`
export const initialToken1AmountHelpText = 'Base-token amount to report.'
export const exactToken1Report = 'Base Token Amount'
export const initialToken2Amount = 'Quote Token Amount'
export const initialToken2AmountHelpText = 'Quote-token amount to report.'
export const fee = 'Fee'
export const identity = 'Identity'
export const initialEconomics = 'Initial Economics'
export const initialReporter = 'Initial Reporter'
export const lastReportOpportunity = 'Last Report Opportunity'
export const reportLoadError = 'Failed to load Open Oracle reports.'
export const reportLoadRequired = 'Select a report first.'
export const escalationMultiplierHelpText = 'Dispute escalation multiplier.'
export const formatNewAmountMustBeExactDetail = (tokenSymbol: string, amount: string) => `New ${tokenSymbol} amount must be exactly ${amount} for this dispute.`
export const oracleBalances = 'Your Oracle Balances'
export const oracleBalancesDetail = 'Settlement rewards, returned report liquidity, and dispute proceeds stay in the Oracle until the credited account withdraws them.'
export const noOracleBalances = 'No withdrawable Oracle balances are available for this token pair.'
export const noWithdrawableBalanceForAsset = 'No withdrawable balance is available for this asset.'
export const loadingOracleBalances = 'Loading Oracle balances…'
export const withdrawBalance = (tokenSymbol: string) => `Withdraw ${tokenSymbol}`
export const withdrawingBalance = (tokenSymbol: string) => `Withdrawing ${tokenSymbol}…`
export const checkingWithdrawalBalance = (tokenSymbol: string) => `Checking ${tokenSymbol} balance…`
export const confirmWithdrawal = 'Confirm Withdrawal'
export const withdrawalRecipient = 'Recipient'
export const formatWithdrawalRisk = (tokenSymbol: CopyTemplateValue) => `Withdraws the full credited ${tokenSymbol} balance to the connected account. Wallet gas is separate.`
export const formatWithdrawalBalanceChanged = (tokenSymbol: CopyTemplateValue) => `Your withdrawable ${tokenSymbol} balance changed. Review the updated amount and confirm again`
export const withdrawalBalanceRefreshFailed = 'Unable to refresh the withdrawable balance'
export const numberOfReports = 'Number of Reports'
export const openReport = 'Open report'
export const oracleAddress = 'Oracle Address'
export const protocolFeeRecipient = 'Protocol Fee Recipient'
export const report = 'Report'
export const formatReportNumberTitle = (reportId: string) => `Report #${reportId}`
export const reportTimestamp = 'Report Timestamp'
export const reportActions = 'Report Actions'
export const searchReports = 'Search Reports'
export const settlingReport = 'Settling report…'
export const settlerRewardHelpText = 'ETH paid to the settler.'
export const settlementSummary = 'Settlement Summary'
export const settlementTimestamp = 'Settlement Timestamp'
export const notSettled = 'Not settled'
export const stateHash = 'State Hash'
export const allStatuses = 'All statuses'
export const disputed = 'Disputed'
export const oracleGamesEmpty = 'No Open Oracle reports found.'
export const reportFiltersEmpty = 'No reports match the current search and status filters.'
export const reportSummariesRefreshingDetail = 'Refreshing report summaries.'
export const refreshReport = 'Refresh report'
export const reportAmounts = 'Report Amounts'
export const openOracleReportDetails = 'Open Oracle Report Details'
export const searchByReportIdTokenSymbolOrTokenAddress = 'Search by report ID, token symbol, or token address'
export const standaloneOracleWarningDetail = 'Standalone only. Start pool-managed requests from a security pool.'
export const standaloneOracleIntroduction = 'Define the token pair and initial report economics first. Default dispute and timing settings are available below for users who need to tune the report lifecycle.'
export const advancedDisputeAndTimingSettings = 'Advanced Dispute & Timing Settings'
export const advancedDisputeAndTimingSettingsDetail = 'These values control how challenges escalate and when settlement becomes available. Keep the defaults unless your report requires different economics.'
export const standaloneFundingRisk = 'The ETH value and settler reward are committed to this standalone report; wallet gas is separate.'
export const standaloneDisputeSettingsRisk = 'Dispute fees, escalation, and timing settings determine when the report can be challenged and settled.'
export const secondsAbbreviation = 's'
export const blocks = 'blocks'
export const formatTimingValue = (timingAmount: CopyTemplateValue, unit: CopyTemplateValue) => `${timingAmount} ${unit}`
export const timing = 'Timing'
export const token1Address = 'Base Token Address'
export const formatTokenApprovalTitle = (tokenSymbol: string) => `${tokenSymbol} Approval`
export const token2Address = 'Quote Token Address'
export const tokenToSwapOut = 'Token to Swap Out'
export const trackDisputes = 'Track Disputes'
export const formatNewTokenAmountFieldLabel = (tokenSymbol: string) => `New ${tokenSymbol} Amount`
export const reporter = 'Reporter'
export const parameterDetails = 'Parameter Details'
export const standaloneParameterDetails = 'Exact report and escalation-halt amounts use base-token decimals. ETH funding must cover required funding and the settler reward. Dispute settings determine escalation timing and economics.'
