import * as commonCopy from './common.js'
import type { CopyTemplateValue } from './types.js'

export const annualFee = 'Annual Fee'
export const depositRep = 'Deposit REP'
export const loadingVault = 'Loading vault…'
export const maxLead = 'Max '
export const openInterestMinted = 'Open Interest Minted'
export const openPool = 'Open Pool'
export const poolAddress = 'Pool Address'
export const poolCollateralization = 'Pool collateralization'
export const priceValidUntil = 'Price Valid Until'
export const refreshing = 'Refreshing…'
export const reviewLiquidation = 'Review Liquidation'
export const selectedVaultAddress = 'Selected Vault Address'
export const setBondAllowance = 'Set Bond Allowance'
export const missingVaultDetail = 'This vault does not exist.'
export const vaults = 'Vaults'
export const withdrawRep = 'Withdraw REP'
export const claimFees = 'Claim Fees'
export const setSecurityBondAllowance = 'Set Security Bond Allowance'
export const walletRep = 'Wallet REP'
export const escalationWithdrawalRequiredDetail = 'Withdraw escalation deposits before redeeming REP.'
export const openInterestFeeYear = 'Open Interest Fee / Year'
export const totalRepCollateral = 'Total REP Collateral'
export const openInterestMintedMax = 'Open Interest Minted / Max'
export const vaultCount = 'Vault Count'
export const totalRepBacking = 'Total REP Backing'
export const currentOraclePrice = 'Current Oracle Price'
export const latestSettlementContextDetail = 'Latest settlement anchors the trading and liquidation views.'
export const retryingSecurityPoolsTruncated = 'Retrying security pools…'
export const retryLoadingPools = 'Retry Loading Pools'
export const searchLoadedPage = 'Search this page'
export const poolSearchPlaceholder = 'Pool address, question ID, or question text'
export const systemState = 'System State'
export const allStates = 'All states'
export const ended = 'Ended'
export const poolForked = 'Pool Forked'
export const forkMigration = 'Fork Migration'
export const vaultCoverage = 'Vault Coverage'
export const allPools = 'All pools'
export const hasVaults = 'Has vaults'
export const noVaults = 'No vaults'
export const formatPoolPageSummary = (matchingPoolCount: CopyTemplateValue, loadedPoolCount: CopyTemplateValue) => `${matchingPoolCount} of ${loadedPoolCount} pool${Number(loadedPoolCount) === 1 ? '' : commonCopy.pluralSuffix} ${Number(matchingPoolCount) === 1 ? 'matches' : 'match'}.`
export const loadSecurityPools = 'Load Security Pools'
export const noSecurityPools = 'No security pools'
export const poolFiltersEmpty = 'No pools match the current search and filter settings.'
export const managerAddress = 'Manager Address'
export const previewDeferred = 'Preview deferred'
export const formatVaultPreviewDeferred = (vaultCount: CopyTemplateValue) => `${vaultCount} vault${Number(vaultCount) === 1 ? '' : commonCopy.pluralSuffix} ${Number(vaultCount) === 1 ? 'is' : 'are'} registered. Open the pool to load individual vault details.`
export const liquidationReviewHint = 'Review liquidation details for this vault before queueing the action.'
export const formatVaultPreviewSummary = (loadedVaultCount: CopyTemplateValue, totalVaultCount: CopyTemplateValue) => `Showing ${loadedVaultCount} of ${totalVaultCount} active vaults in this preview, newest activity first.`
export const formatVaultDirectorySummary = (loadedVaultCount: CopyTemplateValue, totalVaultCount: CopyTemplateValue) => `Showing ${loadedVaultCount} of ${totalVaultCount} active vaults, newest activity first. Enter a vault address above to inspect any specific vault.`
export const poolVaultsEmpty = 'No vaults in this pool.'
export const autoExecPending = 'Auto-exec pending'
export const additionalPoolActions = 'Additional pool actions'
export const directory = 'Directory'
export const executeStagedOperation = 'Execute Staged Operation'
export const executingStagedOperationLabel = 'Executing staged operation…'
export const operationalForkReadOnlyDetail = 'This pool is currently operational, so fork and truth auction actions are read only.'
export const initiator = 'Initiator'
export const loadStagedOperations = 'Load Staged Operations'
export const manualExecution = 'Manual execution'
export const stagedOperationsEmpty = 'No staged operations are currently queued for this pool.'
export const noneQueued = 'None queued'
export const liquidation = 'Liquidation'
export const formatPendingReportLabel = (reportId: string) => commonCopy.formatReportNumberLabel(reportId)
export const primaryPoolActions = 'Primary pool actions'
export const poolNotFound = 'Pool not found'
export const refreshOracle = 'Refresh Oracle'
export const refreshPool = 'Refresh pool'
export const refreshStagedOperations = 'Refresh Staged Operations'
export const refreshingOracle = 'Refreshing oracle…'
export const refreshingOperations = 'Refreshing operations…'
export const refreshingPool = 'Refreshing pool…'
export const requestCost = 'Request Cost'
export const requestNewPrice = 'Request New Price'
export const requestingNewPrice = 'Requesting new price…'
export const liquidationWorkflowDescription = 'Inspect the liquidation quote, timeout, and execution path before queueing liquidation.'
export const selectedPool = 'Selected Pool'
export const selectedPoolVaultViews = 'Selected pool vault views'
export const poolContextAndMetrics = 'Pool context and metrics'
export const selectedPoolViews = 'Selected pool views'
export const waitForPoolLoadingReason = 'Wait for this pool to finish loading.'
export const loadValidPoolReason = 'Load a valid pool before using pool actions.'
export const loadPoolReason = 'Load a pool before using pool actions.'
export const selectedPoolUnavailableDetail = 'This pool does not exist.'
export const securityPoolAddressNotFoundDetail = 'This security pool address was not found.'
export const poolNotFoundDetail = 'Pool not found.'
export const noPoolSelectedBadgeLabel = 'No pool selected'
export const noPoolSelectedDetail = 'No pool selected.'
export const openOracle = 'Open Oracle'
export const parentPool = 'Parent Pool'
export const pendingRequest = 'Pending Request'
export const selectVault = 'Select Vault'
export const formatShowingActiveStagedOperationsLabel = (loadedCount: string, activeCount: string) => `Showing ${loadedCount} of ${activeCount} active staged operations, newest first.`
export const stagedOperationId = 'Staged Operation Id'
export const zeroPlaceholder = '0'
export const stagedOperations = 'Staged Operations'
export const universeMismatch = 'Universe Mismatch'
export const poolUniverseLead = 'This pool belongs to'
export const activeUniverseSeparator = 'but the app is currently set to'
export const missingPoolDetail = 'Pool actions are locked until the app uses the same universe.'
export const switchToPoolUniverse = 'Switch to Pool Universe'
export const returnToCurrentUniverse = 'Return to Current Universe'
export const vaultDirectory = 'Vault Directory'
export const vaultOperations = 'Vault Operations'
export const refreshVaultActionsDetail = 'Refresh the vault to use these actions.'
export const invalidVaultAddressHint = 'Try another vault address.'
export const forkAlreadyTriggeredSettlementReason = 'Zoltar fork has already been triggered for this pool. Continue in Fork & Migration.'
export const poolForkMigrationStatus = 'This pool has already entered Fork & Migration.'
export const forkTriggerUnavailableReason = 'Triggering a Zoltar fork is not available in the current pool state.'
export const reportingLockedDuringMigrationReason = 'This pool is in fork migration. Reporting actions unlock once the pool becomes operational.'
export const parentForkMigrationRedirectDetail = 'This parent pool is forked. Continue in Fork & Migration for migration and settlement.'
export const reportingLockedDuringAuctionReason = 'This pool is in truth auction. Reporting actions unlock once the pool becomes operational.'
export const reportingStartDetail = 'Reporting opens after market end.'
export const operationId = 'Operation Id'
export const createAnotherPool = 'Create Another Pool'
export const creatingPool = 'Creating Pool…'
export const poolCreationLocked = 'Pool Creation Locked'
export const poolCreated = 'Pool Created'
export const poolCreationAfterForkReason = 'Security pools cannot be created after Zoltar has forked.'
export const deploymentTransactionHash = 'Deployment transaction hash'
export const checkingDuplicate = 'Checking Duplicate…'
export const duplicatePoolDetail = 'A pool for this question and security multiplier already exists. Origin pool deployment is deterministic for that pair, so change the security multiplier to create a different pool.'
export const initialOpenInterestFeeYear = 'Starting Annual Fee'
export const ineligibleQuestionDetail = 'Security pools can only be created for exact binary Yes / No questions. Enter an eligible question to proceed.'
export const loadingQuestion = 'Loading question…'
export const poolAddressLabel = 'Pool address'
export const poolAlreadyExists = 'Pool Already Exists'
export const questionIdInputHint = 'Paste an exact binary Yes / No Zoltar question ID.'
export const securityMultiplierHelpText = 'REP target relative to open interest; higher values require more REP.'
export const depositingRep = 'depositing REP'
export const immediateBondAllowanceFailureDetail = 'The oracle manager attempted the allowance update immediately, but the security pool rejected it.'
export const bondAllowanceExecuted = 'Bond Allowance Executed'
export const bondAllowanceFailed = 'Bond Allowance Failed'
export const bondAllowanceQueued = 'Bond Allowance Queued'
export const bondAllowanceSubmitted = 'Bond Allowance Submitted'
export const claimableFees = 'Claimable Fees'
export const claimingFees = 'Claiming fees…'
export const missingVaultDepositDetail = 'This vault does not exist. Deposit REP to create it.'
export const currentBondAllowance = 'Current Bond Allowance'
export const currentSecurityBondAllowance = 'Current Security Bond Allowance'
export const repCollateralAmount = 'REP Collateral Amount'
export const depositRepPendingLabel = 'Depositing REP…'
export const firstDepositTail = 'in the first deposit.'
export const newVaultsRequireAtLeast = 'New vaults require at least'
export const formatInsufficientRepBalanceDetail = (amount: string) => `Insufficient REP balance. Deposit amount exceeds your wallet balance by ${amount} REP.`
export const formatVaultLauncherBlockerReason = (action: 'claim-fees' | 'deposit-rep' | 'rep-exit-redeem' | 'rep-exit-withdraw' | 'set-bond-allowance', blocker: 'connect-wallet' | 'missing-vault' | 'select-own-vault') => {
	if (blocker === 'missing-vault') return missingVaultDetail

	if (blocker === 'connect-wallet') {
		if (action === 'claim-fees') return 'Connect a wallet before claiming fees.'
		if (action === 'deposit-rep') return 'Connect a wallet before depositing REP.'
		if (action === 'rep-exit-redeem') return 'Connect a wallet before redeeming REP.'
		if (action === 'rep-exit-withdraw') return 'Connect a wallet before withdrawing REP.'
		return 'Connect a wallet before setting the security bond allowance.'
	}

	if (action === 'claim-fees') return 'Select your own vault to claim fees.'
	if (action === 'deposit-rep') return 'Select your own vault to deposit REP.'
	if (action === 'rep-exit-redeem') return 'Select your own vault to redeem REP.'
	if (action === 'rep-exit-withdraw') return 'Select your own vault to withdraw REP.'
	return 'Select your own vault to set the security bond allowance.'
}
export const selfServiceExecutionTimeoutHelpText = 'Whole minutes; expires after oracle settlement.'
export const formatManualExecutionTimeoutResolvedDetail = (duration: string) => `This queued self-service operation will expire ${duration} after the oracle settlement window completes.`
export const owned = 'Owned'
export const readOnlyBadgeLabel = 'Read only'
export const refreshingBondAllowanceStatusDetail = 'Refreshing the oracle manager to determine whether the bond allowance was queued or executed immediately.'
export const refreshingBondAllowanceState = 'Refreshing Bond Allowance State'
export const refreshingWithdrawalStatusDetail = 'Refreshing the oracle manager to determine whether the withdrawal was queued or executed immediately.'
export const refreshingWithdrawalState = 'Refreshing Withdrawal State'
export const repAvailableToQueue = 'REP Available To Queue'
export const actionRejectedDetail = 'The security pool rejected the action.'
export const repWithdrawalExecuted = 'REP Withdrawal Executed'
export const repWithdrawalFailed = 'REP Withdrawal Failed'
export const immediateWithdrawalRejectedDetail = 'The oracle manager attempted the withdrawal immediately, but the security pool rejected it.'
export const repWithdrawalQueued = 'REP Withdrawal Queued'
export const repWithdrawalSubmitted = 'REP Withdrawal Submitted'
export const redeemRep = 'Redeem REP'
export const redeemingRep = 'Redeeming REP…'
export const redeemableRep = 'Redeemable REP'
export const repRedemptionDescription = 'Redeem the remaining REP collateral from this ended pool after escalation deposits are settled.'
export const repWithdrawAmount = 'REP Withdraw Amount'
export const repWithdrawalDescription = 'Queue a REP withdrawal now, or let it execute immediately when a valid oracle price is already available.'
export const selectedVaultDetailsUnavailable = 'Selected vault details are unavailable.'
export const securityBondAllowanceAmount = 'Security Bond Allowance Amount'
export const securityVault = 'Security Vault'
export const bondAllowanceWorkflowDescription = 'Queue a new security bond allowance using the current oracle price context.'
export const queueingAllowanceUpdate = 'Queueing allowance update…'
export const selectedVault = 'Selected Vault'
export const immediateBondAllowanceSuccessDetail = 'A valid oracle price was already available, so the new bond allowance executed immediately and no staged operation was created.'
export const immediateWithdrawalSuccessDetail = 'A valid oracle price was already available, so the withdrawal executed immediately and no staged operation was created.'
export const vault = 'Vault'
export const noClaimableFeesReason = 'No fees are available to claim.'
export const vaultActions = 'Vault Actions'
export const vaultLookup = 'Vault Lookup'
export const vaultMissing = 'Vault missing'
export const vaultSummary = 'Vault Summary'
export const withdrawableRep = 'Withdrawable REP'
export const queueingRepWithdrawal = 'Queueing REP withdrawal…'
