import * as commonCopy from './common.js'
import type { CopyTemplateValue } from './types.js'

export const annualFee = 'Annual Fee'
export const depositRep = 'Deposit REP'
export const loadingVault = 'Loading vault…'
export const maxLead = 'Max '
export const openInterestMinted = 'Open Interest Minted'
export const openPool = 'Open Pool'
export const poolAddress = 'Pool Address'
export const poolCollateralization = 'Pool collateralization'
export const priceValidUntil = 'Price Valid Until'
export const refreshing = 'Refreshing…'
export const reviewLiquidation = 'Review Liquidation'
export const selectedVaultAddress = 'Selected Vault Address'
export const setBondAllowance = 'Set Bond Allowance'
export const missingVaultDetail = 'This vault does not exist.'
export const vaults = 'Vaults'
export const withdrawRep = 'Withdraw REP'
export const claimFees = 'Claim Fees'
export const setSecurityBondAllowance = 'Set Security Bond Allowance'
export const walletRep = 'Wallet REP'
export const escalationWithdrawalRequiredDetail = 'Withdraw escalation deposits before redeeming REP.'
export const openInterestFeeYear = 'Open Interest Fee / Year'
export const totalRepCollateral = 'Total REP Collateral'
export const openInterestMintedMax = 'Open Interest Minted / Max'
export const vaultCount = 'Vault Count'
export const totalRepBacking = 'Total REP Backing'
export const currentOraclePrice = 'Current Oracle Price'
export const latestSettlementContextDetail = 'Latest settlement anchors the trading and liquidation views.'
export const formatVaultCountLabel = (vaultCount: CopyTemplateValue) => `${vaultCount} vault${Number(vaultCount) === 1 ? '' : commonCopy.pluralSuffix}`
export const retryingSecurityPoolsTruncated = 'Retrying security pools…'
export const retryLoadingPools = 'Retry Loading Pools'
export const searchLoadedPage = 'Search Loaded Page'
export const poolSearchHelpText = 'Filter this page by pool address, question ID, or question text.'
export const systemState = 'System State'
export const allStates = 'All states'
export const ended = 'Ended'
export const poolForked = 'Pool Forked'
export const forkMigration = 'Fork Migration'
export const vaultCoverage = 'Vault Coverage'
export const allPools = 'All pools'
export const hasVaults = 'Has vaults'
export const noVaults = 'No vaults'
export const formatPoolPageSummary = (shownPoolCount: CopyTemplateValue, filteredPoolCount: CopyTemplateValue) => `Showing ${shownPoolCount} of ${filteredPoolCount} matching pools on this page.`
export const loadSecurityPools = 'Load Security Pools'
export const noSecurityPools = 'No security pools'
export const poolFiltersEmpty = 'No pools match the current search and filter settings.'
export const managerAddress = 'Manager Address'
export const previewDeferred = 'Preview deferred'
export const formatVaultPreviewDeferred = (vaultCount: CopyTemplateValue) => `${vaultCount} vault${Number(vaultCount) === 1 ? '' : commonCopy.pluralSuffix} ${Number(vaultCount) === 1 ? 'is' : 'are'} registered. Open the pool to load individual vault details.`
export const liquidationReviewHint = 'Review liquidation details for this vault before queueing the action.'
export const formatVaultPreviewSummary = (loadedVaultCount: CopyTemplateValue, totalVaultCount: CopyTemplateValue) => `Showing ${loadedVaultCount} of ${totalVaultCount} active vaults in this preview, newest activity first.`
export const formatVaultDirectorySummary = (loadedVaultCount: CopyTemplateValue, totalVaultCount: CopyTemplateValue) => `Showing ${loadedVaultCount} of ${totalVaultCount} active vaults, newest activity first. Enter a vault address above to inspect any specific vault.`
export const poolVaultsEmpty = 'No vaults in this pool.'
export const autoExecPending = 'Auto-exec pending'
export const additionalPoolActions = 'Additional pool actions'
export const directory = 'Directory'
export const executeStagedOperation = 'Execute Staged Operation'
export const executingStagedOperationLabel = 'Executing staged operation…'
export const operationalForkReadOnlyDetail = 'This pool is currently operational, so fork and truth auction actions are read only.'
export const initiator = 'Initiator'
export const loadStagedOperations = 'Load Staged Operations'
export const manualExecution = 'Manual execution'
export const stagedOperationsEmpty = 'No staged operations are currently queued for this pool.'
export const noneQueued = 'None queued'
export const liquidation = 'Liquidation'
export const formatPendingReportLabel = (reportId: string) => commonCopy.formatReportNumberLabel(reportId)
export const primaryPoolActions = 'Primary pool actions'
export const poolNotFound = 'Pool not found'
export const refreshOracle = 'Refresh Oracle'
export const refreshPool = 'Refresh pool'
export const refreshStagedOperations = 'Refresh Staged Operations'
export const refreshingOracle = 'Refreshing oracle…'
export const refreshingOperations = 'Refreshing operations…'
export const refreshingPool = 'Refreshing pool…'
export const requestCost = 'Request Cost'
export const requestNewPrice = 'Request New Price'
export const requestingNewPrice = 'Requesting new price…'
export const selfFundedPriceRequest = 'Self-funded price request'
export const selfFundedPriceRequestDetail = 'Request the price directly with your wallet. You remain the OpenOracle reporter and supply the temporary REP, WETH, and ETH funding.'
export const operationBounties = 'Operation Bounties'
export const operationBountiesDetail = 'Creators escrow REP or WETH for a pool operation. A permissionless operator supplies the OpenOracle reporting capital and earns the reward only after successful execution.'
export const operationBountyAcceptanceDetail = 'Acceptance revalidates the operation and, when the price is stale, requires room in the four-operation settlement batch.'
export const postOperationBounty = 'Post an operation bounty'
export const operation = 'Operation'
export const executionWindow = 'Execution Window'
export const acceptanceWindow = 'Acceptance Window'
export const rewardToken = 'Reward Token'
export const rewardAmount = 'Reward Amount'
export const minimumInitialWeth = 'Minimum Initial Report WETH'
export const maximumInitialWeth = 'Maximum Initial Report WETH'
export const noMinimum = 'No minimum'
export const noMaximum = 'No maximum'
export const initialWethBoundsDetail = "Optional bounds apply to either a proposed new report's WETH amount or the current WETH amount of an existing pending report."
export const executionWindowDetail = 'The cancellation deadline is fixed when accepted: queued time + one oracle settlement window + this execution window. Disputes do not extend it.'
export const selfTargetedBountyDetail = 'This operation targets the connected wallet’s own vault.'
export const postBounty = 'Post Bounty'
export const postingBounty = 'Posting bounty…'
export const availableOperationBounties = 'Operation bounties'
export const operationBountyLookupDetail = 'The newest 25 bounties load automatically. Enter any bounty ID to recover an older creator or operator action.'
export const bountyId = 'Bounty ID'
export const loadBounty = 'Load Bounty'
export const loadingBounty = 'Loading bounty…'
export const enterValidBountyId = 'Enter a positive bounty ID.'
export const bountyPaid = 'Paid'
export const bountyRefunded = 'Refunded'
export const bountyOpen = 'Open'
export const bountyAcceptanceExpiredState = 'Acceptance expired'
export const bountyReadyToClaim = 'Ready to claim'
export const bountyFailed = 'Execution failed'
export const bountyInProgress = 'In progress'
export const bountyExecutionExpired = 'Execution expired'
export const creator = 'Creator'
export const operator = 'Operator'
export const reward = 'Reward'
export const acceptBy = 'Accept By'
export const report = 'Report'
export const acceptAndFund = 'Accept & Fund Report'
export const acceptingBounty = 'Accepting bounty…'
export const claimBounty = 'Claim Bounty'
export const claimingBounty = 'Claiming bounty…'
export const refundBounty = 'Refund Bounty'
export const cancelAndRefundBounty = 'Cancel & Refund'
export const refundingBounty = 'Refunding bounty…'
export const noBounties = 'No bounties'
export const noBountiesDetail = 'No operation bounties have been posted for this pool.'
export const connectWalletForBounty = 'Connect a wallet before posting an operation bounty.'
export const acceptBountyWalletReason = 'Connect a wallet to accept this bounty.'
export const waitForChainTime = 'Wait for the current chain time to load.'
export const refreshBountyTokens = 'Refresh the oracle manager to load its REP and WETH tokens.'
export const enterValidBountyTarget = 'Enter a valid target vault address.'
export const enterValidBountyAmount = 'Enter a valid operation amount.'
export const enterValidBountyReward = 'Enter a reward greater than zero.'
export const enterValidBountyTimeout = 'Enter an execution window from 1 to 5 minutes.'
export const enterValidBountyDeadline = 'Enter an acceptance window greater than zero.'
export const enterValidInitialWethBounds = 'Enter valid decimal initial-report WETH bounds or leave them blank.'
export const enterOrderedInitialWethBounds = 'The minimum initial-report WETH cannot exceed the maximum.'
export const formatOperationAmountLabel = (unit: string) => `Amount (${unit})`
export const bountyAcceptanceExpired = 'This bounty’s acceptance window has expired.'
export const bountySettlementQueueFull = 'This bounty cannot be accepted while the pending settlement queue is full.'
export const failedBountyCannotBeClaimed = 'Failed operation bounties cannot be claimed.'
export const expiredBountyCannotBeClaimed = 'Expired operation bounties cannot be claimed.'
export const waitForBountyExecution = 'Wait for the staged operation to execute successfully.'
export const waitForBountyFailure = 'The creator can refund after the operation fails.'
export const formatOperationBountyLabel = (bountyId: string, operationLabel: string) => `Bounty #${bountyId} · ${operationLabel}`
export const formatExecutionWindowDetail = (minutes: string) => `Fixed cancellation deadline: queued time + oracle settlement time + ${minutes} minutes. Disputes do not extend it.`
export const formatBountyFailureDetail = (errorMessage: string) => `Execution result: ${errorMessage}`
export const formatRefundAvailableAt = (timestamp: string) => `Cancellation becomes available after ${timestamp}.`
export const liquidationWorkflowDescription = 'Inspect the liquidation quote, timeout, and execution path before queueing liquidation.'
export const selectedPool = 'Selected Pool'
export const selectedPoolVaultViews = 'Selected pool vault views'
export const poolContextAndMetrics = 'Pool context and metrics'
export const selectedPoolViews = 'Selected pool views'
export const waitForPoolLoadingReason = 'Wait for this pool to finish loading.'
export const loadValidPoolReason = 'Load a valid pool before using pool actions.'
export const loadPoolReason = 'Load a pool before using pool actions.'
export const selectedPoolUnavailableDetail = 'This pool does not exist.'
export const securityPoolAddressNotFoundDetail = 'This security pool address was not found.'
export const poolNotFoundDetail = 'Pool not found.'
export const noPoolSelectedBadgeLabel = 'No pool selected'
export const noPoolSelectedDetail = 'No pool selected.'
export const openOracle = 'Open Oracle'
export const parentPool = 'Parent Pool'
export const pendingRequest = 'Pending Request'
export const selectVault = 'Select Vault'
export const formatShowingActiveStagedOperationsLabel = (loadedCount: string, activeCount: string) => `Showing ${loadedCount} of ${activeCount} active staged operations, newest first.`
export const stagedOperationId = 'Staged Operation Id'
export const zeroPlaceholder = '0'
export const stagedOperations = 'Staged Operations'
export const stagedOperationsList = 'Staged Operations List'
export const universeMismatch = 'Universe Mismatch'
export const poolUniverseLead = 'This pool belongs to'
export const activeUniverseSeparator = 'but the app is currently set to'
export const missingPoolDetail = 'Pool actions are locked until the app uses the same universe.'
export const switchToPoolUniverse = 'Switch to Pool Universe'
export const returnToCurrentUniverse = 'Return to Current Universe'
export const vaultDirectory = 'Vault Directory'
export const vaultOperations = 'Vault Operations'
export const invalidVaultAddressHint = 'Try another vault address.'
export const forkAlreadyTriggeredSettlementReason = 'Zoltar fork has already been triggered for this pool. Continue in Fork & Migration.'
export const poolForkMigrationStatus = 'This pool has already entered Fork & Migration.'
export const forkTriggerUnavailableReason = 'Triggering a Zoltar fork is not available in the current pool state.'
export const reportingLockedDuringMigrationReason = 'This pool is in fork migration. Reporting actions unlock once the pool becomes operational.'
export const parentForkMigrationRedirectDetail = 'This parent pool is forked. Continue in Fork & Migration for migration and settlement.'
export const reportingLockedDuringAuctionReason = 'This pool is in truth auction. Reporting actions unlock once the pool becomes operational.'
export const reportingStartDetail = 'Reporting opens after market end.'
export const operationId = 'Operation Id'
export const createAnotherPool = 'Create Another Pool'
export const creatingPool = 'Creating Pool…'
export const poolCreationLocked = 'Pool Creation Locked'
export const poolCreated = 'Pool Created'
export const poolCreationAfterForkReason = 'Security pools cannot be created after Zoltar has forked.'
export const deploymentTransactionHash = 'Deployment transaction hash'
export const checkingDuplicate = 'Checking Duplicate…'
export const duplicatePoolDetail = 'A pool for this question and security multiplier already exists. Origin pool deployment is deterministic for that pair, so change the security multiplier to create a different pool.'
export const initialOpenInterestFeeHelpText = 'Initial Open Interest Fee / Year is the starting annualized fee charged against open interest. The rate follows pool utilization after deployment.'
export const initialOpenInterestFeeYear = 'Initial Open Interest Fee / Year'
export const ineligibleQuestionDetail = 'Security pools can only be created for exact binary Yes / No questions. Enter an eligible question to proceed.'
export const loadingQuestion = 'Loading question…'
export const poolAddressLabel = 'Pool address'
export const poolAlreadyExists = 'Pool Already Exists'
export const questionIdInputHint = 'Paste an exact binary Yes / No Zoltar question ID.'
export const securityMultiplierHelpText = 'Security Multiplier sets the REP collateral target relative to open interest. Higher values require more REP backing and create a thicker safety buffer.'
export const depositingRep = 'depositing REP'
export const immediateBondAllowanceFailureDetail = 'The oracle manager attempted the allowance update immediately, but the security pool rejected it.'
export const bondAllowanceExecuted = 'Bond Allowance Executed'
export const bondAllowanceFailed = 'Bond Allowance Failed'
export const bondAllowanceQueued = 'Bond Allowance Queued'
export const bondAllowanceSubmitted = 'Bond Allowance Submitted'
export const feeRedemptionReviewDetail = 'Review claimable fees and confirm the fee redemption for the selected vault.'
export const claimableFees = 'Claimable Fees'
export const feeRedemptionConfirmationDetail = 'Confirm the claimable fee balance before submitting the fee redemption for this vault.'
export const claimingFees = 'Claiming fees…'
export const missingVaultDepositDetail = 'This vault does not exist. Deposit REP to create it.'
export const currentBondAllowance = 'Current Bond Allowance'
export const currentSecurityBondAllowance = 'Current Security Bond Allowance'
export const selectedVaultDepositHint = 'Add REP to the selected vault.'
export const repCollateralAmount = 'REP Collateral Amount'
export const depositRepPendingLabel = 'Depositing REP…'
export const formatFirstDepositMinimumChecklistDetail = (amount: string) => `First deposits must be at least ${amount} REP.`
export const firstDepositTail = 'in the first deposit.'
export const firstDepositMeetsTheVaultMinimum = 'First deposit meets the vault minimum'
export const newVaultsRequireAtLeast = 'New vaults require at least'
export const claimableFeesAreAvailable = 'Claimable fees are available'
export const formatInsufficientRepBalanceDetail = (amount: string) => `Insufficient REP balance. Deposit amount exceeds your wallet balance by ${amount} REP.`
export const formatVaultLauncherBlockerReason = (action: 'claim-fees' | 'deposit-rep' | 'rep-exit-redeem' | 'rep-exit-withdraw' | 'set-bond-allowance', blocker: 'connect-wallet' | 'missing-vault' | 'refresh-vault' | 'select-own-vault') => {
	if (blocker === 'missing-vault') return missingVaultDetail

	if (blocker === 'connect-wallet') {
		if (action === 'claim-fees') return 'Connect a wallet before claiming fees.'
		if (action === 'deposit-rep') return 'Connect a wallet before depositing REP.'
		if (action === 'rep-exit-redeem') return 'Connect a wallet before redeeming REP.'
		if (action === 'rep-exit-withdraw') return 'Connect a wallet before withdrawing REP.'
		return 'Connect a wallet before setting the security bond allowance.'
	}

	if (blocker === 'select-own-vault') {
		if (action === 'claim-fees') return 'Select your own vault to claim fees.'
		if (action === 'deposit-rep') return 'Select your own vault to deposit REP.'
		if (action === 'rep-exit-redeem') return 'Select your own vault to redeem REP.'
		if (action === 'rep-exit-withdraw') return 'Select your own vault to withdraw REP.'
		return 'Select your own vault to set the security bond allowance.'
	}

	if (action === 'claim-fees') return 'Refresh the vault before claiming fees.'
	if (action === 'deposit-rep') return 'Refresh the vault before depositing REP.'
	if (action === 'rep-exit-redeem') return 'Refresh the vault before redeeming REP.'
	if (action === 'rep-exit-withdraw') return 'Refresh the vault before withdrawing REP.'
	return 'Refresh the vault before setting the security bond allowance.'
}
export const oracleFundingPendingDetail = 'Oracle execution can be funded until a fresh price arrives.'
export const selfServiceExecutionTimeoutHelpText = 'Enter whole minutes. Queued self-service operations must stay executable for at least 1 minute after the oracle settlement window completes.'
export const formatManualExecutionTimeoutResolvedDetail = (duration: string) => `This queued self-service operation will expire ${duration} after the oracle settlement window completes.`
export const noEscalationRepStatus = 'No REP remains locked in the escalation game'
export const owned = 'Owned'
export const selectedVaultOwnershipStatus = 'Selected vault is owned by the connected account'
export const readOnlyBadgeLabel = 'Read only'
export const refreshingBondAllowanceStatusDetail = 'Refreshing the oracle manager to determine whether the bond allowance was queued or executed immediately.'
export const refreshingBondAllowanceState = 'Refreshing Bond Allowance State'
export const refreshingWithdrawalStatusDetail = 'Refreshing the oracle manager to determine whether the withdrawal was queued or executed immediately.'
export const refreshingWithdrawalState = 'Refreshing Withdrawal State'
export const repAvailableToQueue = 'REP Available To Queue'
export const walletDepositBalanceStatus = 'Wallet REP balance covers the deposit amount'
export const formatRepBalanceShortageDetail = (amount: string) => `Need ${amount} more REP.`
export const actionRejectedDetail = 'The security pool rejected the action.'
export const invalidPoolAddressHint = 'Try another pool address.'
export const repWithdrawalExecuted = 'REP Withdrawal Executed'
export const repWithdrawalFailed = 'REP Withdrawal Failed'
export const immediateWithdrawalRejectedDetail = 'The oracle manager attempted the withdrawal immediately, but the security pool rejected it.'
export const repWithdrawalQueued = 'REP Withdrawal Queued'
export const repWithdrawalSubmitted = 'REP Withdrawal Submitted'
export const redeemRep = 'Redeem REP'
export const redeemingRep = 'Redeeming REP…'
export const vaultRedeemableRepStatus = 'The vault has redeemable REP'
export const redeemableRep = 'Redeemable REP'
export const repRedemptionDescription = 'Redeem the remaining REP collateral from this ended pool after escalation deposits are settled.'
export const withdrawalWorkflowDescription = 'Queue a REP withdrawal after reviewing the current vault collateral and oracle status.'
export const repWithdrawAmount = 'REP Withdraw Amount'
export const repWithdrawalDescription = 'Queue a REP withdrawal now, or let it execute immediately when a valid oracle price is already available.'
export const selectedVaultDetailsUnavailable = 'Selected vault details are unavailable.'
export const securityBondAllowanceAmount = 'Security Bond Allowance Amount'
export const securityVault = 'Security Vault'
export const bondAllowanceWorkflowDescription = 'Queue a new security bond allowance using the current oracle price context.'
export const bondAllowanceConfirmationDetail = 'Queue a new bond allowance using the latest valid oracle price for the selected vault.'
export const queueingAllowanceUpdate = 'Queueing allowance update…'
export const selectedVault = 'Selected Vault'
export const immediateBondAllowanceSuccessDetail = 'A valid oracle price was already available, so the new bond allowance executed immediately and no staged operation was created.'
export const immediateWithdrawalSuccessDetail = 'A valid oracle price was already available, so the withdrawal executed immediately and no staged operation was created.'
export const manualTimeoutMinimumStatus = 'Manual execution timeout is at least 1 minute'
export const formatAllowanceChecklistLabel = (amount: string) => `Allowance amount is zero or at least ${amount} ETH`
export const oraclePriceAvailableStatus = 'A valid oracle price is available'
export const vault = 'Vault'
export const vaultActions = 'Vault Actions'
export const vaultLookup = 'Vault Lookup'
export const vaultMissing = 'Vault missing'
export const vaultSummary = 'Vault Summary'
export const vaultRepQueueableStatus = 'The vault still holds REP collateral to queue'
export const withdrawableRep = 'Withdrawable REP'
export const queueingRepWithdrawal = 'Queueing REP withdrawal…'
