import type { CopyTemplateValue } from './types.js'

export const pool = 'Pool'
export const settleFinalizedRefunds = 'Settle Finalized Refunds'
export const undefinedValue = 'undefined'
export const nullValue = 'null'
export const circularValue = '[circular value]'
export const contract = 'Contract'
export const to = 'To'
export const functionLabel = 'Function'
export const ethValue = 'ETH Value'
export const argumentListLabel = 'Arguments'
export const formatDeployingValue = (contractLabel: CopyTemplateValue) => `Deploying ${contractLabel}`
export const formatValueDeployed = (contractLabel: CopyTemplateValue) => `${contractLabel} Deployed`
export const simulationSubmissionDetail = 'Submitting in browser simulation. No wallet confirmation is required.'
export const walletConfirmationInstruction = 'Confirm the transaction in your wallet.'
export const walletConfirmationReviewDetail = 'Review the prepared transaction, then confirm it in your wallet.'
export const simulationSubmissionReviewDetail = 'Review the prepared transaction before it is submitted.'
export const creatingQuestion = 'Creating Question'
export const questionCreated = 'Question Created'
export const approvingForkRep = 'Approving Fork REP'
export const forkingZoltar = 'Forking Zoltar'
export const forkRepApproved = 'Fork REP Approved'
export const zoltarForkSubmitted = 'Zoltar Fork Submitted'
export const deployingChildUniverse = 'Deploying Child Universe'
export const childUniverseDeployed = 'Child Universe Deployed'
export const preparingRep = 'Preparing REP'
export const splittingRep = 'Splitting REP'
export const migrationRepPreparationSuccessDetail = 'REP was added to your migration balance.'
export const repSplitSuccessDetail = 'Migration REP was split across the selected child universes.'
export const outcomeIndexes = 'Outcome Indexes'
export const repPrepared = 'REP Prepared'
export const repSplit = 'REP Split'
export const creatingSecurityPool = 'Creating Security Pool'
export const securityPoolCreatedDetail = 'The new security pool is now available for shares, reporting, and vault operations.'
export const securityPoolCreated = 'Security Pool Created'
export const formatQueuedOperationAutoExecutionDetail = (operationId: CopyTemplateValue) => `Staged operation #${operationId} was queued for the next oracle settlement.`
export const formatQueuedOperationManualExecutionDetail = (operationId: CopyTemplateValue) => `Staged operation #${operationId} was queued and must be executed manually after a valid oracle price is available.`
export const completeSetBurnSuccessDetail = 'Matching shares were burned and collateral was returned from the selected pool.'
export const parentPoolSharesMigratedDetail = 'Selected parent-pool shares were migrated into child universes.'
export const shareOutcome = 'Share Outcome'
export const targetOutcomeIndexes = 'Target Outcome Indexes'
export const reportingContributionSuccessDetail = 'Your selected REP was committed to the chosen escalation side.'
export const escalationDepositsSettledDetail = 'Selected escalation deposits were settled against the current finalized outcome.'
export const submittingLiquidation = 'Submitting Liquidation'
export const liquidationRequestSubmittedDetail = 'The liquidation request was submitted successfully.'
export const formatQueuedLiquidationAutoExecutionDetail = (operationId: CopyTemplateValue) => `Liquidation staged as operation #${operationId} for the next oracle settlement.`
export const formatQueuedLiquidationManualExecutionDetail = (operationId: CopyTemplateValue) => `Liquidation staged as operation #${operationId} and must be executed manually after a valid oracle price is available.`
export const liquidationExecutedImmediatelyDetail = 'The liquidation executed immediately.'
export const executingStagedOperation = 'Executing Staged Operation'
export const requestingPrice = 'Requesting Price'
export const stagedOperationExecuted = 'Staged Operation Executed'
export const priceRequested = 'Price Requested'
export const formatFinalizedRefundSettlementResultDetail = (allowanceLabel: CopyTemplateValue) => `Selected finalized truth-auction refund rows were settled. Locked ETH was returned without assigning child-pool REP or ${allowanceLabel}.`
export const formatWinningBidSettlementResultDetail = (allowanceLabel: CopyTemplateValue) => `Selected truth-auction winning bids were settled. The selected bids received child-pool REP plus ${allowanceLabel}, assigning the remaining open-interest debt.`
export const formatMixedBidSettlementResultDetail = (allowanceLabel: CopyTemplateValue) => `Selected truth-auction bids were settled. Winning bids received child-pool REP plus ${allowanceLabel}, assigning the remaining open-interest debt; refund-only rows returned locked ETH.`
export const childUniverseLinkedToForkPathDetail = 'The selected child universe was deployed and linked to this fork path.'
export const ownEscalationForkSubmittedDetail = 'This pool submitted its own escalation fork and moved into Fork & Migration.'
export const zoltarUniverseForkSubmittedDetail = 'The selected Zoltar universe fork was submitted on-chain.'
export const poolReadyForForkMigrationDetail = 'This pool entered fork handling and is ready for migration actions.'
export const parentEscalationDepositsClaimedDetail = 'Selected winning parent deposits were paid directly in child REP. Their carried proofs are now spent in current and later descendants.'
export const claimParentEscalationDeposits = 'Claim Parent Escalation Deposits'
export const poolRepMigrationSuccessDetail = 'Pool-level REP was migrated into the selected child universe.'
export const unresolvedEscalationMigratedDetail = 'The wallet’s parent escalation-lock accounting was cleared in constant-size work. Child backing and proof eligibility were already available and are unchanged.'
export const clearParentEscalationLocks = 'Clear Parent Escalation Locks'
export const vaultMigratedDetail = 'Vault REP collateral and security-bond allowance were migrated into the selected child universe.'
export const losingBidsRefundedDetail = 'Selected losing truth-auction bids were refunded.'
export const forkDepositSettlementSuccessDetail = 'Imported fork-carried escalation deposits were settled.'
export const truthAuctionStartedSuccessDetail = 'Truth auction state was started for the selected child universe.'
export const truthAuctionBidSuccessDetail = 'Truth auction bid submitted. Bid ETH stays committed until settlement.'
export const viewTransaction = 'View transaction'
export const preparing = 'Preparing'
export const awaitingWallet = 'Awaiting Wallet'
export const confirmed = 'Confirmed'
export const attention = 'Attention'
export const dismiss = 'Dismiss'
export const closeStatus = 'Close transaction status'
