import type { CopyTemplateValue } from './types.js'

export const forkZoltar = 'Fork Zoltar'
export const viewForkDetails = 'View Fork Details'
export const migrateRep = 'Migrate REP'
export const prepareRep = 'Prepare REP'
export const splitRep = 'Split REP'
export const migrationNotForkedReason = 'REP migration is unavailable because this universe has not forked.'
export const migrationAmountAlreadySplitDetail = 'This amount is already fully split across the selected universes.'
export const alreadyForkedReason = 'Zoltar is already forked.'
export const formatAddMigrationRepDetail = (repAmount: CopyTemplateValue) => `Add ${repAmount} REP to your migration balance from this universe, then split it across the selected universes.`
export const forkWalletRequiredReason = 'Connect a wallet before forking Zoltar.'
export const forkDataRequiredReason = 'Refresh universe data before forking Zoltar.'
export const forkEconomicsRequiredReason = 'Load the fork burn and migration-credit terms before forking Zoltar.'
export const forkQuestionRequiredReason = 'Select a valid fork question before approving REP or forking Zoltar.'
export const forkRepInsufficientReason = 'Insufficient REP to meet the fork threshold.'
export const forkRepApprovalRequiredReason = 'Approve enough REP before forking Zoltar.'
export const forkConfirmationLabel = 'Type FORK to confirm'
export const forkConfirmationHelp = 'This confirmation acknowledges that the selected fork question and REP burn are irreversible.'
export const forkConfirmationRequiredReason = 'Type FORK to confirm this irreversible action.'
export const forkingActionLabel = 'forking Zoltar'
export const forkRepApprovalPending = 'Approving REP Threshold…'
export const forkQuestionId = 'Fork Question ID'
export const forkSubmissionPending = 'Forking Zoltar…'
export const addAnotherUniverse = 'Add another universe'
export const outcomeUniverses = 'Outcome Universes'
export const outcomeUniversesEmpty = 'No outcome universes available.'
export const walletBalanceLabel = 'Your balance:'
export const migratedBalanceLabel = 'Already migrated:'
export const migrationBalanceReadyDetail = 'This amount is already in your migration balance. Split REP when ready.'
export const formatMigrationRepShortfall = (repShortfall: CopyTemplateValue) => `Need ${repShortfall} more REP in this universe to prepare the selected amount.`
export const migrationApprovalPendingDetail = 'Waiting for approved REP amount before preparing the selected amount.'
export const formatMigrationPreparationRequired = (repAmount: CopyTemplateValue) => `Add ${repAmount} REP to your migration balance first, then split it across the selected universes.`
export const outcomeSelectionRequired = 'Select at least one outcome universe.'
export const outcomeBalancesLoading = 'Loading outcome universe balances…'
export const formatSplitCapacityDetail = (remainingCapacity: CopyTemplateValue) => `The selected universes only have ${remainingCapacity} REP of room left for this amount. Reduce the amount or choose different universes.`
export const migrationSplitInstruction = 'Split the migration REP across the selected universes.'
export const formatMigrationBalanceExceeded = (availableRep: CopyTemplateValue, migrationBalance: CopyTemplateValue, walletBalance: CopyTemplateValue) => `You only have ${availableRep} REP available for migration in this universe (${migrationBalance} in your migration balance and ${walletBalance} wallet REP).`
export const migrationRepBalance = 'Migration REP Balance'
export const universeDataLoading = 'Loading universe data'
export const migrationAmount = 'Migration Amount'
export const preparingCurrentAmountLabel = 'preparing the current amount'
export const preparingRepPending = 'Preparing REP…'
export const splittingRepPending = 'Splitting REP…'
export const preparationNotForkedReason = 'REP preparation is unavailable because this universe has not forked.'
export const migrationWorkflow = 'REP Migration Workflow'
export const migrationWorkflowDetail = 'Move wallet REP into migration custody, then split it into the child universes you choose.'
export const chooseDestinationStep = '1. Choose destination outcome universes'
export const approveRepStep = '2. Approve REP'
export const prepareCustodyStep = '3. Move REP into migration custody'
export const confirmMigrationStep = '4. Confirm destination and amount'
export const splitMigrationStep = '5. Split and migrate'
export const verifyMigrationStep = '6. Verify destination REP'
export const walletRepBalance = 'Wallet REP Balance'
export const selectedDestinations = 'Selected Destinations'
export const afterPrepareWalletBalance = 'Wallet REP After Prepare'
export const afterPrepareCustodyBalance = 'Custody REP After Prepare'
export const afterSplitCustodyBalanceUnchanged = 'Custody REP After Split (Unchanged)'
export const childUniverseRepReceived = 'Child-Universe REP Received'
export const repMovedToMigrationCustody = 'REP Moved to Migration Custody'
export const destinationRepAfterSplit = (destination: CopyTemplateValue) => `${destination} REP After Split`
export const migrationSplitRisk = 'Splitting REP commits that amount to the selected child universes and cannot be reversed through this workflow.'
export const migrationDestinationRisk = 'Verify every destination outcome before splitting; each selected universe receives the migrated amount.'
export const migrationCustodyCredit = 'Migration Custody Credit'
export const permanentRepBurn = 'Permanent REP Burn'
export const zoltarContract = 'Zoltar Contract'
export const forkIrreversibleRisk = 'Fork initiation is irreversible and permanently sets this question as the universe fork question.'
export const forkMigrationRisk = 'After the fork, REP and pool positions must follow the outcome-universe migration process before settlement.'
