import type { CopyTemplateValue } from './types.js'

export const forkZoltar = 'Fork Zoltar'
export const migrateRep = 'Migrate REP'
export const prepareRep = 'Prepare REP'
export const splitRep = 'Split REP'
export const migrationNotForkedReason = 'REP migration is unavailable because this universe has not forked.'
export const migrationAmountAlreadySplitDetail = 'This amount is already fully split across the selected universes.'
export const alreadyForkedReason = 'Zoltar is already forked.'
export const formatAddMigrationRepDetail = (repAmount: CopyTemplateValue) => `Add ${repAmount} REP to your migration balance from this universe, then split it across the selected universes.`
export const forkWalletRequiredReason = 'Connect a wallet before forking Zoltar.'
export const forkDataRequiredReason = 'Refresh universe data before forking Zoltar.'
export const forkQuestionRequiredReason = 'Select a valid fork question before forking Zoltar.'
export const forkRepInsufficientReason = 'Insufficient REP to meet the fork threshold.'
export const forkRepApprovalRequiredReason = 'Approve enough REP before forking Zoltar.'
export const forkingActionLabel = 'forking Zoltar'
export const forkRepApprovalPending = 'Approving REP Threshold…'
export const forkQuestionId = 'Fork Question ID'
export const forkSubmissionPending = 'Forking Zoltar…'
export const addAnotherUniverse = 'Add another universe'
export const outcomeUniverses = 'Outcome Universes'
export const outcomeUniversesEmpty = 'No outcome universes available.'
export const walletBalanceLabel = 'Your balance:'
export const migratedBalanceLabel = 'Already migrated:'
export const migrationBalanceReadyDetail = 'This amount is already in your migration balance. Split REP when ready.'
export const formatMigrationRepShortfall = (repShortfall: CopyTemplateValue) => `Need ${repShortfall} more REP in this universe to prepare the selected amount.`
export const migrationApprovalPendingDetail = 'Waiting for approved REP amount before preparing the selected amount.'
export const formatMigrationPreparationRequired = (repAmount: CopyTemplateValue) => `Add ${repAmount} REP to your migration balance first, then split it across the selected universes.`
export const outcomeSelectionRequired = 'Select at least one outcome universe.'
export const outcomeBalancesLoading = 'Loading outcome universe balances…'
export const formatSplitCapacityDetail = (remainingCapacity: CopyTemplateValue) => `The selected universes only have ${remainingCapacity} REP of room left for this amount. Reduce the amount or choose different universes.`
export const migrationSplitInstruction = 'Split the migration REP across the selected universes.'
export const formatMigrationBalanceExceeded = (availableRep: CopyTemplateValue, migrationBalance: CopyTemplateValue, walletBalance: CopyTemplateValue) => `You only have ${availableRep} REP available for migration in this universe (${migrationBalance} in your migration balance and ${walletBalance} wallet REP).`
export const migrationRepBalance = 'Migration REP Balance'
export const universeDataLoading = 'Loading universe data'
export const migrationAmount = 'Migration Amount'
export const preparingCurrentAmountLabel = 'preparing the current amount'
export const preparingRepPending = 'Preparing REP…'
export const splittingRepPending = 'Splitting REP…'
export const preparationNotForkedReason = 'REP preparation is unavailable because this universe has not forked.'
