export const connecting = 'Connecting…'
export const changeWallet = 'Change wallet'
export const disconnectWallet = 'Disconnect'
export const accountMenu = 'Account Menu'
export const currentNetwork = 'Current Network'
export const switchToEthereumMainnet = 'Switch to Ethereum mainnet'
export const formatSwitchToNetwork = (networkName: string) => `Switch to ${networkName}`
export const ethereumMainnet = 'Ethereum Mainnet'
export const managingWallet = 'Updating wallet…'
export const unknownNetwork = 'Unknown network'
export const sepoliaNetwork = 'Sepolia (11155111)'
export const formatNetworkWithChainId = (networkLabel: string, chainId: string) => `${networkLabel} (${chainId})`
export const refreshRepPrices = 'Refresh REP prices'
export const formatRepPricingUnavailable = (networkName: string) => `Not configured on ${networkName}`
export const repPriceNoLiquidity = 'No liquidity available'
export const repPriceRequestFailed = 'Quote failed'
export const repPerEthCompact = 'REP/ETH'
export const skipToMainContent = 'Skip to main content'
export const deployContracts = 'Deploy Contracts'
export const manageSecurityPool = 'Manage Security Pool'
export const pageNotFoundTitle = 'Page Not Found'
export const browseReports = 'Browse Reports'
export const createReport = 'Create Report'
export const viewReport = 'View Report'
export const securityPoolsViews = 'Security Pools views'
export const zoltarViews = 'Zoltar views'
export const usdc = 'USDC'
export const activeReadRpc = 'Active read RPC'
export const configuredFallbackReadRpc = 'Configured fallback read RPC'
export const defaultSource = 'default'
export const environment = 'environment'
export const explicitOverride = 'explicit override'
export const deploymentIncompleteReason = 'Required application contracts are not deployed.'
export const globalRuntime = 'global runtime'
export const readRpcOverrideIgnored = 'Read RPC override ignored'
export const localStorage = 'local storage'
export const pageUrl = 'page URL'
export const formatReadRpcOverrideIgnoredDetail = (sourceLabel: string, url: string, reason: string, configuredRpcLabel: string, activeRpcUrl: string) => `Ignored ${sourceLabel} RPC override (${url}): ${reason} ${configuredRpcLabel} is ${activeRpcUrl}.`
export const formatReadRpcOverrideFromUrlDetail = (configuredRpcLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from the page URL: ${rpcUrl}. Verify this endpoint before relying on displayed onchain state.`
export const formatReadRpcOverrideActiveDetail = (configuredRpcLabel: string, sourceLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from ${sourceLabel}: ${rpcUrl}. Verify this endpoint before relying on displayed onchain state.`
export const customReadRpcWarningDetail = 'Custom read RPC active. Verify it before acting on displayed chain state.'
export const readRpcOverrideIgnoredDetail = 'A custom read RPC was ignored. The configured fallback is active.'
export const readWriteNetworkMismatchDetail = 'Displayed onchain state may not match the network this interface writes to.'
export const readRpcMismatch = 'Read RPC mismatch'
export const readRpcOverrideActive = 'Read RPC override active'
export const setupIncomplete = 'Setup incomplete'
export const simulationBootstrapFailed = 'Simulation bootstrap failed'
export const staleReadBackendDetail = 'Displayed onchain state may be behind the latest chain state. Refresh or switch RPC before acting on balances, settlement, or liquidation.'
export const urlProvidedReadRpc = 'URL-provided read RPC'
export const address = 'Address'
export const formatShowEarlierNavigationItems = (navigationLabel: string) => `Show earlier ${navigationLabel}`
export const formatShowLaterNavigationItems = (navigationLabel: string) => `Show later ${navigationLabel}`
export const connected = 'Connected'
export const notConnected = 'Not connected'
export const repUsdc = 'REP/USDC'
export const refreshingRepPrices = 'Refreshing REP prices…'
export const simulation = 'Simulation'
export const universeForkedDetail = 'This universe has forked.'
export const universeForkedWarningTitle = 'Migration required'
export const universeForkedWarningDetail = 'Migrate REP into the destination universe before continuing with new actions.'
export const zoltarForkedOn = 'Universe forked on'
export const transactionUniverseMismatch = 'Transaction universe mismatch'
export const formatTransactionUniverseMismatch = (transactionUniverse: string, activeUniverse: string) => `This transaction belongs to ${transactionUniverse}, while the header shows ${activeUniverse}.`
export const formatWrongNetworkBadgeLabel = (networkLabel: string) => `Wrong Network (${networkLabel})`
export const showEnvironmentDetails = 'Show environment details'
export const hideEnvironmentDetails = 'Hide environment details'
export const applicationSections = 'Application sections'
export const deploymentRequiredDetail = 'Deploy the application contracts before using this section.'
export const deploymentDescription = 'Deploy and verify the shared deterministic contracts that back the application.'
export const currentApplicationSection = 'Current application section'
export const protocolGuide = 'Protocol Guide'
export const protocolGuideHref = 'https://augurproject.github.io/zoltar/docs/documentation.html'
export const applicationErrorTitle = 'Application error'
export const applicationErrorFallback = 'The current screen could not be displayed.'
export const applicationInitializationErrorFallback = 'The application environment could not be initialized.'
export const reloadApplication = 'Reload application'
export const settings = 'Settings'
export const applicationSettings = 'Application settings'
export const rpcNetwork = 'RPC network'
export const sepolia = 'Sepolia'
export const browserSimulation = 'Browser Simulation'
export const browserLocalSimulator = 'Browser-local simulator'
export const fallbackRpcUrl = 'Fallback RPC URL'
export const simulationRpcDetail = 'Simulation uses its browser-local chain and does not contact an RPC server.'
export const formatFallbackRpcDetail = (defaultRpcUrl: string) => `Used for reads when a wallet is unavailable. Leave blank to use ${defaultRpcUrl}.`
export const saveRpc = 'Save RPC'
export const uiPriceOracle = 'UI price oracle'
export const uniswap = 'Uniswap'
export const latestOpenOraclePrice = 'Latest Open Oracle price'
export const openOracleThenUniswap = 'Open Oracle, then Uniswap'
export const uniswapUiPriceDetail = 'Uses the latest Uniswap REP/ETH quote for UI calculations.'
export const openOracleUiPriceDetail = 'Uses the latest pool Open Oracle price, even when that price has expired.'
export const openOracleFallbackUiPriceDetail = 'Uses a valid pool Open Oracle price, or falls back to Uniswap when it is unavailable or expired.'
export const rpcSaveFailed = 'Unable to save the RPC URL.'
export const savingRpc = 'Saving RPC…'
export const rpcSaved = 'RPC setting saved.'
