export const connecting = 'Connecting…'
export const changeWallet = 'Change wallet'
export const disconnectWallet = 'Disconnect'
const accountMenu = 'Account menu'
export const formatAccountMenuLabel = (account: string) => `${accountMenu} ${account}`
export const formatSwitchToNetwork = (networkName: string) => `Switch to ${networkName}`
export const qaWallet = 'QA wallet'
export const simulationQaWallet = 'Simulation QA wallet'
export const qaWalletConnected = 'Connected'
export const qaWalletDisconnected = 'Disconnected'
export const qaAccountDisconnected = 'Wallet disconnected'
export const qaWalletDisconnectedDetail = 'No account is exposed until the app connects the wallet.'
export const ethereumMainnet = 'Ethereum mainnet'
export const switchingNetwork = 'Switching network…'
export const unknownNetwork = 'Unknown network'
export const refreshRepPrices = 'Refresh REP prices'
export const formatRepPricingUnavailable = (networkName: string) => `Not configured on ${networkName}`
export const repPriceNoLiquidity = 'No liquidity available'
export const repPriceRequestFailed = 'Quote failed'
export const repPerEthCompact = 'REP/ETH'
export const skipToMainContent = 'Skip to main content'
export const deployContracts = 'Deploy contracts'
export const pageNotFoundTitle = 'Page not found'
export const browseReports = 'Browse reports'
export const createReport = 'Create report'
export const viewReport = 'View report'
export const zoltarViews = 'Zoltar views'
export const usdc = 'USDC'
export const activeReadRpc = 'Active read RPC'
export const configuredFallbackReadRpc = 'Configured fallback read RPC'
export const defaultSource = 'default'
export const environment = 'environment'
export const explicitOverride = 'explicit override'
export const deploymentIncompleteReason = 'Required application contracts are not deployed.'
export const globalRuntime = 'global runtime'
export const readRpcOverrideIgnored = 'Custom RPC URL ignored'
export const localStorage = 'Settings'
export const pageUrl = 'page URL'
export const formatReadRpcOverrideIgnoredDetail = (sourceLabel: string, url: string, reason: string, configuredRpcLabel: string, activeRpcUrl: string) => `Ignored the custom RPC URL from ${sourceLabel} (${url}): ${reason} ${configuredRpcLabel} is ${activeRpcUrl}.`
export const formatReadRpcOverrideFromUrlDetail = (configuredRpcLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from the page URL: ${rpcUrl}.`
export const formatReadRpcOverrideActiveDetail = (configuredRpcLabel: string, sourceLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from ${sourceLabel}: ${rpcUrl}.`
export const formatReadRpcSavedInSettingsDetail = (configuredRpcLabel: string, rpcUrl: string) => `${configuredRpcLabel} is the custom RPC URL saved in Settings: ${rpcUrl}.`
export const customReadRpcWarningDetail = 'A custom RPC URL is active. Verify it before acting on displayed onchain state.'
export const readRpcOverrideIgnoredDetail = 'A custom RPC URL was ignored. The configured fallback is active.'
export const readWriteNetworkMismatchDetail = 'Displayed onchain state may not match the network this interface writes to.'
export const staleReadRpc = 'Stale read RPC'
export const readRpcMismatch = 'Read RPC mismatch'
export const readRpcOverrideActive = 'Custom RPC URL active'
export const readRpcStale = 'Read RPC out of date'
export const setupIncomplete = 'Setup incomplete'
export const simulationBootstrapFailed = 'Simulation bootstrap failed'
export const staleReadBackendDetail = 'Displayed onchain state may be behind the latest chain state. Switch to an up-to-date RPC before sending transactions.'
export const urlProvidedReadRpc = 'Custom RPC URL from page URL'
export const repUsdc = 'REP/USDC'
export const refreshingRepPrices = 'Refreshing REP prices…'
export const universeForkedLead = 'This universe forked'
export const forkedOnConnector = 'on'
export const migrateRepToChildUniverse = 'Migrate your REP to a child universe.'
export const migrateRep = 'Migrate REP'
export const transactionUniverseMismatch = 'Transaction universe mismatch'
export const formatTransactionUniverseMismatch = (transactionUniverse: string, activeUniverse: string) => `This transaction belongs to ${transactionUniverse}, while the header shows ${activeUniverse}.`
export const formatWrongNetworkBadgeLabel = (networkLabel: string) => `Wrong network (${networkLabel})`
export const accountDetails = 'Account details'
export const network = 'Network'
export const latestBlock = 'Latest block'
export const moreSections = 'More'
export const applicationSections = 'Application sections'
export const deploymentDescription = 'Deploy and verify the shared deterministic contracts that back the application.'
export const deploymentInProgress = 'Deployment in progress'
export const formatDeployContract = (contractLabel: string) => `Deploy ${contractLabel}`
export const formatDeployingContract = (contractLabel: string) => `Deploying ${contractLabel}…`
export const protocolGuide = 'Protocol guide'
export const protocolGuideHref = 'https://augurproject.github.io/zoltar/docs/documentation.html'
export const applicationErrorTitle = 'Application error'
export const applicationInitializationErrorFallback = 'The application environment could not be initialized.'
export const reloadApplication = 'Reload application'
export const settings = 'Settings'
export const applicationSettings = 'Application settings'
export const rpcNetwork = 'RPC network'
export const sepolia = 'Sepolia'
export const browserSimulation = 'Browser simulation'
export const browserLocalSimulator = 'Browser-local simulator'
export const fallbackRpcUrl = 'Fallback RPC URL'
export const simulationRpcDetail = 'Simulation uses its browser-local chain and does not contact an RPC server.'
export const saveRpc = 'Save RPC'
export const rpcSaveFailed = 'Unable to save the RPC URL.'
export const savingRpc = 'Saving RPC…'
export const rpcSaved = 'RPC setting saved.'
export const theme = 'Theme'
export const themeSystem = 'System'
export const themeLight = 'Light'
export const themeDark = 'Dark'

export const mainnetDisabledTitle = 'Ethereum mainnet is disabled'
export const mainnetDisabled = 'Ethereum mainnet is disabled.'
export const mainnetDisabledDetail = 'Switch your wallet to Sepolia or use browser simulation.'
