import type { CopyTemplateValue } from './types.js'

export const formatWrappedValue = (value: CopyTemplateValue) => `(${value})`
export const repPriceUnavailableDetail = 'REP per ETH price source is unavailable until a quote loads.'
export const simulationPriceSourceDetail = 'Uses the simulation REP per ETH mock price.'
export const uniswapV4PriceSourceDetail = 'Uses the live Uniswap V4 REP per ETH quote.'
export const uniswapV3PriceSourceDetail = 'Uses the live Uniswap V3 REP per ETH quote.'
export const mock = 'MOCK'
export const priceFromTheSimulationMock = 'Price from the simulation mock'
export const targetCollateralizationAtSimulationPrice = 'Target collateralization @ simulation price'
export const simulationRepEth = 'Simulation REP per ETH'
export const uniswapV4BadgeLabel = 'u4'
export const priceFromUniswapV4 = 'Price from Uniswap V4'
export const targetCollateralizationAtUniswapV4Price = 'Target collateralization @ Uniswap V4 price'
export const uniswapV4RepEth = 'Uniswap V4 REP per ETH'
export const uniswapV3BadgeLabel = 'u3'
export const priceFromUniswapV3 = 'Price from Uniswap V3'
export const targetCollateralizationAtUniswapV3Price = 'Target collateralization @ Uniswap V3 price'
export const uniswapV3RepEth = 'Uniswap V3 REP per ETH'
export const targetCollateralization = 'Target collateralization'
export const formatCopyExactCurrencyValue = (exactValue: CopyTemplateValue) => `Copy exact value ${exactValue}`
