import { formatActionTense } from './transactionActionTenses.js'
export const notCompleted = 'Not completed'
export const skipped = 'Not needed'
export const ifNeeded = 'If needed'
export const totalEth = 'Total ETH sent'
export const fundingDetail = 'Required deposits can change before submission. Unspent WETH stays in your wallet.'
export const depositAndReturn = 'Deposit / undisputed return'
export const settlementBounty = 'Settler bounty'
export const coordinatorReturnDetail = 'Both deposits return in full if undisputed. Disputes can change returns.'
export const standaloneReturnDetail = 'If undisputed, withdraw both deposits after settlement in separate transactions. Disputes can change returns.'
export const fundReport = 'funding the report'
export const fundingRequired = 'Required token balances and approvals must be available.'
export const transactionPending = 'Wait for the pending transaction to confirm.'
export const prerequisitesRequired = 'Complete the required setup transactions first.'
export const formatPendingAction = (title: string) => `${formatActionTense(title, 'pending')}…`
export const requirementsFailed = 'Could not refresh transaction requirements. Close and review the action again.'
export const formatTokenApproved = (symbol: string) => `${symbol} approved`
export const formatStepCompleted = (label: string) => `${label} ✓`
export const wrapEthIntoWeth = 'Wrap ETH into WETH'
export const ethWrapped = 'ETH wrapped'
