const APP_DOCUMENT_TITLE_SUFFIX = 'Zoltar + Augur Placeholder'
const COMMON_ANSWER_UNIT_LABEL = 'Answer Unit'
const COMMON_ALREADY_FORKED_LABEL = 'Already Forked'
const COMMON_CLAIM_FEES_LABEL = 'Claim Fees'
const COMMON_CONNECT_WALLET_LABEL = 'Connect wallet'
const COMMON_CONNECTING_LABEL = 'Connecting...'
const COMMON_CREATE_QUESTION_LABEL = 'Create Question'
const COMMON_CREATE_POOL_LABEL = 'Create Pool'
const COMMON_CLOSE_LABEL = 'Close'
const COMMON_MANUAL_EXECUTION_TIMEOUT_LABEL = 'Manual Execution Timeout'
const COMMON_DEPOSIT_REP_LABEL = 'Deposit REP'
const COMMON_DEPLOY_LABEL = 'Deploy'
const COMMON_DISPUTE_AND_SWAP_LABEL = 'Dispute & Swap'
const COMMON_DISPUTE_DELAY_LABEL = 'Dispute Delay'
const COMMON_END_TIME_LABEL = 'End Time'
const COMMON_ESCALATION_HALT_LABEL = 'Escalation Halt'
const COMMON_FEE_PERCENTAGE_LABEL = 'Fee Percentage'
const COMMON_FORK_ZOLTAR_LABEL = 'Fork Zoltar'
const COMMON_FORKED_LABEL = 'Forked'
const COMMON_GO_TO_GENESIS_UNIVERSE_LABEL = 'Go to Genesis universe'
const COMMON_HEX_VALUE_PLACEHOLDER = '0x...'
const COMMON_LIQUIDATE_VAULT_LABEL = 'Liquidate Vault'
const COMMON_LOADING_BADGE_LABEL = 'Loading'
const COMMON_LOADING_LABEL = 'Loading...'
const COMMON_MARKETS_LABEL = 'Markets'
const COMMON_MIGRATE_REP_LABEL = 'Migrate REP'
const COMMON_MULTIPLIER_LABEL = 'Multiplier'
const COMMON_MULTIPLIER_SUFFIX = 'x'
const COMMON_OUTCOMES_LABEL = 'Outcomes'
const COMMON_NONE_LABEL = 'None'
const COMMON_NOT_CHECKED_LABEL = 'Not checked'
const COMMON_NOT_FOUND_LABEL = 'Not found'
const COMMON_ORACLE_REPORTS_LABEL = 'Oracle Reports'
const COMMON_PRICE_LABEL = 'Price'
const COMMON_PROTOCOL_FEE_LABEL = 'Protocol Fee'
const COMMON_QUESTION_ID_LABEL = 'Question ID'
const COMMON_QUESTION_TYPE_LABEL = 'Question Type'
const COMMON_QUESTIONS_AND_MARKETS_LABEL = 'Questions & Markets'
const COMMON_REFRESH_LABEL = 'Refresh'
const COMMON_REFRESH_REP_PRICES_LABEL = 'Refresh REP prices'
const COMMON_REFRESHING_LABEL = 'Refreshing'
const COMMON_REPORT_DETAILS_LABEL = 'Report Details'
const COMMON_REPORT_ID_LABEL = 'Report ID'
const COMMON_REP_LABEL = 'REP'
const COMMON_REP_PER_ETH_LABEL = 'REP/ETH'
const COMMON_RETURN_TO_BROWSE_LABEL = 'Return to Browse'
const COMMON_SCALAR_LABEL = 'Scalar'
const COMMON_SECURITY_MULTIPLIER_LABEL = 'Security Multiplier'
const COMMON_SECURITY_POOL_ADDRESS_LABEL = 'Security Pool Address'
const COMMON_SECURITY_POOLS_LABEL = 'Security Pools'
const COMMON_SET_BOND_ALLOWANCE_LABEL = 'Set Bond Allowance'
const COMMON_SETTLE_REPORT_LABEL = 'Settle Report'
const COMMON_SETTLED_LABEL = 'Settled'
const COMMON_SETTLEMENT_TIME_LABEL = 'Settlement Time'
const COMMON_SETTLER_REWARD_LABEL = 'Settler Reward'
const COMMON_SET_SECURITY_BOND_ALLOWANCE_LABEL = 'Set Security Bond Allowance'
const COMMON_STATUS_LABEL = 'Status'
const COMMON_SUBMIT_INITIAL_REPORT_LABEL = 'Submit Initial Report'
const COMMON_TOKEN_PAIR_LABEL = 'Token Pair'
const COMMON_UNAVAILABLE_LABEL = 'Unavailable'
const COMMON_UNIVERSE_LABEL = 'Universe'
const COMMON_VIEW_IN_STAGED_OPERATIONS_LABEL = 'View In Staged Operations'
const COMMON_WALLET_REP_LABEL = 'Wallet REP'
const COMMON_WRONG_NETWORK_LABEL = 'Wrong network'
const COMMON_YES_LABEL = 'Yes'
const COMMON_NO_LABEL = 'No'
const COMMON_INVALID_LABEL = 'Invalid'
const COMMON_AMOUNT_LABEL = 'Amount'
const COMMON_EXECUTED_LABEL = 'Executed'
const STAGED_OPERATION_RETRY_DETAIL = 'Submit a new staged operation if you want to try again.'
const TRANSACTION_STATE_UNAVAILABLE_DETAIL = 'The transaction succeeded, but the latest manager state is not available.'
const REP_COLLATERAL_LABEL = 'REP Collateral'
const WITHDRAW_ESCALATION_DEPOSITS_DETAIL = 'Withdraw escalation deposits before redeeming REP.'
const MANUAL_QUEUED_OPERATION_DETAIL = 'The settlement auto-execute list is full. Execute this staged operation manually with its id after a valid oracle price is available.'
export const UI_STRINGS = {
	appPageTitle: {
		createOracleReportPageTitle: 'Create Oracle Report',
		createQuestionPageTitle: COMMON_CREATE_QUESTION_LABEL,
		createSecurityPoolPageTitle: 'Create Security Pool',
		deployContractsPageTitle: 'Deploy Contracts',
		documentTitleSuffix: APP_DOCUMENT_TITLE_SUFFIX,
		forkOraclePageTitle: COMMON_FORK_ZOLTAR_LABEL,
		manageSecurityPoolPageTitle: 'Manage Security Pool',
		migrateRepPageTitle: COMMON_MIGRATE_REP_LABEL,
		openOracleReportDetailsPageTitle: 'Oracle Report Details',
		openOracleReportsPageTitle: COMMON_ORACLE_REPORTS_LABEL,
		pageNotFoundPageTitle: 'Page Not Found',
		questionsAndMarketsPageTitle: COMMON_QUESTIONS_AND_MARKETS_LABEL,
		securityPoolsPageTitle: COMMON_SECURITY_POOLS_LABEL,
	},
	app: {
		openOracle: {
			browseLabel: 'Browse',
			createReportLabel: 'Create Report',
			reportDetailsLabel: COMMON_REPORT_DETAILS_LABEL,
			subNavigationAriaLabel: 'Oracle report views',
		},
		securityPools: {
			browsePoolsLabel: 'Browse Pools',
			createPoolLabel: COMMON_CREATE_POOL_LABEL,
			managePoolLabel: 'Manage Pool',
			subNavigationAriaLabel: 'Security Pools views',
		},
		zoltar: {
			createQuestionLabel: COMMON_CREATE_QUESTION_LABEL,
			forkOracleLabel: COMMON_FORK_ZOLTAR_LABEL,
			forkOracleRequiredForRepMigrationReason: 'REP migration is unavailable because this universe has not forked.',
			migrateRepLabel: COMMON_MIGRATE_REP_LABEL,
			questionsAndMarketsLabel: COMMON_QUESTIONS_AND_MARKETS_LABEL,
			subNavigationAriaLabel: 'Market views',
		},
	},
	common: {
		cancelLabel: 'Cancel',
		closeLabel: COMMON_CLOSE_LABEL,
		hexValuePlaceholder: COMMON_HEX_VALUE_PLACEHOLDER,
		failedBadgeLabel: 'Failed',
		loadingBadgeLabel: COMMON_LOADING_BADGE_LABEL,
		loadingLabel: COMMON_LOADING_LABEL,
		maxLabel: 'Max',
		metricUnavailablePlaceholder: '—',
		minutesLabel: 'minutes',
		multiplierSuffix: COMMON_MULTIPLIER_SUFFIX,
		noLabel: COMMON_NO_LABEL,
		notChosenLabel: 'Not chosen',
		noneLabel: COMMON_NONE_LABEL,
		noneSelectedLabel: 'None selected',
		notCheckedBadgeLabel: COMMON_NOT_CHECKED_LABEL,
		notFoundBadgeLabel: COMMON_NOT_FOUND_LABEL,
		noneYetBadgeLabel: COMMON_NONE_LABEL,
		ethSuffix: 'ETH',
		repPerEthSuffix: 'REP / ETH',
		usdcSuffix: 'USDC',
		wethSuffix: 'WETH',
		repLabel: COMMON_REP_LABEL,
		refreshLabel: COMMON_REFRESH_LABEL,
		unavailableLabel: COMMON_UNAVAILABLE_LABEL,
		yesLabel: COMMON_YES_LABEL,
	},
	childUniversesSection: {
		existsLabel: 'Exists',
		notDeployedLabel: 'Not deployed',
		workingLabel: 'Working...',
	},
	appStatusNotices: {
		activeReadRpcLabel: 'Active read RPC',
		appErrorTitle: 'Error',
		configuredFallbackReadRpcLabel: 'Configured fallback read RPC',
		defaultRpcSourceLabel: 'default',
		environmentRpcSourceLabel: 'environment',
		explicitOverrideRpcSourceLabel: 'explicit override',
		finishSetupBeforeUsingAppDetail: 'Required application contracts are not deployed.',
		globalRuntimeRpcSourceLabel: 'global runtime',
		ignoredReadRpcOverrideTitle: 'Read RPC override ignored',
		localStorageRpcSourceLabel: 'local storage',
		pageUrlRpcSourceLabel: 'page URL',
		readRpcOverrideIgnoredDetail: (sourceLabel: string, url: string, reason: string, configuredRpcLabel: string, activeRpcUrl: string) => `Ignored ${sourceLabel} RPC override (${url}): ${reason} ${configuredRpcLabel} is ${activeRpcUrl}.`,
		readRpcOverrideFromUrlDetail: (configuredRpcLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from the page URL: ${rpcUrl}. Verify this endpoint before relying on displayed onchain state.`,
		readRpcOverrideActiveDetail: (configuredRpcLabel: string, sourceLabel: string, rpcUrl: string) => `${configuredRpcLabel} came from ${sourceLabel}: ${rpcUrl}. Verify this endpoint before relying on displayed onchain state.`,
		readBackendMismatchSuffix: 'Displayed onchain state may not match the network this interface writes to.',
		readRpcMismatchTitle: 'Read RPC mismatch',
		readRpcOverrideActiveTitle: 'Read RPC override active',
		setupIncompleteTitle: 'Setup incomplete',
		simulationBootstrapFailedTitle: 'Simulation bootstrap failed',
		staleReadBackendSuffix: 'Displayed onchain state may be behind the latest chain state. Refresh or switch RPC before acting on balances, settlement, or liquidation.',
		universeForkedOnDetailSuffix: 'has forked on',
		universeForkedTitle: 'Universe forked',
		urlProvidedReadRpcTitle: 'URL-provided read RPC',
		wrongNetworkDetailPrefix: 'This interface only enables contract interactions on Ethereum mainnet.',
		wrongNetworkMainnetInstruction: 'Switch the connected wallet network to Ethereum mainnet to continue.',
		wrongNetworkTitle: COMMON_WRONG_NETWORK_LABEL,
	},
	truthAuctionMarketViewSection: {
		currentFormPriceBadgeLabel: 'Current form price',
		currentSizeLabel: 'Current size',
		clearingLevelBadgeLabel: 'Clearing level',
		loadedDepthLabel: 'Loaded depth',
		loadMorePriceLevelsLabel: 'Load More Price Levels',
		loadingOrderBookDetail: 'Loading order book…',
		loadingPriceLevelsDetail: 'Loading price levels…',
		marketViewTitle: 'Market View',
		noActiveLevelsDetail: 'No active levels are visible.',
		noLivePriceLevelsDetail: 'No live price levels are currently active for this auction.',
		priceLadderTitle: 'Price Ladder',
		priceLevelLabel: 'Price level',
		submissionsLabel: (count: string) => `${count} submissions`,
		visibleDepthTitle: 'Visible Depth',
	},
	deploymentSection: {
		canDeployNowDetail: 'Can deploy now.',
		codeFoundAtExpectedAddressDetail: 'Code found at expected address.',
		connectWalletToContinueDetail: 'Connect wallet to continue.',
		deployedBadgeLabel: 'Deployed',
		deployButtonLabel: COMMON_DEPLOY_LABEL,
		deployingBadgeLabel: 'Deploying...',
		deployingDetail: 'Deployment in progress.',
		deployingPendingLabel: 'Deploying...',
		notDeployedBadgeLabel: 'Not Deployed',
		waitingBadgeLabel: 'Waiting',
		waitingForPrerequisiteDetail: (prerequisiteLabel: string) => `Waiting for ${prerequisiteLabel}.`,
	},
	securityPoolWorkflowSection: {
		autoExecPendingLabel: 'Auto-exec pending',
		additionalPoolActionsAriaLabel: 'Additional pool actions',
		amountLabel: 'Amount',
		directoryViewLabel: 'Directory',
		executeStagedOperationLabel: 'Execute Staged Operation',
		executingStagedOperationLabel: 'Executing staged operation...',
		forkAndTruthReadOnlyReason: 'This pool is currently operational, so fork and truth auction actions are read only.',
		initiatorLabel: 'Initiator',
		loadingVaultDetail: 'Loading vault...',
		loadStagedOperationsLabel: 'Load Staged Operations',
		manualExecutionLabel: 'Manual execution',
		noStagedOperationsQueuedDetail: 'No staged operations are currently queued for this pool.',
		noVaultsInThisPoolDetail: 'No vaults in this pool.',
		noneQueuedBadgeLabel: 'None queued',
		noneYetBadgeLabel: COMMON_NONE_LABEL,
		pendingOperationLiquidationLabel: 'Liquidation',
		pendingOperationSetBondAllowanceLabel: 'Set Bond Allowance',
		pendingOperationWithdrawRepLabel: 'Withdraw REP',
		pendingReportLabel: (reportId: string) => `Report #${reportId}`,
		primaryPoolActionsAriaLabel: 'Primary pool actions',
		poolNotFoundTitle: 'Pool not found',
		managePoolTitle: 'Manage Pool',
		refreshOracleLabel: 'Refresh Oracle',
		refreshPoolLabel: 'Refresh pool',
		refreshStagedOperationsLabel: 'Refresh Staged Operations',
		refreshingOracleLabel: 'Refreshing oracle...',
		refreshingOperationsLabel: 'Refreshing operations...',
		refreshingPoolLabel: 'Refreshing pool...',
		refreshingVaultLabel: 'Refreshing...',
		requestCostLabel: 'Request Cost',
		requestNewPriceLabel: 'Request New Price',
		requestingNewPriceLabel: 'Requesting new price...',
		reviewLiquidationActionLabel: 'Review Liquidation',
		reviewLiquidationDescription: 'Inspect the liquidation quote, timeout, and execution path before queueing liquidation.',
		reviewLiquidationTitle: 'Review Liquidation',
		selectedBadgeLabel: 'Selected',
		selectedPoolTitle: 'Selected Pool',
		selectedPoolVaultViewsAriaLabel: 'Selected pool vault views',
		selectedPoolViewsAriaLabel: 'Selected pool views',
		notFoundBadgeLabel: 'Not found',
		openOraclePriceLabel: 'Open Oracle Price',
		openOracleTitle: 'Open Oracle',
		parentPoolLabel: 'Parent Pool',
		pendingRequestLabel: 'Pending Request',
		questionTitle: 'Question',
		selectVaultActionLabel: 'Select Vault',
		selectedViewLabel: 'Selected',
		showingActiveStagedOperationsLabel: (loadedCount: string, activeCount: string) => `Showing ${loadedCount} of ${activeCount} active staged operations, newest first.`,
		stagedOperationIdLabel: 'Staged Operation Id',
		stagedOperationIdPlaceholder: '0',
		stagedOperationsLabel: 'Staged Operations',
		stagedOperationsListLabel: 'Staged Operations List',
		targetVaultLabel: 'Target Vault',
		universeMismatchTitle: 'Universe Mismatch',
		universeMismatchDetailPrefix: 'This pool belongs to',
		universeMismatchDetailMiddle: 'but the app is currently set to',
		universeMismatchDetailSuffix: 'This pool does not exist.',
		vaultDirectoryTitle: 'Vault Directory',
		vaultMissingDetail: 'This vault does not exist.',
		vaultOperationsTitle: 'Vault Operations',
		selectedVaultAddressLabel: 'Selected Vault Address',
		securityPoolAddressLabel: 'Security Pool Address',
		tryAnotherVaultAddressDetail: 'Try another vault address.',
		triggerZoltarForkAlreadyTriggeredReason: 'Zoltar fork has already been triggered for this pool. Continue in Fork & Migration.',
		triggerZoltarForkEnteredForkWorkflowReason: 'This pool has already entered Fork & Migration.',
		triggerZoltarForkUnavailableReason: 'Triggering a Zoltar fork is not available in the current pool state.',
		reportingLockedForkMigrationReason: 'This pool is in fork migration. Reporting actions unlock once the pool becomes operational.',
		reportingLockedForkedReason: 'This parent pool is forked. Continue in Fork & Migration for migration and settlement.',
		reportingLockedTruthAuctionReason: 'This pool is in truth auction. Reporting actions unlock once the pool becomes operational.',
		reportingOpensAfterMarketEndReason: 'Reporting opens after market end.',
		operationIdLabel: 'Operation Id',
	},
	forkAuctionSection: {
		childUniverseNotCreatedForOutcomeDetail: (outcomeLabel: string) => `Child universe not created for the ${outcomeLabel} outcome.`,
	},
	liquidationModal: {
		callerCollateralizationAtOpenOracleLabel: 'Caller Collateralization @ Open Oracle',
		collateralizationAtOpenOracleLabel: 'Collateralization @ Open Oracle',
		callerVaultAfterLiquidationTitle: 'Caller Vault After Liquidation',
		callerVaultLabel: 'Caller Vault',
		checkStateBadgeLabel: 'Check State',
		closeButtonAriaLabel: COMMON_CLOSE_LABEL,
		enterLiquidationAmountReason: 'Enter a liquidation amount.',
		enterLiquidationTimeoutReason: 'Enter a liquidation timeout of at least 1 minute.',
		executeLiquidationPendingLabel: 'Executing liquidation...',
		executeVaultLiquidationTitle: 'Execute Vault Liquidation',
		failedBadgeLabel: 'Failed',
		invalidLiquidationPairTitle: 'Invalid Liquidation Pair',
		liquidateVaultIdleLabel: COMMON_LIQUIDATE_VAULT_LABEL,
		liquidateVaultPendingLabel: 'Submitting liquidation...',
		liquidateVaultTitle: COMMON_LIQUIDATE_VAULT_LABEL,
		liquidationAmountLabel: 'Liquidation Amount (ETH)',
		liquidationAmountPlaceholder: '0.0',
		liquidationExecutedTitle: 'Liquidation Executed',
		liquidationFailedDetail: 'The oracle manager attempted the liquidation immediately, but the security pool rejected it.',
		liquidationFailedTitle: 'Liquidation Failed',
		liquidationQueuedTitle: 'Liquidation Queued',
		liquidationSubmittedTitle: 'Liquidation Submitted',
		manualExecutionTimeoutLabel: COMMON_MANUAL_EXECUTION_TIMEOUT_LABEL,
		manualQueuedLiquidationDetail: MANUAL_QUEUED_OPERATION_DETAIL,
		metricAmountLabel: COMMON_AMOUNT_LABEL,
		openOraclePriceLabel: 'Open Oracle Price',
		operationExecutedBadgeLabel: COMMON_EXECUTED_LABEL,
		queueLiquidationActionLabel: 'queue liquidation',
		queueLiquidationIdleLabel: 'Queue Liquidation',
		queueLiquidationPendingLabel: 'Queueing liquidation...',
		queueVaultLiquidationTitle: 'Queue Vault Liquidation',
		queuedBadgeLabel: 'Queued',
		refreshingBadgeLabel: COMMON_REFRESHING_LABEL,
		refreshingLiquidationStateDetail: 'Refreshing liquidation state.',
		refreshingLiquidationStateTitle: 'Refreshing Liquidation State',
		refreshingOpenOracleValidityReason: 'Refreshing price validity.',
		reloadPoolBeforeExecutingReason: 'Reload the selected pool before executing liquidation.',
		reloadPoolBeforeLiquidatingReason: 'Reload the selected pool before liquidating.',
		repCollateralLabel: REP_COLLATERAL_LABEL,
		repMovedLabel: 'Rep Moved',
		securityBondAllowanceLabel: 'Security Bond Allowance',
		securityMultiplierLabel: COMMON_SECURITY_MULTIPLIER_LABEL,
		securityPoolLabel: 'Security Pool',
		selectDifferentTargetVaultReason: 'Select a target vault that is different from the caller vault.',
		selectTargetVaultReason: 'Select a target vault first.',
		submitNewStagedOperationDetail: STAGED_OPERATION_RETRY_DETAIL,
		targetCollateralizationAtOpenOracleLabel: 'Target Collateralization @ Open Oracle',
		targetVaultLabel: 'Target Vault',
		timeoutHelpTextInvalid: 'Enter whole minutes. Queued staged operations must stay executable for at least 1 minute after the oracle settlement window completes.',
		timeoutHelpTextResolved: (duration: string) => `This queued staged operation will expire ${duration} after the oracle settlement window completes.`,
		transactionStateUnavailableDetail: TRANSACTION_STATE_UNAVAILABLE_DETAIL,
		validOracleExecutedDetail: 'A valid oracle price was already available, so the liquidation executed immediately and no staged operation was created.',
		viewInStagedOperationsLabel: COMMON_VIEW_IN_STAGED_OPERATIONS_LABEL,
	},
	deploymentRouteContent: {
		allDeployedLabel: 'All deployed',
		completedSectionTitle: (sectionTitle: string) => `${sectionTitle} (Completed)`,
		contractsDeployedLabel: 'Contracts deployed',
		deployButtonIdleLabel: 'Deploy Next Missing',
		deployButtonPendingLabel: 'Deploying...',
		deploymentGroupsDescription: 'All deterministic contracts are deployed in grouped sections.',
		deploymentGroupsTitle: 'Deployment Groups',
		deploymentInProgressLabel: 'Deployment In Progress',
		deterministicContractDeploymentDescription: 'Deploy and verify the shared deterministic contracts that back the application.',
		deterministicContractDeploymentTitle: 'Deterministic contract deployment',
		deployRouteEyebrow: COMMON_DEPLOY_LABEL,
		loadingDeploymentStatusLabel: 'Loading deployment status...',
		loadingLabel: COMMON_LOADING_LABEL,
		nextDeployableLabel: 'Next deployable',
		nextDeployablePrefix: 'Next deployable contract:',
	},
	marketSection: {
		forkActionLabel: COMMON_FORK_ZOLTAR_LABEL,
		forkZoltarModalTitle: COMMON_FORK_ZOLTAR_LABEL,
		forkSectionTitle: 'Fork',
		marketsSectionTitle: COMMON_MARKETS_LABEL,
		openRepMigrationLabel: 'Open REP Migration',
		postForkActionsDescription: 'The universe is forked. Migration is now the primary follow-up action.',
		postForkActionsTitle: 'Post-Fork Actions',
		questionsLabel: 'Questions',
		selectedForkQuestionPrefix: 'Selected fork question:',
		statusForkedLabel: COMMON_FORKED_LABEL,
		statusLabel: COMMON_STATUS_LABEL,
		statusUnforkedLabel: 'Unforked',
		universeLabel: COMMON_UNIVERSE_LABEL,
	},
	marketOverviewSection: {
		childUniverseAlreadyDeployedReason: 'Child universe already deployed.',
		childUniverseNotAlreadyDeployedLabel: 'Child universe not already deployed',
		childUniversesUnavailableReason: 'Child universes are unavailable because this universe has not forked.',
		universeIsForkedLabel: 'Universe is forked',
	},
	marketCreateQuestionSection: {
		alreadyForkedLabel: COMMON_ALREADY_FORKED_LABEL,
		answerUnitFieldLabel: COMMON_ANSWER_UNIT_LABEL,
		answerUnitFieldPlaceholder: 'USD',
		createAnotherQuestionLabel: 'Create Another Question',
		createPoolFromQuestionLabel: 'Create Pool From Question',
		createQuestionButtonIdleLabel: COMMON_CREATE_QUESTION_LABEL,
		createQuestionButtonPendingLabel: 'Creating Question...',
		createQuestionDescription: 'Define the market type, timing, and outcomes for a new Zoltar question.',
		createQuestionTitle: COMMON_CREATE_QUESTION_LABEL,
		creationTransactionHashLabel: 'Creation transaction hash',
		descriptionFieldHelpText: 'Include the resolution source, any edge cases, and what should make the question resolve as invalid.',
		descriptionFieldLabel: 'Description',
		descriptionFieldPlaceholder: 'Optional question context',
		draftPreviewDescription: 'Draft Preview shows the level of clarity traders and reporters will see before trusting the question.',
		draftPreviewTitle: 'Draft Preview',
		draftQuestionStatusAriaLabel: 'Draft question status',
		draftQuestionSummaryAriaLabel: 'Draft question summary',
		chooseEndTimeLabel: 'Choose an end time',
		contextPresentForReviewLabel: 'Context is present for review',
		draftQuestionContextProvidedLabel: 'Context provided',
		draftQuestionNeedsContextLabel: 'Needs context',
		endTimeFieldLabel: COMMON_END_TIME_LABEL,
		immediatelyAfterCreationLabel: 'Immediately after creation',
		lowTrustUntilContextAddedLabel: 'Low trust until context is added',
		outcomeFieldLabelPrefix: 'Outcome',
		outcomesFieldLabel: COMMON_OUTCOMES_LABEL,
		addOutcomeLabel: 'Add Outcome',
		addAtLeastTwoOutcomesLabel: 'Add at least 2 outcomes',
		removeOutcomeLabel: 'Remove',
		outcomesFieldHelpText: 'Use concise, mutually exclusive labels. Users should be able to tell at a glance which outcome would win.',
		poolEligibilityBinaryQuestionText: 'Placeholder origin security pools support this exact Yes / No question shape.',
		poolEligibilityCategoricalQuestionText: 'Categorical questions are valid in Zoltar, but Placeholder origin security pools currently require an exact binary Yes / No question.',
		poolEligibilityScalarQuestionText: 'Scalar questions are valid in Zoltar, but Placeholder origin security pools currently require an exact binary Yes / No question.',
		questionDefaultDescriptionText: 'Add resolution notes, evidence sources, and edge-case handling so other users know how this question will settle.',
		questionDefaultTitleText: 'Add a clear question title',
		questionFallbackTitle: 'Question',
		questionTypeAriaLabel: COMMON_QUESTION_TYPE_LABEL,
		questionTypeGuidanceTitle: 'Question Type Guidance',
		questionTypeLabel: COMMON_QUESTION_TYPE_LABEL,
		questionDetailsLoadingAriaLabel: 'Loading question details',
		questionDetailsNotLoadedText: 'Question details are not available.',
		riskCueFieldLabel: 'Risk cue',
		scalarFieldHelpText: 'Scalar questions settle to a numeric result inside the range above. Use a unit that matches the public source you expect to cite.',
		scalarIncrementFieldLabel: 'Scalar Increment',
		scalarIncrementFieldPlaceholder: '0.1',
		scalarMaxFieldLabel: 'Scalar Max',
		scalarMaxFieldPlaceholder: '10',
		scalarMinFieldLabel: 'Scalar Min',
		scalarMinFieldPlaceholder: '1',
		scalarPreviewPromptText: 'Enter scalar min, max, and increment to preview the tick slider.',
		startTimeFieldLabel: 'Start Time',
		startsLabel: 'Starts',
		endsLabel: 'Ends',
		timingFieldHelpText: 'Times use your browser timezone. Leave start time blank to allow activity immediately after creation.',
		titleFieldHelpText: 'Keep the title self-contained so users can understand the exact question before opening details.',
		titleFieldPlaceholder: 'Will event X happen?',
		titleFieldLabel: 'Title',
		useForForkLabel: 'Use For Fork',
		walletRequiredReason: 'Connect a wallet before creating a question.',
		workflowIntroTitle: 'Write the question the way a resolver will read it.',
		workflowStepDefineEventLabel: '1. Define the event clearly',
		workflowStepExplainResolutionLabel: '2. Explain how it resolves',
		workflowStepSetTimingWindowLabel: '3. Set the timing window',
		marketTypeOptions: {
			binaryLabel: 'Binary',
			categoricalLabel: 'Categorical',
			scalarLabel: COMMON_SCALAR_LABEL,
		},
		marketTypeGuidance: {
			binary: {
				description: 'Ask a yes-or-no question that can be resolved from one public source of truth.',
				stepOne: 'Write the title so it can be answered with Yes, No, or Invalid.',
				stepTwo: 'Name the event window clearly in the title or description.',
				stepThree: 'Use the description for the exact resolution source and edge cases.',
			},
			categorical: {
				description: 'List the mutually exclusive outcomes that could win this question.',
				stepOne: 'Keep outcomes short and clearly distinct from each other.',
				stepTwo: 'Use the description to explain how ties, cancellations, or exceptions resolve.',
				stepThree: 'Only include outcomes that a resolver can verify from a public source.',
			},
			scalar: {
				description: 'Ask for a measurable number with a unit, range, and increment that users can understand.',
				stepOne: 'Pick a range that covers realistic answers without being overly broad.',
				stepTwo: 'Set the answer unit so users know what the number represents.',
				stepThree: 'Use the description to explain rounding, source data, and invalid conditions.',
			},
		},
	},
	marketQuestionsSection: {
		alreadyForkedLabel: COMMON_ALREADY_FORKED_LABEL,
		loadingQuestionsLabel: 'Loading questions...',
		marketsTitle: COMMON_MARKETS_LABEL,
		noQuestionsEmptyBadgeLabel: 'No questions',
		noQuestionsBadgeLabel: 'No questions',
		noQuestionsDetail: 'No questions.',
		nonBinaryPoolRestrictionDetail: 'Non-binary questions are valid in Zoltar, but Placeholder origin pools currently require an exact binary Yes / No question.',
		pageUnavailableDetail: 'Question page unavailable.',
	},
	openOracleSection: {
		advancedStandaloneOracleGameDescription: 'Direct Open Oracle creation for protocol testing. This bypasses pool-managed oracle-manager staging, so confirm addresses, token amounts, fees, and timing before submitting.',
		advancedStandaloneOracleGameTitle: 'Open Oracle Game',
		approvingTokenPendingLabel: (tokenSymbol: string) => `Approving ${tokenSymbol}...`,
		browseReportsTitle: 'Browse Reports',
		browseReportsDescription: (pageSize: string) => `Browse every Open Oracle game and open a selected report view. Page size is fixed at ${pageSize} reports.`,
		browseShownCountSummary: (shownCount: string, pageCount: string) => `${shownCount} of ${pageCount} reports shown on this page.`,
		callbackContractLabel: 'Callback Contract',
		callbackExtraTitle: 'Callback / Extra',
		callbackGasLimitLabel: 'Callback Gas Limit',
		currentAmount1Label: (tokenSymbol: string) => `Current Amount 1 (${tokenSymbol})`,
		currentAmount2Label: (tokenSymbol: string) => `Current Amount 2 (${tokenSymbol})`,
		tokenPairSuffix: (token1Symbol: string, token2Symbol: string) => `${token1Symbol} / ${token2Symbol}`,
		createAnotherLabel: 'Create Another',
		createStandaloneOracleGameButtonIdleLabel: 'Create Standalone Oracle Game',
		createStandaloneOracleGameButtonPendingLabel: 'Creating...',
		createSuccessDescription: 'The report instance was created successfully.',
		createSuccessTitle: 'Create Success',
		currentPriceLabel: 'Current Price',
		currentReportStateTitle: 'Current Report State',
		currentReporterLabel: 'Current Reporter',
		currentReporterAwaitingInitialReportLabel: 'None (awaiting initial report)',
		booleanNoLabel: COMMON_NO_LABEL,
		booleanYesLabel: COMMON_YES_LABEL,
		disputeAndSwapModalDescription: 'Provide the replacement swap amounts for the selected report.',
		disputeAndSwapModalTitle: COMMON_DISPUTE_AND_SWAP_LABEL,
		disputeAndSwapPendingLabel: 'Submitting dispute...',
		disputingReportActionLabel: 'disputing the report',
		disputeDelayFieldHelpText: 'Delay in seconds after the initial report before disputes can begin.',
		disputeDelayFieldLabel: COMMON_DISPUTE_DELAY_LABEL,
		disputeDelayLabel: COMMON_DISPUTE_DELAY_LABEL,
		disputeOccurredLabel: 'Dispute Occurred',
		disputeReportActionLabel: COMMON_DISPUTE_AND_SWAP_LABEL,
		disconnectedWalletApprovalReason: (tokenSymbol: string) => `Connect a wallet before approving ${tokenSymbol}.`,
		disconnectedWalletDisputeReason: 'Connect a wallet before disputing the report.',
		disconnectedWalletSettleReason: 'Connect a wallet before settling the report.',
		disconnectedWalletSubmitInitialReportReason: 'Connect a wallet before submitting the initial report.',
		disconnectedWalletWrapEthReason: 'Connect a wallet before wrapping ETH.',
		disputeReportTitle: 'Dispute Report',
		economicsTitle: 'Economics',
		enterValidDisputeAmountsBeforeApprovingReason: (tokenSymbol: string) => `Enter valid dispute amounts before approving ${tokenSymbol}.`,
		enterValidPriceBeforeApprovingReason: (token1Symbol: string, token2Symbol: string) => `Enter a valid ${token1Symbol} / ${token2Symbol} price before approving ${token2Symbol}.`,
		escalationHaltFieldHelpText: 'Token1 amount where dispute escalation stops, entered as a decimal value for the token1 address.',
		escalationHaltFieldLabel: COMMON_ESCALATION_HALT_LABEL,
		escalationHaltLabel: COMMON_ESCALATION_HALT_LABEL,
		ethValueToSendFieldHelpText: 'ETH sent with creation; must cover required funding and the settler reward.',
		ethValueToSendFieldLabel: 'ETH Value To Send',
		exactTokenRequiredLabel: (tokenSymbol: string) => `Exact ${tokenSymbol} Required`,
		exactToken1ReportFieldHelpText: 'Token1 amount to report, entered as a decimal value for the token1 address.',
		exactToken1ReportFieldLabel: 'Exact Token1 Report',
		feeFieldHelpText: 'Fee charged during dispute economics, entered as a percentage.',
		feeFieldLabel: COMMON_FEE_PERCENTAGE_LABEL,
		feePercentageLabel: COMMON_FEE_PERCENTAGE_LABEL,
		feeLabel: 'Fee',
		fetchPriceFromUniswapIdleLabel: 'Fetch price from Uniswap',
		fetchPriceFromUniswapPendingLabel: 'Fetching...',
		identityTitle: 'Identity',
		initialEconomicsTitle: 'Initial Economics',
		initialReportContextTitle: 'Report Context',
		initialReportModalDescription: 'Review price source, approvals, and token balances before submitting the initial report.',
		initialReportModalTitle: COMMON_SUBMIT_INITIAL_REPORT_LABEL,
		initialReportTitle: 'Initial Report',
		initialReporterLabel: 'Initial Reporter',
		initialReportTokenApprovalActionLabel: 'submitting the initial report',
		lastReportOpportunityLabel: 'Last Report Opportunity',
		loadOpenOracleReportsFailedMessage: 'Failed to load Open Oracle reports',
		loadReportFirstReason: 'Load a report first.',
		multiplierFieldHelpText: 'Escalation multiplier for dispute economics.',
		multiplierFieldLabel: COMMON_MULTIPLIER_LABEL,
		multiplierLabel: COMMON_MULTIPLIER_LABEL,
		newAmountMustBeExactDetail: (tokenSymbol: string, amount: string) => `New ${tokenSymbol} amount must be exactly ${amount} for this dispute.`,
		noWriteActionsAvailableDetail: 'This report is settled. No write actions are available.',
		numberOfReportsLabel: 'Number of Reports',
		openReportButtonLabel: 'Open report',
		oracleAddressLabel: 'Oracle Address',
		priceFieldPlaceholder: '1.00',
		priceFieldLabel: (token1Symbol: string, token2Symbol: string) => `Price (${token1Symbol} / ${token2Symbol})`,
		priceLabel: COMMON_PRICE_LABEL,
		priceSourceLabelPrefix: 'Price source:',
		protocolFeeFieldHelpText: 'Protocol fee charged during disputes, entered as a percentage.',
		protocolFeeFieldLabel: COMMON_PROTOCOL_FEE_LABEL,
		protocolFeeLabel: COMMON_PROTOCOL_FEE_LABEL,
		protocolFeeRecipientLabel: 'Protocol Fee Recipient',
		reportDetailsTitle: COMMON_REPORT_DETAILS_LABEL,
		reportIdFieldLabel: COMMON_REPORT_ID_LABEL,
		reportIdLabel: COMMON_REPORT_ID_LABEL,
		reportLabel: 'Report',
		reportNumberTitle: (reportId: string) => `Report #${reportId}`,
		reportTimestampLabel: 'Report Timestamp',
		reportActionsTitle: 'Report Actions',
		reportActionsDescription: 'Open a focused action flow for the selected report when it is available.',
		returnToBrowseLabel: COMMON_RETURN_TO_BROWSE_LABEL,
		searchReportsLabel: 'Search Reports',
		settleConfirmationDetail: 'Settlement is confirmation-first. Review the current report state and confirm only when the dispute window is closed.',
		settleReportIdleLabel: COMMON_SETTLE_REPORT_LABEL,
		settleReportModalDescription: 'Confirm settlement once the selected report is ready.',
		settleReportModalTitle: COMMON_SETTLE_REPORT_LABEL,
		settleReportPendingLabel: 'Settling report...',
		settleReportTitle: COMMON_SETTLE_REPORT_LABEL,
		settledLabel: COMMON_SETTLED_LABEL,
		settledReportTitle: 'Settled Report',
		settlerRewardFieldHelpText: 'ETH paid to the account that settles the report.',
		settlerRewardFieldLabel: COMMON_SETTLER_REWARD_LABEL,
		settlerRewardLabel: COMMON_SETTLER_REWARD_LABEL,
		settlementSummaryTitle: 'Settlement Summary',
		settlementTimeFieldHelpText: 'Delay in seconds after the initial report before settlement can begin.',
		settlementTimeFieldLabel: COMMON_SETTLEMENT_TIME_LABEL,
		settlementTimeLabel: COMMON_SETTLEMENT_TIME_LABEL,
		settlementTimestampLabel: 'Settlement Timestamp',
		settlementTitle: 'Settlement',
		notSettledLabel: 'Not settled',
		stateHashLabel: 'State Hash',
		statusFieldLabel: COMMON_STATUS_LABEL,
		statusFilterAllLabel: 'All statuses',
		statusFilterAwaitingInitialReportLabel: 'Awaiting initial report',
		statusFilterPendingLabel: 'Pending',
		statusFilterDisputedLabel: 'Disputed',
		statusFilterSettledLabel: COMMON_SETTLED_LABEL,
		noneYetBadgeLabel: COMMON_NONE_LABEL,
		noMatchesBadgeLabel: 'No matches',
		noOpenOracleGamesDetail: 'No Open Oracle games found.',
		noReportsMatchFiltersDetail: 'No reports match the current search and status filters.',
		refreshingReportSummariesDetail: 'Refreshing report summaries.',
		refreshReportButtonLabel: 'Refresh report',
		reportAmountsTitle: 'Report Amounts',
		selectedReportEyebrow: 'Open Oracle Report Details',
		searchReportsPlaceholder: 'Search by report ID, token symbol, or token address',
		staleQuoteRefreshDetail: 'This quote is stale and will be refreshed before submission.',
		standaloneOracleWarning: 'Use this only when you intend to create a standalone oracle game directly from the connected wallet. Pool-managed oracle requests should be started from a selected security pool.',
		statusTitle: COMMON_STATUS_LABEL,
		submitInitialReportIdleLabel: COMMON_SUBMIT_INITIAL_REPORT_LABEL,
		submitInitialReportPendingLabel: 'Submitting...',
		timeInBlocksSuffix: ' blocks',
		timeInSecondsSuffix: 's',
		timingTitle: 'Timing',
		quoteLoadedDetail: (quoteBlockNumberText: string | undefined, ageText: string) => (quoteBlockNumberText === undefined ? `Quote loaded ${ageText}.` : `Quote loaded at block ${quoteBlockNumberText} ${ageText}.`),
		quoteAgeText: (quoteLoadedAtMs: number) => {
			const elapsedSeconds = Math.max(0, Math.floor((Date.now() - quoteLoadedAtMs) / 1000))
			if (elapsedSeconds < 60) return `${elapsedSeconds}s ago`
			const elapsedMinutes = Math.floor(elapsedSeconds / 60)
			if (elapsedMinutes < 60) return `${elapsedMinutes}m ago`
			const elapsedHours = Math.floor(elapsedMinutes / 60)
			return `${elapsedHours}h ago`
		},
		token1AddressFieldHelpText: 'Base token for the reported pair.',
		token1AddressFieldLabel: 'Token1 Address',
		tokenApprovalTitle: (tokenSymbol: string) => `${tokenSymbol} Approval`,
		token2AddressFieldHelpText: 'Quote token for the reported pair.',
		token2AddressFieldLabel: 'Token2 Address',
		tokenPairLabel: COMMON_TOKEN_PAIR_LABEL,
		tokenPairTitle: COMMON_TOKEN_PAIR_LABEL,
		tokenSwapOutLabel: 'Token to Swap Out',
		trackDisputesLabel: 'Track Disputes',
		awaitingInitialReportLabel: 'Awaiting Initial Report',
		newTokenAmountFieldLabel: (tokenSymbol: string) => `New ${tokenSymbol} Amount`,
		requiredWethWrapDetailPrefix: 'Need',
		requiredWethWrapDetailSuffix: 'more WETH for this report.',
		wrapEthToWethIdleLabel: 'Wrap needed ETH to WETH',
		wrapEthToWethPendingLabel: 'Wrapping ETH...',
		stickyContextFields: {
			priceLabel: COMMON_PRICE_LABEL,
			reporterLabel: 'Reporter',
			stageLabel: 'Stage',
			tokenPairLabel: COMMON_TOKEN_PAIR_LABEL,
		},
	},
	zoltarMigrationSection: {
		prepareRepIdleLabel: 'Prepare REP',
		preparingRepPendingLabel: 'Preparing REP...',
		repMigrationUnavailableReason: 'REP migration is unavailable because this universe has not forked.',
		repPreparationUnavailableReason: 'REP preparation is unavailable because this universe has not forked.',
		splitRepIdleLabel: 'Split REP',
		splittingRepPendingLabel: 'Splitting REP...',
	},
	overviewPanels: {
		addressLabel: 'Address',
		augurPlaceholderTitle: 'Augur Placeholder',
		connectWalletIdleLabel: COMMON_CONNECT_WALLET_LABEL,
		connectWalletPendingLabel: COMMON_CONNECTING_LABEL,
		connectedBadgeLabel: 'Connected',
		connectingDetail: COMMON_CONNECTING_LABEL,
		ethBalanceLabel: 'ETH',
		forkedBadgeLabel: COMMON_FORKED_LABEL,
		goToGenesisUniverseLabel: COMMON_GO_TO_GENESIS_UNIVERSE_LABEL,
		notConnectedLabel: 'Not connected',
		operationsEyebrow: 'Operations',
		parentUniverseLabel: 'Parent Universe',
		readOnlyBadgeLabel: 'Read-only',
		repBalanceLabel: COMMON_REP_LABEL,
		repPerEthLabel: COMMON_REP_PER_ETH_LABEL,
		repUsdcLabel: 'REP/USDC',
		refreshRepPricesAriaLabel: COMMON_REFRESH_REP_PRICES_LABEL,
		refreshRepPricesIdleTitle: COMMON_REFRESH_REP_PRICES_LABEL,
		refreshRepPricesPendingTitle: 'Refreshing REP prices...',
		simulationBadgeLabel: 'Simulation',
		simulationDescription: 'Simulation mode uses browser-local contract state. Transactions do not affect a public network.',
		universeForkedDescription: 'This universe has forked.',
		universeForkedOnDetailPrefix: 'Zoltar forked on',
		universeLabel: COMMON_UNIVERSE_LABEL,
		wethBalanceLabel: 'WETH',
		wrongNetworkBadgeLabel: 'Wrong Network',
	},
	question: {
		answerUnitLabel: COMMON_ANSWER_UNIT_LABEL,
		createdLabel: 'Created',
		displayRangeLabel: 'Display Range',
		endTimeLabel: COMMON_END_TIME_LABEL,
		invalidOutcomeLabel: COMMON_INVALID_LABEL,
		loadingQuestionDetailsLabel: 'Loading question details...',
		outcomesLabel: COMMON_OUTCOMES_LABEL,
		questionIdLabel: COMMON_QUESTION_ID_LABEL,
		questionTimelineAriaLabel: 'Question timeline',
		scalarOutcomeLabel: COMMON_SCALAR_LABEL,
		ticksLabel: 'Ticks',
		untitledQuestionLabel: 'Untitled question',
	},
	scalarDeploymentSection: {
		childUniverseAlreadyDeployedDetail: 'Child universe already deployed.',
		childUniverseAlreadyDeployedReason: 'Child universe already deployed.',
		childUniverseNotAlreadyDeployedLabel: 'Child universe not already deployed',
		childUniverseSelectedTitle: 'Selected Child Universe',
		childUniversesTitle: 'Child Universes',
		connectWalletBeforeDeployingChildUniverseReason: 'Connect a wallet before deploying a child universe.',
		createChildUniverseLabel: 'Create child universe',
		createChildUniverseTitle: 'Create Child Universe',
		createInvalidUniverseLabel: 'Create invalid universe',
		deployedLabel: 'Deployed',
		deployInvalidUniverseLabel: 'Deploy Invalid Universe',
		deployUniverseLabel: 'Deploy Universe',
		deployingUniversePendingLabel: 'Deploying universe...',
		existingChildUniversesTitle: 'Existing Child Universes',
		executeChildUniverseDeploymentDescription: 'Confirm the selected scalar outcome and deploy its child universe in one bounded execution flow.',
		forkBeforeDeployingChildUniversesReason: 'Child universes are unavailable because this universe has not forked.',
		loadingScalarRangeDetail: 'Loading scalar range...',
		noChildUniverseSelectedMessage: 'No child universe selected.',
		noDeployedChildUniversesMessage: 'No deployed child universes.',
		openingChildUniversePendingLabel: 'Opening...',
		scalarForksCanDeployOneOutcomeUniverseAtATimeDetail: 'Scalar forks can deploy one outcome universe at a time.',
		selectChildUniverseLabel: 'Select Child Universe',
		selectedTickInvalidLabel: COMMON_INVALID_LABEL,
		selectedTickInvalidReason: 'Selected tick is invalid',
		universeIsForkedLabel: 'Universe is forked',
		walletConnectedLabel: 'Wallet connected',
	},
	shareMigrationTargetsSection: {
		addTargetLabel: 'Add Target',
		childDeployedLabel: 'Child deployed',
		childNotDeployedLabel: 'Child not deployed',
		clearLabel: 'Clear',
		loadingForkQuestionDetailsDetail: 'Loading fork question details...',
		loadingForkTargetUniversesDetail: 'Loading fork target universes...',
		malformedOutcomeLabel: (outcomeIndex: string) => `Malformed (${outcomeIndex})`,
		loadingScalarForkDetailsDetail: 'Loading scalar fork details...',
		noTargetChildUniversesDetail: 'No target child universes available.',
		notSelectedLabel: 'Not selected',
		removeTargetLabel: 'Remove Target',
		selectAllLabel: 'Select all',
		selectScalarTargetLabel: 'Select Scalar Target',
		selectScalarTargetUniverseDetail: 'Select at least one scalar target universe.',
		selectedLabel: 'Selected',
		selectedTickLabel: (selectedTick: string, totalTicks: string) => `${selectedTick} / ${totalTicks}`,
		targetChildUniversesTitle: 'Target Child Universes',
		targetsUnlockAfterForkDetail: 'Child-universe targets unlock after this universe forks.',
	},
	scalarOutcomePicker: {
		currentValueLabel: 'Current Value',
		invalidLabel: COMMON_INVALID_LABEL,
		maxValueLabel: 'Max Value',
		minValueLabel: 'Min Value',
		orLabel: 'or',
		selectedOutcomeLabel: 'Selected Outcome',
		selectedTickLabel: 'Selected Tick',
	},
	reportingSection: {
		belowMinimumSelectedSideCapacityReason: 'Remaining selected-side capacity is below the minimum report bond.',
		continueInForkAndMigrationReason: 'Continue in Fork & Migration to migrate unresolved escalation deposits into a child universe.',
		continueInForkAndMigrationLabel: 'Continue in Fork & Migration',
		contributionAmountHelpText: 'This is the REP you are willing to lock on the selected side. Larger amounts can change the proposed outcome or extend the escalation timer.',
		contributionAmountLabel: 'Contribution Amount (REP)',
		enterValidReportAmountReason: 'Enter a valid report amount to preview profit.',
		escalationMetricsTitle: 'Escalation Metrics',
		escalationStartedLabel: 'Escalation started',
		escalationWorkflowSummary: 'Select the answer you believe should finalize, lock REP behind it, and return after finalization to settle deposits.',
		establishedReportOutcomeLabel: 'Report Outcome',
		chooseDepositsToSettleLabel: 'Choose deposits to settle',
		forkAlreadyTriggeredReportReason: 'Escalation reached non-decision and Zoltar fork has already been triggered for this pool. Continue in Fork & Migration.',
		forkAlreadyTriggeredSettlementReason: 'Escalation deposits remain locked after non-decision. Zoltar fork has already been triggered for this pool, so continue in Fork & Migration.',
		forkTriggeredReportReason: 'Escalation reached non-decision. Trigger Zoltar Fork here if this pool should fork the universe.',
		forkTriggeredSettlementReason: 'Escalation deposits remain locked after non-decision. Trigger Zoltar Fork here if this pool should fork the universe.',
		initiallyDepositedLabel: 'Initially deposited:',
		leadHoldingCapitalLabel: 'Lead-holding capital',
		loadingAvailableVaultRepReason: 'Loading available vault REP.',
		loadingEscalationDepositsReason: 'Loading escalation deposits.',
		loadReportingDetailsReason: 'Load reporting details before using presets.',
		loadingEscalationLabel: 'Loading escalation...',
		loadingReportingLabel: 'Refresh reporting',
		maxProfitNotStartedReason: 'Max profit becomes available after the escalation game starts.',
		maxProfitLabel: 'Max profit',
		maxProfitWindowFilledReason: 'Max profit preset unavailable because the reward window is already filled on the selected side.',
		minToTakeTheLeadLabel: 'Min to take the lead',
		noSelectedSideCapacityReason: 'No remaining contribution capacity is available on the selected side.',
		noUnlockedVaultRepReason: 'No unlocked vault REP available for reporting.',
		nonDecisionThresholdLabel: 'Non-decision threshold',
		reportOnSelectedSideLabel: 'Report On Selected Side',
		reportOutcomeAriaLabel: 'Report outcome',
		reportSelectedOutcomeButtonLabel: (selectedOutcomeLabel: string) => `Report ${selectedOutcomeLabel}`,
		reportOutcomeSelectionMessage: 'Select an outcome side above to enable reporting.',
		reportingActiveDetail: 'Escalation is live. Review the bond, side balances, and time remaining before contributing or withdrawing.',
		reportingWorkflowTitle: 'Reporting Workflow',
		reportingLatestOutcomeReminderImmediate: (selectedOutcomeLabel: string) => `Check back immediately to confirm the market finalized as ${selectedOutcomeLabel}.`,
		reportingLatestOutcomeReminderLater: (selectedOutcomeLabel: string) => `Check back later to confirm ${selectedOutcomeLabel} is the leading outcome.`,
		reportingLatestOutcomeReminderBeforeRewardWindowPrefix: 'Check back no later than ',
		reportingLatestOutcomeReminderBeforeRewardWindowMiddle: ' to confirm ',
		reportingLatestOutcomeReminderBeforeRewardWindowSuffix: ' is the leading outcome before the remaining reward-eligible REP on ',
		reportingLatestOutcomeReminderBeforeRewardWindowTail: ' is filled.',
		reportingLatestOutcomeReminderBeforeFinalizationPrefix: 'Check back no later than ',
		reportingLatestOutcomeReminderBeforeFinalizationMiddle: ' to confirm ',
		reportingLatestOutcomeReminderBeforeFinalizationSuffix: ' is the leading outcome before finalization.',
		reportingProjectionProfitPrefix: 'If ',
		reportingProjectionProfitMiddle: ' wins and no one else contributes afterward, this amount projects roughly ',
		reportingProjectionProfitSuffix: ' of profit. ',
		reportingProjectionNotStartedPrefix: 'If no one disputes after this report, the market would finalize in ',
		reportingProjectionNotStartedCheckBackPrefix: 'Check back no later than ',
		reportingProjectionNotStartedCheckBackMiddle: ' to confirm ',
		reportingProjectionNotStartedCheckBackSuffix: ' is still leading if later disputes keep escalation open.',
		reportingProjectionNotStartedSimpleSuffix: '. ',
		reportingProjectionEndsImmediatelyText: 'This contribution would end the escalation and finalize the market immediately. ',
		reportingProjectionExtendsPrefix: 'This contribution would extend the timer by ',
		reportingProjectionExtendsMiddle: ', and if no one disputes after it, the market would finalize in ',
		reportingProjectionDoesNotExtendPrefix: 'This contribution would not extend the timer, and if no one disputes after it, the market would finalize in ',
		reportingContributionLockPrefix: 'Based on the current escalation state, this action would lock ',
		reportingContributionLockSuffix: ' instead of the full entered amount.',
		openForkAndMigrationLabel: 'Open Fork & Migration',
		settleAllForThisSideReason: 'Select at least one deposit to settle or use Settle all for this side.',
		migrationRequiredReason: 'These escalation deposits must migrate in Fork & Migration.',
		reportingWorkflowStepOutcomeLabel: '1. Outcome',
		reportingWorkflowStepLockRepLabel: '2. Lock REP',
		reportingWorkflowStepSettleLabel: '3. Settle',
		reportingWorkflowCardDescription: 'Select the answer you believe should finalize, lock REP behind it, and return after finalization to settle deposits.',
		reportingWorkflowCardTitle: 'Reporting Workflow',
		reportingWorkflowSummary: 'Select the answer you believe should finalize, lock REP behind it, and return after finalization to settle deposits.',
		submitReportPendingLabel: 'Submitting report...',
		reportingSettlementTitle: 'Settle Escalation Deposits',
		reportingMetricsTitle: 'Escalation Metrics',
		reportingOutcomeTitle: 'Report Outcome',
		reportingNotEnabledTitle: 'Reporting Not Enabled',
		reportingOpenTitle: 'Reporting Open',
		resolvedTitle: 'Resolved',
		activeTitle: 'Active',
		forkTriggeredTitle: 'Fork Triggered',
		timedOutTitle: 'Timed Out',
		pendingFinalizationLabel: 'Pending finalization',
		timeLeftLabel: 'Time Left',
		claimTypeWinningPayoutLabel: 'Winning payout',
		claimTypeLosingDepositSettlementLabel: 'Losing deposit settlement',
		currentClaimTypePrefix: 'Current claim type:',
		entryDepthLabel: 'Entry depth:',
		reportingHasEndedRefreshReason: 'Escalation has ended. Refresh reporting to view the finalized outcome before settling deposits.',
		reportingOpenDetail: 'Load reporting details to view the escalation state for this pool.',
		reportingOpenMessage: 'Reporting is open.',
		reportingOpenSelectOutcomeMessage: 'Reporting is open. Select an outcome side below to enable reporting.',
		reportingPoolAlreadyFinalizedReason: 'This pool is already finalized.',
		settlementLockedUntilFinalizedReason: 'Escalation deposits cannot be settled until the question is finalized.',
		reportingResolvedDetail: 'Market finalized as',
		reportingResolvedDetailLabel: (selectedOutcomeLabel: string) => `Market finalized as ${selectedOutcomeLabel}.`,
		reportingTimedOutReason: 'Escalation ended by timeout. The winner is computed from the current stakes.',
		reportingTimedOutDetail: 'Escalation ended by timeout. The winner is computed from the current stakes.',
		migrationExpiredReason: 'The migration window for these unresolved escalation deposits has closed.',
		worthAfterFinalizationPendingLabel: 'Worth after finalization: Pending finalization',
		worthNowLabel: 'Worth now:',
		selectOutcomeAboveToEnableReportingMessage: 'Select an outcome side above to enable reporting.',
		selectOutcomePresetReason: 'Select an outcome side before using presets.',
		selectedSideAlreadyLeadsReason: 'Selected side already leads.',
		selectedSideUnavailableReason: 'Selected side is unavailable.',
		selectedSideLabel: 'Selected Side',
		securityPoolAddressLabel: 'Security Pool Address',
		settleAllDepositsLabel: (sideLabel: string) => `Settle All ${sideLabel} Deposits`,
		settleSelectedDepositsLabel: (sideLabel: string) => `Settle Selected ${sideLabel} Deposits`,
		settlingDepositsPendingLabel: (sideLabel: string) => `Settling ${sideLabel} deposits...`,
		startBondLabel: 'Start Bond',
		totalSideStakeLabel: 'Total side stake',
		selectedSideStakeLabel: 'Your side stake',
		triggeringZoltarForkLabel: 'Triggering Zoltar fork...',
		triggerZoltarForkIdleLabel: 'Trigger Zoltar Fork',
		triggerZoltarForkLabel: 'Trigger Zoltar Fork',
		loadingEscalationDepositReason: 'Loading escalation deposits.',
		loadingEscalationDepositsDetail: 'Loading escalation deposits...',
		availableUnlockedVaultRepPrefix: 'Available unlocked vault REP for reporting:',
		withdrawSelectedAllReason: 'Select at least one deposit to settle or use Settle all for this side.',
		withdrawEmptyStateDetail: 'Connected wallet has no unsettled escalation deposits.',
		thisPoolAlsoHasForkCarriedEscalationPositionsDetail: 'This pool also has fork-carried escalation positions. Settle those in Fork & Migration.',
	},
	securityPoolSection: {
		createAnotherPoolLabel: 'Create Another Pool',
		createPoolButtonIdleLabel: COMMON_CREATE_POOL_LABEL,
		createPoolButtonPendingLabel: 'Creating Pool...',
		createPoolLockedLabel: 'Pool Creation Locked',
		createPoolPanelTitle: COMMON_CREATE_POOL_LABEL,
		createdPoolCardTitle: 'Pool Created',
		creationLockedError: 'Security pools cannot be created after Zoltar has forked.',
		deploymentTransactionHashLabel: 'Deployment transaction hash',
		duplicateCheckPendingLabel: 'Checking Duplicate...',
		duplicatePoolError: 'A pool for this question and security multiplier already exists. Origin pool deployment is deterministic for that pair, so change the security multiplier to create a different pool.',
		initialOpenInterestFeeHelpText: 'Initial Open Interest Fee / Year is the starting annualized fee charged against open interest. The rate follows pool utilization after deployment.',
		initialOpenInterestFeeLabel: 'Initial Open Interest Fee / Year',
		ineligibleQuestionError: 'Security pools can only be created for exact binary Yes / No questions. Enter an eligible question to proceed.',
		loadingQuestionLabel: 'Loading question...',
		openPoolLabel: 'Open Pool',
		poolAddressLabel: 'Pool address',
		poolAlreadyExistsLabel: 'Pool Already Exists',
		questionHelpText: 'Paste an exact binary Yes / No Zoltar question ID.',
		questionIdLabel: COMMON_QUESTION_ID_LABEL,
		questionIdPlaceholder: COMMON_HEX_VALUE_PLACEHOLDER,
		returnToBrowseLabel: COMMON_RETURN_TO_BROWSE_LABEL,
		securityMultiplierHelpText: 'Security Multiplier sets the REP collateral target relative to open interest. Higher values require more REP backing and create a thicker safety buffer.',
		securityMultiplierLabel: COMMON_SECURITY_MULTIPLIER_LABEL,
		universeLabel: COMMON_UNIVERSE_LABEL,
	},
	securityVaultSection: {
		approveRepActionLabel: 'depositing REP',
		approvingRepPendingLabel: 'Approving REP...',
		bondAllowanceRejectedDetail: 'The oracle manager attempted the allowance update immediately, but the security pool rejected it.',
		bondAllowanceExecutedTitle: 'Bond Allowance Executed',
		bondAllowanceFailedTitle: 'Bond Allowance Failed',
		bondAllowanceQueuedTitle: 'Bond Allowance Queued',
		bondAllowanceSubmittedTitle: 'Bond Allowance Submitted',
		claimFeesActionDescription: 'Review claimable fees and confirm the fee redemption for the selected vault.',
		claimFeesAmountLabel: 'Claimable Fees',
		claimFeesIdleLabel: COMMON_CLAIM_FEES_LABEL,
		claimFeesModalDescription: 'Confirm the claimable fee balance before submitting the fee redemption for this vault.',
		claimFeesPendingLabel: 'Claiming fees...',
		claimFeesTitle: COMMON_CLAIM_FEES_LABEL,
		createVaultByDepositingRepDetail: 'This vault does not exist. Deposit REP to create it.',
		currentBondAllowanceLabel: 'Current Bond Allowance',
		currentSecurityBondAllowanceLabel: 'Current Security Bond Allowance',
		depositRepActionDescription: 'Add REP to the selected vault.',
		depositRepAmountLabel: 'REP Collateral Amount',
		depositRepIdleLabel: COMMON_DEPOSIT_REP_LABEL,
		depositRepPendingLabel: 'Depositing REP...',
		depositRepTitle: COMMON_DEPOSIT_REP_LABEL,
		firstDepositMinimumChecklistDetail: (amount: string) => `First deposits must be at least ${amount} REP.`,
		firstDepositMinimumInlineDetailSuffix: 'in the first deposit.',
		escalationEscrowedRepLabel: 'Escrowed REP',
		firstDepositMinimumChecklistLabel: 'First deposit meets the vault minimum',
		firstDepositMinimumDetailPrefix: 'New vaults require at least',
		hasClaimableFeesChecklistLabel: 'Claimable fees are available',
		insufficientRepBalanceDetail: (amount: string) => `Insufficient REP balance. Deposit amount exceeds your wallet balance by ${amount} REP.`,
		loadingVaultDetail: 'Loading vault...',
		missingVaultBlockerDetail: 'This vault does not exist.',
		vaultLauncherBlockerReason: (action: 'claim-fees' | 'deposit-rep' | 'rep-exit-redeem' | 'rep-exit-withdraw' | 'set-bond-allowance', blocker: 'connect-wallet' | 'missing-vault' | 'refresh-vault' | 'select-own-vault' | 'switch-mainnet') => {
			if (blocker === 'missing-vault') return 'This vault does not exist.'

			if (blocker === 'connect-wallet') {
				if (action === 'claim-fees') return 'Connect a wallet before claiming fees.'
				if (action === 'deposit-rep') return 'Connect a wallet before depositing REP.'
				if (action === 'rep-exit-redeem') return 'Connect a wallet before redeeming REP.'
				if (action === 'rep-exit-withdraw') return 'Connect a wallet before withdrawing REP.'
				return 'Connect a wallet before setting the security bond allowance.'
			}

			if (blocker === 'switch-mainnet') {
				return undefined
			}

			if (blocker === 'select-own-vault') {
				if (action === 'claim-fees') return 'Select your own vault to claim fees.'
				if (action === 'deposit-rep') return 'Select your own vault to deposit REP.'
				if (action === 'rep-exit-redeem') return 'Select your own vault to redeem REP.'
				if (action === 'rep-exit-withdraw') return 'Select your own vault to withdraw REP.'
				return 'Select your own vault to set the security bond allowance.'
			}

			if (action === 'claim-fees') return 'Refresh the vault before claiming fees.'
			if (action === 'deposit-rep') return 'Refresh the vault before depositing REP.'
			if (action === 'rep-exit-redeem') return 'Refresh the vault before redeeming REP.'
			if (action === 'rep-exit-withdraw') return 'Refresh the vault before withdrawing REP.'
			return 'Refresh the vault before setting the security bond allowance.'
		},
		noRepLockedChecklistDetail: WITHDRAW_ESCALATION_DEPOSITS_DETAIL,
		oracleExecutionFundingChecklistLabel: 'Oracle execution can be funded until a fresh price arrives',
		manualExecutionTimeoutInvalidDetail: 'Enter whole minutes. Queued self-service operations must stay executable for at least 1 minute after the oracle settlement window completes.',
		manualExecutionTimeoutLabel: COMMON_MANUAL_EXECUTION_TIMEOUT_LABEL,
		manualExecutionTimeoutResolvedDetail: (duration: string) => `This queued self-service operation will expire ${duration} after the oracle settlement window completes.`,
		noRepLockedChecklistLabel: 'No REP remains locked in the escalation game',
		ownedBadgeLabel: 'Owned',
		ownedChecklistLabel: 'Selected vault is owned by the connected account',
		operationExecutedBadgeLabel: COMMON_EXECUTED_LABEL,
		operationStatusUnavailableDetail: TRANSACTION_STATE_UNAVAILABLE_DETAIL,
		oracleManagerAutoExecuteQueueFullDetail: MANUAL_QUEUED_OPERATION_DETAIL,
		priceValidUntilLabel: 'Price Valid Until',
		readOnlyBadgeLabel: 'Read only',
		refreshButtonIdleLabel: COMMON_REFRESH_LABEL,
		refreshButtonPendingLabel: 'Refreshing...',
		refreshingBadgeLabel: COMMON_REFRESHING_LABEL,
		refreshingBondAllowanceStateDetail: 'Refreshing the oracle manager to determine whether the bond allowance was queued or executed immediately.',
		refreshingBondAllowanceStateTitle: 'Refreshing Bond Allowance State',
		refreshingWithdrawalStateDetail: 'Refreshing the oracle manager to determine whether the withdrawal was queued or executed immediately.',
		refreshingWithdrawalStateTitle: 'Refreshing Withdrawal State',
		repAvailableToQueueLabel: 'REP Available To Queue',
		repAmountLabel: COMMON_AMOUNT_LABEL,
		repBalanceChecklistLabel: 'Wallet REP balance covers the deposit amount',
		repBalanceShortageDetail: (amount: string) => `Need ${amount} more REP.`,
		repCollateralLabel: REP_COLLATERAL_LABEL,
		securityPoolRejectedActionDetail: 'The security pool rejected the action.',
		stagedOperationRetryDetail: STAGED_OPERATION_RETRY_DETAIL,
		tryAnotherPoolAddressDetail: 'Try another pool address.',
		repWithdrawalExecutedTitle: 'REP Withdrawal Executed',
		repWithdrawalFailedTitle: 'REP Withdrawal Failed',
		repWithdrawalRejectedDetail: 'The oracle manager attempted the withdrawal immediately, but the security pool rejected it.',
		repWithdrawalQueuedTitle: 'REP Withdrawal Queued',
		repWithdrawalSubmittedTitle: 'REP Withdrawal Submitted',
		redeemRepIdleLabel: 'Redeem REP',
		redeemRepPendingLabel: 'Redeeming REP...',
		redeemableRepChecklistLabel: 'The vault has redeemable REP',
		redeemableRepLabel: 'Redeemable REP',
		repExitRedeemDescription: 'Redeem the remaining REP collateral from this ended pool after escalation deposits are settled.',
		repExitWithdrawDescription: 'Queue a REP withdrawal after reviewing the current vault collateral and oracle status.',
		repWithdrawAmountLabel: 'REP Withdraw Amount',
		repWithdrawQueueDescription: 'Queue a REP withdrawal now, or let it execute immediately when a valid oracle price is already available.',
		selectedVaultDetailsUnavailableDetail: 'Selected vault details are unavailable.',
		securityPoolAddressLabel: COMMON_SECURITY_POOL_ADDRESS_LABEL,
		securityPoolAddressPlaceholder: COMMON_HEX_VALUE_PLACEHOLDER,
		securityBondAllowanceAmountLabel: 'Security Bond Allowance Amount',
		securityVaultTitle: 'Security Vault',
		setBondAllowanceActionDescription: 'Queue a new security bond allowance using the current oracle price context.',
		setBondAllowanceModalTitle: COMMON_SET_BOND_ALLOWANCE_LABEL,
		setBondAllowanceIdleLabel: COMMON_SET_BOND_ALLOWANCE_LABEL,
		setSecurityBondAllowanceIdleLabel: COMMON_SET_SECURITY_BOND_ALLOWANCE_LABEL,
		setSecurityBondAllowanceModalDescription: 'Queue a new bond allowance using the latest valid oracle price for the selected vault.',
		setSecurityBondAllowancePendingLabel: 'Queueing allowance update...',
		setSecurityBondAllowanceTitle: COMMON_SET_SECURITY_BOND_ALLOWANCE_LABEL,
		selectedVaultAddressLabel: 'Selected Vault Address',
		selectedVaultTitle: 'Selected Vault',
		stagedOperationLabel: 'Staged Operation',
		successfulImmediateBondAllowanceDetail: 'A valid oracle price was already available, so the new bond allowance executed immediately and no staged operation was created.',
		successfulImmediateWithdrawalDetail: 'A valid oracle price was already available, so the withdrawal executed immediately and no staged operation was created.',
		timeoutChecklistLabel: 'Manual execution timeout is at least 1 minute',
		allowanceChecklistLabel: (amount: string) => `Allowance amount is zero or at least ${amount} ETH`,
		validOraclePriceChecklistLabel: 'A valid oracle price is available',
		vaultLabel: 'Vault',
		vaultActionsTitle: 'Vault Actions',
		vaultLookupTitle: 'Vault Lookup',
		vaultLookupPlaceholder: COMMON_HEX_VALUE_PLACEHOLDER,
		vaultMissingBadgeLabel: 'Vault missing',
		vaultSummaryTitle: 'Vault Summary',
		viewInStagedOperationsLabel: COMMON_VIEW_IN_STAGED_OPERATIONS_LABEL,
		walletRepLabel: COMMON_WALLET_REP_LABEL,
		withdrawEscalationDepositsDetail: WITHDRAW_ESCALATION_DEPOSITS_DETAIL,
		withdrawFundingChecklistLabel: 'The vault still holds REP collateral to queue',
		withdrawableRepLabel: 'Withdrawable REP',
		withdrawRepIdleLabel: 'Withdraw REP',
		withdrawRepPendingLabel: 'Queueing REP withdrawal...',
	},
	tradingSection: {
		actionUnavailableReason: (actionLabel: string) => `${actionLabel} is not available right now.`,
		completeSetRedeemAmountLabel: 'Redeem Complete Sets Amount',
		connectWalletToMigrateSharesReason: 'Connect a wallet before migrating shares.',
		connectWalletToMintReason: 'Connect a wallet before minting complete sets.',
		connectWalletToRedeemCompleteSetsReason: 'Connect a wallet before redeeming complete sets.',
		connectWalletToRedeemSharesReason: 'Connect a wallet before redeeming shares.',
		loadWalletShareBalancesReason: 'Loading wallet share balances.',
		loadPoolToMigrateSharesReason: 'Load a pool before migrating shares.',
		loadPoolToMintReason: 'Load a pool before minting complete sets.',
		loadPoolToRedeemCompleteSetsReason: 'Load a pool before redeeming complete sets.',
		loadPoolToRedeemSharesReason: 'Load a pool before redeeming shares.',
		loadingForkTargetUniversesReason: 'Loading fork target universes.',
		refreshForkTargetUniversesReason: 'Refresh the fork target universes.',
		loadingMintCapacityReason: 'Loading mint capacity.',
		migrateForkedSharesActionLabel: 'Migrate forked shares',
		migrateForkedSharesDescription: 'Burn parent-pool shares for one outcome and recreate them across selected child universes.',
		migrateForkedSharesModalDescription: 'Migrating burns the selected parent-pool share balance and recreates it across the chosen child universes. Review the source outcome and target universes carefully before submitting.',
		migrateForkedSharesTitle: 'Migrate Forked Shares',
		migrateSharesIdleLabel: 'Migrate Shares',
		migrateSharesPendingLabel: 'Migrating shares...',
		marketAlreadyFinalizedReason: 'This market has already finalized.',
		mintCompleteSetsAmountLabel: 'Mint Complete Sets Amount',
		mintCompleteSetsActionLabel: 'Mint complete sets',
		mintCompleteSetsDescription: 'Lock collateral to mint a fresh Yes, No, and Invalid share set for this pool.',
		mintCompleteSetsModalDescription: 'Review available capacity and confirm the complete-set mint amount before submitting.',
		mintCompleteSetsPendingLabel: 'Minting complete sets...',
		mintCompleteSetsTitle: 'Mint Complete Sets',
		noMintCapacityRemainingReason: 'No mint capacity remaining.',
		noSharesAvailableToMigrateReason: (outcomeLabel: string) => `No ${outcomeLabel} shares available to migrate.`,
		redeemResolvedSharesModalDescription: 'Redeem finalized winning shares once the selected pool has resolved.',
		repBackingLabel: 'REP Backing',
		redeemCompleteSetsActionLabel: 'Redeem complete sets',
		redeemCompleteSetsDescription: 'Burn matching Yes, No, and Invalid shares to recover collateral from the current pool.',
		redeemCompleteSetsModalDescription: 'Redeeming complete sets requires matching yes, no, and invalid shares. Use the redeemable complete sets amount as the ceiling.',
		redeemCompleteSetsPendingLabel: 'Redeeming complete sets...',
		redeemCompleteSetsTitle: 'Redeem Complete Sets',
		redeemSharesActionLabel: 'Redeem resolved shares',
		redeemSharesDescription: 'Redeem final winning shares after the selected pool fully resolves.',
		redeemSharesIdleLabel: 'Redeem Shares',
		redeemSharesPendingLabel: 'Redeeming shares...',
		redeemSharesTitle: 'Redeem Resolved Shares',
		redeemableCompleteSetsDetail: 'Limited by your smallest Yes, No, or Invalid balance.',
		redeemableCompleteSetsLabel: 'Redeemable Complete Sets',
		bondAllowanceInUseLabel: 'Bond Allowance In Use',
		securityPoolAddressLabel: COMMON_SECURITY_POOL_ADDRESS_LABEL,
		shareBalancesNotLoadedMessage: 'Wallet balances are not loaded.',
		shareOutcomeInvalidLabel: COMMON_INVALID_LABEL,
		shareOutcomeNoLabel: COMMON_NO_LABEL,
		shareOutcomeYesLabel: COMMON_YES_LABEL,
		shareOutcomeToMigrateLabel: 'Share Outcome To Migrate',
		sharesSectionTitle: 'Shares',
		totalAcrossOutcomesLabel: 'Total Across Outcomes',
		waitForPoolToResolveReason: 'Wait for the selected pool to resolve before redeeming shares.',
		yourHoldingsTitle: 'Your Holdings',
		tradingRouteTitle: 'Trading',
	},
	tabNavigation: {
		applicationSectionsAriaLabel: 'Application sections',
		deployContractsFirstReason: 'Deploy the application contracts before using this section.',
		deployTabLabel: COMMON_DEPLOY_LABEL,
		marketsTabLabel: COMMON_MARKETS_LABEL,
		oracleReportsTabLabel: COMMON_ORACLE_REPORTS_LABEL,
		securityPoolsTabLabel: COMMON_SECURITY_POOLS_LABEL,
	},
	userCopy: {
		pageNotFound: {
			actionHint: 'Open one of the sections below.',
			badgeLabel: 'Page not found',
		},
		poolRegistry: {
			collection: {
				emptyActionHint: 'Create a pool from an exact Yes / No question to enable shares, reporting, and vault workflows.',
				emptyBadgeLabel: COMMON_NONE_LABEL,
				emptyDetail: 'No security pools are available in this universe.',
				loadingBadgeLabel: COMMON_LOADING_BADGE_LABEL,
				loadingDetail: 'Refreshing pools.',
				notCheckedBadgeLabel: COMMON_NOT_CHECKED_LABEL,
				notCheckedDetail: 'Load security pools to check what is available in this universe.',
			},
			selection: {
				loadingBadgeLabel: COMMON_LOADING_BADGE_LABEL,
				loadingDetail: COMMON_LOADING_LABEL,
				notCheckedBadgeLabel: COMMON_NOT_CHECKED_LABEL,
				notFoundBadgeLabel: COMMON_NOT_FOUND_LABEL,
			},
		},
		report: {
			loadingDetail: 'retrieving...',
			notCheckedBadgeLabel: COMMON_NOT_CHECKED_LABEL,
			notFoundBadgeLabel: COMMON_NOT_FOUND_LABEL,
			questionNoun: 'questions',
			refreshActionHintPrefix: COMMON_REFRESH_LABEL,
			refreshOrTryAnotherIdSuffix: 'or try another ID.',
			refreshToCheckIdSuffix: 'to check this ID.',
			reportNoun: 'reports',
		},
		universe: {
			goToGenesisUniverseActionHint: COMMON_GO_TO_GENESIS_UNIVERSE_LABEL,
			loadingBadgeLabel: COMMON_LOADING_BADGE_LABEL,
			loadingDetail: 'Loading universe details.',
			notCheckedBadgeLabel: COMMON_NOT_CHECKED_LABEL,
			notCheckedDetail: 'Choose a universe to continue.',
			notFoundBadgeLabel: COMMON_NOT_FOUND_LABEL,
			notFoundDetail: 'Choose another universe.',
		},
		wallet: {
			connectWalletBadgeLabel: COMMON_CONNECT_WALLET_LABEL,
			connectWalletDetail: 'Connect wallet to continue.',
			installWalletDetail: 'Install or enable a wallet to continue.',
			switchToMainnetDetail: 'Switch to Ethereum mainnet.',
			wrongNetworkBadgeLabel: COMMON_WRONG_NETWORK_LABEL,
		},
	},
} as const
