import type { Address, Hash } from '@zoltar/shared/ethereum';
import type { WriteOperationsParameters } from '../../../types/app.js';
import type { DeploymentStatus, ZoltarUniverseSummary } from '@zoltar/ui-core-shared/types/contracts.js';
type UseZoltarOperationsParameters = {
    accountAddress: Address | undefined;
    activeUniverseId: bigint;
    activeZoltarView: 'create' | 'fork' | 'migrate' | 'questions';
    autoLoadInitialData: boolean;
    deploymentStatuses: DeploymentStatus[];
    environmentRefreshKey: number;
    onTransactionFailed?: WriteOperationsParameters['onTransactionFailed'];
    onTransactionFinished: () => void;
    onTransactionPresented: WriteOperationsParameters['onTransactionPresented'];
    onTransactionPrepared?: WriteOperationsParameters['onTransactionPrepared'];
    onTransactionRequested: WriteOperationsParameters['onTransactionRequested'];
    onTransactionSubmitted: (hash: Hash) => void;
    refreshState: WriteOperationsParameters['refreshState'];
};
export declare function useZoltarOperations({ accountAddress, activeUniverseId, activeZoltarView, autoLoadInitialData, deploymentStatuses, environmentRefreshKey, onTransactionFailed, onTransactionFinished, onTransactionPresented, onTransactionPrepared, onTransactionRequested, onTransactionSubmitted, refreshState, }: UseZoltarOperationsParameters): {
    createChildUniverse: (outcomeIndex: bigint) => Promise<void>;
    migrateInternalRep: () => Promise<void>;
    prepareRepForMigration: () => Promise<void>;
    setZoltarMigrationForm: (updater: (current: import("../../../types/app.js").ZoltarMigrationFormState) => import("../../../types/app.js").ZoltarMigrationFormState) => void;
    zoltarMigrationActiveAction: "prepare" | "split" | undefined;
    zoltarMigrationError: string | undefined;
    zoltarMigrationFeedback: import("@zoltar/ui-core-shared/lib/actionFeedback.js").ActionFeedback<"addRepToMigrationBalance" | "splitMigrationRep"> | undefined;
    zoltarMigrationForm: import("../../../types/app.js").ZoltarMigrationFormState;
    zoltarMigrationPending: boolean;
    approveZoltarForkRep: (amount?: bigint) => Promise<void>;
    forkZoltar: () => Promise<void>;
    loadZoltarForkAccess: (universe?: ZoltarUniverseSummary | undefined) => Promise<void>;
    loadingZoltarForkAccess: boolean;
    zoltarForkActiveAction: "fork" | "approve" | undefined;
    zoltarForkApproval: import("@zoltar/ui-core-shared/lib/tokenApproval.js").TokenApprovalState;
    zoltarForkError: string | undefined;
    zoltarForkFeedback: import("@zoltar/ui-core-shared/lib/actionFeedback.js").ActionFeedback<"forkZoltar" | "approveForkRep"> | undefined;
    zoltarForkPending: boolean;
    zoltarForkQuestionId: string;
    zoltarForkRepBalanceAttoRep: bigint | undefined;
    zoltarForkResult: import("@zoltar/ui-core-shared/types/contracts.js").ZoltarForkActionResult | undefined;
    zoltarMigrationChildRepBalancesAttoRep: Record<string, bigint | undefined>;
    zoltarMigrationPreparedRepBalanceAttoRep: bigint | undefined;
    setZoltarForkQuestionId: (questionId: string) => void;
    ensureZoltarUniverse: () => Promise<ZoltarUniverseSummary>;
    hasLoadedZoltarQuestions: boolean;
    loadingZoltarQuestionCount: boolean;
    loadingZoltarQuestion: boolean;
    loadingZoltarQuestions: boolean;
    loadingZoltarUniverse: boolean;
    loadZoltarQuestionCount: () => Promise<void>;
    loadZoltarQuestion: (questionId: string) => Promise<void>;
    loadZoltarQuestionPage: (pageIndex: number, pageSize: number) => Promise<void>;
    loadZoltarQuestions: () => Promise<void>;
    loadZoltarUniverse: (options?: {
        clearCurrentState?: boolean;
    }) => Promise<ZoltarUniverseSummary | undefined>;
    zoltarChildUniverseFeedback: import("@zoltar/ui-core-shared/lib/actionFeedback.js").ActionFeedback<"createChildUniverse"> | undefined;
    refreshZoltarUniverse: () => Promise<ZoltarUniverseSummary | undefined>;
    zoltarChildUniverseError: string | undefined;
    zoltarChildUniversePendingOutcomeIndex: bigint | undefined;
    zoltarQuestionPage: import("@zoltar/ui-core-shared/types/contracts.js").MarketDetailsPage | undefined;
    zoltarQuestionCount: bigint | undefined;
    zoltarQuestionLookupError: string | undefined;
    zoltarQuestionLookupId: string | undefined;
    zoltarQuestions: import("@zoltar/ui-core-shared/types/contracts.js").MarketDetails[];
    zoltarQuestionsError: string | undefined;
    zoltarUniverse: ZoltarUniverseSummary | undefined;
    zoltarUniverseError: string | undefined;
    zoltarUniverseLoadedId: bigint | undefined;
    zoltarUniverseResolvedId: bigint | undefined;
    zoltarUniverseMissing: boolean;
};
export {};
//# sourceMappingURL=useZoltarOperations.d.ts.map