import type { Address, Hash } from '@zoltar/shared/ethereum';
import type { WriteOperationsParameters } from '../../../types/app.js';
import type { DeploymentStatus, ZoltarUniverseSummary } from '@zoltar/ui-core-shared/types/contracts.js';
type UseZoltarOperationsParameters = {
    accountAddress: Address | undefined;
    activeUniverseId: bigint;
    activeZoltarView: 'create' | 'fork' | 'migrate' | 'questions';
    autoLoadInitialData: boolean;
    deploymentStatuses: DeploymentStatus[];
    environmentRefreshKey: number;
    onTransactionFailed?: WriteOperationsParameters['onTransactionFailed'];
    onTransactionFinished: () => void;
    onTransactionPresented: WriteOperationsParameters['onTransactionPresented'];
    onTransactionPrepared?: WriteOperationsParameters['onTransactionPrepared'];
    onTransactionRequested: WriteOperationsParameters['onTransactionRequested'];
    onTransactionSubmitted: (hash: Hash) => void;
    refreshState: WriteOperationsParameters['refreshState'];
};
export declare function useZoltarOperations({ accountAddress, activeUniverseId, activeZoltarView, autoLoadInitialData, deploymentStatuses, environmentRefreshKey, onTransactionFailed, onTransactionFinished, onTransactionPresented, onTransactionPrepared, onTransactionRequested, onTransactionSubmitted, refreshState, }: UseZoltarOperationsParameters): {
    createChildUniverse: (outcomeIndex: bigint) => Promise<void>;
    migrateInternalRep: () => Promise<void>;
    prepareRepForMigration: () => Promise<void>;
    setZoltarMigrationForm: any;
    zoltarMigrationActiveAction: "prepare" | "split" | undefined;
    zoltarMigrationError: string | undefined;
    zoltarMigrationFeedback: any;
    zoltarMigrationForm: any;
    zoltarMigrationPending: boolean;
    approveZoltarForkRep: (amount?: bigint) => Promise<void>;
    forkZoltar: () => Promise<void>;
    loadZoltarForkAccess: (universe?: ZoltarUniverseSummary | undefined) => Promise<void>;
    loadingZoltarForkAccess: any;
    zoltarForkActiveAction: "fork" | "approve" | undefined;
    zoltarForkApproval: any;
    zoltarForkError: string | undefined;
    zoltarForkFeedback: any;
    zoltarForkPending: boolean;
    zoltarForkQuestionId: string;
    zoltarForkRepBalanceAttoRep: bigint | undefined;
    zoltarForkResult: any;
    zoltarMigrationChildRepBalancesAttoRep: Record<string, bigint | undefined>;
    zoltarMigrationPreparedRepBalanceAttoRep: bigint | undefined;
    setZoltarForkQuestionId: (questionId: string) => void;
    ensureZoltarUniverse: () => Promise<ZoltarUniverseSummary>;
    hasLoadedZoltarQuestions: boolean;
    loadingZoltarQuestionCount: any;
    loadingZoltarQuestion: any;
    loadingZoltarQuestions: any;
    loadingZoltarUniverse: any;
    loadZoltarQuestionCount: () => Promise<void>;
    loadZoltarQuestion: (questionId: string) => Promise<void>;
    loadZoltarQuestionPage: (pageIndex: number, pageSize: number) => Promise<void>;
    loadZoltarQuestions: () => Promise<void>;
    loadZoltarUniverse: (options?: {
        clearCurrentState?: boolean;
    }) => Promise<any>;
    zoltarChildUniverseFeedback: any;
    refreshZoltarUniverse: () => Promise<any>;
    zoltarChildUniverseError: string | undefined;
    zoltarChildUniversePendingOutcomeIndex: bigint | undefined;
    zoltarQuestionPage: any;
    zoltarQuestionCount: bigint | undefined;
    zoltarQuestionLookupError: string | undefined;
    zoltarQuestionLookupId: string | undefined;
    zoltarQuestions: MarketDetails[];
    zoltarQuestionsError: string | undefined;
    zoltarUniverse: any;
    zoltarUniverseError: string | undefined;
    zoltarUniverseLoadedId: bigint | undefined;
    zoltarUniverseResolvedId: bigint | undefined;
    zoltarUniverseMissing: boolean;
};
export {};
//# sourceMappingURL=useZoltarOperations.d.ts.map