import type { Address, Hash } from '@zoltar/shared/ethereum';
import { createZoltarChildUniverse, loadAllZoltarQuestions, loadMarketDetails, loadZoltarQuestionCount, loadZoltarQuestionPage, loadZoltarUniverseSummary } from '../../../protocol/index.js';
import { createConnectedReadClient, createWalletWriteClient } from '@zoltar/ui-core-shared/lib/clients.js';
import type { WriteOperationsParameters } from '../../../types/app.js';
import type { DeploymentStatus, ZoltarUniverseSummary } from '@zoltar/ui-core-shared/types/contracts.js';
type UseZoltarUniverseParameters = {
    accountAddress: Address | undefined;
    activeUniverseId: bigint;
    autoLoadInitialData: boolean;
    deploymentStatuses: DeploymentStatus[];
    environmentRefreshKey: number;
    onTransactionFailed?: WriteOperationsParameters['onTransactionFailed'];
    onTransactionFinished: () => void;
    onTransactionPresented: WriteOperationsParameters['onTransactionPresented'];
    onTransactionPrepared?: WriteOperationsParameters['onTransactionPrepared'];
    onTransactionRequested: WriteOperationsParameters['onTransactionRequested'];
    onTransactionSubmitted: (hash: Hash) => void;
};
export type UseZoltarUniverseDependencies = {
    createConnectedReadClient: typeof createConnectedReadClient;
    createWalletWriteClient: typeof createWalletWriteClient;
    createZoltarChildUniverse: typeof createZoltarChildUniverse;
    loadAllZoltarQuestions: typeof loadAllZoltarQuestions;
    loadMarketDetails: typeof loadMarketDetails;
    loadZoltarQuestionCount: typeof loadZoltarQuestionCount;
    loadZoltarQuestionPage: typeof loadZoltarQuestionPage;
    loadZoltarUniverseSummary: typeof loadZoltarUniverseSummary;
};
export declare function useZoltarUniverse({ accountAddress, activeUniverseId, autoLoadInitialData, deploymentStatuses, environmentRefreshKey, onTransactionFailed, onTransactionFinished, onTransactionPresented, onTransactionPrepared, onTransactionRequested, onTransactionSubmitted }: UseZoltarUniverseParameters, dependencies?: UseZoltarUniverseDependencies): {
    createChildUniverse: (outcomeIndex: bigint) => Promise<void>;
    ensureZoltarUniverse: () => Promise<ZoltarUniverseSummary>;
    hasLoadedZoltarQuestions: boolean;
    loadingZoltarQuestionCount: any;
    loadingZoltarQuestion: any;
    loadingZoltarQuestions: any;
    loadingZoltarUniverse: any;
    loadZoltarQuestionCount: () => Promise<void>;
    loadZoltarQuestion: (questionId: string) => Promise<void>;
    loadZoltarQuestionPage: (pageIndex: number, pageSize: number) => Promise<void>;
    loadZoltarQuestions: () => Promise<void>;
    loadZoltarUniverse: (options?: {
        clearCurrentState?: boolean;
    }) => Promise<any>;
    zoltarChildUniverseFeedback: any;
    refreshZoltarUniverse: () => Promise<any>;
    zoltarChildUniverseError: string | undefined;
    zoltarChildUniversePendingOutcomeIndex: bigint | undefined;
    zoltarQuestionPage: any;
    zoltarQuestionCount: bigint | undefined;
    zoltarQuestionLookupError: string | undefined;
    zoltarQuestionLookupId: string | undefined;
    zoltarQuestions: MarketDetails[];
    zoltarQuestionsError: string | undefined;
    zoltarUniverse: any;
    zoltarUniverseError: string | undefined;
    zoltarUniverseLoadedId: bigint | undefined;
    zoltarUniverseResolvedId: bigint | undefined;
    zoltarUniverseMissing: boolean;
};
export {};
//# sourceMappingURL=useZoltarUniverse.d.ts.map