import dependencySources from '../config/dependency-abi-sources.json'

// Only scanner names that differ from compiler names need an explicit alias.
const kindAliases: Readonly<Record<string, string>> = {
	ERC20Authorization: 'usdc',
	EscalationGameProofVerifier: 'escalationProofVerifier',
	OpenOraclePriceCoordinator: 'priceCoordinator',
	PriceOracleManagerAndOperatorQueuerFactory: 'priceCoordinatorFactory',
	TwoWayConstantProductFactory: 'ammFactory',
	TwoWayConstantProductPair: 'ammPair',
	UniformPriceDualCapBatchAuction: 'truthAuction',
	UniformPriceDualCapBatchAuctionFactory: 'truthAuctionFactory',
	WETH9: 'weth',
}

export function systemContractMappings(contractNames: readonly string[], deploymentIds: readonly string[]) {
	const interfaces: Record<string, { type: 'artifact'; name: string }> = {}
	const candidates = new Map<string, string>()
	const reservedKinds = new Set(['proxyDeployer', ...Object.keys(dependencySources)])
	for (const name of [...contractNames].sort()) {
		const kind = kindAliases[name] ?? `${name.slice(0, 1).toLowerCase()}${name.slice(1)}`
		if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) throw new Error(`Ambiguous compiled contract name: ${name}`)
		if (reservedKinds.has(kind)) throw new Error(`Compiled contract conflicts with a dependency or raw kind: ${kind}`)
		if (interfaces[kind] !== undefined) throw new Error(`Conflicting compiled contracts for kind: ${kind}`)
		interfaces[kind] = { type: 'artifact', name }
		for (const key of [name, kind].map(value => value.toLowerCase())) {
			const existing = candidates.get(key)
			if (existing !== undefined && existing !== kind) throw new Error(`Ambiguous deployment ABI match: ${key}`)
			candidates.set(key, kind)
		}
	}
	const deploymentKinds: Record<string, string> = {}
	for (const id of [...new Set(deploymentIds)].sort()) {
		if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(id)) throw new Error(`Invalid deployment ID: ${id}`)
		const kind = id === 'proxyDeployer' ? 'proxyDeployer' : candidates.get(id.toLowerCase())
		if (kind === undefined) throw new Error(`Unmapped deployment ID: ${id}`)
		deploymentKinds[id] = kind
	}
	return { interfaces, deploymentKinds }
}

export function serializeSystemContracts(mappings: ReturnType<typeof systemContractMappings>): string {
	const entries = Object.entries(mappings.interfaces).map(([kind, { name }]) => `\t${kind}: { type: 'artifact', name: '${name}' },`)
	return `// Generated by metadata:snapshot. Do not edit.\nexport const generatedSystemInterfaces = {\n${entries.join('\n')}\n} as const\n`
}
