// Generated by scripts/generate-open-oracle-arbitrager-abi.mts. Do not edit.
export const openOracleArbitrageExecutorAbi = [
	{
		type: 'event',
		name: 'HedgeAndDisputeExecuted',
		anonymous: false,
		inputs: [
			{
				name: 'account',
				type: 'address',
				internalType: 'address',
				indexed: true,
			},
			{
				name: 'reportId',
				type: 'uint256',
				internalType: 'uint256',
				indexed: true,
			},
			{
				name: 'boughtToken2',
				type: 'bool',
				internalType: 'bool',
				indexed: false,
			},
			{
				name: 'hedgeAmountToken2',
				type: 'uint256',
				internalType: 'uint256',
				indexed: false,
			},
			{
				name: 'hedgeAmountWeth',
				type: 'uint256',
				internalType: 'uint256',
				indexed: false,
			},
			{
				name: 'contribution1',
				type: 'uint256',
				internalType: 'uint256',
				indexed: false,
			},
			{
				name: 'contribution2',
				type: 'uint256',
				internalType: 'uint256',
				indexed: false,
			},
		],
	},
	{
		type: 'function',
		name: 'assertParentBlock',
		stateMutability: 'view',
		inputs: [
			{
				name: 'parentBlockNumber',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'expectedParentBlockHash',
				type: 'bytes32',
				internalType: 'bytes32',
			},
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'contributions',
		stateMutability: 'pure',
		inputs: [
			{
				name: 'game',
				type: 'tuple',
				internalType: 'struct IOpenOracleDispute.OracleGame',
				components: [
					{
						name: 'currentAmount1',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'currentAmount2',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'currentReporter',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'reportTimestamp',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'settlementTimestamp',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'token1',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'lastReportOppoTime',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'settlementTime',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'escalationHalt',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'protocolFeeRecipient',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'settlerReward',
						type: 'uint96',
						internalType: 'uint96',
					},
					{
						name: 'token2',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'numReports',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'disputeDelay',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'feePercentage',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'multiplier',
						type: 'uint16',
						internalType: 'uint16',
					},
					{
						name: 'callbackContract',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'callbackGasLimit',
						type: 'uint32',
						internalType: 'uint32',
					},
					{
						name: 'protocolFee',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'flags',
						type: 'uint8',
						internalType: 'uint8',
					},
				],
			},
			{
				name: 'newAmount1',
				type: 'uint128',
				internalType: 'uint128',
			},
			{
				name: 'newAmount2',
				type: 'uint128',
				internalType: 'uint128',
			},
		],
		outputs: [
			{
				name: 'contribution1',
				type: 'uint256',
				internalType: 'uint256',
			},
			{
				name: 'contribution2',
				type: 'uint256',
				internalType: 'uint256',
			},
		],
	},
	{
		type: 'function',
		name: 'dispute',
		stateMutability: 'nonpayable',
		inputs: [
			{
				name: 'openOracle',
				type: 'address',
				internalType: 'address',
			},
			{
				name: 'newAmount1',
				type: 'uint128',
				internalType: 'uint128',
			},
			{
				name: 'newAmount2',
				type: 'uint128',
				internalType: 'uint128',
			},
			{
				name: 'game',
				type: 'tuple',
				internalType: 'struct IOpenOracleDispute.OracleGame',
				components: [
					{
						name: 'currentAmount1',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'currentAmount2',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'currentReporter',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'reportTimestamp',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'settlementTimestamp',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'token1',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'lastReportOppoTime',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'settlementTime',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'escalationHalt',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'protocolFeeRecipient',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'settlerReward',
						type: 'uint96',
						internalType: 'uint96',
					},
					{
						name: 'token2',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'numReports',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'disputeDelay',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'feePercentage',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'multiplier',
						type: 'uint16',
						internalType: 'uint16',
					},
					{
						name: 'callbackContract',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'callbackGasLimit',
						type: 'uint32',
						internalType: 'uint32',
					},
					{
						name: 'protocolFee',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'flags',
						type: 'uint8',
						internalType: 'uint8',
					},
				],
			},
			{
				name: 'helper',
				type: 'tuple',
				internalType: 'struct IOpenOracleDispute.PreimageHelper',
				components: [
					{
						name: 'reportId',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'creator',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'blockTimestamp',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockNumber',
						type: 'uint256',
						internalType: 'uint256',
					},
				],
			},
			{
				name: 'timing',
				type: 'tuple',
				internalType: 'struct IOpenOracleDispute.TimingBoundaries',
				components: [
					{
						name: 'blockNumber',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockNumberBound',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockTimestamp',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockTimestampBound',
						type: 'uint256',
						internalType: 'uint256',
					},
				],
			},
		],
		outputs: [],
	},
	{
		type: 'function',
		name: 'hedgeAndDispute',
		stateMutability: 'nonpayable',
		inputs: [
			{
				name: 'request',
				type: 'tuple',
				internalType: 'struct OpenOracleArbitrageExecutor.HedgeRequest',
				components: [
					{
						name: 'openOracle',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'router',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'poolFee',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'newAmount1',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'newAmount2',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'hedgeWethLimit',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'swapDeadline',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'expectedParentBlockHash',
						type: 'bytes32',
						internalType: 'bytes32',
					},
				],
			},
			{
				name: 'game',
				type: 'tuple',
				internalType: 'struct IOpenOracleDispute.OracleGame',
				components: [
					{
						name: 'currentAmount1',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'currentAmount2',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'currentReporter',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'reportTimestamp',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'settlementTimestamp',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'token1',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'lastReportOppoTime',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'settlementTime',
						type: 'uint48',
						internalType: 'uint48',
					},
					{
						name: 'escalationHalt',
						type: 'uint128',
						internalType: 'uint128',
					},
					{
						name: 'protocolFeeRecipient',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'settlerReward',
						type: 'uint96',
						internalType: 'uint96',
					},
					{
						name: 'token2',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'numReports',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'disputeDelay',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'feePercentage',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'multiplier',
						type: 'uint16',
						internalType: 'uint16',
					},
					{
						name: 'callbackContract',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'callbackGasLimit',
						type: 'uint32',
						internalType: 'uint32',
					},
					{
						name: 'protocolFee',
						type: 'uint24',
						internalType: 'uint24',
					},
					{
						name: 'flags',
						type: 'uint8',
						internalType: 'uint8',
					},
				],
			},
			{
				name: 'helper',
				type: 'tuple',
				internalType: 'struct IOpenOracleDispute.PreimageHelper',
				components: [
					{
						name: 'reportId',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'creator',
						type: 'address',
						internalType: 'address',
					},
					{
						name: 'blockTimestamp',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockNumber',
						type: 'uint256',
						internalType: 'uint256',
					},
				],
			},
			{
				name: 'timing',
				type: 'tuple',
				internalType: 'struct IOpenOracleDispute.TimingBoundaries',
				components: [
					{
						name: 'blockNumber',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockNumberBound',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockTimestamp',
						type: 'uint256',
						internalType: 'uint256',
					},
					{
						name: 'blockTimestampBound',
						type: 'uint256',
						internalType: 'uint256',
					},
				],
			},
		],
		outputs: [],
	},
] as const
