import type { Address, Hash } from '@zoltar/shared/ethereum';
import type { ActionFeedback } from '@zoltar/ui-core-shared/lib/actionFeedback.js';
import { createMarketParameters } from '../lib/marketCreation.js';
import type { MarketFormState, WriteOperationsParameters } from '../../../types/app.js';
import type { DeploymentStatus, MarketCreationResult } from '@zoltar/ui-core-shared/types/contracts.js';
type UseMarketCreationParameters = {
    accountAddress: Address | undefined;
    activeUniverseId: bigint;
    activeZoltarView: 'create' | 'fork' | 'migrate' | 'questions';
    autoLoadInitialData: boolean;
    deploymentStatuses: DeploymentStatus[];
    environmentRefreshKey: number;
    onTransactionFailed?: WriteOperationsParameters['onTransactionFailed'];
    onTransactionFinished: () => void;
    onTransactionPresented: WriteOperationsParameters['onTransactionPresented'];
    onTransactionPrepared?: WriteOperationsParameters['onTransactionPrepared'];
    onTransactionRequested: WriteOperationsParameters['onTransactionRequested'];
    onTransactionSubmitted: (hash: Hash) => void;
    refreshState: WriteOperationsParameters['refreshState'];
};
export type UseMarketCreationDependencies = {
    createMarket: (accountAddress: Address, callbacks: {
        onTransactionPrepared?: WriteOperationsParameters['onTransactionPrepared'];
        onTransactionSubmitted: (hash: Hash) => void;
    }, parameters: ReturnType<typeof createMarketParameters>) => Promise<MarketCreationResult & {
        hash: Hash;
    }>;
};
export declare function useMarketCreation({ accountAddress, activeUniverseId, activeZoltarView, autoLoadInitialData, deploymentStatuses, environmentRefreshKey, onTransactionFailed, onTransactionFinished, onTransactionPresented, onTransactionPrepared, onTransactionRequested, onTransactionSubmitted, refreshState }: UseMarketCreationParameters, dependencies?: UseMarketCreationDependencies): {
    createMarket: () => Promise<void>;
    marketFeedback: ActionFeedback<"createMarket"> | undefined;
    marketCreating: boolean;
    marketError: string | undefined;
    marketForm: MarketFormState;
    marketResult: MarketCreationResult | undefined;
    resetMarket: () => void;
    setMarketForm: (updater: (current: MarketFormState) => MarketFormState) => void;
    createChildUniverse: (outcomeIndex: bigint) => Promise<void>;
    migrateInternalRep: () => Promise<void>;
    prepareRepForMigration: () => Promise<void>;
    setZoltarMigrationForm: (updater: (current: import("@zoltar/ui-zoltar/types/app.js").ZoltarMigrationFormState) => import("@zoltar/ui-zoltar/types/app.js").ZoltarMigrationFormState) => void;
    zoltarMigrationActiveAction: "prepare" | "split" | undefined;
    zoltarMigrationError: string | undefined;
    zoltarMigrationFeedback: import("@zoltar/ui-core-shared/lib/actionFeedback.js").ActionFeedback<"addRepToMigrationBalance" | "splitMigrationRep"> | undefined;
    zoltarMigrationForm: import("@zoltar/ui-zoltar/types/app.js").ZoltarMigrationFormState;
    zoltarMigrationPending: boolean;
    approveZoltarForkRep: (amount?: bigint) => Promise<void>;
    forkZoltar: () => Promise<void>;
    loadZoltarForkAccess: (universe?: import("@zoltar/ui-core-shared/types/contracts.js").ZoltarUniverseSummary | undefined) => Promise<void>;
    loadingZoltarForkAccess: boolean;
    zoltarForkActiveAction: "fork" | "approve" | undefined;
    zoltarForkApproval: import("@zoltar/ui-core-shared/lib/tokenApproval.js").TokenApprovalState;
    zoltarForkError: string | undefined;
    zoltarForkFeedback: import("@zoltar/ui-core-shared/lib/actionFeedback.js").ActionFeedback<"forkZoltar" | "approveForkRep"> | undefined;
    zoltarForkPending: boolean;
    zoltarForkQuestionId: string;
    zoltarForkRepBalanceAttoRep: bigint | undefined;
    zoltarForkResult: import("@zoltar/ui-core-shared/types/contracts.js").ZoltarForkActionResult | undefined;
    zoltarMigrationChildRepBalancesAttoRep: Record<string, bigint | undefined>;
    zoltarMigrationPreparedRepBalanceAttoRep: bigint | undefined;
    setZoltarForkQuestionId: (questionId: string) => void;
    ensureZoltarUniverse: () => Promise<import("@zoltar/ui-core-shared/types/contracts.js").ZoltarUniverseSummary>;
    hasLoadedZoltarQuestions: boolean;
    loadingZoltarQuestionCount: boolean;
    loadingZoltarQuestion: boolean;
    loadingZoltarQuestions: boolean;
    loadingZoltarUniverse: boolean;
    loadZoltarQuestionCount: () => Promise<void>;
    loadZoltarQuestion: (questionId: string) => Promise<void>;
    loadZoltarQuestionPage: (pageIndex: number, pageSize: number) => Promise<void>;
    loadZoltarQuestions: () => Promise<void>;
    loadZoltarUniverse: (options?: {
        clearCurrentState?: boolean;
    }) => Promise<import("@zoltar/ui-core-shared/types/contracts.js").ZoltarUniverseSummary | undefined>;
    zoltarChildUniverseFeedback: import("@zoltar/ui-core-shared/lib/actionFeedback.js").ActionFeedback<"createChildUniverse"> | undefined;
    refreshZoltarUniverse: () => Promise<import("@zoltar/ui-core-shared/types/contracts.js").ZoltarUniverseSummary | undefined>;
    zoltarChildUniverseError: string | undefined;
    zoltarChildUniversePendingOutcomeIndex: bigint | undefined;
    zoltarQuestionPage: import("@zoltar/ui-core-shared/types/contracts.js").MarketDetailsPage | undefined;
    zoltarQuestionCount: bigint | undefined;
    zoltarQuestionLookupError: string | undefined;
    zoltarQuestionLookupId: string | undefined;
    zoltarQuestions: import("@zoltar/ui-core-shared/types/contracts.js").MarketDetails[];
    zoltarQuestionsError: string | undefined;
    zoltarUniverse: import("@zoltar/ui-core-shared/types/contracts.js").ZoltarUniverseSummary | undefined;
    zoltarUniverseError: string | undefined;
    zoltarUniverseLoadedId: bigint | undefined;
    zoltarUniverseResolvedId: bigint | undefined;
    zoltarUniverseMissing: boolean;
};
export {};
//# sourceMappingURL=useMarketCreation.d.ts.map