import type { Address, Hash } from '@zoltar/shared/ethereum';
import { loadAllSecurityPools, loadCoordinatorInitialReportFundingRequirement, loadOracleManagerDetails, queueSecurityPoolLiquidation } from '../../../protocol/index.js';
import { createWalletWriteClient } from '@zoltar/ui-core-shared/lib/clients.js';
import type { ActionFeedback } from '@zoltar/ui-core-shared/lib/actionFeedback.js';
import type { WriteOperationsParameters } from '../../../types/app.js';
import type { LiquidationApprovalDetails, LiquidationFundingPreview, ListedSecurityPool, SecurityPoolBrowsePage, SecurityPoolOverviewActionResult, SecurityPoolPage, SecurityPoolVaultSummary } from '@zoltar/ui-core-shared/types/contracts.js';
type UseSecurityPoolsOverviewParameters = {
    accountAddress: Address | undefined;
    environmentRefreshKey: number;
    onTransactionCanceled?: WriteOperationsParameters['onTransactionCanceled'];
    onTransactionFailed?: WriteOperationsParameters['onTransactionFailed'];
    onTransactionFinished: () => void;
    onTransactionPresented: WriteOperationsParameters['onTransactionPresented'];
    onTransactionPrepared?: WriteOperationsParameters['onTransactionPrepared'];
    onTransactionRequested: WriteOperationsParameters['onTransactionRequested'];
    onTransactionSubmitted: (hash: Hash) => void;
    refreshState: WriteOperationsParameters['refreshState'];
};
type SecurityPoolsOverviewReadClient = {
    getBalance: (parameters: {
        address: Address;
    }) => Promise<bigint>;
};
type SecurityPoolsOverviewProductionWriteClient = ReturnType<typeof createWalletWriteClient>;
type LoadAllSecurityPoolsOptions = Parameters<typeof loadAllSecurityPools>[1];
type SecurityPoolLiquidationQueueResult = Awaited<ReturnType<typeof queueSecurityPoolLiquidation>>;
export type UseSecurityPoolsOverviewDependencies<TWriteClient = SecurityPoolsOverviewProductionWriteClient> = {
    createConnectedReadClient: () => SecurityPoolsOverviewReadClient;
    createWalletWriteClient: (walletAddress: Address, callbacks?: Parameters<typeof createWalletWriteClient>[1]) => TWriteClient;
    loadAllSecurityPools: (options: LoadAllSecurityPoolsOptions) => Promise<ListedSecurityPool[]>;
    loadCoordinatorInitialReportFundingRequirement: (client: TWriteClient, managerAddress: Address, walletAddress: Address) => Promise<Awaited<ReturnType<typeof loadCoordinatorInitialReportFundingRequirement>>>;
    loadLiquidationApproval: (managerAddress: Address, approvalId: Hash) => Promise<LiquidationApprovalDetails>;
    loadSecurityPoolVaultSummary: (securityPoolAddress: Address, vaultAddress: Address) => Promise<SecurityPoolVaultSummary>;
    loadOracleManagerDetails: (managerAddress: Address) => Promise<Awaited<ReturnType<typeof loadOracleManagerDetails>>>;
    loadOracleManagerQueueOperationEthValue: (client: TWriteClient, managerAddress: Address) => Promise<bigint>;
    loadSecurityPoolPage: (pageIndex: number, pageSize: number, accountAddress: Address | undefined) => Promise<SecurityPoolPage>;
    queueSecurityPoolLiquidation: (client: TWriteClient, managerAddress: Address, targetVault: Address, amount: bigint, validForSeconds: bigint, requestedInitialAttoWeth?: bigint, receiverVault?: Address, approvalId?: Hash) => Promise<SecurityPoolLiquidationQueueResult>;
    waitForSecurityPoolReadBackend: () => Promise<void>;
};
export declare function shouldFallbackToAllSecurityPoolsPage(error: unknown): boolean;
export declare function createSecurityPoolPageFromLoadedPools(pools: ListedSecurityPool[], pageIndex: number, pageSize: number): SecurityPoolPage;
declare function useSecurityPoolsOverviewWithDependencies<TWriteClient>({ accountAddress, environmentRefreshKey, onTransactionCanceled, onTransactionFailed, onTransactionFinished, onTransactionPresented, onTransactionPrepared, onTransactionRequested, onTransactionSubmitted, refreshState }: UseSecurityPoolsOverviewParameters, dependencies: UseSecurityPoolsOverviewDependencies<TWriteClient>): {
    liquidationDebtEthAmount: string;
    maximumLiquidationDebtAttoEth: bigint | undefined;
    liquidationManagerAddress: `0x${string}` | undefined;
    liquidationFundingPreview: LiquidationFundingPreview | undefined;
    liquidationFundingPreviewError: string | undefined;
    liquidationModalOpen: boolean;
    liquidationTargetVault: string;
    liquidationReceiverVault: string;
    liquidationApprovalId: string;
    liquidationApprovalDetails: LiquidationApprovalDetails | undefined;
    liquidationApprovalError: string | undefined;
    liquidationReceiverVaultSummary: SecurityPoolVaultSummary | undefined;
    liquidationReceiverVaultSummaryError: string | undefined;
    liquidationReceiverVaultSummaryResolved: boolean;
    liquidationTimeoutMinutes: string;
    checkedSecurityPoolAddress: string | undefined;
    hasLoadedSecurityPools: boolean;
    securityPoolsLoadedEnvironmentRefreshKey: number | undefined;
    hasLoadedSecurityPoolPage: boolean;
    liquidationSecurityPoolAddress: `0x${string}` | undefined;
    loadingSecurityPoolPage: boolean;
    loadingSecurityPools: boolean;
    loadingLiquidationFundingPreview: boolean;
    loadingLiquidationApproval: boolean;
    loadingLiquidationReceiverVaultSummary: boolean;
    closeLiquidationModal: () => void;
    loadBrowseSecurityPoolPage: (pageIndex: number, pageSize: number, requestKey: string) => Promise<void>;
    loadLiquidationFundingPreview: (managerAddress: Address) => Promise<boolean>;
    loadLiquidationApproval: () => Promise<boolean>;
    loadLiquidationReceiverVaultSummary: () => Promise<boolean>;
    openLiquidationModal: (managerAddress: Address, securityPoolAddress: Address, vaultAddress: Address, maxAmount: bigint | undefined) => void;
    queueLiquidation: (managerAddress: Address, securityPoolAddress: Address) => Promise<void>;
    securityPoolOverviewActiveAction: "queueLiquidation" | undefined;
    securityPoolOverviewError: string | undefined;
    securityPoolsLoadError: string | undefined;
    securityPoolsLoadErrorEnvironmentRefreshKey: number | undefined;
    securityPoolLiquidationError: string | undefined;
    securityPoolOverviewFeedback: ActionFeedback<"queueLiquidation"> | undefined;
    securityPoolOverviewResult: SecurityPoolOverviewActionResult | undefined;
    securityPoolBrowseCount: bigint | undefined;
    securityPoolPage: SecurityPoolBrowsePage | undefined;
    securityPools: ListedSecurityPool[];
    setLiquidationAmount: (value: string) => void;
    setLiquidationTimeoutMinutes: (value: string) => void;
    setLiquidationTargetVault: (value: string) => void;
    setLiquidationReceiverVault: (value: string) => void;
    setLiquidationApprovalId: (value: string) => void;
    loadSecurityPools: (securityPoolAddress?: string) => Promise<boolean>;
};
export declare function useSecurityPoolsOverview(parameters: UseSecurityPoolsOverviewParameters): ReturnType<typeof useSecurityPoolsOverviewWithDependencies<SecurityPoolsOverviewProductionWriteClient>>;
export declare function useSecurityPoolsOverview<TWriteClient>(parameters: UseSecurityPoolsOverviewParameters, dependencies: UseSecurityPoolsOverviewDependencies<TWriteClient>): ReturnType<typeof useSecurityPoolsOverviewWithDependencies<TWriteClient>>;
export {};
//# sourceMappingURL=useSecurityPoolsOverview.d.ts.map