import { readFile } from 'node:fs/promises'
import path from 'node:path'
import solc from 'solc'

const projectRoot = path.resolve(import.meta.dir, '..')
const repositoryRoot = path.resolve(projectRoot, '..', '..')
const outputPath = path.join(projectRoot, 'src', 'contracts', 'artifacts.generated.ts')
const harnessOutputPath = path.join(projectRoot, 'tests', 'contracts', 'harness-artifacts.generated.ts')
const entrypoints = ['open-oracle-arbitrager/contracts/OpenOracleArbitrageExecutor.sol', 'open-oracle-arbitrager/contracts/test/OpenOracleArbitrageExecutorHarnesses.sol'] as const

type CompilerContract = {
	abi?: unknown
	evm?: {
		bytecode?: {
			object?: unknown
		}
		deployedBytecode?: {
			object?: unknown
		}
	}
}

type CompilerOutput = {
	contracts?: Record<string, Record<string, CompilerContract>>
	errors?: readonly {
		formattedMessage?: string
		severity?: string
	}[]
}

const sources: Record<string, { content: string }> = {}
const importPattern = /import\s+(?:[^'"]*?\s+from\s+)?['"]([^'"]+)['"]\s*;/g

async function addSource(sourceName: string): Promise<void> {
	const normalizedName = path.posix.normalize(sourceName)
	if (sources[normalizedName] !== undefined) return
	const physicalName = normalizedName.startsWith('open-oracle-arbitrager/') ? path.posix.join('bots', normalizedName) : normalizedName
	const content = await readFile(path.join(repositoryRoot, physicalName), 'utf8')
	sources[normalizedName] = { content }
	for (const match of content.matchAll(importPattern)) {
		const importedName = match[1]
		if (importedName === undefined) continue
		if (!importedName.startsWith('.')) throw new Error(`Unsupported non-relative Solidity import ${importedName} in ${normalizedName}`)
		await addSource(path.posix.join(path.posix.dirname(normalizedName), importedName))
	}
}

for (const entrypoint of entrypoints) await addSource(entrypoint)

const input = {
	language: 'Solidity',
	settings: {
		evmVersion: 'osaka',
		viaIR: true,
		optimizer: {
			enabled: true,
			runs: 200,
		},
		outputSelection: {
			'*': {
				'*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'],
			},
		},
	},
	sources,
}

const output = JSON.parse(solc.compile(JSON.stringify(input))) as CompilerOutput
const errors = output.errors?.filter(error => error.severity === 'error') ?? []
if (errors.length !== 0) throw new Error(errors.map(error => error.formattedMessage ?? 'Unknown Solidity compiler error').join('\n'))

const artifactNames = [['executorArtifact', entrypoints[0], 'OpenOracleArbitrageExecutor']] as const
const harnessArtifactNames = [
	['targetArtifact', entrypoints[1], 'OpenOracleArbitrageExecutorTarget'],
	['feeTokenArtifact', entrypoints[1], 'OpenOracleFeeToken'],
	['routerArtifact', entrypoints[1], 'OpenOracleSwapRouterTarget'],
	['tokenArtifact', entrypoints[1], 'OpenOracleTestToken'],
	['v4PoolManagerArtifact', entrypoints[1], 'OpenOracleV4PoolManagerTarget'],
	['wethArtifact', entrypoints[1], 'OpenOracleWethTarget'],
] as const

function artifactExports(names: readonly (readonly [string, string, string])[]) {
	return names.map(([exportName, sourceName, contractName]) => {
		const contract = output.contracts?.[sourceName]?.[contractName]
		if (!Array.isArray(contract?.abi) || typeof contract.evm?.bytecode?.object !== 'string' || typeof contract.evm?.deployedBytecode?.object !== 'string') {
			throw new Error(`Missing compiled artifact ${sourceName}:${contractName}`)
		}
		return `export const ${exportName} = ${JSON.stringify({ abi: contract.abi, evm: { bytecode: { object: contract.evm.bytecode.object }, deployedBytecode: { object: contract.evm.deployedBytecode.object } } }, undefined, '\t')} as const`
	})
}

async function formatGenerated(filePath: string, exports: readonly string[]) {
	const unformatted = `${['// Generated by scripts/compile-contracts.mts. Do not edit.', ...exports].join('\n\n')}\n`
	const formatter = Bun.spawnSync(['bunx', '@biomejs/biome', 'format', '--stdin-file-path', filePath], {
		stderr: 'pipe',
		stdin: Buffer.from(unformatted),
		stdout: 'pipe',
	})
	if (!formatter.success) throw new Error(`Could not format generated contract artifacts: ${formatter.stderr.toString()}`)
	return formatter.stdout.toString()
}

const generatedOutputs = [
	[outputPath, await formatGenerated(outputPath, artifactExports(artifactNames))],
	[harnessOutputPath, await formatGenerated(harnessOutputPath, artifactExports(harnessArtifactNames))],
] as const

for (const [filePath, generated] of generatedOutputs) {
	if (process.argv.includes('--check')) {
		const current = await readFile(filePath, 'utf8').catch(error => {
			throw new Error(`Generated contract artifacts are missing: ${error instanceof Error ? error.message : String(error)}`)
		})
		if (current !== generated) throw new Error(`Generated contract artifacts ${path.relative(projectRoot, filePath)} are stale; run bun run compile-contracts`)
	} else {
		await Bun.write(filePath, generated)
	}
}
