/// <reference types='bun-types' />

import { describe, expect, test } from 'bun:test'

describe('documented protocol constants', () => {
	test('keeps Placeholder OpenOracle timing constants aligned with the implementation', async () => {
		const whitepaper = await Bun.file('docs/whitepaper_placeholder.html').text()
		const openOracleIntegration = await Bun.file('docs/openOracleIntegration.html').text()

		expect(whitepaper).toContain('PRICE_VALID_FOR_SECONDS = 5 minutes')
		expect(whitepaper).toMatch(/<td><code>PRICE_VALID_FOR_SECONDS<\/code><\/td>\s*<td><code>5 minutes<\/code><\/td>/)
		expect(whitepaper).toMatch(/OpenOracle <code>settlementTime<\/code><\/td>\s*<td>\s*<math aria-label="40 times 12" data-source="40 \\cdot 12"/)
		expect(whitepaper).toContain('<code>480 seconds (8 minutes)</code>')
		expect(whitepaper).toMatch(/the configured OpenOracle <code>timeType<\/code> uses\s+seconds/)
		expect(openOracleIntegration).toContain('<code>480 seconds (8 minutes)</code>')
		expect(openOracleIntegration).toMatch(/the configured OpenOracle <code>timeType<\/code> uses seconds/)
		expect(whitepaper).not.toContain('PRICE_VALID_FOR_SECONDS = 1 hour')
		expect(whitepaper).not.toContain('Settlement delay encoded as <code>15 \\cdot 12</code>.')
	})

	test('keeps Placeholder REP-denominated docs constants explicit', async () => {
		const whitepaper = await Bun.file('docs/whitepaper_placeholder.html').text()

		expect(whitepaper).toContain('<code>1 REP</code> default deployment value')
		expect(whitepaper).toMatch(/<td><code>initialEscalationGameDeposit<\/code><\/td>\s*<td><code>1 REP<\/code> default<\/td>/)
		expect(whitepaper).toContain('<code>1000000000000000000</code> atomic REP units')
		expect(whitepaper).not.toMatch(/initialEscalationGameDeposit[\s\S]{0,200}<code>1 ether<\/code>/)
	})

	test('keeps REP/ETH tooltip aliases aligned on price direction', async () => {
		const protocolTerms = await Bun.file('docs/protocolTerms.js').text()

		expect(protocolTerms).toContain('const repEthPriceDefinition')
		expect(protocolTerms).toContain('The REP cost of 1 ETH')
		expect(protocolTerms).toContain('A higher value means ETH is more expensive in REP terms')
		expect(protocolTerms).toContain('A delayed action that cannot run until the coordinator has a fresh REP/ETH price.')
		expect(protocolTerms).toContain('A Zoltar truth branch. Each universe has its own REP token and may have a parent universe.')
		expect(protocolTerms).toContain('A timed sale with fixed rules.')
		expect(protocolTerms).toContain('A REP-backed underwriting pool for one question in one universe.')
		expect(protocolTerms).toContain("'bond allowance': 'The amount of REP-backed security-bond exposure a vault currently permits.'")
		expect(protocolTerms).toContain("'security-bond allowance': 'The current amount of REP-backed exposure a vault allows the pool or coordinator to use.'")
		expect(protocolTerms).toContain('A holder can reproduce it into selected child universes; each child can receive up to the source balance.')
		expect(protocolTerms).toContain('when holders can reproduce migration balance into selected child REP')
		expect(protocolTerms).toMatch(/splitMigrationRep: 'The Zoltar function that mints a chosen amount of child REP in each selected child universe, capped per child by the caller migration balance\. This is reproduction, not pro-rata splitting\.'/)
		expect(protocolTerms).toContain("'split migration rep': 'The action that mints a chosen amount of child REP in each selected child universe, capped per child by the caller migration balance. This is reproduction, not pro-rata splitting.'")
		expect(protocolTerms).toContain('The REP/ETH price above which a vault can become liquidatable, after the configured distance check.')
		expect(protocolTerms).toContain('The REP/ETH price above which the modeled liquidation path can become executable, after the configured distance check.')
		expect(protocolTerms).toContain("'binary censorship bound': 'A simple attack-cost check for yes/no liquidation payoffs. The attacker only gains if the bad report is strictly above the liquidation threshold and satisfies the configured distance check.'")
		expect(protocolTerms).toContain("'binary dynamic programming terminal': 'The final payoff rule in the simplified delay model. The attacker is paid only if the manipulated price is strictly above the liquidation threshold and satisfies the configured distance check.'")
		expect(protocolTerms).toContain("'staged liquidation': 'A delayed liquidation that runs only if a fresh price is strictly above the liquidation threshold and satisfies the configured distance check.'")
		expect(protocolTerms).toMatch(/repPerEthPrice: repEthPriceDefinition/)
		expect(protocolTerms).toMatch(/'rep\/eth price': repEthPriceDefinition/)
	})

	test('keeps educational entry points and auction design in HTML docs', async () => {
		const readme = await Bun.file('README.md').text()
		const startHere = await Bun.file('docs/start-here.html').text()
		const auctionDesign = await Bun.file('docs/auction-design.html').text()
		const openOracleIntegration = await Bun.file('docs/openOracleIntegration.html').text()
		const placeholder = await Bun.file('docs/whitepaper_placeholder.html').text()

		expect(readme).toContain('./docs/start-here.html')
		expect(readme).toContain('./docs/auction-design.html')
		expect(startHere).toContain('Placeholder and Zoltar Start Here')
		expect(startHere).toContain('One Example Market End to End')
		expect(startHere).toContain('Concept Glossary by Lifecycle Stage')
		expect(startHere).toContain('Start with these words')
		expect(startHere).toContain('A <em>universe</em> is a Zoltar truth branch')
		expect(startHere.indexOf('Start with these words')).toBeLessThan(startHere.indexOf('The core idea is split responsibility'))
		expect(startHere.indexOf('<em>migration balance</em>')).toBeLessThan(startHere.indexOf('<em>child REP</em> is REP minted'))
		expect(startHere).toContain('reproduced into selected fork branches')
		expect(startHere).toMatch(/each branch receiving at\s+most that source balance/)
		expect(startHere).toMatch(/Reproduce parent-universe migration balance[\s\S]*each\s+child capped by the source balance/)
		expect(startHere).toMatch(/the\s+amount of REP-backed exposure they permit/)
		expect(startHere).toMatch(/the REP value\s+available after a fork/)
		expect(startHere).toContain('fig-start-here-lifecycle')
		expect(startHere).toContain('eq-start-here-complete-set')
		expect(startHere).toContain('Why it exists')
		expect(auctionDesign).toContain('Uniform Price Dual Cap Batch Auction')
		expect(auctionDesign).toContain('Why This Auction Exists')
		expect(auctionDesign).toMatch(/A <em>fork<\/em> is\s+the split/)
		expect(auctionDesign).toMatch(/A\s+<em>child pool<\/em> is\s+the market pool in one fork branch/)
		expect(auctionDesign).toMatch(/A\s+<em>truth auction<\/em> is a sale that\s+repairs a child pool after a\s+fork/)
		expect(auctionDesign.search(/A\s+<em>fork<\/em>/)).toBeLessThan(auctionDesign.search(/A\s+<em>fork branch<\/em>/))
		expect(auctionDesign.search(/A\s+<em>child pool<\/em>/)).toBeLessThan(auctionDesign.search(/A\s+<em>truth auction<\/em>/))
		expect(auctionDesign.search(/A\s+<em>truth auction<\/em>/)).toBeLessThan(auctionDesign.indexOf('<code>SecurityPoolForker</code> uses this auction'))
		expect(auctionDesign).toContain('<em>child-universe REP</em> is REP minted inside that branch')
		expect(auctionDesign).toContain('same-tick bids fill FIFO by submission order')
		expect(auctionDesign).toContain('Try a simple auction clearing run')
		expect(auctionDesign).toContain('fig-auction-lifecycle')
		expect(auctionDesign).toContain('eq-auction-rep-won')
		expect(auctionDesign).toContain('underfundedWinningEth')
		expect(auctionDesign).toContain('minBidSize = max(ethRaiseCap / 100000, 1 wei)')
		expect(auctionDesign).toContain('const activeBids = bids.filter((bid) => bid.eth > 0)')
		expect(openOracleIntegration).toMatch(/current REP\/ETH price is\s+strictly above that threshold and at least the configured\s+<span class="term" tabindex="0">liquidation distance<\/span> beyond it/)
		expect(openOracleIntegration).toMatch(/manipulated REP\/ETH price is strictly above\s+the liquidation threshold and satisfies the configured liquidation\s+distance check/)
		expect(openOracleIntegration).not.toContain('crosses the liquidation threshold')
		expect(placeholder).toContain('Why not fork immediately?')
		expect(placeholder).toMatch(/fresh current REP\/ETH price is strictly above\s+the computed threshold and far enough beyond it to satisfy the\s+configured <code>minLiquidationPriceDistanceBps<\/code> liquidation\s+distance check/)
		expect(placeholder).toContain('Escalation Deposit Trace')
		expect(placeholder).toContain('Escalation cost curve')
		expect(placeholder).toContain('fixed-point integer approximation using <code>SCALE = 1e6</code>')
		expect(placeholder).toContain('floor(bindingCapital / excessRewardWindowDivisor)')
		expect(placeholder).toContain('every Solidity division floors before the next step')
		expect(placeholder).toContain('Unresolved Escalation Migration Trace')
		expect(placeholder).toContain('initializeForkCarrySnapshotWithResolutionBalances')
		expect(placeholder).toContain('Fork Migration Contract Trace')
		expect(placeholder).toContain('Oracle-Staged Operation Trace')
		expect(placeholder).toContain('./auction-design.html')
		expect(await Bun.file('docs/auction-design.md').exists()).toBe(false)
	})
})
