import { jsx as _jsx, jsxs as _jsxs } from "preact/jsx-runtime";
import * as commonCopy from '@zoltar/ui-core-shared/copy/common.js';
import * as forkAuctionCopy from '@zoltar/ui-zoltar/copy/forkAuction.js';
import { CurrencyValue } from '@zoltar/ui-core-shared/components/CurrencyValue.js';
import { MetricField } from '@zoltar/ui-core-shared/components/MetricField.js';
import { SectionBlock } from '@zoltar/ui-core-shared/components/SectionBlock.js';
import { AUCTIONED_CAPACITY_OWNERSHIP_ATTO_REP_LABEL } from '../lib/forkAuction.js';
export function TruthAuctionSummaryCard({ auctionedCapacityOwnershipAttoRepDisplay, badge, clearingPriceDisplay, displayedEthRaisedAttoEth, displayedRepSoldAttoRep, endsDisplay, attoEthRaiseCap, ethRaisedProgress, maxAttoRepBeingSold, minBidSizeAttoEth, repSoldProgress, startedDisplay, winningThresholdPriceDisplay, }) {
    return (_jsx(SectionBlock, { badge: badge, className: 'fork-workflow-summary-card truth-auction-summary-card', title: commonCopy.truthAuction, variant: 'embedded', children: _jsxs("div", { className: 'fork-workflow-summary', children: [_jsxs("div", { className: 'fork-workflow-summary-primary truth-auction-summary-primary', children: [_jsxs("div", { className: 'fork-workflow-summary-stat-group truth-auction-progress-group', children: [_jsxs("div", { className: 'fork-workflow-summary-stat-copy truth-auction-progress-copy', children: [_jsx("span", { children: forkAuctionCopy.attoEthRaised }), _jsxs("strong", { children: [_jsx(CurrencyValue, { value: displayedEthRaisedAttoEth, suffix: commonCopy.eth }), " / ", _jsx(CurrencyValue, { value: attoEthRaiseCap, suffix: commonCopy.eth })] })] }), _jsx("div", { className: 'truth-auction-progress-track', children: _jsx("div", { className: 'truth-auction-progress-fill is-eth', style: { width: `${ethRaisedProgress}%` } }) })] }), _jsxs("div", { className: 'fork-workflow-summary-stat-group truth-auction-progress-group', children: [_jsxs("div", { className: 'fork-workflow-summary-stat-copy truth-auction-progress-copy', children: [_jsx("span", { children: forkAuctionCopy.attoRepSold }), _jsxs("strong", { children: [_jsx(CurrencyValue, { value: displayedRepSoldAttoRep, suffix: commonCopy.rep }), " / ", _jsx(CurrencyValue, { value: maxAttoRepBeingSold, suffix: commonCopy.rep })] })] }), _jsx("div", { className: 'truth-auction-progress-track', children: _jsx("div", { className: 'truth-auction-progress-fill is-rep', style: { width: `${repSoldProgress}%` } }) })] })] }), _jsxs("div", { className: 'fork-workflow-summary-metrics', children: [_jsx(MetricField, { label: commonCopy.starts, children: startedDisplay }), _jsx(MetricField, { label: forkAuctionCopy.clearingPrice, children: clearingPriceDisplay }), auctionedCapacityOwnershipAttoRepDisplay === undefined ? undefined : _jsx(MetricField, { label: AUCTIONED_CAPACITY_OWNERSHIP_ATTO_REP_LABEL, children: auctionedCapacityOwnershipAttoRepDisplay }), _jsx(MetricField, { label: forkAuctionCopy.minBid, children: _jsx(CurrencyValue, { value: minBidSizeAttoEth, suffix: commonCopy.eth }) }), _jsx(MetricField, { label: commonCopy.ends, children: endsDisplay }), winningThresholdPriceDisplay === undefined ? undefined : _jsx(MetricField, { label: forkAuctionCopy.winningThreshold, children: winningThresholdPriceDisplay })] })] }) }));
}
//# sourceMappingURL=TruthAuctionSummaryCard.js.map