import type { Address } from '@zoltar/shared/ethereum';
import { type RepPriceSource } from '@zoltar/ui-zoltar/features/open-oracle/lib/repPriceSource.js';
import type { SecurityPoolStateModel } from '../lib/securityPoolState.js';
import type { LiquidationApprovalDetails, LiquidationFundingPreview, ListedSecurityPool, OracleManagerDetails, SecurityPoolOverviewActionResult, SecurityPoolVaultSummary } from '@zoltar/ui-core-shared/types/contracts.js';
type LiquidationModalProps = {
    accountAddress: Address | undefined;
    closeLiquidationModal: () => void;
    currentPoolOracleManagerDetails: OracleManagerDetails | undefined;
    isOnActiveAppChain: boolean;
    liquidationDebtEthAmount: string;
    maximumLiquidationDebtAttoEth: bigint | undefined;
    liquidationManagerAddress: Address | undefined;
    liquidationFundingPreview?: LiquidationFundingPreview | undefined;
    liquidationFundingPreviewError?: string | undefined;
    liquidationModalOpen: boolean;
    liquidationSecurityPoolAddress: Address | undefined;
    liquidationTimeoutMinutes: string;
    loadingPoolOracleManager: boolean;
    loadingLiquidationFundingPreview?: boolean | undefined;
    onLoadLiquidationFundingPreview?: ((managerAddress: Address) => void) | undefined;
    onLoadPoolOracleManager: (managerAddress: Address) => void;
    poolOracleManagerError?: string | undefined;
    onSelectedPoolViewChange: (view: string | undefined) => void;
    repPerEthPrice: bigint | undefined;
    repPerEthSource: RepPriceSource | undefined;
    repPerEthSourceUrl: string | undefined;
    poolState?: SecurityPoolStateModel | undefined;
    selectedPool: ListedSecurityPool | undefined;
    securityPoolOverviewActiveAction: 'queueLiquidation' | undefined;
    securityPoolLiquidationError: string | undefined;
    securityPoolOverviewResult: SecurityPoolOverviewActionResult | undefined;
    receiverVaultSummary?: SecurityPoolVaultSummary | undefined;
    callerVaultSummary?: SecurityPoolVaultSummary | undefined;
    targetVaultSummary: SecurityPoolVaultSummary | undefined;
    liquidationTargetVault: string;
    liquidationReceiverVault?: string | undefined;
    liquidationApprovalId?: string | undefined;
    liquidationApprovalDetails?: LiquidationApprovalDetails | undefined;
    liquidationApprovalError?: string | undefined;
    liquidationReceiverVaultSummaryError?: string | undefined;
    liquidationReceiverVaultSummaryResolved?: boolean | undefined;
    loadingLiquidationApproval?: boolean | undefined;
    loadingLiquidationReceiverVaultSummary?: boolean | undefined;
    onLiquidationAmountChange: (value: string) => void;
    onLiquidationReceiverVaultChange?: ((value: string) => void) | undefined;
    onLiquidationApprovalIdChange?: ((value: string) => void) | undefined;
    onLoadLiquidationApproval?: (() => void) | undefined;
    onLoadLiquidationReceiverVaultSummary?: (() => void) | undefined;
    onLiquidationTimeoutMinutesChange: (value: string) => void;
    onQueueLiquidation: (managerAddress: Address, securityPoolAddress: Address) => void;
    walletBalanceAttoEth?: bigint | undefined;
};
export declare function LiquidationModal({ accountAddress, closeLiquidationModal, currentPoolOracleManagerDetails, isOnActiveAppChain, liquidationDebtEthAmount, maximumLiquidationDebtAttoEth, liquidationManagerAddress, liquidationFundingPreview, liquidationFundingPreviewError, liquidationModalOpen, liquidationSecurityPoolAddress, liquidationTimeoutMinutes, loadingPoolOracleManager, loadingLiquidationFundingPreview, liquidationTargetVault, liquidationReceiverVault, liquidationApprovalId, liquidationApprovalDetails, liquidationApprovalError, liquidationReceiverVaultSummaryError, liquidationReceiverVaultSummaryResolved, loadingLiquidationApproval, loadingLiquidationReceiverVaultSummary, onLoadPoolOracleManager, onLoadLiquidationFundingPreview, onSelectedPoolViewChange, poolState, poolOracleManagerError, repPerEthPrice, repPerEthSource, repPerEthSourceUrl, selectedPool, securityPoolOverviewActiveAction, securityPoolLiquidationError, securityPoolOverviewResult, receiverVaultSummary: loadedReceiverVaultSummary, callerVaultSummary, targetVaultSummary, onLiquidationAmountChange, onLiquidationReceiverVaultChange, onLiquidationApprovalIdChange, onLoadLiquidationApproval, onLoadLiquidationReceiverVaultSummary, onLiquidationTimeoutMinutesChange, onQueueLiquidation, walletBalanceAttoEth, }: LiquidationModalProps): import("preact").JSX.Element | undefined;
export {};
//# sourceMappingURL=LiquidationModal.d.ts.map