import { jsx as _jsx, jsxs as _jsxs } from "preact/jsx-runtime";
import * as commonCopy from '@zoltar/ui-core-shared/copy/common.js';
import * as securityPoolCopy from '@zoltar/ui-zoltar/copy/securityPool.js';
import { AddressValue } from '@zoltar/ui-core-shared/components/AddressValue.js';
import { CurrencyValue } from '@zoltar/ui-core-shared/components/CurrencyValue.js';
import { MetricGrid } from '@zoltar/ui-core-shared/components/MetricGrid.js';
import { MetricField } from '@zoltar/ui-core-shared/components/MetricField.js';
import { OpenOraclePriceValue } from '@zoltar/ui-zoltar/features/open-oracle/components/OpenOraclePriceValue.js';
import { ProgressMeter } from '@zoltar/ui-core-shared/components/ProgressMeter.js';
import { UniverseLink } from '@zoltar/ui-zoltar/features/universes/components/UniverseLink.js';
import { openInterestFeePerYearBigint } from '../lib/retentionRate.js';
import { calculateMintingCapacityAttoEth, formatStatoblastSecurityMultiplier } from '../../markets/lib/trading.js';
import { getToneRatioThreshold, getVisualRatio } from '@zoltar/ui-core-shared/lib/visualMetrics.js';
import { formatCurrencyBalance } from '@zoltar/ui-core-shared/lib/formatters.js';
export function SecurityPoolSummaryMetrics({ children, className = '', currentTimestamp, metricVariant = 'default', pool, showPoolAddress = false, showTotalBacking = false, showUniverse = false, variant = 'embedded' }) {
    const mintingCapacityAttoEth = calculateMintingCapacityAttoEth(pool.totalCapacityOwnershipAttoRep, pool.lastOraclePrice, pool.statoblastSecurityMultiplierBps);
    if (variant === 'embedded')
        return (_jsxs(MetricGrid, { className: className, variant: metricVariant, children: [showPoolAddress ? (_jsx(MetricField, { label: securityPoolCopy.poolAddress, children: _jsx(AddressValue, { address: pool.securityPoolAddress }) })) : undefined, showUniverse ? (_jsx(MetricField, { label: commonCopy.universe, children: _jsx(UniverseLink, { universeId: pool.universeId }) })) : undefined, _jsx(MetricField, { label: securityPoolCopy.vaultCount, children: pool.vaultCount.toString() }), _jsxs(MetricField, { label: commonCopy.statoblastSecurityMultiplierBps, children: [formatStatoblastSecurityMultiplier(pool.statoblastSecurityMultiplierBps), "x"] }), _jsx(MetricField, { label: commonCopy.initialReportPriorityFee, children: `${formatCurrencyBalance(pool.initialReportPriorityFeeAttoEthPerGas, 9)} ${commonCopy.gwei}` }), _jsx(MetricField, { label: securityPoolCopy.openInterestFeeYear, children: _jsx(CurrencyValue, { value: openInterestFeePerYearBigint(pool.currentRetentionRate), suffix: commonCopy.percent }) }), showTotalBacking ? (_jsx(MetricField, { label: securityPoolCopy.totalPoolHeldAttoRep, children: _jsx(CurrencyValue, { value: pool.totalPoolHeldAttoRep, suffix: commonCopy.rep }) })) : undefined, _jsxs(MetricField, { label: securityPoolCopy.openInterestMintedMax, children: [_jsx(CurrencyValue, { value: pool.settlementCollateralAttoEth, suffix: commonCopy.eth }), " / ", mintingCapacityAttoEth === undefined ? commonCopy.unavailable : _jsx(CurrencyValue, { value: mintingCapacityAttoEth, suffix: commonCopy.eth })] }), children] }));
    return (_jsxs("div", { className: ['security-pool-hero-metrics', className].filter(Boolean).join(' '), children: [_jsxs("div", { className: 'security-pool-hero-ribbon', children: [_jsxs("div", { className: 'security-pool-ribbon-stat', children: [_jsx("span", { className: 'security-pool-ribbon-stat-label', children: securityPoolCopy.vaultCount }), _jsx("strong", { className: 'security-pool-ribbon-stat-value', children: pool.vaultCount.toString() })] }), _jsxs("div", { className: 'security-pool-ribbon-stat', children: [_jsx("span", { className: 'security-pool-ribbon-stat-label', children: commonCopy.statoblastSecurityMultiplierBps }), _jsxs("strong", { className: 'security-pool-ribbon-stat-value', children: [formatStatoblastSecurityMultiplier(pool.statoblastSecurityMultiplierBps), "x"] })] }), _jsxs("div", { className: 'security-pool-ribbon-stat', children: [_jsx("span", { className: 'security-pool-ribbon-stat-label', children: securityPoolCopy.annualFee }), _jsx("strong", { className: 'security-pool-ribbon-stat-value', children: _jsx(CurrencyValue, { value: openInterestFeePerYearBigint(pool.currentRetentionRate), suffix: commonCopy.percent }) })] }), _jsxs("div", { className: 'security-pool-ribbon-stat', children: [_jsx("span", { className: 'security-pool-ribbon-stat-label', children: securityPoolCopy.totalPoolHeldAttoRep }), _jsx("strong", { className: 'security-pool-ribbon-stat-value', children: _jsx(CurrencyValue, { compactWhenOverflow: true, copyable: false, value: pool.totalPoolHeldAttoRep, suffix: commonCopy.rep }) })] })] }), _jsxs("div", { className: 'security-pool-hero-main', children: [_jsxs("div", { className: 'security-pool-hero-oracle', children: [_jsx("span", { className: 'security-pool-hero-oracle-label', children: securityPoolCopy.currentOraclePrice }), _jsx("strong", { className: 'security-pool-hero-oracle-value', children: _jsx(OpenOraclePriceValue, { currentTimestamp: currentTimestamp, lastPrice: pool.lastOraclePrice, lastSettlementTimestamp: pool.lastOracleSettlementTimestamp, priceValidUntilTimestamp: undefined }) }), _jsx("span", { className: 'detail', children: securityPoolCopy.latestSettlementContextDetail })] }), _jsx("div", { className: 'security-pool-hero-progress', children: _jsx(ProgressMeter, { className: 'security-pool-hero-meter', label: securityPoolCopy.openInterestMinted, maxValue: mintingCapacityAttoEth ?? 0n, secondaryValue: _jsxs("span", { className: 'detail', children: [securityPoolCopy.maxLead, mintingCapacityAttoEth === undefined ? commonCopy.unavailable : _jsx(CurrencyValue, { value: mintingCapacityAttoEth, suffix: commonCopy.eth })] }), tone: getToneRatioThreshold({
                                ratio: getVisualRatio({ value: pool.settlementCollateralAttoEth, maxValue: mintingCapacityAttoEth ?? 0n }),
                                successThreshold: 0.6,
                                warningThreshold: 0.85,
                            }), value: pool.settlementCollateralAttoEth, valueText: _jsx(CurrencyValue, { value: pool.settlementCollateralAttoEth, suffix: commonCopy.eth }) }) })] }), showPoolAddress || showUniverse || children === undefined ? (_jsxs("div", { className: 'security-pool-secondary-facts', children: [showPoolAddress ? (_jsx(MetricField, { label: securityPoolCopy.poolAddress, children: _jsx(AddressValue, { address: pool.securityPoolAddress }) })) : null, showUniverse ? (_jsx(MetricField, { label: commonCopy.universe, children: _jsx(UniverseLink, { universeId: pool.universeId }) })) : null, children] })) : null] }));
}
//# sourceMappingURL=SecurityPoolSummaryMetrics.js.map