import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "preact/jsx-runtime";
import * as securityPoolCopy from '@zoltar/ui-zoltar/copy/securityPool.js';
import { AddressValue } from '@zoltar/ui-core-shared/components/AddressValue.js';
import { VaultMetricGrid } from './VaultMetricGrid.js';
export function SecurityPoolVaultDirectory({ emptyState, pool, renderActions, renderBadge, renderTitle, repPerEthPrice, repPerEthSource, repPerEthSourceUrl }) {
    if (pool === undefined)
        return _jsx(_Fragment, { children: emptyState });
    const loadedVaultCount = BigInt(pool.vaults.length);
    const showingPartialDirectory = loadedVaultCount < pool.vaultCount;
    return (_jsxs("div", { className: 'vault-position-list', children: [pool.vaultScanCapped === true ? _jsx("p", { className: 'status warning', children: securityPoolCopy.vaultRegistryScanCapped }) : null, loadedVaultCount > 0n && showingPartialDirectory ? _jsx("p", { className: 'detail', children: securityPoolCopy.formatVaultDirectorySummary(loadedVaultCount, pool.vaultCount) }) : null, pool.vaults.length === 0 ? emptyState : null, pool.vaults.map(vault => (_jsxs("div", { className: 'vault-position-strip', children: [_jsxs("div", { className: 'vault-position-strip-head', children: [_jsx("div", { className: 'vault-position-strip-title', children: _jsx("div", { className: 'vault-position-title-copy', children: renderTitle === undefined ? _jsx(AddressValue, { address: vault.vaultAddress }) : renderTitle(vault) }) }), _jsx("div", { className: 'vault-position-strip-meta', children: renderBadge === undefined ? null : renderBadge(vault) })] }), _jsx(VaultMetricGrid, { badDebtAttoEth: vault.badDebtAttoEth, className: 'workflow-vault-grid', layout: 'preview', disputeStakedAttoRep: vault.disputeStakedAttoRep, vaultAttoRepBacking: vault.vaultAttoRepBacking, repPerEthPrice: repPerEthPrice, repPerEthSource: repPerEthSource, repPerEthSourceUrl: repPerEthSourceUrl, selectedPoolStatoblastSecurityMultiplierBps: pool.statoblastSecurityMultiplierBps, capacityOwnershipAttoRep: vault.capacityOwnershipAttoRep, claimableFeesAttoEth: vault.claimableFeesAttoEth }), _jsx("div", { className: 'vault-position-strip-actions', children: renderActions === undefined ? null : renderActions(vault) })] }, `${pool.securityPoolAddress}-${vault.vaultAddress}`)))] }));
}
//# sourceMappingURL=SecurityPoolVaultDirectory.js.map