import { jsx as _jsx, jsxs as _jsxs } from "preact/jsx-runtime";
import * as commonCopy from '@zoltar/ui-core-shared/copy/common.js';
import * as securityPoolCopy from '@zoltar/ui-zoltar/copy/securityPool.js';
import { CurrencyValue } from '@zoltar/ui-core-shared/components/CurrencyValue.js';
import { MetricField } from '@zoltar/ui-core-shared/components/MetricField.js';
import { TimestampValue } from '@zoltar/ui-core-shared/components/TimestampValue.js';
function VaultPrimaryMetric({ className, label, suffix, value }) {
    return (_jsxs("div", { className: className, children: [_jsx("span", { children: label }), _jsx("strong", { children: _jsx(CurrencyValue, { value: value, suffix: suffix }) })] }));
}
export function VaultMetricGrid({ badDebtAttoEth, className = '', layout = 'grid', disputeStakedAttoRep, priceValidUntilTimestamp, vaultAttoRepBacking, capacityOwnershipAttoRep }) {
    if (layout === 'preview')
        return (_jsxs("div", { className: ['vault-preview-strip', className].filter(Boolean).join(' '), children: [_jsx("div", { className: 'vault-preview-strip-head', children: _jsx(VaultPrimaryMetric, { className: 'vault-preview-capacity-ownership', label: commonCopy.capacityOwnershipAttoRep, value: capacityOwnershipAttoRep, suffix: commonCopy.rep }) }), _jsx("div", { className: 'vault-preview-side-metrics', children: _jsx(VaultPrimaryMetric, { label: commonCopy.poolHeldVaultRepBackingAttoRep, value: vaultAttoRepBacking, suffix: commonCopy.rep }) }), _jsxs("div", { className: 'vault-preview-meta', children: [badDebtAttoEth !== undefined && badDebtAttoEth > 0n ? (_jsx(MetricField, { label: securityPoolCopy.badDebt, children: _jsx(CurrencyValue, { value: badDebtAttoEth, suffix: commonCopy.eth }) })) : null, disputeStakedAttoRep === undefined ? null : (_jsx(MetricField, { label: commonCopy.disputeStakedAttoRep, children: _jsx(CurrencyValue, { value: disputeStakedAttoRep, suffix: commonCopy.rep }) })), priceValidUntilTimestamp === undefined ? null : (_jsx(MetricField, { label: securityPoolCopy.priceValidUntil, children: _jsx(TimestampValue, { timestamp: priceValidUntilTimestamp }) }))] })] }));
    return (_jsxs("div", { className: ['vault-detail-stage', className].filter(Boolean).join(' '), children: [_jsxs("div", { className: 'vault-detail-hero', children: [_jsx(VaultPrimaryMetric, { className: 'vault-detail-hero-primary', label: commonCopy.capacityOwnershipAttoRep, value: capacityOwnershipAttoRep, suffix: commonCopy.rep }), _jsx("div", { className: 'vault-detail-hero-secondary', children: _jsx(VaultPrimaryMetric, { label: commonCopy.poolHeldVaultRepBackingAttoRep, value: vaultAttoRepBacking, suffix: commonCopy.rep }) })] }), _jsxs("div", { className: 'vault-detail-meta', children: [_jsx("p", { className: 'detail', children: securityPoolCopy.vaultCoverageDetail }), badDebtAttoEth === undefined ? undefined : (_jsx(MetricField, { label: securityPoolCopy.badDebt, children: _jsx(CurrencyValue, { value: badDebtAttoEth, suffix: commonCopy.eth }) })), disputeStakedAttoRep === undefined ? undefined : (_jsx(MetricField, { label: commonCopy.disputeStakedAttoRep, children: _jsx(CurrencyValue, { value: disputeStakedAttoRep, suffix: commonCopy.rep }) })), priceValidUntilTimestamp === undefined ? undefined : (_jsx(MetricField, { label: securityPoolCopy.priceValidUntil, children: _jsx(TimestampValue, { timestamp: priceValidUntilTimestamp }) }))] })] }));
}
//# sourceMappingURL=VaultMetricGrid.js.map