import { element } from './dom.ts'

/** Looks up every fixed dashboard element the page controllers use once; a missing element fails the page load with its ID. */
export function createDashboardElements() {
	return {
		modeBadge: element('mode-badge'),
		runStatusBadge: element('run-status-badge'),
		capabilityBadge: element('capability-badge'),
		headerNetworkBadge: element('header-network-badge'),
		attentionBadge: element('attention-badge', HTMLAnchorElement),
		retryStatusBadge: element('retry-status-badge'),
		notice: element('notice'),
		launchNotice: element('launch-notice'),
		pauseButton: element('pause-button', HTMLButtonElement),
		cancelResume: element('cancel-resume'),
		confirmResume: element('confirm-resume', HTMLButtonElement),
		strategyFieldset: element('strategy-fieldset', HTMLFieldSetElement),
		submissionFieldset: element('submission-fieldset', HTMLFieldSetElement),
		connectivityFieldset: element('connectivity-fieldset', HTMLFieldSetElement),
		deploymentFieldset: element('deployment-fieldset', HTMLFieldSetElement),
		create2Fieldset: element('create2-fieldset', HTMLFieldSetElement),
		signerFieldset: element('signer-fieldset', HTMLFieldSetElement),
		tokensFieldset: element('tokens-fieldset', HTMLFieldSetElement),
		runtimeFieldset: element('runtime-fieldset', HTMLFieldSetElement),
		settlementFieldset: element('settlement-fieldset', HTMLFieldSetElement),
		executionFieldset: element('execution-fieldset', HTMLFieldSetElement),
		marketFieldset: element('market-fieldset', HTMLFieldSetElement),
		configurationFieldset: element('configuration-fieldset', HTMLFieldSetElement),
		configurationJson: element('configuration-json', HTMLTextAreaElement),
		reloadConfigurationButton: element('reload-configuration-button', HTMLButtonElement),
		profileSwitchRetryButton: element('profile-switch-retry-button', HTMLButtonElement),
		profileSwitchRetryActions: element('profile-switch-retry-actions'),
		settingsLoadState: element('settings-load-state'),
		retrySettingsButton: element('retry-settings-button', HTMLButtonElement),
		networkTargetStatus: element('network-target-status'),
		networkName: element('network-name', HTMLSelectElement),
		rpcQuorum: element('rpc-quorum', HTMLSelectElement),
		readRpcUrl: element('read-rpc-url', HTMLInputElement),
		publicRpcUrls: element('public-rpc-urls', HTMLTextAreaElement),
		quorumRpcUrls: element('quorum-rpc-urls', HTMLTextAreaElement),
		connectivityForm: element('connectivity-form', HTMLFormElement),
		create2Form: element('create2-form', HTMLFormElement),
		create2Recovery: element('create2-recovery'),
		create2RecoveryCopy: element('create2-recovery-copy'),
		deployExecutorButton: element('deploy-executor-button', HTMLButtonElement),
		signerForm: element('signer-form', HTMLFormElement),
		signerStatus: element('signer-status'),
		privateKey: element('private-key', HTMLInputElement),
		rememberSigner: element('remember-signer', HTMLInputElement),
		setSignerButton: element('set-signer-button', HTMLButtonElement),
		clearSignerButton: element('clear-signer-button', HTMLButtonElement),
		forgetSignerButton: element('forget-signer-button', HTMLButtonElement),
		tokensForm: element('tokens-form'),
		approvedUniverses: element('approved-universes'),
		tokenMarketsBody: element('token-markets-body', HTMLTableSectionElement),
		tokenMarketsEmpty: element('token-markets-empty'),
		priceToken: element('price-token', HTMLSelectElement),
		opportunitiesBody: element('opportunities-body', HTMLTableSectionElement),
		opportunitiesEmpty: element('opportunities-empty'),
		historyBody: element('history-body', HTMLTableSectionElement),
		historyEmpty: element('history-empty'),
		profitChart: element('profit-chart'),
		positionsBody: element('positions-body', HTMLTableSectionElement),
		positionsEmpty: element('positions-empty'),
		endpointChecks: element('endpoint-checks'),
		transactionFilter: element('transaction-filter', HTMLSelectElement),
		operationFilter: element('operation-filter', HTMLSelectElement),
		operationsBody: element('operations-body', HTMLTableSectionElement),
		operationsEmpty: element('operations-empty'),
		disputePaths: element('dispute-paths'),
		disputePathsEmpty: element('dispute-paths-empty'),
	}
}

export type DashboardElements = ReturnType<typeof createDashboardElements>
