import type { PublicOperatorSnapshot } from '#state/operator-state'
import { array, booleanValue, numberValue, object, oneOf, optional, stringValue, union } from '@zoltar/bot-shared/dashboard/response-validation'

const hexValue = (value: unknown): value is `0x${string}` => typeof value === 'string' && /^0x[0-9a-fA-F]+$/.test(value)
const nullValue = (value: unknown): value is null => value === null

export const isSnapshot = object<PublicOperatorSnapshot>({
	marketAvailability: optional(
		union(
			object({
				kind: oneOf('missing-deployment'),
				chainId: numberValue,
				contracts: array(
					object({
						address: hexValue,
						name: stringValue,
					}),
				),
			}),
			object({
				kind: oneOf('no-v3-liquidity'),
				chainId: numberValue,
			}),
		),
	),
	lastError: optional(stringValue),
	lastPollAt: optional(stringValue),
	lastPollFailureAt: optional(stringValue),
	lastRetryAt: optional(stringValue),
	nextRetryAt: optional(stringValue),
	retryInProgress: optional(booleanValue),
	universes: optional(
		array(
			object({
				id: stringValue,
				parentId: optional(stringValue),
				outcomeIndex: optional(stringValue),
				repToken: hexValue,
			}),
		),
	),
	tokenAddresses: array(hexValue),
	tokenMarkets: array(
		object({
			address: hexValue,
			balance: optional(stringValue),
			decimals: numberValue,
			name: stringValue,
			pools: array(
				object({
					address: hexValue,
					fee: numberValue,
					liquidity: stringValue,
					priceWeth: optional(stringValue),
					url: stringValue,
					venue: stringValue,
				}),
			),
			symbol: stringValue,
		}),
	),
	priceHistory: array(
		object({
			blockNumber: stringValue,
			pool: hexValue,
			priceWeth: stringValue,
			sampledAt: stringValue,
			symbol: stringValue,
			token: hexValue,
			venue: stringValue,
		}),
	),
	activeReportCount: numberValue,
	consecutivePollFailures: optional(numberValue),
	balances: optional(
		object({
			availableEth: stringValue,
			availableRep: stringValue,
			availableWeth: stringValue,
			repValueWeth: optional(stringValue),
			totalValueWeth: optional(stringValue),
		}),
	),
	blockNumber: optional(stringValue),
	blockTimestamp: optional(stringValue),
	centralizedMarket: optional(
		object({
			assetId: stringValue,
			askDepthEth: stringValue,
			bidDepthEth: stringValue,
			chainId: numberValue,
			maximumPriceRepPerEth: stringValue,
			minimumPriceRepPerEth: stringValue,
			observations: array(
				object({
					askDepthEth: stringValue,
					bestAskQuote: stringValue,
					bestBidQuote: stringValue,
					bidDepthEth: stringValue,
					chainId: numberValue,
					exchangeId: stringValue,
					ethTickerTimestamp: optional(stringValue),
					observedAt: stringValue,
					orderBookTimestamp: optional(stringValue),
					priceRepPerEth: stringValue,
					repMarket: stringValue,
					usesEthTicker: booleanValue,
				}),
			),
			priceRepPerEth: stringValue,
			reasons: array(stringValue),
			reliable: booleanValue,
		}),
	),
	marketConsensus: optional(
		object({
			assetId: stringValue,
			cex: object({
				askDepthEth: stringValue,
				bidDepthEth: stringValue,
				priceRepPerEth: stringValue,
				reasons: array(stringValue),
				reliable: booleanValue,
				sourceCount: numberValue,
			}),
			chainId: numberValue,
			dex: object({
				askDepthEth: stringValue,
				bidDepthEth: stringValue,
				priceRepPerEth: stringValue,
				reasons: array(stringValue),
				reliable: booleanValue,
				sourceCount: numberValue,
			}),
			priceRepPerEth: optional(stringValue),
			reasons: array(stringValue),
			reliable: booleanValue,
			sourceCount: numberValue,
		}),
	),
	execute: booleanValue,
	executor: optional(hexValue),
	executionHistory: array(
		object({
			actualGasCostEth: stringValue,
			direction: oneOf('buy-rep', 'sell-rep'),
			estimatedNetProfitWeth: stringValue,
			executedAt: stringValue,
			reportId: stringValue,
			requiredToken: stringValue,
			requiredWeth: stringValue,
			tokenSymbol: stringValue,
			trackedNetProfitEth: stringValue,
			transactionHash: hexValue,
		}),
	),
	executionHistoryRecordCount: numberValue,
	positionRecordCount: numberValue,
	expectedChainId: numberValue,
	explorerUrl: stringValue,
	endpointChecks: array(
		object({
			authenticatedAddress: optional(hexValue),
			chainId: optional(numberValue),
			checkedAt: stringValue,
			error: optional(stringValue),
			failureDisposition: optional(oneOf('connectivity-degraded', 'safety-paused')),
			kind: oneOf('private-relay', 'public-rpc', 'read-rpc'),
			status: oneOf('failed', 'healthy'),
			target: stringValue,
		}),
	),
	rpcEndpointHealth: optional(
		array(
			object({
				consecutiveFailures: numberValue,
				error: optional(stringValue),
				lastFailureAt: optional(stringValue),
				lastSuccessAt: optional(stringValue),
				latencyMilliseconds: optional(numberValue),
				nextRetryAt: optional(stringValue),
				status: oneOf('healthy', 'degraded', 'offline', 'unknown'),
				target: stringValue,
			}),
		),
	),
	gameCapital: object({
		eth: stringValue,
		totalEthWeth: stringValue,
		weth: stringValue,
	}),
	mode: oneOf('dry-run', 'execute'),
	network: oneOf('mainnet', 'sepolia'),
	networkConfigured: booleanValue,
	openOracle: hexValue,
	operatorCapable: booleanValue,
	operationLog: array(
		object({
			reportId: optional(stringValue),
			category: oneOf('configuration', 'decision', 'scan', 'transaction'),
			level: oneOf('error', 'info', 'warning'),
			message: stringValue,
			timestamp: stringValue,
			details: optional(stringValue),
			reason: optional(stringValue),
		}),
	),
	opportunities: array(
		object({
			centralizedPriceDeviationBps: optional(stringValue),
			decision: oneOf('dry-run-opportunity', 'eligible', 'execution-failed', 'history-unavailable', 'insufficient-inventory', 'market-risk', 'paused', 'risk-limit', 'selected', 'self-report', 'signer-unavailable', 'submitted', 'unprofitable'),
			direction: oneOf('buy-rep', 'sell-rep'),
			estimatedNetProfitWeth: stringValue,
			estimatedNetProfitEth: stringValue,
			executablePriceRepPerEth: stringValue,
			hasRequiredInventory: optional(booleanValue),
			pool: hexValue,
			poolFee: numberValue,
			reportId: stringValue,
			requiredToken: stringValue,
			requiredWeth: stringValue,
			token: hexValue,
			tokenSymbol: stringValue,
			timeRemaining: stringValue,
			venue: optional(oneOf('uniswap-v2', 'uniswap-v3', 'uniswap-v4')),
			windowUnit: oneOf('blocks', 'seconds'),
		}),
	),
	positions: array(
		object({
			direction: oneOf('buy-rep', 'sell-rep'),
			reportId: stringValue,
			tokenSymbol: stringValue,
			actualEntryGasCostEth: stringValue,
			entryTransactionHash: hexValue,
			hedgedProfitBeforeGasEth: stringValue,
			lifecycleGasCostEth: stringValue,
			lifecycleReceiptRecovered: booleanValue,
			lifecycleSettlerRewardEth: optional(stringValue),
			openedAt: stringValue,
			realizedNetProfitEth: optional(stringValue),
			status: oneOf('closed', 'closed-pending-finality', 'expired-not-included', 'open', 'pending-entry', 'recovery-required', 'replaced', 'settled', 'withdrawing'),
			withdrawnToken: stringValue,
			withdrawnWeth: stringValue,
			hasLifecycleTransactions: booleanValue,
			manuallyReconciled: booleanValue,
		}),
	),
	paused: booleanValue,
	queuedWallet: optional(union(nullValue, hexValue)),
	savedWallet: optional(hexValue),
	status: oneOf('connectivity-degraded', 'error', 'paused', 'running', 'stopped', 'syncing'),
	submission: object({
		minimumBundleRelaySuccesses: numberValue,
		mode: oneOf('private', 'public'),
	}),
	reportPaths: array(
		object({
			reportId: stringValue,
			settled: booleanValue,
			steps: array(
				object({
					amount1: optional(stringValue),
					amount2: optional(stringValue),
					blockNumber: stringValue,
					event: oneOf('submitted', 'settled', 'disputed'),
					reporter: optional(hexValue),
					transactionHash: optional(hexValue),
				}),
			),
		}),
	),
	risk: object({
		limits: object({
			lifecycleGasReserveWeth: stringValue,
			maxConcurrentPositions: numberValue,
			maxDailyGasSpendWeth: stringValue,
			maxPositionNotionalWeth: stringValue,
			maxTotalLockedWeth: stringValue,
		}),
		usage: object({
			dailyGasSpentWeth: stringValue,
			lockedWeth: stringValue,
			openPositions: numberValue,
		}),
	}),
	totalActualGasCostEth: stringValue,
	totalHedgedProfitBeforeGasEth: stringValue,
	totalOpenHedgedNetProfitEth: stringValue,
	totalRealizedNetProfitEth: stringValue,
	transactionActivity: array(
		object({
			actualGasCostEth: optional(stringValue),
			reportId: stringValue,
			tokenSymbol: optional(stringValue),
			trackedNetProfitEth: optional(stringValue),
			status: oneOf('confirmation-unknown', 'confirmed', 'pending', 'reverted', 'submission-failed', 'submitting'),
			mode: oneOf('private', 'public'),
			acceptedTargets: array(stringValue),
			estimatedNetProfitEth: optional(stringValue),
			hash: hexValue,
			kind: oneOf('approval-token', 'approval-weth', 'canonical-head', 'dispute', 'settle', 'withdraw-replacement', 'withdraw-token', 'withdraw-weth'),
			updatedAt: stringValue,
			failedTargets: array(
				object({
					error: optional(stringValue),
					target: stringValue,
				}),
			),
		}),
	),
	wallet: optional(hexValue),
})
