import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { executorArtifact } from '#contracts/artifacts.generated'

const projectRoot = resolve(import.meta.dir, '..')
const outputPath = resolve(projectRoot, 'src/contracts/executor-abi.generated.ts')
const unformatted = `// Generated by scripts/generate-executor-abi.mts. Do not edit.\nexport const openOracleArbitrageExecutorAbi = ${JSON.stringify(executorArtifact.abi, undefined, '\t')} as const\n`
const formatter = Bun.spawnSync(['bunx', '@biomejs/biome', 'format', '--stdin-file-path', outputPath], {
	stderr: 'pipe',
	stdin: Buffer.from(unformatted),
	stdout: 'pipe',
})
if (!formatter.success) throw new Error(`Could not format generated executor ABI: ${formatter.stderr.toString()}`)
const generated = formatter.stdout.toString()

if (process.argv.includes('--check')) {
	let current: string
	try {
		current = await readFile(outputPath, 'utf8')
	} catch (error) {
		throw new Error(`Generated executor ABI is missing: ${error instanceof Error ? error.message : String(error)}`)
	}
	if (current !== generated) throw new Error('Generated OpenOracle arbitrager executor ABI is stale; run bun run generate:abi')
} else {
	await Bun.write(outputPath, generated)
}
