import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dir, '..')
const artifactPath = resolve(root, 'solidity/artifacts/Contracts.json')
const outputPath = resolve(root, 'open-oracle-arbitrager/executor-abi.generated.ts')
const sourceName = 'contracts/peripherals/OpenOracleArbitrageExecutor.sol'
const contractName = 'OpenOracleArbitrageExecutor'

type ArtifactRoot = {
	contracts?: Record<string, Record<string, { abi?: unknown }>>
}

const artifacts = JSON.parse(await readFile(artifactPath, 'utf8')) as ArtifactRoot
const abi = artifacts.contracts?.[sourceName]?.[contractName]?.abi
if (!Array.isArray(abi)) throw new Error(`Missing ${sourceName}:${contractName} ABI in ${artifactPath}`)
const unformatted = `// Generated by scripts/generate-open-oracle-arbitrager-abi.mts. Do not edit.\nexport const openOracleArbitrageExecutorAbi = ${JSON.stringify(abi, undefined, '\t')} as const\n`
const formatter = Bun.spawnSync(['bunx', '@biomejs/biome', 'format', '--stdin-file-path', outputPath], {
	stderr: 'pipe',
	stdin: Buffer.from(unformatted),
	stdout: 'pipe',
})
if (!formatter.success) throw new Error(`Could not format generated executor ABI: ${formatter.stderr.toString()}`)
const generated = formatter.stdout.toString()

if (process.argv.includes('--check')) {
	let current: string
	try {
		current = await readFile(outputPath, 'utf8')
	} catch (error) {
		throw new Error(`Generated executor ABI is missing: ${error instanceof Error ? error.message : String(error)}`)
	}
	if (current !== generated) throw new Error('Generated OpenOracle arbitrager executor ABI is stale; run bun run generate:open-oracle-arbitrager-abi')
} else {
	await Bun.write(outputPath, generated)
}
