export const sharedBrowserArtifactRelativePaths = [
	'shared/js/bigInt.js',
	'shared/js/constants.js',
	'shared/js/deploymentAddresses.js',
	'shared/js/escalationMath.js',
	'shared/js/ethereum.js',
	'shared/js/liquidation.js',
	'shared/js/logScan.js',
	'shared/js/openOracle.js',
	'shared/js/oracleInitialReport.js',
	'shared/js/protocolConfig.js',
	'shared/js/scalarOutcome.js',
	'shared/js/sepoliaRepAllocations.js',
	'shared/js/truthAuctionTickMath.js',
] as const
