import type { Address } from '@zoltar/shared/ethereum';
import type { DeploymentStatus } from '@zoltar/ui-core-shared/types/contracts.js';
import type { ReportingOutcomeKey, TradingShareBalances, ZoltarUniverseSummary } from '@zoltar/ui-core-shared/types/contracts.js';
type CollateralizationDisplayState = 'value' | 'noActiveCapacityOwnership' | 'unavailable';
type CollateralizationTone = 'success' | 'danger';
export declare const MARKET_NOT_FINALIZED_MESSAGE = "This market has not finalized.";
export declare const SHARE_MIGRATION_AFTER_FORK_MESSAGE = "Share migration is only available after this universe has forked.";
export declare const NO_MINT_CAPACITY_NO_ACTIVE_CAPACITY_OWNERSHIP_MESSAGE = "No mint capacity. No active capacity ownership.";
export declare const NEED_MATCHING_COMPLETE_SET_SHARES_MESSAGE = "Need matching Invalid, Yes, and No shares to redeem complete sets.";
export declare const UNDEFINED_COMPLETE_SET_EXCHANGE_RATE_MESSAGE = "Minting is unavailable because this pool has complete-set shares but no collateral.";
export declare function hasUndefinedCompleteSetExchangeRate(settlementCollateralAttoEth: bigint | undefined, shareTokenSupplyAttoShares: bigint | undefined): boolean | undefined;
export declare function calculateMintingCapacityAttoEth(capacityOwnershipAttoRep: bigint | undefined, repPerEthPrice: bigint | undefined, statoblastSecurityMultiplierBps: bigint | undefined): bigint | undefined;
export declare function getRemainingMintCapacity(mintingCapacityAttoEth: bigint | undefined, settlementCollateralAttoEth: bigint | undefined, shareTokenSupplyAttoShares?: bigint | undefined): bigint | undefined;
export declare function getMaximumMintAmount(walletEthBalanceAttoEth: bigint | undefined, remainingMintCapacityAttoEth: bigint | undefined): bigint | undefined;
export declare function estimateMintCheckpoint({ currentRetentionRate, currentTimestamp, feeEligibleCapacityOwnershipAttoRep, feeEndTimestamp, feeIndexRemainder, lastUpdatedFeeAccumulator, settlementCollateralAttoEth, totalFeesOwedRemainder, }: {
    currentRetentionRate: bigint | undefined;
    currentTimestamp: bigint | undefined;
    feeEligibleCapacityOwnershipAttoRep: bigint | undefined;
    feeEndTimestamp: bigint | undefined;
    feeIndexRemainder: bigint | undefined;
    lastUpdatedFeeAccumulator: bigint | undefined;
    settlementCollateralAttoEth: bigint | undefined;
    totalFeesOwedRemainder: bigint | undefined;
}): {
    estimatedRetentionFeeAttoEth: bigint;
    settlementCollateralAfterFeesAttoEth: bigint;
} | undefined;
export declare function getPoolCollateralizationPercent(totalPoolHeldAttoRep: bigint | undefined, totalCapacityOwnershipAttoRep: bigint | undefined, repPerEthPrice: bigint | undefined): bigint | undefined;
export declare function getVaultCollateralizationPercent(vaultAttoRepBacking: bigint | undefined, capacityOwnershipAttoRep: bigint | undefined, repPerEthPrice: bigint | undefined): bigint | undefined;
export declare function getCollateralizationTone(collateralizationPercent: bigint | undefined, statoblastSecurityMultiplierBps: bigint | undefined): CollateralizationTone | undefined;
export declare function formatStatoblastSecurityMultiplier(statoblastSecurityMultiplierBps: bigint): string;
export declare function getCollateralizationDisplayState(capacityOwnershipAttoRep: bigint | undefined, collateralizationPercent: bigint | undefined): CollateralizationDisplayState;
export declare function hasRepBackedPoolWithNoActiveCapacityOwnership(totalPoolHeldAttoRep: bigint | undefined, feeEligibleCapacityOwnershipAttoRep: bigint | undefined): boolean;
export declare function getMaxRedeemableCompleteSets(shareBalances: TradingShareBalances | undefined): bigint | undefined;
export declare function convertAttoSharesToSettlementCollateralAttoEth(amountAttoShares: undefined, settlementCollateralAttoEth: bigint | undefined, shareTokenSupplyAttoShares: bigint | undefined): undefined;
export declare function convertAttoSharesToSettlementCollateralAttoEth(amountAttoShares: bigint, settlementCollateralAttoEth: bigint | undefined, shareTokenSupplyAttoShares: bigint | undefined): bigint;
export declare function convertAttoSharesToSettlementCollateralAttoEth(amountAttoShares: bigint | undefined, settlementCollateralAttoEth: bigint | undefined, shareTokenSupplyAttoShares: bigint | undefined): bigint | undefined;
export declare function convertSettlementCollateralAttoEthToAttoShares(amountAttoEth: bigint, settlementCollateralAttoEth: bigint | undefined, shareTokenSupplyAttoShares: bigint | undefined): bigint | undefined;
export declare function convertMintSettlementCollateralAttoEthToAttoShares(amountAttoEth: bigint, settlementCollateralAttoEth: bigint | undefined, shareTokenSupplyAttoShares: bigint | undefined): bigint | undefined;
export declare function getSelectedOutcomeShareBalance(shareBalances: TradingShareBalances | undefined, outcome: ReportingOutcomeKey): bigint | undefined;
export declare function getTradingGuardDisplayMessage(message: string | undefined): string | undefined;
export declare function getDefaultShareMigrationTargetOutcomeIndexes(tradingForkUniverse: ZoltarUniverseSummary | undefined): string;
export declare function isTradingSystemDeployed(deploymentStatuses: DeploymentStatus[]): boolean;
export declare function getTradingMintGuardMessage({ accountAddress, settlementCollateralAttoEth, ethBalanceAttoEth, mintingCapacityAttoEth, hasSelectedPool, isOnActiveAppChain, isPriceValid, mintAmountInput, shareTokenSupplyAttoShares, totalPoolHeldAttoRep, }: {
    accountAddress: Address | undefined;
    settlementCollateralAttoEth: bigint | undefined;
    ethBalanceAttoEth: bigint | undefined;
    mintingCapacityAttoEth: bigint | undefined;
    hasSelectedPool: boolean;
    isOnActiveAppChain: boolean;
    isPriceValid?: boolean;
    mintAmountInput: string;
    shareTokenSupplyAttoShares: bigint | undefined;
    totalPoolHeldAttoRep: bigint | undefined;
}): string | undefined;
export declare function getTradingRedeemCompleteSetGuardMessage({ accountAddress, settlementCollateralAttoEth, hasSelectedPool, isOnActiveAppChain, loadingTradingDetails, redeemAmountInput, shareBalances, shareTokenSupplyAttoShares, }: {
    accountAddress: Address | undefined;
    settlementCollateralAttoEth: bigint | undefined;
    hasSelectedPool: boolean;
    isOnActiveAppChain: boolean;
    loadingTradingDetails: boolean;
    redeemAmountInput: string;
    shareBalances: TradingShareBalances | undefined;
    shareTokenSupplyAttoShares: bigint | undefined;
}): string | undefined;
export declare function getTradingMigrateSharesGuardMessage({ accountAddress, hasSelectedPool, isOnActiveAppChain, loadingTradingForkUniverse, loadingTradingDetails, selectedShareOutcome, shareBalances, targetOutcomeIndexesInput, tradingForkUniverse, }: {
    accountAddress: Address | undefined;
    hasSelectedPool: boolean;
    isOnActiveAppChain: boolean;
    loadingTradingForkUniverse: boolean;
    loadingTradingDetails: boolean;
    selectedShareOutcome: ReportingOutcomeKey;
    shareBalances: TradingShareBalances | undefined;
    targetOutcomeIndexesInput: string;
    tradingForkUniverse: ZoltarUniverseSummary | undefined;
}): string | undefined;
export declare function getTradingRedeemSharesGuardMessage({ accountAddress, hasSelectedPool, isOnActiveAppChain }: {
    accountAddress: Address | undefined;
    hasSelectedPool: boolean;
    isOnActiveAppChain: boolean;
}): string | undefined;
export {};
//# sourceMappingURL=trading.d.ts.map