export const deploying = 'Deploying…';
export const deploymentReadyStatus = 'Can deploy now.';
export const deploymentRunningStatus = 'Deployment in progress.';
export const notDeployedBadgeLabel = 'Not Deployed';
export const waiting = 'Waiting';
export const formatPrerequisiteDetail = (prerequisiteLabel) => `Requires ${prerequisiteLabel}`;
export const allDeployed = 'All deployed';
export const formatDeployContract = (contractLabel) => `Deploy ${contractLabel}`;
export const formatDeployingContract = (contractLabel) => `Deploying ${contractLabel}…`;
export const contractsDeployed = 'Contracts deployed';
export const deployNextMissing = 'Deploy next missing';
export const browseQuestions = 'Browse questions';
export const allContracts = 'All contracts';
export const deploymentRunningStatusLabel = 'Deployment in progress';
export const deploymentOverviewDetail = 'Deploy and verify the shared deterministic contracts that back the application.';
export const deterministicContractDeployment = 'Deterministic contract deployment';
export const loadingDeploymentStatus = 'Loading deployment status…';
export const deploymentStatusUnavailableReason = 'Deployment status is unavailable.';
export const nextDeployable = 'Next deployable';
//# sourceMappingURL=deployment.js.map