import type { SQL } from 'bun'
import { CURRENT_SCHEMA_VERSION, INITIAL_MIGRATABLE_SCHEMA_VERSION, type SupportedSchemaVersion } from './schema-policy.ts'

interface SchemaLayout {
	readonly relations: readonly string[]
	readonly columns: readonly string[]
	readonly constraints: readonly string[]
	readonly indexes: readonly string[]
	readonly unsupportedObjects: readonly string[]
}

type SchemaLayoutDifferences = Partial<Record<keyof SchemaLayout, { readonly missing: readonly string[]; readonly unexpected: readonly string[] }>>

const schemaLayoutKeys = ['relations', 'columns', 'constraints', 'indexes', 'unsupportedObjects'] as const

export const schemaLayoutDifferences = (expected: SchemaLayout, actual: SchemaLayout): SchemaLayoutDifferences => {
	const differences: SchemaLayoutDifferences = {}
	for (const key of schemaLayoutKeys) {
		const expectedValues = new Set(expected[key])
		const actualValues = new Set(actual[key])
		const missing = expected[key].filter(value => !actualValues.has(value))
		const unexpected = actual[key].filter(value => !expectedValues.has(value))
		if (missing.length > 0 || unexpected.length > 0) differences[key] = { missing, unexpected }
	}
	return differences
}

const historicalIntegrityTables = new Set([
	'action_interpretations',
	'address_balance_observations',
	'augurscan_schema_migrations',
	'chain_reorganizations',
	'entity_state_observations',
	'history_invalidation_causes',
	'history_invalidation_occurrences',
	'indexer_runs',
	'log_interpretations',
	'token_metadata_observations',
])

const historicalIntegrityColumns = new Set([
	'contracts.configured_deployment_block',
	'networks.applied_abi_source_hash',
	'networks.applied_application_source_hash',
	'networks.applied_projection_source_hash',
	'entity_state_snapshots.indexer_run_id',
	'entity_state_snapshots.abi_source_hash',
	'entity_state_snapshots.application_source_hash',
	'entity_state_snapshots.projection_source_hash',
])

const historicalIntegrityIndexes = new Set(['pool_snapshots_detail_page', 'protocol_timeline_entity_history_page', 'protocol_timeline_history_page', 'vault_snapshots_detail_page'])

const ownershipTables = new Set(['indexer_ownership'])

const ownershipIndexes = new Set(['indexer_ownership_heartbeat'])

const normalizeDefinition = (value: string): string => {
	const normalized = value.replaceAll('public.', '').replace(/\s+/g, ' ').trim().replace(/;$/, '')
	// PostgreSQL 17 preserves one additional pair of parentheses around some
	// CHECK expressions compared with the canonical schema source. The pair is
	// formatting only, so normalize it before comparing otherwise exact layouts.
	return normalized.replace(/^CHECK \(\((.*)\)\)$/, 'CHECK ($1)')
}

const sorted = (values: Iterable<string>): string[] => [...values].sort()

const columnSignature = (table: string, column: string, type: string, notNull: boolean, identity: string, defaultExpression: string | undefined): string => `${table}.${column}|${normalizeDefinition(type)}|${notNull ? 'not-null' : 'nullable'}|${identity}|${normalizeDefinition(defaultExpression ?? '')}`

const identityGeneration = (columnDefinition: string): 'a' | 'd' | '' => {
	if (/\bGENERATED ALWAYS AS IDENTITY\b/.test(columnDefinition)) return 'a'
	return /\bGENERATED BY DEFAULT AS IDENTITY\b/.test(columnDefinition) ? 'd' : ''
}

export const expectedSchemaLayout = (schema: string, version: SupportedSchemaVersion): SchemaLayout => {
	const normalizedSchema = schema.replaceAll('\r\n', '\n')
	const relations = new Set<string>(['table:augurscan_schema'])
	const columns = new Set<string>([columnSignature('augurscan_schema', 'singleton', 'boolean', true, '', 'true'), columnSignature('augurscan_schema', 'schema_version', 'text', true, '', undefined), columnSignature('augurscan_schema', 'initialized_at', 'timestamp with time zone', true, '', 'now()')])
	const constraints = new Set<string>(['augurscan_schema.augurscan_schema_pkey|PRIMARY KEY (singleton)', 'augurscan_schema.augurscan_schema_singleton_check|CHECK (singleton)'])
	const indexes = new Set<string>()
	const defaultOverrides = new Map<string, string>()
	for (const match of normalizedSchema.matchAll(/ALTER TABLE ONLY public\.([a-z_][a-z0-9_]*) ALTER COLUMN ([a-z_][a-z0-9_]*) SET DEFAULT ([\s\S]*?);/g)) {
		const [, table, column, expression] = match
		if (table !== undefined && column !== undefined && expression !== undefined) defaultOverrides.set(`${table}.${column}`, expression)
	}
	for (const match of normalizedSchema.matchAll(/CREATE TABLE public\.([a-z_][a-z0-9_]*) \(\n([\s\S]*?)\n\);/g)) {
		const [, table, body] = match
		if (table === undefined || body === undefined || (version === INITIAL_MIGRATABLE_SCHEMA_VERSION && historicalIntegrityTables.has(table)) || (version !== CURRENT_SCHEMA_VERSION && ownershipTables.has(table))) continue
		relations.add(`table:${table}`)
		for (const sourceLine of body.split('\n')) {
			const line = sourceLine.trim().replace(/,$/, '')
			const constraintMatch = /^CONSTRAINT ([a-z_][a-z0-9_]*) (.+)$/.exec(line)
			if (constraintMatch !== null) {
				const [, name, definition] = constraintMatch
				if (name !== undefined && definition !== undefined) constraints.add(`${table}.${name}|${normalizeDefinition(definition)}`)
				continue
			}
			const columnMatch = /^(?:"([^"]+)"|([a-z_][a-z0-9_]*))\s+(timestamp with time zone|numeric\(\d+,\d+\)|bigint|integer|text|boolean|jsonb)([\s\S]*)$/.exec(line)
			if (columnMatch === null) continue
			const [, quotedColumn, plainColumn, type, remainderValue] = columnMatch
			const column = quotedColumn ?? plainColumn
			if (column === undefined || type === undefined) continue
			if (version === INITIAL_MIGRATABLE_SCHEMA_VERSION && historicalIntegrityColumns.has(`${table}.${column}`)) continue
			const remainder = remainderValue ?? ''
			const defaultMatch = /\bDEFAULT ([\s\S]*?)(?=\s+NOT NULL|\s+GENERATED (?:ALWAYS|BY DEFAULT) AS IDENTITY|$)/.exec(remainder)
			const identity = identityGeneration(remainder)
			const defaultExpression = defaultOverrides.get(`${table}.${column}`) ?? defaultMatch?.[1]
			columns.add(columnSignature(table, column, type, /\bNOT NULL\b/.test(remainder), identity, defaultExpression))
			if (identity !== '') relations.add(`sequence:${table}_${column}_seq`)
		}
	}
	for (const match of normalizedSchema.matchAll(/ALTER TABLE ONLY public\.([a-z_][a-z0-9_]*)\s+ADD CONSTRAINT ([a-z_][a-z0-9_]*) ([\s\S]*?);/g)) {
		const [, table, name, definition] = match
		if (table === undefined || name === undefined || definition === undefined) continue
		if (version === INITIAL_MIGRATABLE_SCHEMA_VERSION && historicalIntegrityTables.has(table)) continue
		if (version !== CURRENT_SCHEMA_VERSION && ownershipTables.has(table)) continue
		constraints.add(`${table}.${name}|${normalizeDefinition(definition)}`)
	}
	for (const match of normalizedSchema.matchAll(/CREATE (UNIQUE )?INDEX ([a-z_][a-z0-9_]*)\s+ON public\.([a-z_][a-z0-9_]*)\s+([\s\S]*?);/g)) {
		const [, unique, name, table, definition] = match
		if (name === undefined || table === undefined || definition === undefined) continue
		if (version === INITIAL_MIGRATABLE_SCHEMA_VERSION && (historicalIntegrityTables.has(table) || historicalIntegrityIndexes.has(name))) continue
		if (version !== CURRENT_SCHEMA_VERSION && (ownershipTables.has(table) || ownershipIndexes.has(name))) continue
		indexes.add(`${name}|${normalizeDefinition(`CREATE ${unique ?? ''}INDEX ${name} ON public.${table} ${definition}`)}`)
	}
	for (const match of normalizedSchema.matchAll(/CREATE SEQUENCE public\.([a-z_][a-z0-9_]*)/g)) {
		const sequence = match[1]
		if (sequence !== undefined) relations.add(`sequence:${sequence}`)
	}
	return {
		relations: sorted(relations),
		columns: sorted(columns),
		constraints: sorted(constraints),
		indexes: sorted(indexes),
		unsupportedObjects: [],
	}
}

export const actualSchemaLayout = async (connection: Awaited<ReturnType<SQL['reserve']>>): Promise<SchemaLayout> => {
	const [relations, columns, constraints, indexes, unsupportedObjects] = await Promise.all([
		connection`
			SELECT CASE class.relkind WHEN 'r' THEN 'table:' ELSE 'sequence:' END || class.relname AS signature
			FROM pg_catalog.pg_class class
			JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
			WHERE namespace.nspname = 'public' AND class.relkind IN ('r', 'S')
			ORDER BY signature
		`,
		connection`
			SELECT class.relname AS table_name, attribute.attname AS column_name,
				pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) AS formatted_type,
				attribute.attnotnull AS not_null, attribute.attidentity AS identity,
				pg_catalog.pg_get_expr(defaults.adbin, defaults.adrelid) AS default_expression
			FROM pg_catalog.pg_attribute attribute
			JOIN pg_catalog.pg_class class ON class.oid = attribute.attrelid AND class.relkind = 'r'
			JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
			LEFT JOIN pg_catalog.pg_attrdef defaults ON defaults.adrelid = attribute.attrelid AND defaults.adnum = attribute.attnum
			WHERE namespace.nspname = 'public' AND attribute.attnum > 0 AND NOT attribute.attisdropped
			ORDER BY class.relname, attribute.attnum
		`,
		connection`
			SELECT class.relname AS table_name, constraint_record.conname AS constraint_name,
				pg_catalog.pg_get_constraintdef(constraint_record.oid, false) AS definition
			FROM pg_catalog.pg_constraint constraint_record
			JOIN pg_catalog.pg_class class ON class.oid = constraint_record.conrelid
			JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
			WHERE namespace.nspname = 'public'
			ORDER BY class.relname, constraint_record.conname
		`,
		connection`
			SELECT index_class.relname AS index_name, pg_catalog.pg_get_indexdef(index_class.oid, 0, false) AS definition
			FROM pg_catalog.pg_index index_record
			JOIN pg_catalog.pg_class index_class ON index_class.oid = index_record.indexrelid
			JOIN pg_catalog.pg_namespace namespace ON namespace.oid = index_class.relnamespace
			WHERE namespace.nspname = 'public' AND NOT EXISTS (
				SELECT FROM pg_catalog.pg_constraint constraint_record
				WHERE constraint_record.conindid = index_record.indexrelid AND constraint_record.contype IN ('p', 'u', 'x')
			)
			ORDER BY index_class.relname
		`,
		connection`
			SELECT kind || ':' || object_name AS signature FROM (
				SELECT 'function' AS kind, procedure_record.proname AS object_name
				FROM pg_catalog.pg_proc procedure_record JOIN pg_catalog.pg_namespace namespace ON namespace.oid = procedure_record.pronamespace
				WHERE namespace.nspname = 'public'
				UNION ALL
				SELECT 'operator', operator_record.oprname
				FROM pg_catalog.pg_operator operator_record JOIN pg_catalog.pg_namespace namespace ON namespace.oid = operator_record.oprnamespace
				WHERE namespace.nspname = 'public'
				UNION ALL
				SELECT 'collation', collation_record.collname
				FROM pg_catalog.pg_collation collation_record JOIN pg_catalog.pg_namespace namespace ON namespace.oid = collation_record.collnamespace
				WHERE namespace.nspname = 'public'
				UNION ALL
				SELECT 'type', type_record.typname
				FROM pg_catalog.pg_type type_record JOIN pg_catalog.pg_namespace namespace ON namespace.oid = type_record.typnamespace
				WHERE namespace.nspname = 'public' AND type_record.typrelid = 0 AND type_record.typtype IN ('d', 'e', 'm', 'r')
				UNION ALL
				SELECT 'relation', class.relname
				FROM pg_catalog.pg_class class JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
				WHERE namespace.nspname = 'public' AND class.relkind NOT IN ('r', 'i', 'S')
				UNION ALL
				SELECT 'trigger', class.relname || '.' || trigger_record.tgname
				FROM pg_catalog.pg_trigger trigger_record
				JOIN pg_catalog.pg_class class ON class.oid = trigger_record.tgrelid
				JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
				WHERE namespace.nspname = 'public' AND NOT trigger_record.tgisinternal
				UNION ALL
				SELECT 'rule', class.relname || '.' || rewrite.rulename
				FROM pg_catalog.pg_rewrite rewrite
				JOIN pg_catalog.pg_class class ON class.oid = rewrite.ev_class
				JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
				WHERE namespace.nspname = 'public' AND rewrite.rulename <> '_RETURN'
				UNION ALL
				SELECT 'policy', class.relname || '.' || policy_record.polname
				FROM pg_catalog.pg_policy policy_record
				JOIN pg_catalog.pg_class class ON class.oid = policy_record.polrelid
				JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
				WHERE namespace.nspname = 'public'
				UNION ALL
				SELECT 'table-security', class.relname || ':row=' || class.relrowsecurity::text || ':force=' || class.relforcerowsecurity::text
				FROM pg_catalog.pg_class class
				JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
				WHERE namespace.nspname = 'public' AND class.relkind = 'r'
					AND (class.relrowsecurity OR class.relforcerowsecurity)
			) objects
			ORDER BY signature
		`,
	])
	return {
		relations: sorted(relations.flatMap((row: { signature?: unknown }) => (typeof row.signature === 'string' ? [row.signature] : []))),
		columns: sorted(
			columns.flatMap((row: Record<string, unknown>) => {
				if (typeof row['table_name'] !== 'string' || typeof row['column_name'] !== 'string' || typeof row['formatted_type'] !== 'string' || typeof row['not_null'] !== 'boolean' || typeof row['identity'] !== 'string') return []
				return [columnSignature(row['table_name'], row['column_name'], row['formatted_type'], row['not_null'], row['identity'], typeof row['default_expression'] === 'string' ? row['default_expression'] : undefined)]
			}),
		),
		constraints: sorted(constraints.flatMap((row: Record<string, unknown>) => (typeof row['table_name'] === 'string' && typeof row['constraint_name'] === 'string' && typeof row['definition'] === 'string' ? [`${row['table_name']}.${row['constraint_name']}|${normalizeDefinition(row['definition'])}`] : []))),
		indexes: sorted(indexes.flatMap((row: Record<string, unknown>) => (typeof row['index_name'] === 'string' && typeof row['definition'] === 'string' ? [`${row['index_name']}|${normalizeDefinition(row['definition'])}`] : []))),
		unsupportedObjects: sorted(unsupportedObjects.flatMap((row: { signature?: unknown }) => (typeof row.signature === 'string' ? [row.signature] : []))),
	}
}
