import type { ContractReference } from './contract-reference-metadata.mts'

export const coreContractReferences: ContractReference[] = [
	{
		compiledAbiFingerprint: '580109cfcebb3ce505def01895f7b6567e75bbd8e8ccac857bdd00d54f15c37f',
		name: 'ZoltarQuestionData',
		purpose: 'Creates immutable, content-addressed scalar or categorical questions and exposes their display metadata.',
		readAbiFingerprint: '964d0ce318d2890011ff485c8d78e933cabc8d10e489a0c22f0e266fa2563ded',
		readSurface:
			'Use `getQuestionId` before submission; `questionCreatedTimestamp` and `questions` for direct lookup; `getQuestionCount` and `getQuestions` for indexed or paged discovery; and `getQuestionEndDate`, `getOutcomeLabels`, `splitUint256IntoTwoWithInvalid`, `hasNonZeroScalarReservedBits`, `isMalformedAnswerOption`, and `getAnswerOptionName` when validating or displaying answers. In the `QuestionData` tuple, `startTime` and `endTime` are `uint48`, while `numTicks` is `uint120`; clients must use these exact widths because they determine the `getQuestionId` and `createQuestion` selectors.',
		readDeclarations: [
			{ name: 'getQuestionId' },
			{ name: 'getQuestionCount' },
			{ name: 'getQuestions' },
			{ name: 'getQuestionEndDate' },
			{ name: 'getOutcomeLabels' },
			{ name: 'splitUint256IntoTwoWithInvalid' },
			{ name: 'hasNonZeroScalarReservedBits' },
			{ name: 'isMalformedAnswerOption' },
			{ name: 'getAnswerOptionName' },
		],
		readStorageDeclarations: [{ name: 'questionCreatedTimestamp' }, { name: 'questions' }],
		sourcePath: 'solidity/contracts/ZoltarQuestionData.sol',
		interactions: [
			{
				call: '`createQuestion(questionData, outcomeOptions)`',
				caller: 'Anyone',
				effect: 'Stores the question at its deterministic content hash, records the creation timestamp, appends it to discovery order, and stores categorical labels when supplied.',
				declarations: [{ name: 'createQuestion' }],
				preconditions: 'Question ID not already created; end time is on or after start time. Scalar questions use no labels, require display maximum greater than minimum, and positive ticks. Categorical questions require nonempty labels whose `keccak256(abi.encode(label))` values are strictly descending.',
				signals: '`QuestionCreated`',
			},
		],
	},
	{
		compiledAbiFingerprint: '9aec957d945308eaeaa9a2d497f6a1efefe2253de96b527a02b121a58d9dc2ec',
		name: 'Zoltar',
		purpose: 'Registers universe forks, charges the fork admission haircut, and mints branch-specific child REP.',
		readAbiFingerprint: '888b513263619c6b31966cd009e078c19223641b9c4a6df0909bce3f797e37e2',
		readSurface:
			'Use `universes`, `forkThresholdDivisor`, `forkBurnDivisor`, `zoltarQuestionData`, `genesisReputationToken`, `childReputationTokenCount`, `getForkTime`, `forkQuestionMatches`, `getRepToken`, `getForkThresholdAttoRep`, `getNonDecisionThresholdAttoRep`, `getUniverseTheoreticalSupplyAttoRep`, `getChildUniverseId`, `getDeployedChildUniverses`, `getMigrationRepBalanceAttoRep`, and `getChildMigrationRepAmountsAttoRep` to reconstruct universe and migration state. The child migration getter accepts an array of child universe IDs and returns cumulative amounts in the same order, with zero for unused IDs. The fork threshold is the live universe theoretical supply divided by `forkThresholdDivisor`, rounded up, so every nonzero-supply universe has a positive fork cost. Construction requires a deployed genesis REP token with the REPv2 `getTotalTheoreticalSupply()` selector, theoretical supply from one attoREP through 11 million REP, and `forkBurnDivisor >= 5`, which caps the uncredited fork haircut at 20% of the threshold. Genesis REP uses ordinary ERC-20 approvals because the configured mainnet REPv2 token does not implement ERC-2612 or ERC-3009.',
		securityBoundary: 'Security boundaries for these calls are [A15 intended question selection](./security-model.html#assumption-a15) and [A25 safe immutable parameters](./security-model.html#assumption-a25).',
		readDeclarations: [
			{ name: 'getForkTime' },
			{ name: 'forkQuestionMatches' },
			{ name: 'getRepToken' },
			{ name: 'getForkThresholdAttoRep' },
			{ name: 'getNonDecisionThresholdAttoRep' },
			{ name: 'getUniverseTheoreticalSupplyAttoRep' },
			{ name: 'getChildUniverseId' },
			{ name: 'getDeployedChildUniverses' },
			{ name: 'getMigrationRepBalanceAttoRep' },
			{ name: 'getChildMigrationRepAmountsAttoRep' },
		],
		readStorageDeclarations: [{ name: 'universes' }, { name: 'forkThresholdDivisor' }, { name: 'forkBurnDivisor' }, { name: 'zoltarQuestionData' }, { name: 'genesisReputationToken' }, { name: 'childReputationTokenCount' }],
		sourcePath: 'solidity/contracts/Zoltar.sol',
		interactions: [
			{
				call: '`forkUniverse(universeId, questionId)`',
				caller: 'Any address able to fund the current fork threshold',
				effect: 'Records the fork, removes threshold REP from the parent universe, and credits the caller with the threshold minus the configured uncredited haircut.',
				declarations: [{ name: 'forkUniverse' }],
				preconditions: 'Initialized and unforked universe; existing ended question; sufficient caller REP. Genesis REP requires allowance; child REP is burned directly without allowance.',
				signals: '`UniverseForked`',
			},
			{
				call: '`burnRep(universeId, amountAttoRep)`',
				caller: 'Any REP holder; the caller can burn only its own balance',
				effect: 'Permanently removes REP without creating migration credit; escalation settlement uses this when the haircut was not paid through its own fork.',
				declarations: [{ name: 'burnRep' }],
				preconditions: 'Initialized universe; positive amount; sufficient caller REP and theoretical supply. Genesis REP requires allowance.',
				signals: '`RepBurned` and the token burn or transfer event',
			},
			{
				call: '`deployChild(universeId, outcomeIndex)`',
				caller: 'Anyone',
				effect: 'Deploys the deterministic child REP token and initializes the child universe.',
				declarations: [{ name: 'deployChild' }],
				preconditions: 'Parent forked; outcome is well formed; child is not already deployed.',
				signals: '`TheoreticalSupplySet`, `ReputationTokenInitialized`, `DeployChild`, and `ChildReputationTokenInitialized`',
			},
			{
				call: '`addRepToMigrationBalance(universeId, amountAttoRep)`',
				caller: 'Parent REP holder',
				effect: "Burns or sinks additional parent REP and increases the caller's reusable migration balance.",
				declarations: [{ name: 'addRepToMigrationBalance' }],
				preconditions: 'Universe forked; sufficient caller REP. Genesis REP requires allowance; child REP is burned directly without allowance.',
				signals: '`MigrationRepAdded`',
			},
			{
				call: '`prepareAndSplitMigrationRep`(`universeId`, `amountAttoRep`, `outcomeIndexes`, `preparationAttoRep`)',
				caller: 'Parent REP holder',
				effect:
					'Adds the supplied preparation amount to migration credit, then splits the requested REP into the supplied outcomes using the existing migration checks. Both steps revert together on failure. Callers compute any preparation shortfall from cumulative child migration amounts, rather than current child token holdings.',
				declarations: [{ name: 'prepareAndSplitMigrationRep' }],
				preconditions: 'Forked universe; positive split amount; nonempty valid outcomes; sufficient parent REP for the exact preparationAttoRep supplied and sufficient migration credit for every split. Outcome order is unrestricted. Genesis REP requires allowance for preparation; child REP needs no allowance.',
				signals: '`MigrationRepAdded` when preparationAttoRep is positive; `DeployChild`, `TheoreticalSupplySet`, and `ChildReputationTokenInitialized` when children are deployed; child REP `Transfer`, `Mint`, and `MigrationRepSplit` for each destination',
			},
			{
				call: '`splitMigrationRep(universeId, amountAttoRep, outcomeIndexes)`',
				caller: 'Migration-balance holder',
				effect: 'Mints `amountAttoRep` of child REP into every selected branch, deploying missing children lazily.',
				declarations: [{ name: 'splitMigrationRep' }],
				preconditions: "Universe forked; positive split amount; nonempty list of well-formed outcomes; the cumulative amount per child must not exceed the caller's migration balance.",
				signals: '`DeployChild`, `TheoreticalSupplySet`, and `ChildReputationTokenInitialized` when children are deployed; child REP `Transfer` and `Mint`, then `MigrationRepSplit`, per selected branch',
			},
		],
	},
	{
		compiledAbiFingerprint: 'c870ce39465c90820caef827233163f7898f339aba3563d29b7014e60da28687',
		name: 'ReputationToken',
		purpose: 'Implements universe-specific ERC-20 REP, ERC-2612 permits, and ERC-3009 transfers while enforcing the supply ceiling maintained by Zoltar.',
		readAbiFingerprint: '1cedbd5efbd60e56cb8f88586096eba913a58cbf7fc5d9908649ea4cc8a0658b',
		readSurface: 'Use `getTotalTheoreticalSupply`, `zoltar`, `universeId`, `repNumber`, the standard ERC-20 `name`, `symbol`, `decimals`, `totalSupply`, `balanceOf`, and `allowance` reads, and authorization reads `nonces`, `DOMAIN_SEPARATOR`, and `authorizationState`.',
		readDeclarations: [
			{ name: 'getTotalTheoreticalSupply' },
			{ name: 'name', sourcePath: 'solidity/contracts/ERC20.sol' },
			{ name: 'symbol', sourcePath: 'solidity/contracts/ERC20.sol' },
			{ name: 'decimals', sourcePath: 'solidity/contracts/ERC20.sol' },
			{ name: 'totalSupply', sourcePath: 'solidity/contracts/ERC20.sol' },
			{ name: 'balanceOf', sourcePath: 'solidity/contracts/ERC20.sol' },
			{ name: 'allowance', sourcePath: 'solidity/contracts/ERC20.sol' },
			{ name: 'nonces', sourcePath: 'solidity/contracts/vendor/authorization/ERC20Authorization.sol' },
			{ name: 'DOMAIN_SEPARATOR', sourcePath: 'solidity/contracts/vendor/authorization/ERC20Authorization.sol' },
			{ name: 'authorizationState', sourcePath: 'solidity/contracts/vendor/authorization/ERC20Authorization.sol' },
		],
		readStorageDeclarations: [{ name: 'zoltar' }, { name: 'universeId' }, { name: 'repNumber' }],
		sourcePath: 'solidity/contracts/ReputationToken.sol',
		interactions: [
			{
				call: '`initialize(universeId, totalTheoreticalSupplyAttoRep, repNumber)`',
				caller: '`Zoltar` only',
				effect: 'Atomically assigns the child universe, global display sequence, name, symbol, and theoretical-supply ceiling used to bound migration mints.',
				declarations: [{ name: 'initialize' }],
				preconditions: 'Called once by Zoltar as part of child-universe creation; universe, REP number, and theoretical supply are nonzero; supply does not exceed 11 million REP.',
				signals: '`TheoreticalSupplySet` and `ReputationTokenInitialized`',
			},
			{
				call: '`mint(account, valueAttoRep)`',
				caller: '`Zoltar` only',
				effect: 'Mints branch REP to an account.',
				declarations: [{ name: 'mint' }],
				preconditions: '`account` is nonzero; resulting ERC-20 supply does not exceed theoretical supply.',
				signals: '`Mint` and ERC-20 `Transfer`',
			},
			{
				call: '`burn(account, valueAttoRep)`',
				caller: '`Zoltar` only',
				effect: 'Burns account REP and reduces both actual and theoretical supply by the same amount.',
				declarations: [{ name: 'burn' }],
				preconditions: '`account` is nonzero and has sufficient REP; theoretical supply covers the burn.',
				signals: '`Burn` and ERC-20 `Transfer`',
			},
			{
				call: '`transfer(to, value)`',
				caller: 'REP holder',
				effect: 'Moves REP from the caller without changing actual or theoretical supply.',
				declarations: [{ name: 'transfer', sourcePath: 'solidity/contracts/ERC20.sol' }],
				preconditions: 'Destination is nonzero; caller has sufficient balance.',
				signals: '`Transfer`',
			},
			{
				call: '`approve(spender, value)`',
				caller: 'Any REP account setting its own allowance',
				effect: 'Replaces the named spender allowance without moving REP.',
				declarations: [{ name: 'approve', sourcePath: 'solidity/contracts/ERC20.sol' }],
				preconditions: 'Spender is nonzero.',
				signals: '`Approval`',
			},
			{
				call: '`transferFrom(from, to, value)`',
				caller: 'A spender with sufficient allowance from `from`',
				effect: 'Moves REP from `from`; a finite allowance decreases by `value`, while an infinite allowance remains unchanged. Neither allowance path emits `Approval`.',
				declarations: [{ name: 'transferFrom', sourcePath: 'solidity/contracts/ERC20.sol' }],
				preconditions: 'Source and destination are nonzero; source has sufficient balance; caller has sufficient allowance, including when caller equals source.',
				signals: '`Transfer` only',
			},
			{
				call: '`permit(owner, spender, value, deadline, v, r, s)`',
				caller: "Anyone presenting the owner's valid ERC-2612 signature",
				effect: "Sets the signed allowance and advances the owner's permit nonce.",
				declarations: [{ name: 'permit', sourcePath: 'solidity/contracts/vendor/authorization/ERC20Authorization.sol' }],
				preconditions: 'Deadline has not passed; signature matches the current chain, token domain, owner, spender, value, and nonce.',
				signals: '`Approval`',
			},
			{
				call: '`transferWithAuthorization(from, to, value, validAfter, validBefore, nonce, v, r, s)`',
				caller: "Anyone presenting the source's valid ERC-3009 signature",
				effect: 'Consumes the authorization nonce and transfers the exact signed amount to the signed recipient.',
				declarations: [{ name: 'transferWithAuthorization', sourcePath: 'solidity/contracts/vendor/authorization/ERC20Authorization.sol' }],
				preconditions: 'The strict validity window is open; the nonce is unused; signature fields and source balance are valid.',
				signals: '`AuthorizationUsed` and `Transfer`',
			},
			{
				call: '`receiveWithAuthorization(from, to, value, validAfter, validBefore, nonce, v, r, s)`',
				caller: "The signed recipient presenting the source's valid ERC-3009 signature",
				effect: 'Consumes the authorization nonce and transfers the exact signed amount to the caller-bound recipient.',
				declarations: [{ name: 'receiveWithAuthorization', sourcePath: 'solidity/contracts/vendor/authorization/ERC20Authorization.sol' }],
				preconditions: 'Caller equals the signed recipient; the strict validity window is open; the nonce is unused; signature fields and source balance are valid.',
				signals: '`AuthorizationUsed` and `Transfer`',
			},
			{
				call: '`cancelAuthorization(authorizer, nonce, v, r, s)`',
				caller: "Anyone presenting the authorizer's valid ERC-3009 cancellation signature",
				effect: 'Marks the authorization nonce as consumed without transferring tokens.',
				declarations: [{ name: 'cancelAuthorization', sourcePath: 'solidity/contracts/vendor/authorization/ERC20Authorization.sol' }],
				preconditions: 'The nonce is unused and the cancellation signature matches the authorizer.',
				signals: '`AuthorizationCanceled`',
			},
		],
	},
	{
		compiledAbiFingerprint: 'dfb1fa56f97df8c86f07105cb6b8f9e55c08205c43dce3b216331397b0196d1e',
		name: 'SecurityPoolFactory',
		purpose: 'Creates and canonically registers origin and child security pools with their share token, oracle coordinator, and optional Truth Auction.',
		readAbiFingerprint: 'ee2532194c63d917a4665729c7456b2905cf62bfd69555cb023d1c7e00566473',
		readSurface:
			'Use `minimumSecurityBondDebtAttoEth` and `minimumVaultRepDepositAttoRep` for immutable deployment floors. Each pool derives its effective escalation deposit directly from its REP token at construction as `max(1 REP, theoretical REP supply / 10,000,000)`. A zero configured vault REP floor selects the default `theoretical REP supply / 100,000`; a nonzero constructor value is the exact override. The security-bond debt floor defaults to 1 ETH. Construction rejects a zero or code-less operations delegate. Use `securityPoolDeploymentCount` with the strict `securityPoolDeploymentsRange(startIndex, count)` pager, which reverts rather than truncating when the requested range exceeds the array. Use `getOriginId`, `getPoolId`, `getSecurityPool`, `getSecurityPoolOriginId`, and `getSecurityPoolHasInheritedForkOutcome` for canonical lookup.',
		readDeclarations: [{ name: 'securityPoolDeploymentCount' }, { name: 'securityPoolDeploymentsRange' }, { name: 'getOriginId' }, { name: 'getPoolId' }, { name: 'getSecurityPool' }, { name: 'getSecurityPoolOriginId' }, { name: 'getSecurityPoolHasInheritedForkOutcome' }],
		readStorageDeclarations: [{ name: 'minimumSecurityBondDebtAttoEth' }, { name: 'minimumVaultRepDepositAttoRep' }],
		sourcePath: 'solidity/contracts/statoblast/factories/SecurityPoolFactory.sol',
		interactions: [
			{
				call: '`deployOriginSecurityPool(universeId, questionId, statoblastSecurityMultiplierBps, initialReportPriorityFeeAttoEthPerGas)`',
				caller: 'Anyone',
				effect: 'Creates the canonical origin pool, its lineage-wide share token, and its price coordinator with the configured initial-report priority fee, then wires and registers them atomically.',
				declarations: [{ name: 'deployOriginSecurityPool' }],
				preconditions:
					'`statoblastSecurityMultiplierBps > 10_001`, which makes the halfway migration component strictly greater than one; the effective pool-held vault REP backing multiplier separately floors that component at the 10,500-BPS liquidation-award reserve described by the [liquidation design](../explanation/liquidations.html#rule). `initialReportPriorityFeeAttoEthPerGas > 0` and remains within the coordinator-computed OpenOracle `uint128` report/escalation-halt capacity bound; question exists, the transaction timestamp is strictly before its end time, and it has exactly the categorical labels `Yes`, then `No`; universe is unforked and has a REP token; the non-decision threshold exceeds the construction-time effective escalation deposit `max(1 REP, theoretical REP supply / 10,000,000)`; the origin/universe/priority-fee slot has not already been claimed.',
				signals: '`SecurityPoolRegistered`, then `DeploySecurityPool`',
			},
			{
				call: '`deployChildSecurityPool(parent, shareToken, universeId, questionId, statoblastSecurityMultiplierBps, currentRetentionRate, settlementCollateralAttoEth)`',
				caller: '`SecurityPoolForker` only',
				effect: 'Creates and registers a canonical child pool with a coordinator that inherits `initialReportPriorityFeeAttoEthPerGas` from the parent coordinator and a forker-owned Truth Auction, while retaining the parent lineage share token.',
				declarations: [{ name: 'deployChildSecurityPool' }],
				preconditions: 'Parent is the canonical pool for its lineage; supplied share token equals the parent share token; target origin/universe slot is unclaimed; deployment arguments satisfy downstream constructors and wiring.',
				signals: '`SecurityPoolRegistered`, then `DeploySecurityPool`',
			},
		],
	},
]
