import type { ContractReference } from './contract-reference-metadata.mts'

export const forkEscalationContractReferences: ContractReference[] = [
	{
		compiledAbiFingerprint: 'cbde7d4ca1c41aa7a92d04162002915ae0edbcf1e47ae3cf9328a0603356d840',
		name: 'SecurityPoolForker',
		purpose: 'Freezes parent pools, creates selected child pools, migrates vault and escalation state, and settles collateral-repair [Truth Auctions](./glossary.html#truth-auction).',
		readAbiFingerprint: '44f89debf797ddb63c2614a513b7d04dfe528074f30a513ae53c700d9627fb51',
		readSurface:
			'Use `zoltar`, `forkData`, `getUnassignedPosition`, `isEscalationDepositClaimedDirectly`, `getEscalationDepositId`, `getDirectlyClaimedEscalationPrincipal`, `isEscalationWinnerHaircutPaidByFork`, `getEscalationMigrationEntitlementStatus`, `getOwnForkRepBuckets`, `getOwnForkMigrationStatus`, `getMigrationProxyAddress`, `getQuestionOutcome`, `attoRepToBackingUnits`, and `backingUnitsToAttoRep` to reconstruct fork progress and preview migration conversions. `forkData` includes cumulative migrated REP and the fork-activation timestamp. `getUnassignedPosition` returns pending REP backing units, underwriting commitment, raw auction bad debt, that debt’s generation, and the auction-finalization fee index; consumers count the debt only while its generation equals the pool snapshot’s current `badDebtGeneration`.',
		readDeclarations: [
			{ name: 'forkData' },
			{ name: 'getUnassignedPosition' },
			{ name: 'isEscalationDepositClaimedDirectly' },
			{ name: 'getEscalationDepositId' },
			{ name: 'getDirectlyClaimedEscalationPrincipal' },
			{ name: 'isEscalationWinnerHaircutPaidByFork' },
			{ name: 'getEscalationMigrationEntitlementStatus' },
			{ name: 'getOwnForkRepBuckets' },
			{ name: 'getOwnForkMigrationStatus' },
			{ name: 'getMigrationProxyAddress' },
			{ name: 'getQuestionOutcome' },
			{ name: 'attoRepToBackingUnits', sourcePath: 'solidity/contracts/statoblast/SecurityPoolForkerBase.sol' },
			{ name: 'backingUnitsToAttoRep', sourcePath: 'solidity/contracts/statoblast/SecurityPoolForkerBase.sol' },
		],
		readStorageDeclarations: [{ name: 'zoltar', sourcePath: 'solidity/contracts/statoblast/SecurityPoolForkerBase.sol' }],
		interactionNotes: '`claimForkedEscalationDeposits` and `migrateVaultWithUnresolvedEscalation` revert without reason data when one of the prerequisites marked "no reason data" fails; the forker omits those reason strings to stay within the contract code-size limits.',
		securityBoundaryHeading: 'Child-game trust boundary',
		securityBoundary:
			'Fork entrypoints and child setup may receive contracts through unauthenticated pool lineages. External-universe initiation requires the supplied pool to be authorized by its declared share token, but that relationship alone does not prove factory registration; own-game initiation does not perform that authorization check. Canonicality comes from the configured `SecurityPoolFactory` registry. A game relationship check is point-in-time: the reported nonzero game address must return the supplied pool or child from `securityPool()` when validated. This does not prove that an arbitrary game getter is immutable or that the address was factory-deployed. Child setup captures one reported game address, validates it before privileged use, and reuses that exact address for continuation backing and escrow work. When unresolved escalation requires a continuation and setup initially reports no game, initialization creates one; the forker then captures and validates it before continuation use. Combined vault migration passes the captured child/game pair into unresolved cleanup without reading the child getter again. Truth Auction completion performs a fresh point-in-time validation of the game reported then before checking continuation readiness. Genuine factory-deployed `EscalationGame` instances store their pool immutably, but safety on unauthenticated paths does not assume arbitrary contracts do.',
		sourcePath: 'solidity/contracts/statoblast/SecurityPoolForker.sol',
		interactions: [
			{
				call: '`initiateSecurityPoolFork(securityPool)`',
				caller: 'Anyone',
				effect: 'Freezes the supplied pool after an external universe fork, drains its pool and game REP, and records a migration snapshot keyed by that address. The snapshot is canonical only when the supplied pool is already registered by the configured `SecurityPoolFactory`.',
				declarations: [{ name: 'initiateSecurityPoolFork' }],
				preconditions:
					'Pool operational with no inherited fixed outcome; the pool is authorized by its declared share token; its universe already forked; pool not already `PoolForked`; if an escalation game exists, it reports the supplied pool from `securityPool()` when validated and the universe fork occurred before that game settled. Declared-token authorization is not configured-factory registration; see the [child-game trust boundary](#child-game-trust-boundary).',
				signals: '`SecurityPoolForkSnapshot` and `ParentRepLocked`; additionally `DisputeStakedRepDrainedAtFork` when unresolved escalation exists',
			},
			{
				call: '`forkZoltarWithOwnEscalationGame(securityPool)`',
				caller: 'Anyone',
				effect: "Uses the supplied pool game's non-decision to fork Zoltar, freezes that pool, and records own-fork REP buckets and snapshot state keyed by its address. The snapshot is canonical only when the supplied pool is already registered by the configured `SecurityPoolFactory`.",
				declarations: [{ name: 'forkZoltarWithOwnEscalationGame' }],
				preconditions:
					'Pool operational with no inherited fixed outcome; its escalation game reports the supplied pool from `securityPool()` when validated and `canTriggerOwnFork()` is true because it recorded a local non-decision or inherited a threshold tie without a game-level fixed outcome (`Need game`); pool not already `PoolForked` (`Forked`) and `Operational` (`Inactive`); universe not already forked; the pool and game REP released to the forker reaches the Zoltar fork threshold (`Fork threshold not reached`). The game-local predicate does not bypass the pool guard. Unlike external-universe initiation, this entrypoint does not require declared-share-token authorization; neither path authenticates the supplied address against the configured pool factory. See the [child-game trust boundary](#child-game-trust-boundary).',
				signals: '`SecurityPoolForkSnapshot`, `ParentRepLocked`, and Zoltar fork events; additionally `DisputeStakedRepDrainedAtFork` when unresolved escalation exists',
			},
			{
				call: '`migrateRepToZoltar(securityPool, outcomeIndices)`',
				caller: 'Anyone',
				effect: "For a positive migration amount and nonempty list, ensures that the forker's recorded pool migration amount has been split into each selected child REP branch. A zero migration amount or empty list returns after the proxy and pool-state guards without per-outcome validation or events.",
				declarations: [{ name: 'migrateRepToZoltar' }],
				preconditions:
					'Migration proxy exists and the pool is `PoolForked`. Only a positive migration amount with at least one selected outcome checks the eight-week window, existing child `ForkMigration` state, outcome validity, and cumulative split bound. A zero amount skips those checks even when outcome values are supplied.',
				signals: '`MigrationRepSplit` and `ChildRepSplit` when a selected branch requires a new split; no event for a zero amount, empty list, or already-satisfied branch',
			},
			{
				call: '`createChildUniverse(securityPool, outcomeIndex)`',
				caller: 'Anyone',
				effect:
					"Loads an already deployed child universe and REP token or deploys them when absent, then lazily deploys the selected child pool, coordinator, and auction; authorizes and links the child; captures and validates the child's escalation game; and initializes any continuation snapshot and materializes or sweeps child backing through that validated game.",
				declarations: [{ name: 'createChildUniverse' }],
				preconditions:
					"Parent in migration window; selected fork outcome is well formed; child pool is not already deployed. The returned auction is nonzero, deployed, and has never been trusted by this forker; the child's fork-data slot is unused; and the child reports the expected parent, universe, source factory, forker, and auction. The selected child's reported nonzero escalation game passes the [child-game trust boundary](#child-game-trust-boundary). These relationship checks do not independently prove configured-factory registration.",
				signals:
					'`DeployChild` only when child REP was absent; always `SecurityPoolRegistered`, `DeploySecurityPool`, `AuthorizationUpdated`, `ChildPoolLinked`, and `TotalRepBackingUnitsSet`; `AwaitingForkContinuationSet`, `EscalationGameSet`, `GameContinuedFromFork`, `ForkCarryCheckpoint`, `MigrationRepSplit`, `ChildDisputeStakedRepMaterialized`, and `PoolHeldRepSweptToChild` as continuation and backing state requires',
			},
			{
				call: '`migrateVault(securityPool, outcomeIndex)`',
				caller: 'Vault owner for their non-escrowed position',
				declarations: [{ name: 'migrateVault' }],
				effect:
					"Converts the caller's parent REP backing-unit claim to REP at the fork snapshot and credits that REP amount as child-local backing units; transfers the underwriting commitment and any tracked vault bad debt into one child pool; checkpoints but retains claimable fees in the parent vault; and separately routes proportional pool-level settlement collateral while preserving aggregate bad debt. The underwriting commitment migrates separately from REP backing. Repeat calls can have no additional REP backing units, underwriting commitment, or vault bad debt to move.",
				preconditions: "Migration window open; the selected child's reported nonzero escalation game passes the [child-game trust boundary](#child-game-trust-boundary). The optional unresolved parent escalation-deposit accounting cleanup wrapper calls this function first to migrate transferable vault state.",
				signals: '`VaultBadDebtMigrated` and `VaultMigrationCheckpoint`',
			},
			{
				call: '`migrateVaultWithUnresolvedEscalation(securityPool, vault, childOutcomeIndex)`',
				caller: 'The named vault owner',
				effect:
					"First runs `migrateVault(securityPool, childOutcomeIndex)` for the caller, with that row's effects, and keeps the child and the validated escalation game that call captured, without reading the child's game again. It then clears that vault's unresolved parent escalation-deposit accounting in constant-size work and records it; the cleanup neither funds dispute-staked REP backing nor authorizes carried proofs.",
				declarations: [{ name: 'migrateVaultWithUnresolvedEscalation' }],
				preconditions: "The `migrateVault` prerequisites. No reason data: caller equals `vault`; migration window open; the fork recorded unresolved escalation (`unresolvedEscalationAtFork`); selected child not already recorded for this vault's cleanup; the selected child has an escalation game.",
				signals: 'The `migrateVault` signals; `EscalationMigrationEntitlementInitialized` on the first cleanup for the vault; `EscalationMigrationEntitlementMaterialized` for the selected child',
			},
			{
				call: '`claimForkedEscalationDeposits(securityPool, vault, outcomeIndex, depositIndexes)`',
				caller: 'The named vault owner (`Vault`)',
				effect:
					"First gets or lazily deploys the selected child universe, REP token, pool, coordinator, and auction, then captures and validates the child's escalation game and uses that same game for continuation backing and escrow payment. A nonempty list claims winning own-fork parent deposits and records their stable identities against descendant replay. An empty list still performs child setup and emits a zero-valued claim summary.",
				declarations: [{ name: 'claimForkedEscalationDeposits' }],
				preconditions:
					'Caller equals `vault`. No reason data: unresolved escalation existed when the pool initiated its own fork and the parent game still satisfies `canTriggerOwnFork()` by having either a local non-decision or an inherited threshold tie without a fixed outcome; the selected child remains in `ForkMigration`, is inside the eight-week claim window, and has a continuation game; every listed deposit commits `vault` as its immutable depositor. The selected child can be created or loaded and its game passes the [child-game trust boundary](#child-game-trust-boundary). A nonempty list additionally requires the matching winning outcome and unclaimed deposit identities.',
				signals:
					'`DeployChild`, `SecurityPoolRegistered`, `DeploySecurityPool`, `AuthorizationUpdated`, `ChildPoolLinked`, `TotalRepBackingUnitsSet`, `AwaitingForkContinuationSet`, `EscalationGameSet`, `GameContinuedFromFork`, `ForkCarryCheckpoint`, `MigrationRepSplit`, `ChildDisputeStakedRepMaterialized`, and `PoolHeldRepSweptToChild` as setup requires; per claimed deposit, `CarryDepositConsumed` and `ClaimDeposit`; escrow record/export events when REP is paid; always `ClaimForkedEscalationDepositsToWallet`, including for an empty list',
			},
			{
				call: '`startTruthAuction(securityPool)`',
				caller: 'Anyone',
				effect: "Copies the frozen parent's remaining economic claim supply into the child, closes migration accounting, and either reopens a fully backed child or starts its repair auction.",
				declarations: [{ name: 'startTruthAuction' }],
				preconditions: 'Child migration window ended; pool is in fork migration; required child REP is available. If unresolved escalation existed at fork, any game reported during immediate completion passes the [child-game trust boundary](#child-game-trust-boundary).',
				signals: '`ShareTokenSupplySet`, then `TruthAuctionStarted` when an auction starts; immediate no-auction completion instead emits `TruthAuctionFinalized`, pool accounting checkpoints, and `ForkContinuationResumed` for an unresolved continuation',
			},
			{
				call: '`finalizeTruthAuction(securityPool)`',
				caller: 'Anyone',
				effect:
					'Finalizes the ended auction, accounts migration-routed settlement collateral plus accepted bid ETH, and records every unmigrated REP backing unit, commitment unit, and the unmigrated remainder of the parent’s fork-time bad debt in an explicit nonwithdrawable unassigned position. It activates the child and saves the fee index. For positive existing-owner REP residue, total backing units are P × H / (H − Q), rounded up to a whole unit, where P is fork-time pool-held REP for all existing owners including unmigrated vault owners, H is finalization pool-held REP including sold escrow REP, and Q is purchased REP. The bidder backing-unit budget is total units minus P. If H − Q is zero, bidder units use H × PRICE_PRECISION (1e18) while migrated units remain in the total. Underwriting commitment has a separate budget. Positive-purchase auction ownership becomes fee eligible immediately; after a zero-purchase auction, the unassigned underwriting commitment remains outside fee eligibility.',
				declarations: [{ name: 'finalizeTruthAuction' }],
				preconditions:
					'`msg.value` is zero (`No repair ETH`); the Truth Auction started and its one-week window has passed (`Auction open`). Actual child ETH covers the installed settlement collateral plus accrued fee liabilities. Installing these inherited liabilities does not require current REP backing. If unresolved escalation existed at fork, the game reported at completion passes the [child-game trust boundary](#child-game-trust-boundary).',
				signals: '`TruthAuctionFinalized`, auction `AuctionFinalized`, and pool accounting checkpoints; `TruthAuctionHaircutApplied` when purchased REP removes a positive escalation allocation; `ForkContinuationResumed` for an unresolved continuation',
			},
			{
				call: '`settleAuctionBids(securityPool, vault, claimTickIndices, refundTickIndices)`',
				caller: 'Anyone on behalf of the named bidder vault',
				declarations: [{ name: 'settleAuctionBids' }],
				effect: 'Before finalization, refunds the listed provably losing bids through the auction `refundLosingBidsFor`. After finalization, appends the refund list to the claim list and performs the `claimAuctionProceeds` settlement on the combined list.',
				preconditions: 'At least one index (`Need action`). Before finalization the claim list must be empty (`Not final`) and the refund indexes must satisfy the `refundLosingBidsFor` prerequisites. After finalization, the `claimAuctionProceeds` prerequisites apply to the combined list.',
				signals: 'Before finalization, auction `BidSettled` per refunded bid and one aggregate `EthRefundCredited` when total credited ETH is positive. After finalization, the `claimAuctionProceeds` signals',
			},
			{
				call: '`takeOverUnassignedCommitment(securityPool, maximumCommitmentAttoEth)`',
				caller: 'Receiving vault owner',
				declarations: [{ name: 'takeOverUnassignedCommitment' }],
				effect:
					'Assigns all residual ETH commitment, unassigned REP backing, and unclaimed auctioned bad debt from a finalized zero-purchase auction to the caller; the bad debt is assigned only while the recorded auction bad-debt generation is current. Conserves total commitments and backing units. Preserves earned fees and starts recovered fee rights at the takeover checkpoint.',
				preconditions: 'Positive residual commitment within the caller’s explicit maximum; no auction purchases; fresh price; operational, unforked pool; receiver fully backs its entire resulting underwriting commitment. Sold entitlements are never available for takeover.',
				signals: '`UnassignedCommitmentTakenOver` and vault/pool accounting checkpoints',
			},
			{
				call: '`claimAuctionProceeds(securityPool, vault, tickIndices)`',
				caller: 'Anyone on behalf of the named bidder vault',
				declarations: [{ name: 'claimAuctionProceeds' }],
				effect:
					"For a nonempty list, withdraws finalized bid settlements and transfers each claim's proportional REP backing units, underwriting commitment, and finalization-to-claim fees from the unassigned position to the bidder vault. Its bad-debt share transfers only while the auction's recorded debt generation is still current; after those collateral claims are exhausted, the old debt expires while raw claimed-auction counters continue to settle deterministically. Commitment and bad-debt division dust follows each bid's deterministic cumulative ETH position, so claim order cannot change individual or aggregate settlement. The transfer does not change total underwriting commitment, fee eligibility, active open interest, total bad debt, retention, or aggregate accrued fees. A winning dust bid can receive underwriting commitment when its REP allocation rounds to zero. The call's aggregate positive refund is credited to the named bidder's pull-payment balance without calling recipient code. For an empty list, the wrapper exits after the finalization guard without validating bids or the named beneficiary, changing state, or emitting events.",
				preconditions: 'Auction finalized (`Not final`). A nonempty list additionally requires every index to belong to the named vault owner and remain unsettled.',
				signals:
					'For processed bids, underlying auction `BidSettled`; one aggregate `EthRefundCredited` per call when total credited ETH is positive; `ClaimAuctionProceeds` when REP backing, underwriting commitment, or raw auction bad-debt settlement advances. Its cumulative claimed and total auctioned bad-debt fields are raw counters; effective vault debt still requires the recorded auction generation to match the pool’s current generation; no event for an empty list',
			},
			{
				call: '`initializeChildForkedEscalationGameIfNeeded(parent, child, childEscalationGame)`',
				caller: 'This `SecurityPoolForker` contract only (`Only self`), through its migration delegate callback',
				effect:
					'Allows delegated migration code to initialize a child continuation while preserving the forker as the authoritative caller and the already captured child-game identity. When unresolved escalation requires a continuation and no game existed, it captures and validates the game created by initialization before any continuation use.',
				declarations: [{ name: 'initializeChildForkedEscalationGameIfNeeded' }],
				preconditions: 'External caller is the forker itself, so parent and child come from its own migration path; a supplied nonzero game passes the [child-game trust boundary](#child-game-trust-boundary).',
				signals: '`EscalationGameSet` and `GameContinuedFromFork` when a continuation game is created; `ForkCarryCheckpoint` when the carry snapshot is installed; `ForkContinuationResumed` and `AwaitingForkContinuationSet` only when the child is already operational',
			},
			{
				call: 'Direct ETH transfer to `receive()`',
				caller: 'A child-pool Truth Auction trusted by this forker during `ChildPoolLinked` (`Only trusted auction`)',
				effect: 'Accepts auction ETH during forker-controlled auction finalization.',
				declarations: [{ kind: 'receive', name: 'receive' }],
				preconditions: '`trustedAuctionAddresses[msg.sender]` was set when the forker linked the child and emitted `ChildPoolLinked`; configured-factory registration determines whether that lineage is canonical.',
				signals: 'No dedicated receive event; auction `AuctionFinalized` is followed by forker `TruthAuctionFinalized` and pool accounting checkpoints',
			},
		],
	},
	{
		compiledAbiFingerprint: '4b56e4d5ffb33e8069757425ff28959cc54d714529927f0b71f221a4e03a1ebd',
		name: 'EscalationGame',
		purpose: 'Escrows outcome REP, raises the running resolution cost, detects [non-decision](./glossary.html#non-decision-threshold), and settles local or carried deposits.',
		readAbiFingerprint: '758abbd7c7c8651a4529ea9dd79049f8eb134075cde6fa80042ad2ec3151a30b',
		readSurface:
			'Base getters are `securityPool`, `repToken`, `activationTime`, `nonDecisionThresholdAttoRep`, `startBondAttoRep`, `nonDecisionTimestamp`, `nonDecisionState`, `forkContinuation`, `forkElapsedAtStart`, `forkResumedAt`, `fixedQuestionOutcome`, `nodes`, `disputeStakedRepByVaultAttoRep`, `totalDisputeStakedAttoRep`, `truthAuctionRepBeforeAttoRep`, and `truthAuctionRepRemainingAttoRep`. The fallback forwards every selector other than the two signed deposits to `EscalationGameClaimDelegate`, which provides the reads `rootClaimSourceGame`, `getInheritedClaimAllocation`, and `getUnresolvedClaimInterval`. The allocation read returns source principal, retained principal, reward-interval length, and the cumulative reward endpoint after per-generation auction rounding. The reward interval is the deposit’s range within its outcome’s cumulative deposits: its start is the returned endpoint minus the returned length. It determines which portion enters the reward calculation; the length is not a payable reward. Exported principal intervals compact consumed prefixes, while reward positions remain unshifted by prior claims. Allocations within a game stay fixed in every claim order. `disputeStakedRepByVaultAttoRep` is locally attributed current-game escrow used for health; inherited carry remains aggregate commitment state until proof settlement. Use `previewDepositOnOutcome`, `computeIterativeAttritionCostAttoRep`, `computeTimeSinceStartFromAttritionCostAttoRep`, `totalCostAttoRep`, `getEscalationGameEndDate`, `getQuestionResolution`, `getFinalQuestionResolution`, `hasReachedNonDecision`, `canTriggerOwnFork`, `getBindingCapitalAttoRep`, `getOutcomeBalancesAttoRep`, `getDepositsByOutcome`, `getDepositsByOutcomeLength`, `forkCarrySnapshotInitialized`, `getOutcomeState`, `getForkCarrySnapshot`, `getForkCarryRoots`, `isForkCarryFundingComplete`, `getCarryLeafPageByOutcome`, `getProofConsumedCarriedDepositIndexesByOutcome`, `getLocalUnresolvedPrincipalByVaultAndOutcome`, and `getForkedEscrowByVaultAndOutcome` for calculations, lifecycle authorization, pages, carry state, and escrow. Vault-funded deposits and ordinary withdrawals route through `SecurityPool`, while own-fork direct claims route through `SecurityPoolForker`; after an ordinary game starts, wallet-funded deposits use `depositRepOnOutcome`, `depositRepOnOutcomeWithPermit`, or `depositRepOnOutcomeWithAuthorization` and mint no pool backing units.',
		interactionNotes:
			'Rows marked "through `fallback()`" are not in the compiled ABI: the fallback forwards the two signed deposit selectors to `EscalationGameDepositDelegate` and every other unknown selector to `EscalationGameClaimDelegate` by `delegatecall`, and returns or reverts with the delegate output. A call restricted to the owning pool or its forker reverts without reason data for any other caller.',
		readDeclarations: [
			{ name: 'previewDepositOnOutcome' },
			{ name: 'disputeStakedRepByVaultAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameState.sol' },
			{ name: 'rootClaimSourceGame', sourcePath: 'solidity/contracts/statoblast/EscalationGameClaimDelegate.sol' },
			{ name: 'getInheritedClaimAllocation', sourcePath: 'solidity/contracts/statoblast/EscalationGameClaimDelegate.sol' },
			{ name: 'getUnresolvedClaimInterval', sourcePath: 'solidity/contracts/statoblast/EscalationGameClaimDelegate.sol' },
			{ name: 'computeIterativeAttritionCostAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'computeTimeSinceStartFromAttritionCostAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'totalCostAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'getEscalationGameEndDate', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'getQuestionResolution', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'getFinalQuestionResolution', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'hasReachedNonDecision', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'canTriggerOwnFork', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'getBindingCapitalAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'getOutcomeBalancesAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameCalculations.sol' },
			{ name: 'getDepositsByOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' },
			{ name: 'getDepositsByOutcomeLength', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' },
			{ name: 'forkCarrySnapshotInitialized', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' },
			{ name: 'getOutcomeState', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' },
			{ name: 'getForkCarrySnapshot', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' },
			{ name: 'getForkCarryRoots', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' },
			{ name: 'isForkCarryFundingComplete', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' },
			{ name: 'getCarryLeafPageByOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' },
			{ name: 'getProofConsumedCarriedDepositIndexesByOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' },
			{ name: 'getLocalUnresolvedPrincipalByVaultAndOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameEscrow.sol' },
			{ name: 'getForkedEscrowByVaultAndOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameEscrow.sol' },
		],
		readStorageDeclarations: [
			{ name: 'securityPool', sourcePath: 'solidity/contracts/statoblast/EscalationGameState.sol' },
			{ name: 'repToken', sourcePath: 'solidity/contracts/statoblast/EscalationGameState.sol' },
			{ name: 'activationTime', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'nonDecisionThresholdAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'startBondAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'nonDecisionTimestamp', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'nonDecisionState', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'forkContinuation', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'forkElapsedAtStart', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'forkResumedAt', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'nodes', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'totalDisputeStakedAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'truthAuctionRepBeforeAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'truthAuctionRepRemainingAttoRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
			{ name: 'fixedQuestionOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameStorage.sol' },
		],
		sourcePath: 'solidity/contracts/statoblast/EscalationGame.sol',
		interactions: [
			{
				call: '`start(startBondAttoRep, nonDecisionThresholdAttoRep)`',
				caller: 'Immutable owner, the `EscalationGameFactory`, only (`Only owner`), during atomic deployment',
				effect: 'Initializes a local game and sets activation three days after deployment. For ordinary pool games, the factory lowers an oversized configured bond to `nonDecisionThresholdAttoRep - 1` before this call.',
				declarations: [{ name: 'start' }],
				preconditions: 'Game not already started, and `nonDecisionThresholdAttoRep > startBondAttoRep > 0` (`Invalid game start`).',
				signals: '`GameStarted`',
			},
			{
				call: '`startFromFork(startBondAttoRep, nonDecisionThresholdAttoRep, elapsedAtFork, fixedQuestionOutcome, winnerHaircutPaidByFork, forkCarryInitialBackingAttoRep)`',
				caller: 'Immutable owner, the `EscalationGameFactory`, only (`Only owner`), during atomic continuation deployment',
				effect: 'Initializes a paused continuation with inherited elapsed time, an optional fixed matching child outcome, and immutable fork-time escalation-haircut and backing accounting. It does not start the remaining clock until `resumeFromFork`.',
				declarations: [{ name: 'startFromFork' }],
				preconditions: 'Game not already started, and `nonDecisionThresholdAttoRep > startBondAttoRep > 0` (`Invalid game start`); `elapsedAtFork` is at most seven weeks (`Invalid fork elapsed time`).',
				signals: '`GameContinuedFromFork`',
			},
			{
				call: '`resumeFromFork()`',
				caller: 'Owning `SecurityPool` only (`Only pool`)',
				effect:
					'Records the resume timestamp once carry funding is complete. The new deadline is `max(rebasedCurveEnd, forkResumedAt + 3 days)`, so even an exhausted inherited clock receives a fresh response period. After that deadline, `getFinalQuestionResolution` returns the fixed outcome when the continuation has one.',
				declarations: [{ name: 'resumeFromFork' }],
				preconditions:
					'Fork-continuation mode; not previously resumed; aggregate REP funding complete (`isForkCarryFundingComplete`). The game does not itself require an installed snapshot; the forker installs it during child initialization. An unrelated fork requires one-to-one backing of effective unresolved principal. For an own-fork continuation, recorded initial backing must be at least `R - ⌊R / 5⌋`, where `R` is the sum of `inheritedUnresolvedTotalAttoRep` and `localUnresolvedTotalAttoRep` across all three outcomes before direct-claim deductions, and `5` is the fixed `Constants.MINIMUM_FORK_BURN_DIVISOR` rather than the configured fork burn divisor. The live balance must cover that initial backing minus child REP already exported by valid direct pre-resume claims, scaled down by any REP `applyTruthAuctionHaircut` removed.',
				signals: '`ForkContinuationResumed`',
			},
			{
				call: '`applyTruthAuctionHaircut(repToRemoveAttoRep)`',
				caller: "The child pool's `SecurityPoolForker` only (`Only forker`)",
				declarations: [{ name: 'applyTruthAuctionHaircut' }],
				effect:
					'Transfers sold REP to the pool, proportionally reduces escrow and outcome balances, and rebases curve time. If an unfixed continuation inherited two threshold-full outcome balances and the auction REP removal leaves them below the current game threshold, ordinary pool-mediated deposit checks apply after the pool resumes the game. Fixed outcomes and local non-decisions retain their state. The game stays paused until the pool resumes it.',
				preconditions: "Paused fork continuation; no prior auction haircut; the requested amount is below the game's live REP balance.",
				signals: '`TruthAuctionHaircutApplied` and REP `Transfer`; `InheritedThresholdTieReopened` when an unfixed inherited tie reopens',
			},
			{
				call: '`depositRepOnOutcome(outcome, maximumDepositAttoRep)`',
				caller: 'Any REP holder',
				effect: 'Transfers the accepted REP directly from the caller into dispute escrow, appends a local deposit, and records its carry leaf without minting pool backing units.',
				declarations: [{ name: 'depositRepOnOutcome' }],
				preconditions: "Current game is the pool's ordinary unresolved game; pool operational; universe unforked; outcome non-`None`; caller allowance to this game covers the accepted REP; preview accepts a positive amount within the remaining threshold room.",
				signals: 'REP `Transfer`, `LocalDepositAppended`, `DepositOnOutcome`, and `NonDecisionReached` when the deposit reaches non-decision',
			},
			{
				call: '`depositRepOnOutcomeWithPermit(outcome, maximumDepositAttoRep, deadline, v, r, s)` through `fallback()`',
				caller: 'Any child-universe REP holder',
				effect: 'Calls the REP token `permit` for the previewed amount from the caller to this game, ignores a failed permit when the existing allowance already covers that amount, then performs the `depositRepOnOutcome` deposit.',
				declarations: [{ kind: 'fallback-routed', name: 'depositRepOnOutcomeWithPermit', sourcePath: 'solidity/contracts/statoblast/EscalationGameDepositDelegate.sol' }],
				preconditions: 'The `depositRepOnOutcome` game, pool, and preview prerequisites; the pool universe is not genesis (`Genesis REP does not support permit`); the permit succeeds or the caller allowance to this game covers the previewed amount (`Game permit and allowance insufficient`).',
				signals: 'REP `Approval` when the permit succeeds, then the `depositRepOnOutcome` signals',
			},
			{
				call: '`depositRepOnOutcomeWithAuthorization(owner, outcome, maximumDepositAttoRep, validAfter, validBefore, nonce, v, r, s)` through `fallback()`',
				caller: "Anyone relaying the owner's ERC-3009 signature",
				effect: 'Pulls the previewed amount from `owner` to this game through the REP token `receiveWithAuthorization` and records the deposit for `owner`.',
				declarations: [{ kind: 'fallback-routed', name: 'depositRepOnOutcomeWithAuthorization', sourcePath: 'solidity/contracts/statoblast/EscalationGameDepositDelegate.sol' }],
				preconditions:
					'The `depositRepOnOutcome` game, pool, and preview prerequisites; the pool universe is not genesis (`Genesis REP does not support authorization`); the signature authorizes the token nonce `keccak256(abi.encode(nonce, operationHash, owner))`, where `operationHash` is `keccak256(abi.encode(depositRepOnOutcomeWithAuthorization.selector, owner, securityPool, universeId, questionId, outcome, maximumDepositAttoRep, previewedAmount))`.',
				signals: 'REP `AuthorizationUsed` and `Transfer`, `LocalDepositAppended`, `DepositOnOutcome`, and `NonDecisionReached` when the deposit reaches non-decision',
			},
			{
				call: '`recordDepositFromSecurityPool(depositor, outcome, amountAttoRep, expectedCumulativeAttoRep)`',
				caller: 'Owning `SecurityPool` only (`Only pool`)',
				effect: 'Appends an accepted local deposit, updates outcome and vault escrow, and records its carry leaf.',
				declarations: [{ name: 'recordDepositFromSecurityPool' }],
				preconditions: 'Explicit non-decision state is `None`; game unresolved; valid outcome; preview and accepted cumulative amount match; room remains below threshold.',
				signals: '`LocalDepositAppended`, `DepositOnOutcome`, and `NonDecisionReached` when the deposit reaches non-decision',
			},
			{
				call: '`withdrawDeposit(depositIndex, outcome)`, the `uint256` overload',
				caller: 'Owning `SecurityPool` only (`Only pool`)',
				declarations: [{ name: 'withdrawDeposit', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' }],
				effect: "Consumes one local deposit after resolution. A winner pays the deposit's immutable depositor after its escalation haircut; a loser only retires its escrow accounting.",
				preconditions: 'Explicit non-decision state is `None`; non-`None` supplied outcome; game final; game and pool final outcomes match; valid unsettled local deposit index.',
				signals: '`CarryDepositConsumed` and `VaultEscrowUpdated`; for a winner, `ClaimDeposit`, positive REP payout `Transfer`, and escalation-haircut burn signals when nonzero',
			},
			{
				call: '`initializeForkCarrySnapshotWithResolutionBalances(sourceGame, snapshotId, snapshotPeaksInput, snapshotLeafCountsInput, snapshotCarryTotalsAttoRep, snapshotResolutionBalancesAttoRep, snapshotNullifierRoots)`',
				caller: 'Owning `SecurityPool` only',
				declarations: [{ name: 'initializeForkCarrySnapshotWithResolutionBalances', sourcePath: 'solidity/contracts/statoblast/EscalationGameCarry.sol' }],
				effect: 'Installs the immutable inherited peaks, leaf counts, carry totals, resolution balances, and normalized nullifier roots; zero snapshot ID selects the computed ID. Two or more threshold-full inherited balances set `nonDecisionState` to `InheritedThresholdTie` without creating a local timestamp.',
				preconditions: 'Fork-continuation mode; no prior snapshot; each leaf count fits the MMR; supplied nonzero snapshot ID equals the hash of the normalized data.',
				signals: '`ForkCarryCheckpoint`; additionally `InheritedThresholdTie` when the installed balances meet the non-decision threshold',
			},
			{
				call: '`initializeForkClaimCheckpoint(sourceGame)` through `fallback()`',
				caller: 'Owning `SecurityPool` only (`Only pool`)',
				declarations: [{ name: 'initializeForkClaimCheckpoint', sourcePath: 'solidity/contracts/statoblast/EscalationGameClaimDelegate.sol' }],
				effect: 'Records the root claim source game: the value `sourceGame` reports from `rootClaimSourceGame()`, or `sourceGame` itself when that value is zero. The game runs the same step internally while installing a carry snapshot with a nonzero source game, and no pool function calls this selector.',
				preconditions: '`sourceGame` equals the source game recorded by the installed carry snapshot (`Claim source`); no Truth Auction haircut has been applied (`Haircut applied`).',
				signals: 'No event',
			},
			{
				call: '`claimDepositForWinning(depositIndex, outcome)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'claimDepositForWinning', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' }],
				effect: "Consumes a selected local deposit as a winner, consumes its vault escrow, burns the computed escalation haircut when nonzero, and transfers the remaining positive REP payout to the deposit's immutable depositor.",
				preconditions: 'Non-`None` supplied outcome and valid unsettled local deposit with sufficient escrow. This entrypoint itself does not check final resolution or that the supplied outcome won; its trusted caller selects that path.',
				signals: '`CarryDepositConsumed`, `VaultEscrowUpdated`, `ClaimDeposit` with `transferredRep = true`; REP payout `Transfer` and escalation-haircut burn signals only when their amounts are positive',
			},
			{
				call: '`claimDepositForWinningWithoutTransfer(depositIndex, outcome)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'claimDepositForWinningWithoutTransfer', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' }],
				effect:
					"Consumes a selected local deposit and its vault escrow. The depositor's raw escrow backing decreases by the inverse-retention claim units corresponding to the deposit's original principal: the principal itself with no local auction checkpoint, or `⌈originalPrincipal × truthAuctionRepBeforeAttoRep / truthAuctionRepRemainingAttoRep⌉` after a local auction REP removal. Other unconsumed deposits by the same depositor remain backed. The game returns the computed winner amount to the trusted caller but deliberately neither transfers REP nor burns the computed escalation haircut.",
				preconditions: 'Valid in-range supplied outcome and unsettled local deposit with sufficient escrow. Unlike the transferring form, it has no explicit non-`None` guard; neither form checks final resolution or that the outcome won.',
				signals: '`CarryDepositConsumed`, `VaultEscrowUpdated`, and `ClaimDeposit` with `transferredRep = false`; no REP transfer or escalation-haircut burn',
			},
			{
				call: '`exportUnresolvedDeposit(depositIndex, outcome)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'exportUnresolvedDeposit', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' }],
				effect: 'Returns deposit identity and amount to the trusted caller while consuming the local deposit from unresolved/escrow accounting without transferring REP.',
				preconditions: 'Non-`None` outcome and a valid unsettled local deposit. Final resolution is not required.',
				signals: '`CarryDepositConsumed` and `VaultEscrowUpdated`; no `ClaimDeposit` or REP transfer',
			},
			{
				call: '`withdrawDeposit(proof, outcome)`, the `CarriedDepositProof` overload',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'withdrawDeposit', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' }],
				effect: 'Consumes an inherited proof, transfers any positive winning payout, and burns the positive escalation haircut unless the fork already paid it.',
				preconditions: 'Non-`None` supplied outcome; game final and matching the pool final outcome; supplied outcome is the winner; parent deposit was not directly claimed; valid unconsumed Merkle/nullifier proof.',
				signals: '`CarryDepositConsumed` and `ClaimDeposit` with `transferredRep = true`; REP payout `Transfer` and escalation-haircut burn signals only when positive',
			},
			{
				call: '`exportVaultUnresolvedTotals(vault, repReceiver)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'exportVaultUnresolvedTotals', sourcePath: 'solidity/contracts/statoblast/EscalationGameEscrow.sol' }],
				effect: "Marks the vault's local unresolved totals exported exactly once, clears each outcome amount, consumes aggregate unresolved and escrow accounting when positive, and transfers the positive total to `repReceiver`.",
				preconditions: '`vault` is nonzero and has not exported before. There is no explicit nonzero-receiver guard: a zero receiver succeeds when the total is zero but the token rejects it when a positive transfer is attempted.',
				signals: 'Always `VaultUnresolvedTotalsExported`, including when every amount is zero; `VaultEscrowUpdated` and REP `Transfer` only for a positive total',
			},
			{
				call: '`exportVaultUnresolvedTotalsWithoutTransfer(vault)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'exportVaultUnresolvedTotalsWithoutTransfer', sourcePath: 'solidity/contracts/statoblast/EscalationGameEscrow.sol' }],
				effect: "Marks the vault's local unresolved totals exported exactly once, clears each outcome amount, and consumes aggregate unresolved and escrow accounting when positive, but leaves token movement to its caller.",
				preconditions: '`vault` is nonzero and has not exported before.',
				signals: 'Always `VaultUnresolvedTotalsExported` with `transferredRep = false`, including when every amount is zero; `VaultEscrowUpdated` only for a positive total; no REP transfer',
			},
			{
				call: '`drainAllRep(receiver)`',
				caller: 'Owning `SecurityPool` only (`Only pool`)',
				declarations: [{ name: 'drainAllRep', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' }],
				effect: "Transfers the game's full REP balance to `receiver`. A zero balance returns zero without a transfer or event.",
				preconditions: '`receiver` is nonzero; no positive-balance requirement. The protocol reaches this call from the owning pool after `activateForkMode` enters `PoolForked`.',
				signals: 'REP `Transfer` for a positive balance; no event at zero balance',
			},
			{
				call: '`recordForkedEscrowForOutcome(depositor, outcome, sourcePrincipalAttoRep, childRepAmountAttoRep)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'recordForkedEscrowForOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameEscrow.sol' }],
				effect:
					'Accumulates source principal and child REP escrow for the depositor and outcome. The depositor remains the immutable payout owner; inherited claims remain in the carry commitment and are not copied into child-local ownership state. When both amounts are zero, returns without changing state or emitting an event.',
				preconditions: 'Outcome is not `None`; depositor is nonzero. Source principal and child REP may independently be zero; when both are zero, the call is a no-op.',
				signals: '`ForkedEscrowRecorded` for a nonzero record; no event when both amounts are zero',
			},
			{
				call: '`exportForkedEscrowByOutcome(vault, repReceiver)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'exportForkedEscrowByOutcome', sourcePath: 'solidity/contracts/statoblast/EscalationGameEscrow.sol' }],
				effect: 'Marks every remaining per-outcome escrow amount exported and transfers its positive child REP. When all outcomes were already empty or exported, returns zero arrays without state change, token transfer, or event.',
				preconditions: '`vault` and `repReceiver` are nonzero.',
				signals: '`ForkedEscrowExported` when any source principal or child REP remains; `VaultEscrowUpdated` and REP `Transfer` when positive child REP is transferred; no event for an already-empty export',
			},
			{
				call: '`exportForkedEscrowByOutcomeWithoutTransfer(vault)`',
				caller: 'Owning `SecurityPool` or its `SecurityPoolForker`',
				declarations: [{ name: 'exportForkedEscrowByOutcomeWithoutTransfer', sourcePath: 'solidity/contracts/statoblast/EscalationGameEscrow.sol' }],
				effect: 'Marks every remaining per-outcome escrow amount exported without transferring child REP. When all outcomes were already empty or exported, returns zero arrays without state change or event.',
				preconditions: '`vault` is nonzero.',
				signals: '`ForkedEscrowExported` with `transferredRep = false` when any source principal or child REP remains; `VaultEscrowUpdated` when positive child REP remains; no REP transfer; no event for an already-empty export',
			},
			{
				call: '`sweepResidualRepToSecurityPool()`',
				caller: 'Anyone',
				effect: 'Returns ordinary-game residual REP to the owning pool. Burns fork-continuation residual so pre-child capital cannot accrue to late or nonexistent child owners.',
				declarations: [{ name: 'sweepResidualRepToSecurityPool', sourcePath: 'solidity/contracts/statoblast/EscalationGameSettlement.sol' }],
				preconditions: 'Final outcome; no unresolved principal; no vault escrow; positive residual balance.',
				signals: '`ResidualRepSweptToSecurityPool` for an ordinary game; `ForkContinuationResidualRepBurned` for a fork continuation',
			},
		],
	},
]
