import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { ensureContractArtifactsAreCurrent } from '../contracts/ensure-contract-artifacts.mts'
import { walkFiles } from '../repo/walk.mts'
import { entrypointSignaturesBySource, fallbackRoutedEntrypointSignatures, interfaceEntrypointExclusionsBySource, readDeclarationExclusionsBySource, stateChangingAbiFingerprintBySource } from './contract-reference-abi-surface.mts'
import { assemblyEventEmissions, delegateEventDeclarationMirrors, documentedEventSchemas, referencedEventAbiFingerprint } from './contract-reference-event-schemas.mts'
import { eventSourceByName } from './contract-reference-event-sources.mts'
import { computeCompiledAbiFingerprint, countEntrypoints, getCompiledContractAbi, getFallbackSelectorReferences } from './contract-reference-abi-readers.mts'
import { contractPageOutputPath, contractPagesDirectory, contractReferences, expectedProductionSoliditySourceFingerprint, outputPath, type ContractDeclaration } from './contract-reference-metadata.mts'
import { renderAccountingExamples } from './contract-reference-examples.mts'
import { escapeHtml, headingId, renderRichText } from './contract-reference-rich-text.mts'
import { renderReferencePage } from './docs-html-page.mts'
import { repositorySourceUrl } from './repository-source-links.mts'

assertDeclarationCheckerRegression()
assertProductionSoliditySourceClassifierRegression()
await ensureContractArtifactsAreCurrent()
const productionSoliditySourceFingerprint = await getProductionSoliditySourceFingerprint()
assert.equal(productionSoliditySourceFingerprint, expectedProductionSoliditySourceFingerprint, 'Production Solidity source changed; re-audit every affected contract behavior against the documentation, then update the pinned source fingerprint')

const generatedPages = await generateReferencePages()
const renderedPages: Array<{ html: string; outputPath: string }> = []
for (const page of generatedPages) {
	assert.match(page.content, /^<!-- Generated by tooling\/docs\/generate-contract-interaction-reference\.mts\. Do not edit directly\. -->/, `${page.outputPath} must identify its canonical generator`)
	renderedPages.push({ html: await renderReferencePage(page.title, page.content, page.outputPath), outputPath: page.outputPath })
}
const expectedContractPageNames = new Set(renderedPages.map(page => path.basename(page.outputPath)).filter(name => name !== path.basename(outputPath)))
const existingContractPageNames = (await readdir(contractPagesDirectory).catch(() => [])).filter(name => name.endsWith('.html'))

if (Bun.argv.includes('--check')) {
	for (const page of renderedPages) {
		const outputFile = Bun.file(page.outputPath)
		assert.equal(await outputFile.exists(), true, `${page.outputPath} is missing; run bun run docs:generate-contract-reference`)
		assert.equal(await outputFile.text(), page.html, `${page.outputPath} is stale; run bun run docs:generate-contract-reference`)
	}
	const unexpectedContractPages = existingContractPageNames.filter(name => !expectedContractPageNames.has(name))
	assert.deepEqual(unexpectedContractPages, [], `${contractPagesDirectory} contains pages without a generating contract reference; run bun run docs:generate-contract-reference`)
} else {
	await mkdir(contractPagesDirectory, { recursive: true })
	for (const page of renderedPages) await writeFile(page.outputPath, page.html)
	for (const name of existingContractPageNames) {
		if (!expectedContractPageNames.has(name)) await unlink(path.join(contractPagesDirectory, name))
	}
}

type GeneratedPage = { content: string; outputPath: string; title: string }

async function generateReferencePages(): Promise<GeneratedPage[]> {
	const sourceByPath = new Map<string, string>()
	const compiledAbiFingerprintByContract = new Map<string, string>()
	const readAbiFingerprintByContract = new Map<string, string>()
	const representedReadNamesBySource = new Map<string, Set<string>>()
	const representedStorageNamesBySource = new Map<string, Set<string>>()
	const representedEntrypointKeys = new Set<string>()
	const representedFallbackEntrypointKeys = new Set<string>()
	const entrypointSignatureCountsByContract = new Map<string, Map<string, number>>()
	const referencedEventNames = new Set<string>()
	const getSource = async (sourcePath: string): Promise<string> => {
		const cachedSource = sourceByPath.get(sourcePath)
		if (cachedSource !== undefined) return cachedSource
		const source = await readFile(sourcePath, 'utf8')
		sourceByPath.set(sourcePath, source)
		return source
	}
	const compiledArtifacts: unknown = JSON.parse(await readFile('solidity/artifacts/Contracts.json', 'utf8'))
	for (const contractReference of contractReferences) {
		const compiledAbi = getCompiledContractAbi(compiledArtifacts, contractReference.sourcePath, contractReference.name)
		const actualFingerprint = computeCompiledAbiFingerprint(compiledAbi)
		assert.equal(actualFingerprint, contractReference.compiledAbiFingerprint, `${contractReference.name} compiled ABI changed; review every inherited function, event, getter, tuple component, and interaction row, then update its pinned fingerprint`)
		compiledAbiFingerprintByContract.set(contractReference.name, actualFingerprint)
	}
	for (const sourcePath of Object.keys(entrypointSignaturesBySource)) {
		assert.ok(sourcePath in stateChangingAbiFingerprintBySource, `${sourcePath} must have a state-changing ABI fingerprint`)
	}
	for (const [sourcePath, expectedFingerprint] of Object.entries(stateChangingAbiFingerprintBySource)) {
		const source = await getSource(sourcePath)
		const signaturesByName = entrypointSignaturesBySource[sourcePath] ?? {}
		const excludedInterfaceNames = new Set(interfaceEntrypointExclusionsBySource[sourcePath] ?? [])
		assert.deepEqual(
			getPublicStateChangingDeclarationNames(source).filter(name => !excludedInterfaceNames.has(name)),
			Object.keys(signaturesByName).sort(),
			`${sourcePath} state-changing public entrypoints must exactly match the interaction metadata`,
		)
		const actualFingerprint = computeStateChangingAbiFingerprint(getPublicStateChangingDeclarations(source))
		assert.equal(actualFingerprint, expectedFingerprint, `${sourcePath} state-changing ABI changed; review the interaction rows and update its pinned fingerprint`)
	}
	for (const [routerSourcePath, signaturesByDelegateSource] of Object.entries(fallbackRoutedEntrypointSignatures)) {
		const expectedSelectorReferences: string[] = []
		for (const [delegateSourcePath, signaturesByName] of Object.entries(signaturesByDelegateSource)) {
			const delegateSource = await getSource(delegateSourcePath)
			for (const [name, expectedSignatures] of Object.entries(signaturesByName)) {
				assertEntrypointSignatures(delegateSource, { name }, expectedSignatures, delegateSourcePath)
				expectedSelectorReferences.push(`${path.basename(delegateSourcePath, '.sol')}.${name}`)
			}
		}
		assert.deepEqual(getFallbackSelectorReferences(await getSource(routerSourcePath), routerSourcePath), expectedSelectorReferences.sort(), `${routerSourcePath} fallback must route exactly the documented delegate selectors`)
	}
	for (const eventSchema of documentedEventSchemas) {
		assertEventSchema(await getSource(eventSchema.sourcePath), eventSchema, eventSchema.sourcePath)
	}
	for (const mirror of delegateEventDeclarationMirrors) {
		const canonicalSourcePath = eventSourceByName[mirror.name]
		assert.ok(canonicalSourcePath, `No canonical event declaration is configured for delegate mirror ${mirror.name}`)
		assertMirroredEventSchema(await getSource(canonicalSourcePath), await getSource(mirror.sourcePath), mirror.name, canonicalSourcePath, mirror.sourcePath)
	}
	for (const emission of assemblyEventEmissions) {
		const canonicalSourcePath = eventSourceByName[emission.name]
		assert.ok(canonicalSourcePath, `No canonical event declaration is configured for assembly emission ${emission.name}`)
		assertEventDeclaration(await getSource(canonicalSourcePath), { name: emission.name }, canonicalSourcePath)
		assertAssemblyEventEmission(await getSource(emission.sourcePath), emission, emission.sourcePath)
	}
	for (const contractReference of contractReferences) {
		const readDeclarations: string[] = []
		for (const declaration of contractReference.readDeclarations) {
			const declarationSourcePath = declaration.sourcePath ?? contractReference.sourcePath
			readDeclarations.push(...assertReadDeclaration(await getSource(declarationSourcePath), declaration, declarationSourcePath))
			assert.ok(new RegExp(`\\\`${declaration.name}(?:\\\`|\\()`).test(contractReference.readSurface), `${contractReference.name} read surface must name validated getter ${declaration.name}`)
			addNameBySource(representedReadNamesBySource, declarationSourcePath, declaration.name)
		}
		for (const declaration of contractReference.readStorageDeclarations ?? []) {
			const declarationSourcePath = declaration.sourcePath ?? contractReference.sourcePath
			readDeclarations.push(assertPublicStorageDeclaration(await getSource(declarationSourcePath), declaration.name, declarationSourcePath))
			assert.ok(new RegExp(`\\\`${declaration.name}\\\``).test(contractReference.readSurface), `${contractReference.name} read surface must name validated storage getter ${declaration.name}`)
			addNameBySource(representedStorageNamesBySource, declarationSourcePath, declaration.name)
		}
		const readAbiFingerprint = computeReadAbiFingerprint(readDeclarations)
		assert.equal(readAbiFingerprint, contractReference.readAbiFingerprint, `${contractReference.name} read ABI changed; review the read surface and update its pinned fingerprint`)
		readAbiFingerprintByContract.set(contractReference.name, readAbiFingerprint)
		for (const interaction of contractReference.interactions) {
			assert.equal(interaction.declarations.length, 1, `${contractReference.name} interaction rows must describe exactly one entrypoint name; split materially different guards, effects, and signals into separate rows`)
			for (const declaration of interaction.declarations) {
				const declarationSourcePath = declaration.sourcePath ?? contractReference.sourcePath
				const source = await getSource(declarationSourcePath)
				const isFallbackRouted = declaration.kind === 'fallback-routed'
				const configuredSourceSignatures = isFallbackRouted ? fallbackRoutedEntrypointSignatures[contractReference.sourcePath]?.[declarationSourcePath] : entrypointSignaturesBySource[declarationSourcePath]
				assert.ok(configuredSourceSignatures, `No entrypoint signature metadata exists for ${declarationSourcePath}`)
				const expectedSignatures = configuredSourceSignatures[declaration.name]
				assert.ok(expectedSignatures, `No entrypoint signatures are configured for ${declarationSourcePath}#${declaration.name}`)
				assertEntrypointSignatures(source, isFallbackRouted ? { name: declaration.name } : declaration, expectedSignatures, declarationSourcePath)
				assert.ok(new RegExp(`\\\`${declaration.name}(?:\\\`|\\()`).test(interaction.call), `${contractReference.name} interaction call must name validated entrypoint ${declaration.name}`)
				assert.doesNotMatch(interaction.call, /\.\.\./, `${contractReference.name} interaction call for ${declaration.name} must list every parameter`)
				if (isFallbackRouted) representedFallbackEntrypointKeys.add(`${contractReference.sourcePath}#${declarationSourcePath}#${declaration.name}`)
				else representedEntrypointKeys.add(`${declarationSourcePath}#${declaration.name}`)
				const signatureCounts = entrypointSignatureCountsByContract.get(contractReference.name) ?? new Map<string, number>()
				signatureCounts.set(`${declarationSourcePath}#${declaration.name}`, expectedSignatures.length)
				entrypointSignatureCountsByContract.set(contractReference.name, signatureCounts)
			}
			for (const eventMatch of interaction.signals.matchAll(/`([A-Z][A-Za-z0-9_]*)`/g)) {
				const eventName = eventMatch[1]
				if (eventName === undefined) throw new Error('Expected an event name capture')
				const eventSourcePath = eventSourceByName[eventName]
				assert.ok(eventSourcePath, `No declaring source is configured for documented event ${eventName}`)
				assertEventDeclaration(await getSource(eventSourcePath), { name: eventName }, eventSourcePath)
				referencedEventNames.add(eventName)
			}
		}
	}
	for (const [sourcePath, representedNames] of representedReadNamesBySource) {
		const excludedNames = new Set(readDeclarationExclusionsBySource[sourcePath] ?? [])
		const actualNames = getPublicReadDeclarationNames(await getSource(sourcePath)).filter(name => !excludedNames.has(name))
		assert.deepEqual(actualNames, Array.from(representedNames).sort(), `${sourcePath} public read functions must exactly match the documented read surface`)
	}
	for (const [sourcePath, representedNames] of representedStorageNamesBySource) {
		assert.deepEqual(getPublicStorageDeclarationNames(await getSource(sourcePath)), Array.from(representedNames).sort(), `${sourcePath} public storage getters must exactly match the documented read surface`)
	}
	const configuredEntrypointKeys = Object.entries(entrypointSignaturesBySource).flatMap(([sourcePath, signaturesByName]) => Object.keys(signaturesByName).map(name => `${sourcePath}#${name}`))
	assert.deepEqual(Array.from(representedEntrypointKeys).sort(), configuredEntrypointKeys.sort(), 'Entrypoint signature metadata must exactly match the declarations represented by interaction rows')
	const configuredFallbackEntrypointKeys = Object.entries(fallbackRoutedEntrypointSignatures).flatMap(([routerSourcePath, signaturesByDelegateSource]) =>
		Object.entries(signaturesByDelegateSource).flatMap(([delegateSourcePath, signaturesByName]) => Object.keys(signaturesByName).map(name => `${routerSourcePath}#${delegateSourcePath}#${name}`)),
	)
	assert.deepEqual(Array.from(representedFallbackEntrypointKeys).sort(), configuredFallbackEntrypointKeys.sort(), 'Fallback-routed entrypoint metadata must exactly match the fallback-routed declarations represented by interaction rows')
	assert.deepEqual(Array.from(referencedEventNames).sort(), Object.keys(eventSourceByName).sort(), 'Event source metadata must exactly match the events named in interaction signals')
	const referencedEventDeclarations: string[] = []
	for (const [eventName, sourcePath] of Object.entries(eventSourceByName)) {
		referencedEventDeclarations.push(assertEventDeclaration(await getSource(sourcePath), { name: eventName }, sourcePath))
	}
	const actualEventAbiFingerprint = computeEventAbiFingerprint(referencedEventDeclarations)
	assert.equal(actualEventAbiFingerprint, referencedEventAbiFingerprint, 'A referenced event ABI changed; review event semantics and update the pinned fingerprint')

	// Pages without a page-specific trust-boundary heading share this one, so every security paragraph sits under a heading.
	const defaultSecurityBoundaryHeading = 'Security assumptions'
	const generatedBanner = '<!-- Generated by tooling/docs/generate-contract-interaction-reference.mts. Do not edit directly. -->'
	const contractPages = contractReferences.map((contractReference): GeneratedPage => {
		const rows = contractReference.interactions
			.map(
				interaction => `<tr>
	<td>${renderCallCell(interaction.call)}</td>
	<td>${renderRichText(interaction.caller)}</td>
	<td>${renderRichText(interaction.preconditions)}</td>
	<td>${renderRichText(interaction.effect)}</td>
	<td>${renderRichText(interaction.signals)}</td>
</tr>`,
			)
			.join('\n')
		const readAbiFingerprint = readAbiFingerprintByContract.get(contractReference.name)
		assert.ok(readAbiFingerprint, `Missing read ABI fingerprint for ${contractReference.name}`)
		const compiledAbiFingerprint = compiledAbiFingerprintByContract.get(contractReference.name)
		assert.ok(compiledAbiFingerprint, `Missing compiled ABI fingerprint for ${contractReference.name}`)
		const securityBoundaryHeadingText = contractReference.securityBoundaryHeading ?? defaultSecurityBoundaryHeading
		const securityBoundaryHeading = contractReference.securityBoundary === undefined ? '' : `<h2 id="${headingId(securityBoundaryHeadingText)}">${escapeHtml(securityBoundaryHeadingText)}</h2>`
		const securityBoundary = contractReference.securityBoundary === undefined ? '' : `<p>${renderRichText(contractReference.securityBoundary)}</p>`
		const content = `${generatedBanner}
	<header>
		<h1>${escapeHtml(contractReference.name)}</h1>
		<p class="lede">${renderRichText(contractReference.purpose)} <a href="${escapeHtml(repositorySourceUrl(contractReference.sourcePath))}">${escapeHtml(contractReference.name)} source contract</a></p>
	</header>
	<h2 id="read-surface">Read surface</h2>
	<p>${renderRichText(contractReference.readSurface)}</p>
	${securityBoundaryHeading}
	${securityBoundary}
	<h2 id="interactions">State-changing interactions</h2>
	<p>Each call lists its parameter names in ABI order. The <a href="../contracts.html#table-columns">contract index</a> defines the columns.${contractReference.interactionNotes === undefined ? '' : ` ${renderRichText(contractReference.interactionNotes)}`}</p>
	<!-- Validated read ABI fingerprint: ${readAbiFingerprint} -->
	<!-- Validated complete compiled ABI fingerprint: ${compiledAbiFingerprint} -->
	<table>
		<thead>
			<tr>
				<th>Transaction</th>
				<th>Caller</th>
				<th>Main prerequisites</th>
				<th>State or asset effect</th>
				<th>Primary signals</th>
			</tr>
		</thead>
		<tbody>
${rows}
		</tbody>
	</table>${renderAccountingExamples(contractReference.name)}`
		return { content, outputPath: contractPageOutputPath(contractReference.name), title: contractReference.name }
	})

	// Index rows keep the fragment ids of the former single page (contract headings and trust-boundary headings), so historical deep links still land on the entry that links to the new page.
	const indexRows = contractReferences
		.map(contractReference => {
			const pageHref = `./${path.posix.relative(path.posix.dirname(outputPath), contractPageOutputPath(contractReference.name))}`
			assert.equal(headingId(contractReference.name), path.basename(contractPageOutputPath(contractReference.name), '.html'), `${contractReference.name} page slug must match its former heading id`)
			const boundaryLink = contractReference.securityBoundaryHeading === undefined ? '' : ` <a id="${headingId(contractReference.securityBoundaryHeading)}" href="${escapeHtml(pageHref)}#${headingId(contractReference.securityBoundaryHeading)}">${escapeHtml(contractReference.securityBoundaryHeading)}</a>`
			return `<tr id="${headingId(contractReference.name)}">
	<td><a href="${escapeHtml(pageHref)}">${escapeHtml(contractReference.name)}</a></td>
	<td>${renderRichText(indexSummary(contractReference.purpose), outputPath)}${boundaryLink}</td>
	<td>${countEntrypoints(entrypointSignatureCountsByContract.get(contractReference.name))}</td>
</tr>`
		})
		.join('\n')
	const indexContent = `${generatedBanner}
	<header>
		<h1>Contract interactions</h1>
		<p class="lede">Open a contract to see its read surface, any security assumptions or trust boundary, and each state-changing entrypoint with its caller, prerequisites, effects, and primary signals.</p>
	</header>
	<p>The entrypoint count is the number of state-changing function signatures a contract answers, counting each overload, each selector its <code>fallback()</code> routes to a delegate, and <code>receive()</code>.</p>
	<h2 id="table-columns">Table columns</h2>
	<p>Every contract page uses the same five columns.</p>
	<ul>
		<li><strong>Transaction</strong>: the function name with its parameter names in ABI order. Overloads appear as separate signatures.</li>
		<li><strong>Caller</strong>: the addresses the contract accepts as <code>msg.sender</code>.</li>
		<li><strong>Main prerequisites</strong>: the conditions the call requires, quoting a revert string where a caller needs it to tell failures apart.</li>
		<li><strong>State or asset effect</strong>: what a successful call changes.</li>
		<li><strong>Primary signals</strong>: the events a successful call emits, each with the condition under which it is emitted, including events emitted by contracts the call reaches. A row says so when a call can succeed without emitting an event.</li>
	</ul>
	<table>
		<thead>
			<tr>
				<th>Contract</th>
				<th>Purpose</th>
				<th>State-changing entrypoints</th>
			</tr>
		</thead>
		<tbody>
${indexRows}
		</tbody>
	</table>`
	return [{ content: indexContent, outputPath, title: 'Contract interactions' }, ...contractPages]
}

// The docs stylesheet keeps a cell's lone code span on one line. A trailing break opportunity makes a multi-parameter signature wrap at its commas instead of forcing the table wider.
function renderCallCell(call: string): string {
	const rendered = renderRichText(call)
	return /<code>[^<]*, [^<]*<\/code>/.test(rendered) ? `${rendered}<wbr />` : rendered
}

// The index keeps only the opening sentence of each purpose; the contract page lede carries the full text.
function indexSummary(purpose: string): string {
	const [firstSentence] = purpose.split(/(?<=\.)\s+(?=[A-Z])/)
	assert.ok(firstSentence !== undefined && firstSentence.length > 0, 'Contract purpose must begin with a sentence')
	return firstSentence
}

function assertEntrypointSignatures(source: string, declaration: ContractDeclaration, expectedSignatures: string[], sourceLabel: string): void {
	if (declaration.kind === 'receive') {
		const receiveMatch = source.match(/^\s*receive\s*\(\s*\)\s*(external|public|internal|private)\s*(payable)?\b/m)
		const actualSignatures = receiveMatch === null ? [] : [`${receiveMatch[1]}${receiveMatch[2] === undefined ? '' : ' payable'}()`]
		assert.deepEqual(actualSignatures, expectedSignatures, `${sourceLabel} receive signature changed; update the interaction reference`)
		return
	}
	const actualSignatures = getFunctionDeclarations(source, declaration.name)
		.filter(sourceDeclaration => sourceDeclaration.visibility === 'external' || sourceDeclaration.visibility === 'public')
		.map(sourceDeclaration => `${sourceDeclaration.visibility}(${sourceDeclaration.parameterTypes.join(',')})`)
		.sort()
	assert.deepEqual(actualSignatures, [...expectedSignatures].sort(), `${sourceLabel} entrypoint signatures for ${declaration.name} changed; update the interaction reference`)
}

function assertReadDeclaration(source: string, declaration: ContractDeclaration, sourceLabel: string): string[] {
	assert.notEqual(declaration.kind, 'receive', `${sourceLabel} receive cannot be documented as a read`)
	const declarationPattern = new RegExp(`^\\s*function\\s+${declaration.name}\\s*\\(([\\s\\S]*?)\\)\\s*([^;{]*)[;{]`, 'gm')
	const declarations = Array.from(source.matchAll(declarationPattern)).filter(match => /\b(?:external|public)\b/.test(match[2] ?? ''))
	assert.ok(declarations.length > 0, `${sourceLabel} no longer declares public read ${declaration.name}; update the interaction reference`)
	return declarations.map(match => {
		const suffix = (match[2] ?? '').replace(/\s+/g, ' ').trim()
		assert.match(suffix, /\b(?:view|pure)\b/, `${sourceLabel} ${declaration.name} is no longer view or pure; move it to an interaction row`)
		return `function ${declaration.name}(${(match[1] ?? '').replace(/\s+/g, ' ').trim()}) ${suffix}`
	})
}

function assertPublicStorageDeclaration(source: string, storageName: string, sourceLabel: string): string {
	const declarationPattern = new RegExp(`^\\s*([^;{}]*\\bpublic(?:\\s+(?:constant|immutable|override))*\\s+${storageName}(?:\\s*=\\s*[^;]+)?);`, 'm')
	const match = source.match(declarationPattern)
	assert.ok(match, `${sourceLabel} no longer declares public storage getter ${storageName}; update the interaction reference`)
	return (match[1] ?? '').replace(/\s+/g, ' ').trim()
}

function getFunctionDeclarations(source: string, name: string): Array<{ parameterTypes: string[]; payable: boolean; visibility: string }> {
	const declarationPattern = new RegExp(`^\\s*function\\s+${name}\\s*\\(([\\s\\S]*?)\\)\\s*(external|public|internal|private)\\b([^;{]*)[;{]`, 'gm')
	return Array.from(source.matchAll(declarationPattern), match => ({
		parameterTypes: parseParameterTypes(match[1] ?? ''),
		payable: /\bpayable\b/.test(match[3] ?? ''),
		visibility: match[2] ?? '',
	}))
}

function getPublicStateChangingDeclarationNames(source: string): string[] {
	return Array.from(
		new Set(
			getPublicStateChangingDeclarations(source).map(declaration => {
				const match = declaration.match(/^(?:function\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*\(/)
				const name = match?.[1]
				if (name === undefined) throw new Error(`Expected a function name in ${declaration}`)
				return name
			}),
		),
	).sort()
}

function getPublicStateChangingDeclarations(source: string): string[] {
	const declarations = Array.from(source.matchAll(/^\s*function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([\s\S]*?)\)\s*([^;{]*)[;{]/gm))
		.filter(match => /\b(?:external|public)\b/.test(match[3] ?? '') && !/\b(?:pure|view)\b/.test(match[3] ?? ''))
		.map(match => {
			const name = match[1]
			if (name === undefined) throw new Error('Expected a Solidity function-name capture')
			return `function ${name}(${normalizeSolidityParameters(match[2] ?? '')}) ${(match[3] ?? '').replace(/\s+/g, ' ').trim()}`
		})
	const receiveDeclarations = Array.from(source.matchAll(/^\s*receive\s*\(\s*\)\s*([^;{]*)[;{]/gm))
		.filter(match => /\b(?:external|public)\b/.test(match[1] ?? ''))
		.map(match => `receive() ${(match[1] ?? '').replace(/\s+/g, ' ').trim()}`)
	return [...declarations, ...receiveDeclarations].sort()
}

function getPublicReadDeclarationNames(source: string): string[] {
	return Array.from(
		new Set(
			Array.from(source.matchAll(/^\s*function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\([\s\S]*?\)\s*([^;{]*)[;{]/gm))
				.filter(match => /\b(?:external|public)\b/.test(match[2] ?? '') && /\b(?:pure|view)\b/.test(match[2] ?? ''))
				.map(match => {
					const name = match[1]
					if (name === undefined) throw new Error('Expected a Solidity read-function-name capture')
					return name
				}),
		),
	).sort()
}

function getPublicStorageDeclarationNames(source: string): string[] {
	return Array.from(
		new Set(
			Array.from(source.matchAll(/^\s*(?:mapping\s*\([^;]+\)|[A-Za-z_][A-Za-z0-9_.]*(?:\[[^\]]*\])*)\s+public(?:\s+(?:constant|immutable|override))*\s+([A-Za-z_][A-Za-z0-9_]*)\b/gm)).map(match => {
				const name = match[1]
				if (name === undefined) throw new Error('Expected a Solidity public-storage-name capture')
				return name
			}),
		),
	).sort()
}

function addNameBySource(namesBySource: Map<string, Set<string>>, sourcePath: string, name: string): void {
	const names = namesBySource.get(sourcePath) ?? new Set<string>()
	names.add(name)
	namesBySource.set(sourcePath, names)
}

function parseParameterTypes(parameters: string): string[] {
	if (parameters.trim() === '') return []
	return parameters.split(',').map(parameter => {
		const tokens = parameter.trim().replace(/\s+/g, ' ').split(' ')
		if (tokens[0] === 'address' && tokens[1] === 'payable') return 'address payable'
		const parameterType = tokens[0]
		if (parameterType === undefined || parameterType === '') throw new Error(`Unable to parse Solidity parameter: ${parameter}`)
		return parameterType
	})
}

function assertEventDeclaration(source: string, event: ContractDeclaration, sourceLabel: string): string {
	const eventPattern = new RegExp(`^\\s*event\\s+${event.name}\\s*\\(([\\s\\S]*?)\\)\\s*;`, 'gm')
	const matches = Array.from(source.matchAll(eventPattern))
	assert.equal(matches.length, 1, `${sourceLabel} must declare exactly one event ${event.name}; update the interaction reference`)
	return `event ${event.name}(${normalizeSolidityParameters(matches[0]?.[1] ?? '')})`
}

function assertEventSchema(source: string, event: { name: string; parameters: string }, sourceLabel: string): void {
	const eventPattern = new RegExp(`^\\s*event\\s+${event.name}\\s*\\(([\\s\\S]*?)\\)\\s*;`, 'm')
	const match = source.match(eventPattern)
	assert.ok(match, `${sourceLabel} no longer declares event ${event.name}; update the event reference`)
	assert.equal(normalizeSolidityParameters(match[1] ?? ''), event.parameters, `${sourceLabel} event schema for ${event.name} changed; update the event reference`)
}

function assertMirroredEventSchema(canonicalSource: string, mirrorSource: string, eventName: string, canonicalSourceLabel: string, mirrorSourceLabel: string): void {
	const canonicalDeclaration = assertEventDeclaration(canonicalSource, { name: eventName }, canonicalSourceLabel)
	const mirrorDeclaration = assertEventDeclaration(mirrorSource, { name: eventName }, mirrorSourceLabel)
	assert.equal(mirrorDeclaration, canonicalDeclaration, `${mirrorSourceLabel} delegate-emitted ${eventName} schema must match ${canonicalSourceLabel}`)
}

function assertAssemblyEventEmission(source: string, emission: { dataArguments: string; indexedArguments: string; name: string; signature: string; signatureConstant: string }, sourceLabel: string): void {
	const compactSource = source.replace(/\s+/g, '')
	assert.ok(compactSource.includes(`bytes32privateconstant${emission.signatureConstant}=keccak256('${emission.signature}');`), `${sourceLabel} assembly event signature for ${emission.name} changed`)
	assert.ok(compactSource.includes(`bytesmemoryeventData=abi.encode(${emission.dataArguments.replace(/\s+/g, '')});`), `${sourceLabel} assembly event data for ${emission.name} changed`)
	const indexedArguments = emission.indexedArguments === '' ? '' : `,${emission.indexedArguments.replace(/\s+/g, '')}`
	const topicCount = emission.indexedArguments === '' ? 1 : emission.indexedArguments.split(',').length + 1
	assert.ok(compactSource.includes(`log${topicCount}(add(eventData,0x20),mload(eventData),eventSignature${indexedArguments})`), `${sourceLabel} assembly event topics for ${emission.name} changed`)
}

function normalizeSolidityParameters(parameters: string): string {
	return parameters
		.replace(/\s+/g, ' ')
		.replace(/\s*,\s*/g, ',')
		.trim()
}

function computeReadAbiFingerprint(declarations: string[]): string {
	return createHash('sha256')
		.update([...declarations].sort().join('\n'))
		.digest('hex')
}

function computeStateChangingAbiFingerprint(declarations: string[]): string {
	return createHash('sha256')
		.update([...declarations].sort().join('\n'))
		.digest('hex')
}

async function getProductionSoliditySourceFingerprint(): Promise<string> {
	const sourcePaths = (await listSoliditySourcePaths('solidity/contracts')).filter(isProductionSoliditySourcePath)
	const sources = await Promise.all(sourcePaths.map(async sourcePath => ({ source: await readFile(sourcePath, 'utf8'), sourcePath })))
	return computeSourceContentFingerprint(sources)
}

function isProductionSoliditySourcePath(sourcePath: string): boolean {
	return !sourcePath.split('/').includes('test')
}

async function listSoliditySourcePaths(directory: string): Promise<string[]> {
	return (await walkFiles(directory, { includeNonFiles: true, include: file => file.endsWith('.sol') })).map(file => file.replaceAll('\\', '/')).sort()
}

function computeSourceContentFingerprint(sources: Array<{ source: string; sourcePath: string }>): string {
	const hash = createHash('sha256')
	for (const { source, sourcePath } of [...sources].sort((left, right) => left.sourcePath.localeCompare(right.sourcePath))) {
		hash.update(sourcePath)
		hash.update('\0')
		hash.update(source.replaceAll('\r\n', '\n'))
		hash.update('\0')
	}
	return hash.digest('hex')
}

function computeEventAbiFingerprint(declarations: string[]): string {
	return createHash('sha256')
		.update([...declarations].sort().join('\n'))
		.digest('hex')
}

function assertDeclarationCheckerRegression(): void {
	const sourceWithoutSecondary = `
		function primary() external {
			secondary();
		}
	`
	assert.throws(() => assertEntrypointSignatures(sourceWithoutSecondary, { name: 'secondary' }, ['external()'], 'grouped fixture'), /entrypoint signatures for secondary changed/)
	assert.throws(() => assertEntrypointSignatures('function caller() external { removed(); }', { name: 'removed' }, ['external()'], 'call-site fixture'), /entrypoint signatures for removed changed/)
	assert.doesNotThrow(() => assertEntrypointSignatures('receive() external payable {}', { kind: 'receive', name: 'receive' }, ['external payable()'], 'receive fixture'))
	const overloadedSource = 'function overloaded(uint256 value) external {}\nfunction overloaded(address value) external {}'
	assert.doesNotThrow(() => assertEntrypointSignatures(overloadedSource, { name: 'overloaded' }, ['external(address)', 'external(uint256)'], 'overload fixture'))
	assert.throws(() => assertEntrypointSignatures(`${overloadedSource}\nfunction overloaded(bytes32 value) external {}`, { name: 'overloaded' }, ['external(address)', 'external(uint256)'], 'added-overload fixture'), /entrypoint signatures for overloaded changed/)
	assert.throws(() => assertEntrypointSignatures('function changed(address value) external {}', { name: 'changed' }, ['external(uint256)'], 'parameter-change fixture'), /entrypoint signatures for changed changed/)
	assert.throws(() => assertEntrypointSignatures('function hidden(uint256 value) internal {}', { name: 'hidden' }, ['external(uint256)'], 'visibility fixture'), /entrypoint signatures for hidden changed/)
	assert.deepEqual(assertReadDeclaration('function available(uint256 key) external view returns (address account) {}', { name: 'available' }, 'read fixture'), ['function available(uint256 key) external view returns (address account)'])
	assert.throws(() => assertReadDeclaration('function hidden() internal view {}', { name: 'hidden' }, 'read fixture'), /read fixture no longer declares public read hidden/)
	assert.throws(() => assertReadDeclaration('function changed() external returns (uint256) {}', { name: 'changed' }, 'read mutability fixture'), /changed is no longer view or pure/)
	assert.notDeepEqual(assertReadDeclaration('function available(address key) external view returns (address account) {}', { name: 'available' }, 'read parameter fixture'), ['function available(uint256 key) external view returns (address account)'])
	assert.notDeepEqual(assertReadDeclaration('function available(uint256 key) external view returns (uint256 value) {}', { name: 'available' }, 'read return fixture'), ['function available(uint256 key) external view returns (address account)'])
	assert.notEqual(computeReadAbiFingerprint(['function available(uint256 key) external view returns (uint256 value)']), computeReadAbiFingerprint(['function available(uint256 key) external view returns (address account)']))
	assert.throws(() => assertPublicStorageDeclaration('uint256 internal removed;', 'removed', 'storage fixture'), /no longer declares public storage getter removed/)
	assert.deepEqual(getPublicReadDeclarationNames('function inspect() public view returns (uint256) { return 1; }\nfunction calculate() external pure returns (uint256) { return 2; }\nfunction mutate() external {}'), ['calculate', 'inspect'])
	assert.deepEqual(getPublicStorageDeclarationNames('uint256 public immutable count;\nmapping(address => uint256) public balances;\nuint256 private hidden;'), ['balances', 'count'])
	assert.doesNotThrow(() => assertEventSchema('event Exact(address indexed account, uint256 value);', { name: 'Exact', parameters: 'address indexed account,uint256 value' }, 'event schema fixture'))
	assert.throws(() => assertEventSchema('event Changed(address account, uint256 value);', { name: 'Changed', parameters: 'address indexed account,uint256 value' }, 'event indexing fixture'), /event schema for Changed changed/)
	const checkpointEvent = assertEventDeclaration('event PoolAccountingCheckpoint(address indexed vault, uint256 value);', { name: 'PoolAccountingCheckpoint' }, 'checkpoint fixture')
	const checkpointIndexingDrift = assertEventDeclaration('event PoolAccountingCheckpoint(address vault, uint256 value);', { name: 'PoolAccountingCheckpoint' }, 'checkpoint indexing fixture')
	const checkpointOrderDrift = assertEventDeclaration('event PoolAccountingCheckpoint(uint256 value, address indexed vault);', { name: 'PoolAccountingCheckpoint' }, 'checkpoint order fixture')
	const auctionEvent = assertEventDeclaration('event AuctionFinalized(int256 indexed clearingTick, uint256 grossEthAccepted);', { name: 'AuctionFinalized' }, 'auction fixture')
	const auctionTypeDrift = assertEventDeclaration('event AuctionFinalized(uint256 indexed clearingTick, uint256 grossEthAccepted);', { name: 'AuctionFinalized' }, 'auction type fixture')
	assert.notEqual(computeEventAbiFingerprint([checkpointEvent]), computeEventAbiFingerprint([checkpointIndexingDrift]))
	assert.notEqual(computeEventAbiFingerprint([checkpointEvent]), computeEventAbiFingerprint([checkpointOrderDrift]))
	assert.notEqual(computeEventAbiFingerprint([auctionEvent]), computeEventAbiFingerprint([auctionTypeDrift]))
	const compiledAbiFixture = [{ inputs: [], name: 'inspect', outputs: [{ components: [{ name: 'amount', type: 'uint256' }], name: 'record', type: 'tuple' }], stateMutability: 'view', type: 'function' }]
	assert.notEqual(computeCompiledAbiFingerprint(compiledAbiFixture), computeCompiledAbiFingerprint([...compiledAbiFixture, { anonymous: false, inputs: [], name: 'InheritedEvent', type: 'event' }]))
	assert.notEqual(
		computeCompiledAbiFingerprint(compiledAbiFixture),
		computeCompiledAbiFingerprint([
			{
				inputs: [],
				name: 'inspect',
				outputs: [
					{
						components: [
							{ name: 'account', type: 'address' },
							{ name: 'amount', type: 'uint256' },
						],
						name: 'record',
						type: 'tuple',
					},
				],
				stateMutability: 'view',
				type: 'function',
			},
		]),
	)
	assert.throws(
		() => assertMirroredEventSchema('event PoolAccountingCheckpoint(address indexed vault);', 'event PoolAccountingCheckpoint(address vault);', 'PoolAccountingCheckpoint', 'interface fixture', 'delegate fixture'),
		/delegate fixture delegate-emitted PoolAccountingCheckpoint schema must match interface fixture/,
	)
	const assemblyEventFixture = `
		bytes32 private constant CHECKPOINT_SIGNATURE = keccak256(
			'Checkpoint(address,uint256)'
		);
		bytes memory eventData = abi.encode(value);
		bytes32 eventSignature = CHECKPOINT_SIGNATURE;
		assembly ('memory-safe') {
			log2(add(eventData, 0x20), mload(eventData), eventSignature, account)
		}
	`
	const assemblyEventMetadata = {
		dataArguments: 'value',
		indexedArguments: 'account',
		name: 'Checkpoint',
		signature: 'Checkpoint(address,uint256)',
		signatureConstant: 'CHECKPOINT_SIGNATURE',
	}
	assert.doesNotThrow(() => assertAssemblyEventEmission(assemblyEventFixture, assemblyEventMetadata, 'assembly fixture'))
	assert.throws(() => assertAssemblyEventEmission(assemblyEventFixture.replace('Checkpoint(address,uint256)', 'Checkpoint(uint256,address)'), assemblyEventMetadata, 'assembly signature fixture'), /assembly event signature for Checkpoint changed/)
	assert.throws(() => assertAssemblyEventEmission(assemblyEventFixture.replace('abi.encode(value)', 'abi.encode(otherValue)'), assemblyEventMetadata, 'assembly data fixture'), /assembly event data for Checkpoint changed/)
	assert.throws(() => assertAssemblyEventEmission(assemblyEventFixture.replace('eventSignature, account', 'eventSignature, otherAccount'), assemblyEventMetadata, 'assembly topic fixture'), /assembly event topics for Checkpoint changed/)
	assert.deepEqual(getPublicStateChangingDeclarationNames('function mutate(uint256 value) external returns (uint256) { return value; }\nfunction inspect() public view returns (uint256) { return 1; }\nreceive() external payable {}'), ['mutate', 'receive'])
	assert.notEqual(computeStateChangingAbiFingerprint(getPublicStateChangingDeclarations('function mutate() external payable {}')), computeStateChangingAbiFingerprint(getPublicStateChangingDeclarations('function mutate() external {}')))
	assert.notEqual(computeStateChangingAbiFingerprint(getPublicStateChangingDeclarations('function mutate() external returns (uint256) {}')), computeStateChangingAbiFingerprint(getPublicStateChangingDeclarations('function mutate() external returns (address) {}')))
	assert.notEqual(computeSourceContentFingerprint([{ sourcePath: 'Fixture.sol', source: 'function mutate(uint256 value) external { require(value > 0); }' }]), computeSourceContentFingerprint([{ sourcePath: 'Fixture.sol', source: 'function mutate(uint256 value) external { require(value > 1); }' }]))
	assert.notEqual(
		computeSourceContentFingerprint([{ sourcePath: 'Fixture.sol', source: 'function mutate() external {}' }]),
		computeSourceContentFingerprint([
			{ sourcePath: 'Fixture.sol', source: 'function mutate() external {}' },
			{ sourcePath: 'NewSupport.sol', source: 'library NewSupport {}' },
		]),
	)
	const fallbackFixture = "contract Router {\n\tfallback() external {\n\t\trequire(msg.sig == Delegate.second.selector || msg.sig == Delegate.first.selector, 'Unsupported');\n\t\tif (true) { forward(); }\n\t}\n\tfunction later() external { Other.ignored.selector; }\n}"
	assert.deepEqual(getFallbackSelectorReferences(fallbackFixture, 'fallback fixture'), ['Delegate.first', 'Delegate.second'])
	assert.throws(() => getFallbackSelectorReferences('contract Plain {}', 'missing fallback fixture'), /missing fallback fixture must declare an external fallback/)
	assert.deepEqual(getPublicStateChangingDeclarations('abstract contract Empty {}'), [])
	assert.notDeepEqual(getPublicStateChangingDeclarations('abstract contract Empty {\nfunction added() external {}\n}'), [])
	assert.throws(() => assertEventDeclaration('function SystemStateSet() external {}', { name: 'SystemStateSet' }, 'event fixture'), /event fixture must declare exactly one event SystemStateSet/)
	assert.throws(() => assertEventDeclaration('event UniverseForked(uint256 value);', { name: 'DeployChild' }, 'intended event source'), /intended event source must declare exactly one event DeployChild/)
}

function assertProductionSoliditySourceClassifierRegression(): void {
	assert.equal(isProductionSoliditySourcePath('solidity/contracts/SecurityPool.sol'), true)
	assert.equal(isProductionSoliditySourcePath('solidity/contracts/test/SecurityPoolHarness.sol'), false)
	assert.equal(isProductionSoliditySourcePath('solidity/contracts/trading/test/TwoWayConstantProductMathHarness.sol'), false)
}
