import type { ContractReference } from './contract-reference-metadata.mts'

export const oracleMarketContractReferences: ContractReference[] = [
	{
		compiledAbiFingerprint: '24fef7375af443bf5477c0c4afa6d6ce6ef852f82a8b17d46bd1cea15bc3c264',
		name: 'LiquidationApprovalRegistry',
		purpose: 'Stores coordinator-local, bounded authorization for a receiver vault to accept liquidation debt from an exact operator.',
		readAbiFingerprint: '04465d90cef2bd37454bf8496fffcaccf07f0ec5808f31ffd6481d4cdc46f810',
		readSurface:
			'Use `coordinator` to identify the validating coordinator and implied security pool. `LIQUIDATION_APPROVAL_TYPEHASH`, `DOMAIN_SEPARATOR`, and `liquidationApprovalDigest` define the chain- and registry-bound EIP-712 message. `getLiquidationApproval` reports parameters plus available, reserved, consumed, and revoked state; `minimumLiquidationApprovalNonce` reports receiver invalidation state; `liquidationReservations` and `minimumHealthFactorBps` expose operation reservation state and its execution-time health floor.',
		readDeclarations: [{ name: 'DOMAIN_SEPARATOR' }, { name: 'liquidationApprovalDigest' }, { name: 'getLiquidationApproval' }, { name: 'minimumHealthFactorBps' }],
		readStorageDeclarations: [{ name: 'coordinator' }, { name: 'LIQUIDATION_APPROVAL_TYPEHASH' }, { name: 'minimumLiquidationApprovalNonce' }, { name: 'liquidationReservations' }],
		sourcePath: 'solidity/contracts/statoblast/LiquidationApprovalRegistry.sol',
		interactions: [
			{
				call: '`initialize(coordinator)`',
				caller: 'Anyone while the registry remains uninitialized; normal factory deployment initializes the clone atomically',
				effect: 'Binds this registry clone to one coordinator and therefore one security pool.',
				declarations: [{ name: 'initialize' }],
				preconditions: 'Coordinator is nonzero and the registry has not been initialized.',
				signals: 'No event; the public `coordinator` getter records the binding.',
			},
			{
				call: '`setLiquidationApproval(params)`',
				caller: 'The receiver vault named by `params`',
				effect: 'Installs explicit onchain bounded approval state and consumes the receiver-scoped nonce.',
				declarations: [{ name: 'setLiquidationApproval' }],
				preconditions: 'Correct local pool; nonzero receiver and operator; positive cumulative and per-operation limits with per-operation no greater than cumulative; health factor at least 10,000 BPS; live ordered validity window; unused, non-invalidated nonce.',
				signals: '`LiquidationApprovalSet`',
			},
			{
				call: '`permitLiquidationApproval(params, signature)`',
				caller: 'Anyone relaying the receiver vault signature',
				effect: 'Validates an EIP-712 EOA or ERC-1271 signature immediately, installs explicit approval state, and consumes the receiver-scoped nonce.',
				declarations: [{ name: 'permitLiquidationApproval' }],
				preconditions: 'Signature is valid for `params.receiverVault`; the chain ID, registry address, stable name/version, pool, receiver, operator, target scope, limits, health factor, window, and nonce are bound by the digest; direct-install validation rules also pass.',
				signals: '`LiquidationApprovalSet`',
			},
			{
				call: '`revokeLiquidationApproval(approvalId)`',
				caller: 'Approval receiver vault only',
				effect: 'Prevents new reservations while leaving reservations already attached to staged operations intact.',
				declarations: [{ name: 'revokeLiquidationApproval' }],
				preconditions: 'Approval exists and is not already revoked.',
				signals: '`LiquidationApprovalRevoked` with available, reserved, and consumed totals',
			},
			{
				call: '`invalidateLiquidationApprovalNonce(newNonce)`',
				caller: 'Receiver vault invalidating its own older nonce range',
				effect: 'Raises the minimum nonce accepted for new approval installation or reservation.',
				declarations: [{ name: 'invalidateLiquidationApprovalNonce' }],
				preconditions: 'New nonce is greater than the receiver current minimum.',
				signals: '`LiquidationApprovalNonceInvalidated`',
			},
			{
				call: '`reserve(operationId, approvalId, receiverVault, targetVault, operator, requestedDebtAttoEth, snapshotTargetDebtAttoEth, latestExecutionTimestamp)`',
				caller: 'Bound coordinator only',
				effect: 'Moves quota from available to pending reserved at staging, bounded by requested debt, target snapshot debt, per-operation limit, and available cumulative quota.',
				declarations: [{ name: 'reserve' }],
				preconditions: 'Approval matches local pool, receiver, exact operator, and exact or wildcard target; it is active, unrevoked, non-invalidated, valid through latest execution, and has positive reservable quota.',
				signals: '`LiquidationApprovalReserved`',
			},
			{
				call: '`release(operationId)`',
				caller: 'Bound coordinator only',
				effect: 'Returns an unsettled delegated reservation to available quota. A missing, self-route, or already settled reservation is a no-op.',
				declarations: [{ name: 'release' }],
				preconditions: 'Coordinator terminal cleanup path.',
				signals: '`LiquidationApprovalReleased` when quota is returned',
			},
			{
				call: '`consume(operationId, debtMovedAttoEth)`',
				caller: 'Bound coordinator only',
				effect: 'Permanently consumes exactly moved debt, releases unused reservation, and settles the reservation once.',
				declarations: [{ name: 'consume' }],
				preconditions: 'For a delegated reservation, it is unsettled and moved debt does not exceed reserved debt. A self route is a no-op.',
				signals: '`LiquidationApprovalConsumed`',
			},
		],
	},
	{
		compiledAbiFingerprint: '96bf38a482665cf0e621d6345f97e7d5900965fcce217565184c1fa9783b79fb',
		name: 'OpenOraclePriceCoordinator',
		purpose: 'Obtains a fresh REP-per-ETH price and coordinates withdrawals, delegated liquidation routing, approval reservations, and terminal cleanup.',
		readAbiFingerprint: '2b4e03586a6b112405e3e8dc00ce49eac9a94cdd943685325ed5b875db742a45',
		readSurface:
			'Configuration getters are `MAX_PENDING_SETTLEMENT_OPERATIONS`, `SETTLEMENT_GAS_OVERHEAD`, `OPEN_INTEREST_DIVIDER`, `reputationToken`, `securityPool`, `openOracle`, `weth`, `liquidationApprovalRegistry`, `vaultOperations`, `gasConsumedOpenOracleReportPrice`, `gasConsumedSettlement`, `gasUnitsForOneDispute`, `initialReportPriorityFeeAttoEthPerGas`, `targetPriceErrorForDispute`, `openOracleSecurityMultiplierBps`, `settlementTime`, `disputeDelay`, `protocolFee`, `feePercentage`, `multiplier`, `timeType`, `trackDisputes`, `protocolFeeRecipient`, `escalationHaltMultiplierBps`, `maxSettlementBaseFeeMultiplierBps`, and `minLiquidationPriceDistanceBps`. Current report and operation getters are `pendingReportId`, `pendingReportSponsor`, `pendingOperationSlotId`, `lastSettlementTimestamp`, `lastPrice`, `pendingReportMaxSettlementBaseFeeAttoEthPerGas`, `stagedOperationCounter`, and `stagedOperations`. `lastSettlementTimestamp` records when the accepted final report reached settlement eligibility (report timestamp plus `settlementTime`), not when `settle` was called, and `isPriceValid` measures freshness from it. Use `isPriceValid`, `minimumToken1ReportAttoEth`, `getRequestPriceCostAttoEth`, `getQueuedOperationCostAttoEth`, `getSettlementCallbackGasLimit`, `getPendingOperationSlot`, `getActiveStagedOperationCount`, `getActiveStagedOperations`, `getPendingSettlementWork`, `getPendingSettlementOperationCount`, and `getPendingSettlementOperationIds` for derived or paged state.',
		securityBoundary:
			'Report and staged-operation liveness depends on [A16 timely inclusion](./security-model.html#assumption-a16), [A17 corrector capability](./security-model.html#assumption-a17), [A18 independent correction incentive](./security-model.html#assumption-a18), [A19 observable correctable price](./security-model.html#assumption-a19), and [A06 lifecycle executors](./security-model.html#assumption-a06). When `lastPrice` is zero, the official client currently needs an offchain market quote to propose the first report; quote availability is a client limitation rather than a protocol security assumption. Proposals copied from a nonzero cached price do not use that quote path.',
		readDeclarations: [
			{ name: 'isPriceValid' },
			{ name: 'minimumToken1ReportAttoEth' },
			{ name: 'getRequestPriceCostAttoEth' },
			{ name: 'getQueuedOperationCostAttoEth' },
			{ name: 'getSettlementCallbackGasLimit' },
			{ name: 'getPendingOperationSlot' },
			{ name: 'getActiveStagedOperationCount' },
			{ name: 'getPendingSettlementOperationCount' },
			{ name: 'getPendingSettlementOperationIds' },
			{ name: 'getActiveStagedOperations' },
			{ name: 'getPendingSettlementWork' },
		],
		readStorageDeclarations: [
			{ name: 'MAX_PENDING_SETTLEMENT_OPERATIONS' },
			{ name: 'SETTLEMENT_GAS_OVERHEAD' },
			{ name: 'OPEN_INTEREST_DIVIDER' },
			{ name: 'pendingReportId' },
			{ name: 'pendingReportSponsor' },
			{ name: 'pendingOperationSlotId' },
			{ name: 'lastSettlementTimestamp' },
			{ name: 'lastPrice' },
			{ name: 'reputationToken' },
			{ name: 'securityPool' },
			{ name: 'openOracle' },
			{ name: 'weth' },
			{ name: 'gasConsumedOpenOracleReportPrice' },
			{ name: 'gasConsumedSettlement' },
			{ name: 'gasUnitsForOneDispute' },
			{ name: 'initialReportPriorityFeeAttoEthPerGas' },
			{ name: 'targetPriceErrorForDispute' },
			{ name: 'openOracleSecurityMultiplierBps' },
			{ name: 'settlementTime' },
			{ name: 'disputeDelay' },
			{ name: 'protocolFee' },
			{ name: 'feePercentage' },
			{ name: 'multiplier' },
			{ name: 'timeType' },
			{ name: 'trackDisputes' },
			{ name: 'protocolFeeRecipient' },
			{ name: 'escalationHaltMultiplierBps' },
			{ name: 'maxSettlementBaseFeeMultiplierBps' },
			{ name: 'minLiquidationPriceDistanceBps' },
			{ name: 'pendingReportMaxSettlementBaseFeeAttoEthPerGas' },
			{ name: 'stagedOperationCounter' },
			{ name: 'stagedOperations' },
			{ name: 'liquidationApprovalRegistry' },
			{ name: 'vaultOperations' },
		],
		sourcePath: 'solidity/contracts/statoblast/OpenOraclePriceCoordinator.sol',
		interactions: [
			{
				call: '`requestPriceIfNeededAndStageLiquidation(targetVault, receiverVault, requestedDebtAttoEth, approvalId, ..., bountyAttoEth)`',
				caller: 'Liquidation operator; a delegated receiver must have approved this exact operator',
				effect:
					'Stages explicit operator, receiver, target backing, and target underwriting commitment and reserves bounded receiver quota before any oracle work. The queue event retains the full historical observation for indexing, while live execution inputs are not duplicated in persistent operation storage. The self-receiving operator path uses a zero approval ID.',
				declarations: [{ name: 'requestPriceIfNeededAndStageLiquidation' }],
				preconditions: 'Receiver differs from target; delegated approval matches pool, receiver, operator, and target scope, has available cumulative and per-operation quota, and remains valid through latest execution.',
				signals: '`LiquidationRouteStaged`; `LiquidationApprovalReserved` on a delegated route; staged-operation lifecycle events',
			},
			{
				call: '`requestPriceIfNeededAndStageOperation(...)` with funding when stale',
				caller: 'Vault owner for self withdrawal or a target change; self-receiving liquidation callers are also supported. While a report is pending, only that report sponsor may stage more operations.',
				effect:
					'Records the operation (`0` transferred commitment in attoETH, `1` withdrawal in attoREP, `2` absolute underwriting commitment in attoETH), executes immediately with a fresh price; otherwise it attaches it to the pending settlement batch while that batch has room, opening a report when none is pending and the batch was empty, or leaves it active outside the batch for a later `executeStagedOperation`. A target change cannot supersede an active dependent bundle. Otherwise, a newly accepted target change consumes any older active target change for the same vault with `success=false` and `Backing target superseded`, freeing its settlement slot. When a report opens, the whole committed `bountyAttoEth` is retained as the settler reward regardless of the inclusion-block cost. If unused ETH is positive, the final caller refund uses a low-level callback; rejection rolls back the entire transaction, including any queueing, immediate execution, or newly opened report.',
				declarations: [{ name: 'requestPriceIfNeededAndStageOperation' }],
				preconditions:
					'`securityPool.isEscalationResolved()` is false; valid self-target for withdrawal or underwriting-limit adjustment; liquidation and withdrawal require positive amounts, and a withdrawal whose previewed REP is zero reverts with `Withdraw amount has no effect`, while an absolute underwriting limit may be zero to request an exit; and timeout from 1 second through 5 minutes. A committed bounty of at least `getRequestPriceCostAttoEth()` covered by `msg.value`, buffered report funding, matching REP, and token approvals are required only when this call opens a new report. The caller must accept any positive unused-ETH refund.',
				signals: '`StagedOperationQueued`; `PriceRequested` when this call opens a report; `ExecutedStagedOperation` for immediate fresh-price execution or a superseded target change; `LiquidationRouteStaged` for operation `0`; authoritative `CoordinatorStateCheckpoint` records',
			},
			{
				call: '`stageVaultOperations(owner, changeCommitment, actionCount, validForSeconds, proposedRepPerEthPrice, requestedInitialAttoWeth, bountyAttoEth)`',
				caller: 'The immutable `vaultOperations` executor only; wallets enter through its `submitVaultOperations` function',
				effect:
					"Records operation type 3 with the submitting wallet as owner and report sponsor. A fresh-price bundle executes commitment changes, other-vault liquidations, and withdrawal atomically; a failure reverts the submission and its deposit. With a stale price, deposits complete immediately and dependent actions queue together. Any change to a queued liquidation target's backing units or underwriting commitment fails the whole bundle, rolling back the owner's commitment change and withdrawal. The failed bundle is consumed while its earlier deposit remains. Each action uses one of four settlement slots; the deposit uses none.",
				declarations: [{ name: 'stageVaultOperations' }],
				preconditions:
					'Execution window is 1–300 seconds; escalation is unresolved; a pending report belongs to the owner; a commitment change has no active preceding commitment operation. Stale-price bundles must fit the remaining weighted callback capacity and satisfy report funding when opening a report. Targets are distinct, nonzero other vaults with a positive commitment; liquidation bundles require a receiver health factor of at least 10,000 bps. All liquidation snapshots and pool safety checks must still pass at execution, and a withdrawal whose resulting REP is zero fails with `Withdraw amount has no effect`.',
				signals: '`StagedOperationQueued`, `PriceRequested` when opening a report, `ExecutedStagedOperation`, and `CoordinatorStateCheckpoint`; the executor also emits bundle and target details',
			},
			{
				call: '`requestPrice(proposedRepPerEthPrice, requestedInitialAttoWeth, bountyAttoEth)` with report funding',
				caller: 'Anyone when no fresh price or report is pending',
				effect: 'Opens and atomically funds a fresh WETH/REP report without staging a new operation, retains the whole committed bounty as the settler reward, then refunds any ETH above the bounty through a low-level caller callback. Callback rejection rolls back the report and initial position.',
				declarations: [{ name: 'requestPrice' }],
				preconditions:
					'Cached price stale; no pending report; nonzero proposed REP/ETH price, a committed bounty of at least `getRequestPriceCostAttoEth()` covered by `msg.value`, and funding and approvals for at least the configured priority report plus the larger of the base-fee and open-interest WETH reports, plus matching REP. Zero requested WETH uses the minimum; a larger request voluntarily increases the initial report. The caller must accept any positive excess-ETH refund.',
				signals: '`PriceRequested` and `CoordinatorStateCheckpoint`',
			},
			{
				call: '`executeStagedOperation(operationId)`',
				caller: 'Anyone',
				effect:
					"Consumes an expired operation and releases its delegated reservation without requiring a valid price. Otherwise, consumes and attempts the active operation using the current fresh price. Price-report funding is independent of the operation's notional; the downstream operation applies its own protocol bounds.",
				declarations: [{ name: 'executeStagedOperation' }],
				preconditions: 'Operation exists. Expired cleanup requires no valid price; a non-expired operation requires a fresh coordinator price. Lifecycle failures are emitted rather than retried.',
				signals: '`ExecutedStagedOperation`, either `LiquidationApprovalConsumed` or `LiquidationApprovalReleased` for a delegated liquidation, and `CoordinatorStateCheckpoint`',
			},
			{
				call: '`expireStagedOperation(operationId)`',
				caller: 'Anyone',
				effect: 'Permissionlessly consumes an expired operation and releases its liquidation reservation without requiring a valid oracle price.',
				declarations: [{ name: 'expireStagedOperation' }],
				preconditions: 'Operation exists and its settlement-plus-validity window has elapsed.',
				signals: '`ExecutedStagedOperation`, `LiquidationApprovalReleased` for a delegated liquidation, and `CoordinatorStateCheckpoint`',
			},
			{
				call: '`recoverSettledPendingReport()`',
				caller: 'Anyone',
				effect: 'Clears a pending report whose normal callback path did not clear coordinator state, consumes every live operation attached to that report, and releases each delegated-liquidation reservation. Operations that were active but outside the bounded pending callback batch remain active.',
				declarations: [{ name: 'recoverSettledPendingReport' }],
				preconditions: 'A pending report ID exists and its stored OpenOracle `storedGame(reportId).settlementTimestamp` is nonzero.',
				signals: '`PendingReportRecovered`, failed `ExecutedStagedOperation` for each live attached operation, `LiquidationApprovalReleased` for each attached delegated liquidation, and `CoordinatorStateCheckpoint`',
			},
			{
				call: '`openOracleCallback(...)`',
				caller: 'Configured `OpenOracle` only',
				effect: 'A valid settlement updates the price and auto-executes the bounded pending batch. A terminally rejected settlement consumes the pending batch and releases every liquidation reservation.',
				declarations: [{ name: 'openOracleCallback' }],
				preconditions: 'Callback report matches the pending report; excessive settlement basefee, a saturated `uint24` report counter, an uneconomic final history record at its recorded base fee plus configured priority fee, a stale report, or zero values reject the price after clearing pending report state.',
				signals: '`PriceReported` or `PriceReportRejected`; operation execution events; authoritative `CoordinatorStateCheckpoint` records',
			},
			{
				call: '`setLiquidationApprovalRegistry(registry)`',
				caller: 'The `PriceCoordinatorDeploymentWorker` that deployed the coordinator only, invoked by `OpenOraclePriceCoordinatorFactory` during deployment',
				effect: 'Binds the coordinator-local approval registry once.',
				declarations: [{ name: 'setLiquidationApprovalRegistry' }],
				preconditions: 'Registry is nonzero and no registry was previously installed.',
				signals: 'No event; deterministic factory deployment and the public getter identify the registry.',
			},
			{
				call: '`setSecurityPool(securityPool)`',
				caller: 'Anyone while `securityPool` remains zero; normal factory deployment calls atomically',
				effect: 'A nonzero value binds the pool permanently. A zero value emits and checkpoints zero but leaves the setter callable. `SecurityPoolFactory` supplies the nonzero canonical pool in the same deployment transaction, immediately after deploying the pool.',
				declarations: [{ name: 'setSecurityPool' }],
				preconditions: 'Current `securityPool` is zero; the argument itself is not required to be nonzero.',
				signals: '`SecurityPoolSet` and `CoordinatorStateCheckpoint`',
			},
			{
				call: '`setRepEthPrice(lastPrice)`',
				caller: 'Configured nonzero `SecurityPool` only',
				effect: "Seeds the coordinator's price value, including zero, for inherited child state.",
				declarations: [{ name: 'setRepEthPrice' }],
				preconditions: 'Caller equals the configured pool.',
				signals: '`RepEthPriceSet` and `CoordinatorStateCheckpoint`',
			},
		],
	},
	{
		compiledAbiFingerprint: 'b4d43db4a275c3118a700ca255a7f63d42dfdca1fb1e7c554d681e589a76ac85',
		name: 'ShareToken',
		purpose: "Stores universe-aware ERC-1155 [outcome shares](./glossary.html#outcome-share) and materializes a holder's persistent source entitlement in selected fork branches.",
		readAbiFingerprint: '6093653de73a0e5fa1e400d77bbded71a92de1197f58bd89da82a657887f349e',
		readSurface:
			'Base and relationship getters are `name`, `symbol`, `zoltar`, `canonicalPoolByUniverse`, `_balances`, `_supplies`, and `_operatorApprovals`. Standard ERC-1155 reads are `supportsInterface`, `balanceOf`, `totalSupply`, `balanceOfBatch`, and `isApprovedForAll`; protocol-specific reads are `isAuthorized`, `totalSupplyForOutcome`, `maximumOutcomeSupply`, `balanceOfOutcome`, `balanceOfShares`, `getMigratedShareAmountAttoShares`, `getTokenId`, `getTokenIds`, and `unpackTokenId`.',
		readDeclarations: [
			{ name: 'supportsInterface', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
			{ name: 'balanceOf', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
			{ name: 'totalSupply', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
			{ name: 'balanceOfBatch', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
			{ name: 'isApprovedForAll', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
			{ name: 'isAuthorized' },
			{ name: 'totalSupplyForOutcome' },
			{ name: 'maximumOutcomeSupply' },
			{ name: 'balanceOfOutcome' },
			{ name: 'balanceOfShares' },
			{ name: 'getMigratedShareAmountAttoShares' },
			{ name: 'getTokenId' },
			{ name: 'getTokenIds' },
			{ name: 'unpackTokenId' },
		],
		readStorageDeclarations: [
			{ name: 'name' },
			{ name: 'symbol' },
			{ name: 'zoltar' },
			{ name: 'canonicalPoolByUniverse' },
			{ name: '_balances', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
			{ name: '_supplies', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
			{ name: '_operatorApprovals', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' },
		],
		sourcePath: 'solidity/contracts/statoblast/tokens/ShareToken.sol',
		interactions: [
			{
				call: '`setApprovalForAll(operator, approved)`',
				caller: 'Any token account setting its own operator approval',
				effect: "Sets or clears the operator's authority over all of the caller's outcome-token balances.",
				declarations: [{ name: 'setApprovalForAll', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' }],
				preconditions: 'The operator differs from the caller.',
				signals: '`ApprovalForAll`',
			},
			{
				call: 'Both `safeTransferFrom(...)` overloads',
				caller: 'Share holder or approved ERC-1155 operator',
				effect: 'Transfers one outcome-token balance without changing supply.',
				declarations: [{ name: 'safeTransferFrom', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' }],
				preconditions:
					'Caller holds the source balance or has operator approval; the source account has not materialized that token into any child branch; destination is nonzero; the source balance is sufficient; under [A22 asset-recipient compatibility](./security-model.html#assumption-a22), a contract recipient accepts the ERC-1155 callback.',
				signals: '`TransferSingle`',
			},
			{
				call: 'Both `safeBatchTransferFrom(...)` overloads',
				caller: 'Share holder or approved ERC-1155 operator for a nonempty batch; any caller for an empty batch',
				effect: 'A nonempty batch transfers each listed outcome-token balance without changing supply. Equal empty ID and value arrays return as a no-op without an event.',
				declarations: [{ name: 'safeBatchTransferFrom', sourcePath: 'solidity/contracts/statoblast/tokens/ERC1155.sol' }],
				preconditions:
					'ID and value array lengths match. A nonempty batch also requires holder or operator authority, no listed source token that the source account has already materialized into a child branch, a nonzero destination, sufficient source balances, and, under [A22 asset-recipient compatibility](./security-model.html#assumption-a22), an accepting ERC-1155 callback from a contract recipient; the empty-batch no-op performs none of those checks.',
				signals: '`TransferBatch` for a nonempty batch; no event for an empty batch',
			},
			{
				call: '`migrate(fromId, targetOutcomeIndexes)`',
				caller: 'Holder of the source token ID',
				effect:
					"If needed, first freezes the operational source pool and records its fork snapshot. A single-target call may lazily create that child while the branch-creation window is open. It keeps and locks the holder's source entitlement, then mints each selected child-universe token ID up to the current source balance. Later source additions materialize only the unminted delta. A contract holder receives the ERC-1155 single-receiver callback for each mint; rejection rolls back the mint and preceding fork or child setup.",
				declarations: [{ name: 'migrate' }],
				preconditions:
					'Source universe forked; canonical source pool is `Operational` or `PoolForked`, and an `Operational` source has no inherited fixed outcome because auto-fork activation rejects one; positive source balance; nonempty, strictly increasing, well-formed outcomes; every target in a multi-target call already has a canonical child pool; after the branch-creation window, a single target must also already exist; at least one selected child has an unmaterialized balance; under [A22 asset-recipient compatibility](./security-model.html#assumption-a22), a contract holder accepts `onERC1155Received` for every target mint.',
				signals:
					'`PoolForkModeActivated`, `PoolAccountingCheckpoint`, `SecurityPoolForkSnapshot`, `ParentRepLocked`, and optionally `DisputeStakedRepDrainedAtFork` when auto-forking; `SecurityPoolRegistered`, `DeploySecurityPool`, `AuthorizationUpdated`, and `ChildPoolLinked` when lazily deploying, plus `DeployChild`, `ChildRepSplit`, `PoolHeldRepSweptToChild`, `EscalationGameSet`, `GameContinuedFromFork`, `ForkCarryCheckpoint`, and `ChildDisputeStakedRepMaterialized` as applicable; then one ERC-1155 mint `TransferSingle` and `Migrate` per materialized target on successful callbacks',
			},
			{
				call: '`authorize(securityPoolCandidate)`',
				caller: 'Initially authorized `SecurityPoolFactory` for an origin pool; an authorized parent `SecurityPool` for a child pool',
				effect: 'Establishes the candidate as `canonicalPoolByUniverse` for its universe and adds it to the set allowed to mint, burn, and authorize descendants. Reauthorizing the same candidate is a no-op.',
				declarations: [{ name: 'authorize' }],
				preconditions: 'Caller is already authorized; the candidate reports this exact share token; its universe has no different canonical pool.',
				signals: '`AuthorizationUpdated` on first authorization; no event when the same candidate is already authorized',
			},
			{
				call: '`mintCompleteSets(universeId, account, amountAttoShares)`',
				caller: 'An authorized `SecurityPool`',
				effect: "Mints `amountAttoShares` each of Invalid, Yes, and No to `account`, then invokes its ERC-1155 batch-receiver callback when it is a contract. Rejection rolls back the mint and the authorized pool's surrounding transaction.",
				declarations: [{ name: 'mintCompleteSets' }],
				preconditions: 'Caller is authorized; `account` is nonzero; `amountAttoShares` is positive; under [A22 asset-recipient compatibility](./security-model.html#assumption-a22), a contract account accepts `onERC1155BatchReceived`.',
				signals: '`TransferBatch` on a successful callback',
			},
			{
				call: '`burnCompleteSets(universeId, owner, amountAttoShares)`',
				caller: 'An authorized `SecurityPool`',
				effect: 'Burns `amountAttoShares` each of Invalid, Yes, and No from `owner`; global outcome supplies may differ.',
				declarations: [{ name: 'burnCompleteSets' }],
				preconditions: 'Caller is authorized; `owner` is nonzero and has at least `amountAttoShares` of every outcome.',
				signals: '`TransferBatch`',
			},
			{
				call: '`burnTokenIdAndGetRemainingSupply(tokenId, owner)`',
				caller: 'An authorized `SecurityPool`',
				effect: "Burns `owner`'s full balance of `tokenId` and returns the burned amount and that token ID's remaining supply.",
				declarations: [{ name: 'burnTokenIdAndGetRemainingSupply' }],
				preconditions: '`owner` is nonzero; caller is authorized.',
				signals: '`TransferSingle`, including when the burned balance is zero',
			},
		],
	},
	{
		compiledAbiFingerprint: '9292800021cde5c8c9dd6f96beb32a33a034949cd1d8d0d68671c3f900b27d2b',
		name: 'UniformPriceDualCapBatchAuction',
		purpose:
			'Collects ETH bids under ETH-raise and REP-sale caps, computes one clearing result, and supports paged settlement. AVL, cumulative-allocation, and refund-prefix mechanics live in [UniformPriceDualCapBatchAuctionStorage](solidity/contracts/statoblast/UniformPriceDualCapBatchAuctionStorage.sol), an internal storage library.',
		readAbiFingerprint: 'e4ad6ab91244711a2008716cfbdf62b6237d39321eefa984a4fdc7856267b8bc',
		readSurface:
			'Auction summary getters are `maxAttoRepBeingSold`, `attoEthRaiseCap`, `finalized`, `clearingTick`, `ethFilledAtClearingAttoEth`, `attoEthRaised`, `totalAttoRepPurchased`, `auctionStarted`, `minBidSizeAttoEth`, `owner`, `underfunded`, `underfundedThreshold`, `underfundedWinningAttoEth`, and `activeTickCount`. `pendingEthRefundsAttoEth` reports ETH credited during settlement and available for the bidder to pull. Use `computeClearing`, `previewFinalization`, `tickToPrice`, `getTickSummary`, `getTickCount`, `getTickPage`, `getActiveTickPage`, `getBidCountAtTick`, `getBidPageAtTick`, `getBidderBidCount`, and `getBidderBidPage` before finalizing or submitting settlement indexes.',
		readDeclarations: [
			{ name: 'computeClearing' },
			{ name: 'previewFinalization' },
			{ name: 'tickToPrice' },
			{ name: 'getTickSummary' },
			{ name: 'getTickCount' },
			{ name: 'getTickPage' },
			{ name: 'getActiveTickPage' },
			{ name: 'getBidCountAtTick' },
			{ name: 'getBidPageAtTick' },
			{ name: 'getBidderBidCount' },
			{ name: 'getBidderBidPage' },
		],
		readStorageDeclarations: [
			{ name: 'maxAttoRepBeingSold' },
			{ name: 'attoEthRaiseCap' },
			{ name: 'finalized' },
			{ name: 'clearingTick' },
			{ name: 'ethFilledAtClearingAttoEth' },
			{ name: 'attoEthRaised' },
			{ name: 'totalAttoRepPurchased' },
			{ name: 'auctionStarted' },
			{ name: 'minBidSizeAttoEth' },
			{ name: 'owner' },
			{ name: 'underfunded' },
			{ name: 'underfundedThreshold' },
			{ name: 'underfundedWinningAttoEth' },
			{ name: 'activeTickCount' },
			{ name: 'pendingEthRefundsAttoEth' },
		],
		sourcePath: 'solidity/contracts/statoblast/UniformPriceDualCapBatchAuction.sol',
		interactions: [
			{
				call: '`startAuction(attoEthRaiseCap, maxAttoRepBeingSold)`',
				caller: 'Auction owner (`SecurityPoolForker`) only',
				effect: 'Starts the one-week auction and fixes its two caps and minimum bid.',
				declarations: [{ name: 'startAuction' }],
				preconditions: 'Auction not previously started; both caps are positive; the REP cap does not exceed 11 million REP; the ETH cap fits in `uint128`; the block timestamp fits in `uint48`.',
				signals: '`AuctionStarted`',
			},
			{
				call: '`submitBid(tick)` with ETH',
				caller: 'Any bidder',
				effect: "Adds ETH demand at the selected positive-price tick while extending that tick's append-only cumulative bid and refund history, including when a fully refunded tick becomes active again.",
				declarations: [{ name: 'submitBid' }],
				preconditions: 'Auction active and unfinalized; before one-week deadline; bid meets `minBidSizeAttoEth`; tick maps to nonzero price; the individual bid and the resulting cumulative ETH at that tick each fit in `uint128`.',
				signals: '`BidSubmitted`',
			},
			{
				call: '`refundLosingBids(tickIndices)`',
				caller: 'Bidder for its own bids',
				declarations: [{ name: 'refundLosingBids' }],
				effect: "A nonempty list marks the caller's bids already provably below the current clearing tick and credits their ETH to `pendingEthRefundsAttoEth` without calling the bidder. An empty list changes no bids.",
				preconditions: 'Auction started and unfinalized; auction has reached a clearing price. Nonempty indexes additionally belong to the caller and are strictly losing and unrefunded.',
				signals: '`BidSettled` per refunded bid; one aggregate `EthRefundCredited` per call when total credited ETH is positive',
			},
			{
				call: '`refundLosingBidsFor(bidder, tickIndices)`',
				caller: 'Auction owner (`SecurityPoolForker`) only; public callers use `settleAuctionBids`',
				declarations: [{ name: 'refundLosingBidsFor' }],
				effect: "A nonempty list marks a named bidder's bids already provably below the current clearing tick and credits their ETH to `pendingEthRefundsAttoEth` without calling the bidder. An empty list changes no bids.",
				preconditions: 'Named bidder is nonzero; auction started and unfinalized; auction has reached a clearing price. Nonempty indexes additionally belong to that bidder and are strictly losing and unrefunded.',
				signals: '`BidSettled` per refunded bid; one aggregate `EthRefundCredited` per call when total credited ETH is positive',
			},
			{
				call: '`finalize()`',
				caller: 'Auction owner (`SecurityPoolForker`) only; users reach it through `finalizeTruthAuction`',
				effect: 'Fixes the clearing mode, clearing tick, ETH totals, and aggregate REP allocation, then calls the owner with the resulting proceeds, including when zero. A rejected call reverts finalization and its event.',
				declarations: [{ name: 'finalize' }],
				preconditions: 'Auction started, not finalized, and one-week deadline reached; owner accepts the proceeds ETH call, including zero value.',
				signals: '`AuctionFinalized`',
			},
			{
				call: '`withdrawBids(withdrawFor, tickIndices, proRataTotal, secondaryProRataTotal, repBackingUnitsTotal)`',
				caller: 'Auction owner only',
				effect:
					'Returns five `uint256` values in ABI order: `totalFilledAttoRep` (filled REP), `totalRefundAttoEth` (ETH refund), `totalProRataAllocation` (capacity), `totalSecondaryProRataAllocation` (bad debt), and `totalRepBackingUnitsAllocation` (REP backing units). The forker credits backing and capacity to the bidder vault and credits bad debt only while the recorded auction debt generation is current; the auction credits refunds to the beneficiary pull-payment balance without calling recipient code. Capacity and debt use fixed cumulative ETH positions. Backing units use the corresponding cumulative filled-REP positions to exhaust `repBackingUnitsTotal` without claim-order dependence. An empty list returns five zeros without changing bids or emitting events.',
				declarations: [{ name: 'withdrawBids' }],
				preconditions: 'Auction finalized; caller is owner. Nonempty indexes belong to `withdrawFor` and remain unsettled.',
				signals: '`BidSettled` per processed bid; one `EthRefundCredited` for the call when aggregate `totalRefundAttoEth` is positive',
			},
			{
				call: '`withdrawPendingEthRefund()`',
				caller: 'Bidder with credited ETH',
				effect: "Clears the caller's complete credited refund and emits its withdrawal before transferring. A rejected pull reverts the transfer, clear, and event, preserving the credit. Checks-effects-interactions makes callback reentry observe a zero balance.",
				declarations: [{ name: 'withdrawPendingEthRefund' }],
				preconditions: 'Caller has a positive `pendingEthRefundsAttoEth` balance and currently accepts ETH.',
				signals: '`PendingEthRefundWithdrawn`',
			},
		],
	},
]
