import type { ContractReference } from './contract-reference-metadata.mts'

export const securityPoolContractReference: ContractReference = {
	compiledAbiFingerprint: '6e87239d65abcf128d5b842fa5420c4181871e3da162c70dda008824eb3c3a5f',
	name: 'SecurityPool',
	delegatedInteractions:
		'Vault owners authorize standing ETH limits with `setUnderwritingLimit(limitAttoEth)` or coordinator operation `SetVaultUnderwritingLimit` (2). The coordinator-only fallback is `setVaultUnderwritingLimit(vault, limitAttoEth)`. Increases require fresh-price backing for the entire resulting limit and open admission. Reductions, including zero exits, require remaining aggregate commitments to cover tracked settlement collateral. Fee weights checkpoint before mutation; no-op updates preserve certificates and remainders. Limits survive empty settlement epochs. `UnderwritingLimitSet` and accounting checkpoints report successful changes.',
	purpose: 'Holds ETH collateral and REP underwriting, accounts for vaults and fees, mints shares, and routes local escalation.',
	readAbiFingerprint: '3b8b9493a0d859ba9f46ff12d5be5ba5755ef999895c64ad0964b34876708355',
	readSurface:
		'Immutable relationship and configuration getters are `questionId`, `universeId`, `initialEscalationGameDepositAttoRep`, `zoltar`, `parent`, `shareToken`, `repToken`, `priceOracleManagerAndOperatorQueuer`, `openOracle`, `escalationGameFactory`, `eventEmitter`, `questionData`, `securityPoolForker`, `truthAuction`, `securityPoolFactory`, and `statoblastSecurityMultiplierBps`; the current game is `escalationGame`. The escalation deposit is derived at construction from live universe theoretical REP supply rather than copied from factory configuration. Accounting getters include `totalUnderwritingLimitAttoEth`, `settlementCollateralAttoEth`, `totalRepBackingUnits`, `shareTokenSupplyAttoShares`, `securityVaults`, `minimumSecurityBondDebtAttoEth`, `minimumVaultRepDepositAttoRep`, `totalBadDebtAttoEth`, and `vaultBadDebtAttoEth`. Aggregate and per-vault bad debt describe only the current collateral-claim generation; `getPoolAccountingSnapshot` exposes its `badDebtGeneration`. Exhausting the remaining claim supply clears aggregate debt and advances the generation before later collateral can be minted. Use `getVaultUnderwritingLimitAttoEth` for the standing owner-authorized ETH commitment, separate from REP deposits. `getCertifiedUnderwritingLimitAttoEth` reports the aggregate certified against the live backing snapshot. Certification is permissionless, one vault per call, and checks full limits. `isVaultCoverageCertified` identifies each vault requiring a keeper transaction without an on-chain scan. Keeper certification is independent of mint workflows, allowing finality waits between transactions. `coverageRevision` invalidates local backing and weight mutations. Global changes may require one transaction per committed vault before minting resumes. Pending migration and unclaimed auction commitments cannot be certified before assignment. Use `getVaultCapacityBackingFactorsBps` for current associated and pool-held REP-per-capacity ratios, `getCurrentMintingCapacityAttoEth` for aggregate standing ETH commitments, and `getVaultOpenInterestAttoEth` for a vault’s live proportional obligation. Other derived and paged reads are `getVaultCount`, `getVaults`, `attoSharesToAttoEth`, `attoEthToAttoShares`, `attoRepToBackingUnits`, `backingUnitsToAttoRep`, `getTotalPoolHeldAttoRep`, `totalAccruedFeesAttoEth`, `getPoolAccountingSnapshot`, `getFeeEpochEndTime`, `getVaultFeeRemainder`, and `isEscalationResolved`. The backing-factor ratios are not current vault health: associated REP includes dispute-staked principal as at-risk security, while current health also depends on the full ETH limit, REP/ETH price, the security multiplier, and both protocol constraints. The vault registry is append-only and newest-registered first. Registration requires only a nonzero address and can occur without economic state; consumers filter current positions from `securityVaults`, escalation stake, and bad debt. `isEscalationResolved()` is true when the pool inherits a fixed fork outcome, or when a local escalation game is configured and the forker routes a non-`None` outcome. An operational fixed-outcome child remains available for settlement and redemption but rejects new collateralized operations. `getFeeEpochEndTime()` returns the effective fee cutoff, or `type(uint256).max` for an open child epoch. A resolved child without a continuation game fixes its cutoff at activation. Lifecycle and fee getters are `totalClaimableVaultFeesAttoEth`, `lastUpdatedFeeAccumulator`, `feeIndex`, `currentRetentionRate`, `awaitingForkContinuation`, and `systemState`.',
	securityBoundary:
		'Price-sensitive withdrawal, dynamic-capacity, and liquidation calls depend on [A16 timely inclusion](./security-model.html#assumption-a16), [A21 genesis REP and WETH behavior](./security-model.html#assumption-a21), [A19 observable correctable price](./security-model.html#assumption-a19), and [A06 lifecycle executors](./security-model.html#assumption-a06). User-initiated pool calls additionally depend on [A28 account authority](./security-model.html#assumption-a28).',
	readDeclarations: [
		{ name: 'getVaultCount' },
		{ name: 'getVaults' },
		{ name: 'attoSharesToAttoEth' },
		{ name: 'attoEthToAttoShares' },
		{ name: 'attoRepToBackingUnits' },
		{ name: 'backingUnitsToAttoRep' },
		{ name: 'getTotalPoolHeldAttoRep' },
		{ name: 'totalAccruedFeesAttoEth' },
		{ name: 'getPoolAccountingSnapshot' },
		{ name: 'getFeeEpochEndTime' },
		{ name: 'getVaultFeeRemainder' },
		{ name: 'getCurrentMintingCapacityAttoEth' },
		{ name: 'getVaultOpenInterestAttoEth' },
		{ name: 'getVaultUnderwritingLimitAttoEth' },
		{ name: 'getCertifiedUnderwritingLimitAttoEth' },
		{ name: 'isVaultCoverageCertified' },
		{ name: 'vaultBadDebtAttoEth' },
		{ name: 'getVaultCapacityBackingFactorsBps' },
		{ name: 'isEscalationResolved' },
	],
	readStorageDeclarations: [
		{ name: 'questionId' },
		{ name: 'universeId' },
		{ name: 'initialEscalationGameDepositAttoRep' },
		{ name: 'zoltar' },
		{ name: 'parent' },
		{ name: 'shareToken' },
		{ name: 'repToken' },
		{ name: 'priceOracleManagerAndOperatorQueuer' },
		{ name: 'openOracle' },
		{ name: 'escalationGameFactory' },
		{ name: 'eventEmitter' },
		{ name: 'escalationGame', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'questionData' },
		{ name: 'securityPoolForker' },
		{ name: 'truthAuction' },
		{ name: 'securityPoolFactory' },
		{ name: 'totalUnderwritingLimitAttoEth', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'settlementCollateralAttoEth', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'totalRepBackingUnits', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'statoblastSecurityMultiplierBps', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'shareTokenSupplyAttoShares', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'totalClaimableVaultFeesAttoEth', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'lastUpdatedFeeAccumulator', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'feeIndex', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'currentRetentionRate', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'awaitingForkContinuation', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'securityVaults', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'totalBadDebtAttoEth', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'systemState', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'minimumSecurityBondDebtAttoEth', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'minimumVaultRepDepositAttoRep', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
		{ name: 'coverageRevision', sourcePath: 'solidity/contracts/statoblast/SecurityPoolStorage.sol' },
	],
	sourcePath: 'solidity/contracts/statoblast/SecurityPool.sol',
	interactions: [
		{
			call: '`burnEscalationWinnerHaircut(amountAttoRep)`',
			caller: "This pool's `EscalationGame` only",
			effect: 'Burns the winning-deposit haircut from REP already escrowed in the game.',
			declarations: [{ name: 'burnEscalationWinnerHaircut' }],
			preconditions: 'Caller is the configured escalation game; amount is positive and the game has already transferred enough REP to the pool.',
			signals: '`RepBurned` and ERC-20 `Transfer`; child REP also emits `Burn`',
		},
		{
			call: '`setUnderwritingLimit(limitAttoEth)`',
			caller: 'Vault owner',
			effect: 'Checkpoints fees and changes the standing ETH commitment independently of REP ownership.',
			declarations: [{ name: 'setUnderwritingLimit' }],
			preconditions: 'Operational; increases require open admission, a fresh price and both full-limit backing checks. Reductions must leave total commitments at least equal to tracked collateral. Resolved operational pools may reduce limits after an unrelated late fork.',
			signals: '`UnderwritingLimitSet` and accounting checkpoints; no-op calls preserve state',
		},
		{
			call: '`certifyVaultCoverage(vault)`',
			caller: 'Anyone',
			effect: 'Adds a positive full limit once per live certificate generation after checking both backing constraints. The aggregate must equal total commitments before minting.',
			declarations: [{ name: 'certifyVaultCoverage' }],
			preconditions: 'Fresh price, no escalation game, positive vault limit, and sufficient full-limit backing. The live snapshot prevents stale certificates authorizing minting.',
			signals: '`VaultCoverageCertified`; repeated certification in the same generation is a no-op',
		},
		{
			call: '`depositRepToVault(attoRepAmount, targetHealthFactorBps)`',
			caller: 'Vault owner',
			effect: 'Prices proportional REP backing units before receiving the transfer, including authorization deposits, then credits only those units. Depositing REP never changes the standing underwriting limit. Backing conversion changes invalidate certification.',
			declarations: [{ name: 'depositRepToVault' }],
			preconditions:
				'Operational and unforked; `isEscalationResolved()` is false; the transaction timestamp is strictly before the question end time unless the pool has an inherited fork-continuation game; deposit amount is positive; target backing ratio is at least `statoblastSecurityMultiplierBps` and resulting vault REP meets the configured supply-scaled minimum. This input does not authorize a commitment.',
			signals: '`RepDepositedToVault` and accounting checkpoints',
		},
		{
			call: '`redeemFees(vault)`',
			caller: 'Anyone; any nonzero ETH payment is always sent to `vault`',
			effect: "First accrues the vault's fees. If resulting claimable fees are zero, returns without payment; otherwise clears and pays the full amount.",
			declarations: [{ name: 'redeemFees' }],
			preconditions: 'A nonzero payment path requires `vault` to accept ETH.',
			signals: 'Accrual checkpoints only when accrual state changes; both `VaultAccountingCheckpoint` and `PoolAccountingCheckpoint` for a nonzero redemption; no event when fees and accrual state are unchanged',
		},
		{
			call: '`createCompleteSet()` with ETH',
			caller: 'Trader',
			effect: 'Adds collateral and mints one `Invalid`, `Yes`, and `No` share per complete-set unit, then invokes the ERC-1155 batch-receiver callback for a contract trader. Callback rejection rolls back the ETH, pool accounting, events, and share mint.',
			declarations: [{ name: 'createCompleteSet' }],
			preconditions:
				'Operational and unforked; no escalation game or pending continuation; fresh oracle price; positive ETH converts to at least one complete-set unit. Resulting tracked collateral must not exceed total commitments, and every commitment must be certified for its full limit against the current price, backing conversion, pool state and accounting revision. A contract trader must accept `onERC1155BatchReceived` under [A22 asset-recipient compatibility](./security-model.html#assumption-a22).',
			signals: '`CompleteSetCreated`, `PoolAccountingCheckpoint`, then ERC-1155 `TransferBatch` on a successful callback',
		},
		{
			call: '`redeemCompleteSet(amountAttoShares)`',
			caller: 'Anyone; positive redemption requires the caller to hold the complete set',
			effect:
				"Burns equal balances of all three outcomes and pays `amountAttoShares * settlementCollateralAttoEth / shareTokenSupplyAttoShares` using the pool's remaining economic claim supply as its collateral denominator. Complete-set issuance adds to that denominator, while complete-set and winning-share redemption consume it; fork-time source entitlements materialize without changing it because their claims are already reserved. When the remaining supply reaches zero, aggregate bad debt is cleared and per-vault bad-debt reads advance to an empty collateral generation. Zero passes the token and accounting checks and follows the normal zero-value event, checkpoint, and ETH-send path; rejection of that ETH call reverts the transaction.",
			declarations: [{ name: 'redeemCompleteSet' }],
			preconditions: 'Operational and unforked; caller holds every outcome amount requested; caller accepts the resulting ETH call, including zero value. Zero is accepted without a token balance.',
			signals: '`CompleteSetRedeemed` and `PoolAccountingCheckpoint`',
		},
		{
			call: '`redeemShares()`',
			caller: 'Anyone; a positive payout requires the caller to hold winning shares',
			effect:
				"Burns the caller's full winning balance and pays its pro-rata remaining collateral. When the remaining supply reaches zero, aggregate bad debt is cleared and per-vault bad-debt reads advance to an empty collateral generation. A zero winning balance passes token and accounting checks and follows the normal zero-value event, checkpoint, and ETH-send path; rejection of that ETH call reverts the transaction.",
			declarations: [{ name: 'redeemShares' }],
			preconditions: 'Operational pool with a final outcome; caller accepts the resulting ETH call, including zero value.',
			signals: '`SharesRedeemed` and `PoolAccountingCheckpoint`',
		},
		{
			call: '`redeemRepFromVault(vault)`',
			caller: 'Vault owner; caller must equal `vault`, and REP is sent to `vault`',
			effect: "Burns the vault's REP backing units and returns its proportional vault REP backing.",
			declarations: [{ name: 'redeemRepFromVault' }],
			preconditions: 'Operational pool with a final outcome; the specified `vault` has no escalation escrow and has redeemable REP.',
			signals: '`RepRedeemedFromVault`',
		},
		{
			call: '`depositToEscalationGame(outcome, maxAmount)`',
			caller: 'Vault owner',
			effect:
				"Deploys the local game on the first deposit. The game factory uses the configured start bond while it is below the live non-decision threshold; if tracked REP supply later makes it too large, the factory uses `nonDecisionThresholdAttoRep - 1` instead. Repeat deposits use the existing game's stored `startBondAttoRep` and `nonDecisionThresholdAttoRep`. Every accepted deposit removes enough REP backing units and escrows dispute-staked REP on the selected outcome.",
			declarations: [{ name: 'depositToEscalationGame' }],
			preconditions:
				'Question end has passed; pool operational in an unforked universe, without an inherited fixed outcome, and not awaiting continuation. On the first deposit, the live non-decision threshold must exceed one attoREP; outcome and amount accepted; the remaining vault and aggregate pool totals each preserve both full-commitment backing requirements; a fresh price is required when total capacity ownership is nonzero.',
			signals: '`EscalationGameSet` on first deposit; `DepositToEscalationGame`',
		},
		{
			call: '`withdrawFromEscalationGame(outcome, depositIndexes)`',
			caller: 'Anyone; a nonempty list must select deposits belonging to one original depositor',
			effect: 'A nonempty list settles local deposits and pays winning REP to the immutable depositor recorded by each deposit. Liquidation cannot change that payout address. An empty list returns after the outer lifecycle checks without settlement, state change, or event.',
			declarations: [{ name: 'withdrawFromEscalationGame' }],
			preconditions:
				'Game configured; operational pool; valid final outcome. If an external fork interrupted the game, parent withdrawal stays unavailable: winners settle in the child by carried proof, inherited losers require no transaction, and unresolved parent escalation-deposit accounting cleanup is optional. A nonempty list additionally requires valid local indexes and one common depositor.',
			signals: 'Per processed deposit, escalation-game `CarryDepositConsumed`; additionally `ClaimDeposit` for a winning payout. No event for an empty list',
		},
		{
			call: '`withdrawForkedEscalationDeposits(outcome, proofs)`',
			caller: 'Anyone; a nonempty list must name one original depositor across all proofs',
			effect:
				'A nonempty list verifies and consumes carried proofs, then pays winning child REP to the immutable depositor committed in each leaf. Stable continuation identities retain the creating game. Allocations follow the source-game chain and apply each auction haircut through cumulative interval rounding; read cost grows with fork depth. An empty list returns after the outer lifecycle checks without proof verification, state change, or event.',
			declarations: [{ name: 'withdrawForkedEscalationDeposits' }],
			preconditions: 'Game configured; operational child pool; valid final outcome. A nonempty list additionally requires an initialized and fully resumed continuation game, valid unconsumed winning proofs, and one common depositor.',
			signals: 'Per processed proof, escalation-game `CarryDepositConsumed` and `ClaimDeposit`. No event for an empty list',
		},
		{
			call: '`updateSettlementCollateral()`',
			caller: 'Anyone',
			effect:
				'For an initial pool, accrues elapsed fees through question end while its universe remains unforked; after that universe forks, its fork timestamp replaces question end as the cutoff, including a later question-end-to-fork interval. Finalizing an activated child starts a separate epoch at that finalization timestamp, which runs until the child game resolves or the child universe subsequently forks. An inherited fixed-outcome child without a continuation game fixes its cutoff at finalization and accrues no later fees. Accumulator timestamps prevent charging an interval twice. It moves whole credited fees from settlement collateral into the unallocated accrued-fee reserve and advances the accumulator. With positive elapsed time but zero fee-eligible capacity ownership it clears denominator-specific remainder and advances the timestamp without charging fees.',
			declarations: [{ name: 'updateSettlementCollateral' }],
			preconditions: 'No caller or lifecycle restriction. It returns unchanged when the accumulator is already at or beyond the clamped timestamp.',
			signals: '`PoolAccountingCheckpoint` whenever positive elapsed time is processed, including the zero-capacity-ownership branch; no event for an unchanged timestamp',
		},
		{
			call: '`updateRetentionRate()`',
			caller: 'Anyone',
			effect: 'Recalculates the retention rate from current collateral and total standing ETH commitments.',
			declarations: [{ name: 'updateRetentionRate' }],
			preconditions: 'No caller restriction. It returns unchanged when the pool is not `Operational` or the calculated rate equals the stored rate. Zero live minting capacity selects the maximum retention rate.',
			signals: '`PoolAccountingCheckpoint` only when the stored retention rate changes; no event for a no-op',
		},
		{
			call: '`updateVaultFees(vault)`',
			caller: 'Anyone for any address',
			effect:
				'A vault accounting checkpoint: first updates pool accrual, then advances the vault fee index and fractional remainder, moves whole assigned fees from reserve to the vault, registers any previously unseen nonzero vault address regardless of economic state, and returns leftover reserve to settlement collateral once a forked pool has checkpointed all fee-eligible capacity ownership. It never changes a standing underwriting limit, including in an empty pool.',
			declarations: [{ name: 'updateVaultFees' }],
			preconditions: 'No caller, nonzero-vault, or lifecycle restriction.',
			signals: 'Accrual `PoolAccountingCheckpoint` when due; `VaultAccountingCheckpoint` when the vault index, remainder, or claimable fee balance changes; an additional `PoolAccountingCheckpoint` when pool accounting changes; no event when neither accrual nor vault or pool accounting changes',
		},
		{
			call: '`withdrawRepFromVault(vault, attoRepAmount)`',
			caller: "This pool's `OpenOraclePriceCoordinator` only",
			effect: 'Removes the requested proportional REP backing units, or all backing units when the requested remainder would fall below the REP minimum; preserves the vault and aggregate standing ETH commitments; recalculates retention; and transfers the resulting withdrawable REP to `vault`.',
			declarations: [{ name: 'withdrawRepFromVault' }],
			preconditions:
				'Fresh coordinator price; operational pool in an unforked universe; `isEscalationResolved()` is false; no vault REP escrow. The remaining vault backing must meet both upward-rounded associated-REP and pool-held-REP requirements for its full standing ETH limit, with equality healthy. A withdrawal cannot implicitly exit a commitment.',
			signals: 'REP `Transfer`; `RepWithdrawnFromVault`; `VaultAccountingCheckpoint`; and applicable fee-accrual or retention `PoolAccountingCheckpoint` events',
		},
		{
			call: '`performLiquidation(request)`',
			caller: "This pool's `OpenOraclePriceCoordinator` only",
			effect:
				'Transfers up to the requested ETH commitment from target to authorized receiver, conserving total commitments. REP awards are capped by available target backing. A sufficiently backed receiver can accept the full limit even when the nominal award is underfunded. Fees checkpoint first and remain with their earners; escalation claims remain with their owners. Residual commitments remain visible and continue earning fees. Liquidation creates no write-off.',
			declarations: [{ name: 'performLiquidation' }],
			preconditions:
				'In ABI order, `request` contains `operationId`, `operator`, `receiverVault`, `targetVault`, `requestedDebtAttoEth`, `snapshot`, `minimumReceiverHealthFactorBps`, and `minLiquidationPriceDistanceBps`. The nested snapshot contains only `targetBackingUnits` and `targetUnderwritingLimitAttoEth`. Fresh settled coordinator price; operational pool in an unforked universe; `isEscalationResolved()` is false; receiver differs from target; neither participant has current-generation bad debt. A bad-debt-bearing vault becomes eligible again after the current collateral claims are exhausted, which clears aggregate debt and advances the bad-debt generation. The two target snapshot fields must match, while execution reads current pool totals. After target and receiver fee checkpoints, the liquidation delegate requires live target backing, dispute-staked REP, and full underwriting limit to remain at least `minLiquidationPriceDistanceBps` beyond the liquidation threshold and requires the live target state to remain unhealthy. When debt moves, the receiver must satisfy the protocol backing checks multiplied by its approved minimum health factor, using live post-liquidation state and upward-rounded requirements; its resulting commitment must meet the configured debt floor and its REP must meet the vault floor. The target resulting commitment must be zero or meet the commitment floor; partial awards reserve the target REP floor when available.',
			signals: 'Fee-accrual and target or receiver `VaultAccountingCheckpoint` events as needed; `VaultLiquidated` identifies operation, operator, receiver, target, transferred commitment in the debt and limit fields, with zero written-off debt; final pool accounting checkpoint',
		},
		{
			call: '`setStartingParams(...)`',
			caller: '`SecurityPoolFactory` only',
			effect: "Sets the fee timestamp and initial question-end epoch cutoff, retention, and collateral, seeds the coordinator with zero for an origin or the parent's last price for a child, then checkpoints initialization.",
			declarations: [{ name: 'setStartingParams' }],
			preconditions: 'Factory caller. The pool has no internal one-shot or lifecycle guard; the factory exposes it only through atomic deployment wiring.',
			signals: 'Coordinator `RepEthPriceSet` and `CoordinatorStateCheckpoint`, then pool `PoolAccountingCheckpoint`, even for zero or repeated values if the factory were to call again',
		},
		{
			call: '`activateForkMode()`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'activateForkMode' }],
			effect:
				"Sets `PoolForked`, accrues through the fork clamp, transfers the pool's entire REP balance to the forker, then makes the pool drain its configured escalation game's entire REP balance to the forker. Repeated calls are not lifecycle-guarded and transfer any balances replenished since the prior call before repeating the checkpoints.",
			preconditions: "The pool has no inherited fixed outcome, so a fixed child cannot reopen for a later universe fork. There is no current-state guard otherwise. A configured game's drain must succeed or the entire activation reverts without propagating its reason data.",
			signals: 'Pool-held REP `Transfer` always, including at zero; configured-game REP `Transfer` only for a positive game balance; accrual checkpoint when due; always `PoolForkModeActivated` and fork-activation `PoolAccountingCheckpoint`',
		},
		{
			call: '`initializeForkedEscalationGame(...)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'initializeForkedEscalationGame' }],
			effect: "Deploys and starts the pool's paused fork-continuation game with inherited timing and optional fixed outcome.",
			preconditions: 'No game is configured; downstream `startFromFork` parameters are valid.',
			signals: 'Escalation `GameContinuedFromFork`, then pool `EscalationGameSet`',
		},
		{
			call: '`initializeForkCarrySnapshotWithResolutionBalances(...)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'initializeForkCarrySnapshotWithResolutionBalances' }],
			effect: "Installs the continuation game's immutable carry peaks, counts, totals, resolution balances, and normalized nullifier roots.",
			preconditions: 'A game is configured; it is a fork continuation with no prior snapshot; leaf counts fit the MMR; supplied or computed snapshot ID matches the data.',
			signals: '`ForkCarryCheckpoint`',
		},
		{
			call: '`resumeForkedEscalationGame()`',
			caller: 'Anyone',
			declarations: [{ name: 'resumeForkedEscalationGame' }],
			effect: "Checks the already-installed immutable carry commitment and aggregate REP funding, clears the pool wait flag, records the resume timestamp, and starts the continuation's remaining escalation clock in one bounded call.",
			preconditions: 'Pool is operational, awaiting a configured fork continuation, and the game has not resumed.',
			signals: '`ForkContinuationResumed` and `AwaitingForkContinuationSet(false)`',
		},
		{
			call: '`setAwaitingForkContinuation(shouldAwait)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'setAwaitingForkContinuation' }],
			effect: 'Stores whether complete-set minting must wait for continuation initialization.',
			preconditions: 'No lifecycle or value-change guard.',
			signals: '`AwaitingForkContinuationSet`, including for a repeated value',
		},
		{
			call: '`setSystemState(newState)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'setSystemState' }],
			effect: 'Replaces the pool lifecycle state directly.',
			preconditions: 'No transition or value-change guard.',
			signals: '`SystemStateSet`, including for a repeated state',
		},
		{
			call: '`configureVault(vault, repBackingUnits, underwritingLimitAttoEth, vaultFeeIndex, newVaultBadDebtAttoEth, newTotalBadDebtAttoEth)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'configureVault' }],
			effect: 'Replaces the vault REP backing units, price-independent capacity ownership, fee index, vault bad debt, and aggregate pool bad debt, clears pooled fee-index remainder when capacity ownership changes, and registers the nonzero vault address regardless of the supplied state.',
			preconditions: '`vault` is nonzero; no lifecycle or value-change guard.',
			signals: 'Always `VaultAccountingCheckpoint` and `PoolAccountingCheckpoint`, including when all supplied values repeat current state',
		},
		{
			call: '`activateRecoveredCommitment(vault, commitmentAttoEth)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'activateRecoveredCommitment' }],
			effect: 'Activates prospective fee eligibility for an orphaned commitment after the forker checkpoints and assigns its backing and limit. Total commitments remain unchanged; certification is invalidated.',
			preconditions: 'Operational, unforked pool, fresh price and both backing checks on the receiver’s entire resulting limit.',
			signals: '`PoolAccountingCheckpoint`',
		},
		{
			call: '`configureFinalizedAuctionVault(vault, repBackingUnits, underwritingLimitAttoEth, vaultFeeIndex, newVaultBadDebtAttoEth, newTotalBadDebtAttoEth)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'configureFinalizedAuctionVault' }],
			effect: 'Assigns finalized-auction REP backing and already-fee-eligible capacity ownership to the winning vault without clearing the pool-wide fee-index remainder, then replaces the vault fee index, bad debt, and aggregate pool bad debt and registers the vault.',
			preconditions: '`vault` is nonzero; the forker has already included the sold capacity ownership in the pool fee denominator at auction finalization.',
			signals: 'Always `VaultAccountingCheckpoint` and `PoolAccountingCheckpoint`, including when all supplied values repeat current state',
		},
		{
			call: '`setTotalRepBackingUnits(newDenominator)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'setTotalRepBackingUnits' }],
			effect: 'Replaces the REP backing units denominator.',
			preconditions: 'No lifecycle or value-change guard.',
			signals: '`TotalRepBackingUnitsSet`, including for zero or a repeated value',
		},
		{
			call: '`setTotalSharesAttoShares(newTotalSharesAttoShares)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'setTotalSharesAttoShares' }],
			effect: 'Replaces stored `shareTokenSupplyAttoShares`, the denominator used by `attoSharesToAttoEth` and complete-set redemption.',
			preconditions: 'No lifecycle or value-change guard.',
			signals: '`ShareTokenSupplySet`, including for zero or a repeated value',
		},
		{
			call: '`setPoolFinancials(newSettlementCollateralAttoEth, newTotalUnderwritingLimitAttoEth, newFeeEligibleUnderwritingLimitAttoEth, newTotalBadDebtAttoEth)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'setPoolFinancials' }],
			effect: 'Replaces settlement collateral, both price-independent capacity-ownership totals, and aggregate pool bad debt, resets the fee timestamp to the current block, opens the finalized child fee epoch unless the child has a fixed outcome and no continuation game, and clears fee-index rounding carry.',
			preconditions: 'Fee-eligible capacity ownership does not exceed total capacity ownership. Actual ETH covers the supplied collateral plus all accrued fee liabilities. Installing inherited liabilities does not require current REP solvency.',
			signals: '`PoolAccountingCheckpoint`, including for repeated financial values',
		},
		{
			call: '`authorizeChildPool(pool)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'authorizeChildPool' }],
			effect: 'Asks the lineage share token to establish `pool` as the canonical authorized pool for its universe; reauthorizing the same pool is a no-op.',
			preconditions: 'This parent pool is already authorized; candidate reports this share token; candidate universe has no different canonical pool. No pool-lifecycle guard.',
			signals: '`AuthorizationUpdated` only on first authorization; no event when already authorized',
		},
		{
			call: '`transferEth(receiver, amountAttoEth)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'transferEth' }],
			effect: 'Reduces tracked settlement collateral by `amount`, checkpoints the reconciliation, and calls `receiver` with that ETH. At zero amount it reduces no settlement collateral but still emits the checkpoint and performs a zero-value call; callback rejection rolls back the transaction and checkpoint.',
			preconditions: 'Fee liabilities are covered; `amount` fits both unreserved pool ETH and tracked settlement collateral; `receiver` accepts the ETH call, including zero value.',
			signals: '`PoolAccountingCheckpoint`, including at zero amount; no dedicated ETH-transfer event',
		},
		{
			call: '`assignFinalizedAuctionFees(vault, amountAttoRep, auctionFeeIndexAtFinalization)`',
			caller: '`SecurityPoolForker` only',
			declarations: [{ name: 'assignFinalizedAuctionFees' }],
			effect:
				'Assigns to the claiming vault the fees its auctioned capacity ownership accrued from truth-auction finalization through the current fee index, combines fractional carry with the vault remainder, and removes whole assigned fees from the unallocated reserve. The ownership was already included in the fee denominator and total ownership at finalization. This call preserves aggregate fees and settlement collateral; after every eligible ownership is reconciled on a forked pool, a subsequent permissionless `updateVaultFees` checkpoint returns any reserve that no vault can individually claim to settlement collateral.',
			preconditions: 'The supplied finalization index does not exceed the current fee index; the forker credit workflow has already checkpointed the vault and added the claimed capacity ownership.',
			signals: '`VaultAccountingCheckpoint` and auction-claim `PoolAccountingCheckpoint`; the calling forker emits `ClaimAuctionProceeds` only after the broader credit workflow completes',
		},
		{
			call: 'Direct ETH transfer to `receive()`',
			caller: "Forker, this pool's Truth Auction, or parent pool only",
			effect: 'Accepts protocol-routed ETH used by migration and auction settlement. Forced ETH remains raw, unaccounted surplus rather than settlement collateral or fees.',
			declarations: [{ kind: 'receive', name: 'receive' }],
			preconditions: 'Sender is one of the three authorized protocol addresses. Forced ETH bypasses this ordinary-call guard.',
			signals: 'No dedicated receive event; the calling protocol step emits its own event',
		},
	],
}
